### ISSUE TITLE
what's the purpose of druid.server.maxSize ? can we delete it ?

### ISSUE THREAD

**Issue by FrankChen021** [apache/druid#10007]
I tried to solve #9998 today and found this parameter seems redundant.

According to the [doc](https://druid.apache.org/docs/latest/configuration/index.html#historical-general-configuration), 
> This is not a limit that Historical processes actually enforces, just a value published to the Coordinator process so it can plan accordingly.

There're two problems here
1. Confusion
Why don't we use the sum of all the `maxSize` in `druid.segmentCache.locations` ?  
What if this value is less than the sum of `maxSize` in `druid.segmentCache.locations` ?
What if this value is greater than the sum of `maxSize` in `druid.segmentCache.locations` ?

    Apparently, it's value should be the same as the total max size of all disks.

2. Redundant configuration
If there're several disks configured, user has to sum the maxSize together by himself to fill this parameter. It's boring.

I checked relevant code, and found no any other special purposes for this parameter.  It seems there's no need to keep this parameter. **Historical node should calculates the total max size based on user's configuration during start up.**

Can we delete this parameter ?

**Comment by a2l007** [comment]
I have a prototype ready that will default the server.maxSize property to the sum of the maxSize values in druid.segmentCache.locations. The PR would be available once requisite testing is completed.

**Comment by FrankChen021** [comment]
@a2l007 Great. I intended to solve this problem but I was working on other problems all the time. Looking forward to your patch.
