### ISSUE TITLE
appenderator-merge too slow(0.17.0)

### ISSUE THREAD

**Issue by wenraoliu** [apache/druid#10031]
org.apache.druid.segment.realtime.appenderator.AppenderatorImpl - Segment[***2020-06-14T05:00:00.000Z_2020-06-14T06:00:00.000Z_2020-06-14T05:00:03.291Z_171] of 602,240,691 bytes built from 16 incremental persist(s) in 1,440,695ms; pushed to deep storage in 53,893ms. Load spec is: {"type":"hdfs","path":"XX.zip"}

merge 16 Segment(500M) cost 1440s (24min), is too slow. how can make it faster.

**Comment by liran-funaro** [comment]
Hi @wenraoliu,
Can you elaborate? What is the size of your data? What hardware do you run? Storage: SSD/HDD?
Can you post here also the ingestion JSON?

Also, I just published a PR that nearly doubles the ingestion speed. You can try it out and let me know if that improves anything for you: #10001.

**Comment by wenraoliu** [comment]
I found the reason: SATA TOO slow.
the PR is a pretty , I am studying. thanks very much

**Comment by liran-funaro** [comment]
Thanks!
