### ISSUE TITLE
Druid SQL multi-lingual decoded problem

### ISSUE THREAD

**Issue by leedohyun** [apache/druid#10064]
Hi! I'm using 0.18.1.

When I executed sql with Korean characters, I got the empty result.
So, I debugged the broker code and there was the problem as follows.
[https://issues.apache.org/jira/browse/CALCITE-2704](https://issues.apache.org/jira/browse/CALCITE-2704)

We need to bump to avatica-0.17.0.
I'd like to ask you to review.

**Comment by clintropolis** [comment]
Thanks for the report and suggested fix @leedohyun. I've opened #10074 and added a test which appears to show the updated Avatica dependency resolve the issue.
