### ISSUE TITLE
How to use environment variables in runtime.properties?

### ISSUE THREAD

**Issue by jp707049** [apache/druid#10078]
Hello,

- We've have an env variable defined in a node called `DRUID_HOST` which points to the actual hostname of the node.
- How can we use `DRUID_HOST` in runtime.properties of a druid service?

I tried the below way but didn't work.
```
druid.host={"type":"environment","variable":"DRUID_HOST"}
```

Thank you,
Jeet

**Comment by FrankChen021** [comment]
You can try to add `-Ddruid.host=$DRUID_HOST` to the java launch command line in `run-druid` shell file under `bin` directory. Or you could add that property to ` jvm.config` file for each druid node.

I've never tried that, hope it works.

**Comment by jp707049** [comment]
Hi,

- I tried using `-Ddruid.host=$DRUID_HOST` in jvm.config but it did not work. Instead the service set the `host=$DRUID_HOST` instead of using value.
- I did a workaround, before running a service, I created a script which will get the value of DRUID_HOST and adds it to `druid.host` property
- Although it would be good if Druid support using env variables.

Thank you,
Jeet

**Comment by FrankChen021** [comment]
I checked the `run-druid` file, putting environment variables in `jvm.config` won't take effect. 

But you can try the first method  I mention above, that is putting `-Ddruid.host=$DRUID_HOST` in [`run-druid`] (https://github.com/apache/druid/blob/d3497a6581c69f810090f5180f1f18328b06c781/examples/bin/run-druid#L45) as below

````
exec "$JAVA_BIN"/java -Ddruid.host=$DRUID_HOST ...
````

**Comment by jp707049** [comment]
Great,
I will check and update here soon using your first method.
Thanks :)

**Comment by jp707049** [comment]
Using `run-druid` example worked :)
