### ISSUE TITLE
Return at least one row

### ISSUE THREAD

**Issue by cosmin-mogos** [apache/druid#10090]
We have a simple druid sql query to return the count of some events.

```sql
select count(*) from events where type='the event'
```

The problem is that if no events match the query no rows are returned, since we use it for alerts we'd like the query above to return a row with 0 value in case no events match the where clause. How can we achieve this?

The closest I managed was with

```sql
select sum(c) from (
    select count(*) as c from events where type='the event'
    union all
    select 0 as c from events limit 1
)
```

which fails with `Cannot build plan for query`, but succeeds if the `sum(c)` is replaced with just `c`.

**Comment by HansFranzHaase** [comment]
I am a bit late, but had the same problem.
Currently it works also with only the inner part:
```sql
select count(*) as c from events where type='the event'
union all
select 0 as c from events limit 1
```
Thanks @cosmin-mogos for also providing the workaround!

**Comment by abhishekagarwal87** [comment]
what druid version are you on?

**Comment by HansFranzHaase** [comment]
That was on version 0.21.0.

While writing these lines I can also try on 2021.12 and the result for 
```sql
select count(*) from events where type='the event'
```
is as expected: 0
