### ISSUE TITLE
DruidSchema is not thread safe

### ISSUE THREAD

**Issue by xiangqiao123** [apache/druid#10118]
### Affected Version

0.18.1

### Description
Suppose that an interval has more than one segment, if some segments are deleted, then refreshing the remaining segments by refreshing segments will be skipped and re added to the segmentsNeedingRefresh. As a result, these remaining segments can no longer be refreshed successfully(PartitionHolders  are not complete). This can easily happen when the broker is restarted. We can see the following logs: (For example, **206 segments left**)
`Refreshed metadata for dataSource[test_datasource] in 156 ms (97 segments queried, 206 segments left).`

Suppose the code is executed as follows
1.removeSegment：segmentsNeedingRefresh.remove(segment)  （delete partial segment for a interval）
2.segmentsToRefresh.addAll(segmentsNeedingRefresh); （add remaining segment to refresh）
   segmentsNeedingRefresh.clear(); (clear segmentsNeedingRefresh)
3.final Set<SegmentId> refreshed = refreshSegments(segmentsToRefresh);
4.segmentsNeedingRefresh.addAll(Sets.difference(segmentsToRefresh, refreshed)); (remaining segment  add to segmentsNeedingRefresh again,and can no longer refresh successfully)

@clintropolis Can you help me confirm that this is a bug? thank you！

**Comment by clintropolis** [comment]
Hi @xiangqiao123, apologies for the delayed response.

I think you are talking about the case where only part of the partition set for a time chunk is queried to refresh? If so, I think #10125 likely also describes the issue and is the fix. The bug in that issue would prevent specific segment queries that did not query the complete partition set for that time chunk from returning results, which probably would have affected this too.

Beyond that, I had a look and can't spot any obvious thread safety issues with `DruidSchema` itself around segment metadata refreshes: everything that reads or writes to `segmentsNeedingRefresh` appears to do so while under the lock, and the `segmentsToRefresh` is a snapshot of `segmentsNeedingRefresh` that is only used/accessed by the refreshing thread.
