### ISSUE TITLE
Option needed to use multiple redis hosts for caching

### ISSUE THREAD

**Issue by neerajtiwar** [apache/druid#10192]
### Description

Currently Druid provides option to use Redis cache for Broker nodes under "druid.cache.host" property, however, it only accepts 1 IP which is not suitable for production and is not fault-tolerant. I tried giving multiple IPs of my Redis cluster but Druid is unable to use it if configured with comma seperated IPs. Below is config I used:

druid.cache.type=redis
druid.broker.cache.useCache=true
druid.broker.cache.populateCache=true
druid.cache.host=10.140.31.43,10.140.31.44,10.140.31.45
druid.cache.port=6379
druid.cache.maxTotalConnections=60
druid.cache.maxIdleConnections=60 

Above config didn't throw any error but never used by DRUID, When I provided single IP it started working.

**Comment by FrankChen021** [comment]
redis-cache extension currently does NOT support redis cluster.  I don't know if there's a plan to support redis cluster since it's a contrib extension created by @QiuMM

**Comment by FrankChen021** [comment]
Besides cluster support, I think redis-cache extension needs to be updated to : 
1.  allow user to specify password of a redis node/cluster
2. allow user to customize database index of a redis node
