### ISSUE TITLE
Re-indexing a Druid datasource from the web console is broken

### ISSUE THREAD

**Issue by suneet-s** [apache/druid#10197]
### Affected Version

0.19.0

### Description

If a user tries to re-index a Druid datasource from the web console, it fails with the following exception

```
Error: Missing type id when trying to resolve subtype of [simple type, class org.apache.druid.data.input.InputFormat]: missing type id property 'type' (for POJO property 'inputFormat') at [Source: (org.eclipse.jetty.server.HttpInputOverHTTP); line: 1, column: 195] (through reference chain: org.apache.druid.indexing.overlord.sampler.IndexTaskSamplerSpec["spec"]>org.apache.druid.indexing.common.task.IndexTask$IndexIngestionSpec["ioConfig"]>org.apache.druid.indexing.common.task.IndexTask$IndexIOConfig["inputFormat"])
```

This is because the type of the inputFormat is not set for the sampler request that the web console sends. Submitting a re-index job without using the web console continues to work as expected.

<img width="1385" alt="Screen Shot 2020-07-16 at 10 04 56 AM" src="https://user-images.githubusercontent.com/44787917/87839848-7ccdf500-c851-11ea-9f48-6fd73b7e395b.png">

**Comment by renjithpaul27** [comment]
When are we planning to merge this?
