### ISSUE TITLE
UI: Filtering by regex raises errors without being handled

### ISSUE THREAD

**Issue by feluelle** [apache/druid#10228]
### Affected Version

0.19.0

### Description

When I try to filter data via /unified-console.html#load-data endpoint and use Type regex and for example don’t pass a Dimension or Pattern it raises an [exception](https://github.com/apache/druid/blob/646fa84d043a075e64efa0d65205a17b066204e9/processing/src/main/java/org/apache/druid/query/filter/RegexDimFilter.java#L60-L61) which makes sense but shouldn’t this exception be caught and “handled”? Because in the UI I am not able to correct it in the same view. I would have to go to “Edit spec” to edit it directly.

Same goes for [invalid regex expressions](https://github.com/apache/druid/blob/646fa84d043a075e64efa0d65205a17b066204e9/processing/src/main/java/org/apache/druid/query/filter/RegexDimFilter.java#L65).

**Screenshot of Issue:**

![Screenshot_2020-08-01 Apache Druid](https://user-images.githubusercontent.com/23282078/89100711-8e8acd00-d3f9-11ea-8f60-756858676721.png)

### Proposed Solution

Catch exception and let the user correct it.

**Comment by vogievetsky** [comment]
This has been fixed :-)

<img width="302" alt="image" src="https://user-images.githubusercontent.com/177816/205183950-6f570970-0815-4635-9524-4843ba98f0c2.png">
