### ISSUE TITLE
How to implement "case when" by Native queries

### ISSUE THREAD

**Issue by Mxdcq** [apache/druid#10236]
Hi, I face a situation where I am not allowed to use SQL syntax to implement "case when". 

1) Therefore, I would like to know if it is possible to do the following "case when" by native queries?
`sum(case when column_A = value_one then column_B when column_A = value_two then column_C else column_D end)`
2) If the answer if "Yes", please give a sample example!

Thanks in advance.

**Comment by BigRantLing** [comment]
[Druid filtered aggregator](https://druid.apache.org/docs/latest/querying/aggregations.html#filtered-aggregator)  may be help you . I think it can be parsed to native query like below:    

```json 
{
    "queryType":"queryType",
    ....
    "aggregations":[
        {
            "type":"filtered",
            "filter":{
                "type":"selector",
                "dimension":"column_A",
                "value":"value_one"
            },
            "aggregator":{
                "type":"longSum",
                "fieldName":"column_B",
                "name":"sum_B"
            }
        },
        {
            "type":"filtered",
            "filter":{
                "type":"selector",
                "dimension":"column_A",
                "value":"value_two"
            },
            "aggregator":{
                "type":"longSum",
                "fieldName":"column_D",
                "name":"sum_D"
            }
        }
    ]
}
```

**Comment by Mxdcq** [comment]
@BigRantLing ,Hi,
Thanks for your help. I think it partially solve my problem by using filtered aggregator. But it cannot do the else part. For example column_A has hundreds of enum values, I want to calculate something if column_A = a_1, something else if column_A = a_2, the rest if column_A not in (a_1, a_2). Anyway, thanks for the instruction.
