### ISSUE TITLE
Update the docs with info on running the service in local

### ISSUE THREAD

**Issue by karthikbhat13** [apache/druid#10231]
### Description

Currently if one tries to find how to run Druid server from local, there is no direct docs for that. You have to read how to build from source [(link)](https://druid.apache.org/docs/latest/development/build.html) and then go to [quickstart](https://druid.apache.org/docs/latest/tutorials/index.html) section to run the server in local. 

### Motivation
It took me some time to figure out how to run the server locally even though all information was there in docs. It would make sense to probably link the latter page in 'Build from Source' section or append it so that you have one page with all information on how to run the server locally.

It also will be helpful to add how to run in intelliJ or other IDEs as well to run in debug mode.

**Comment by FrankChen021** [comment]
The doc for setting up intelliJ locates [here](https://github.com/apache/druid/blob/master/dev/intellij-setup.md). It's not referenced by other docs so maybe it's not easy to find it.
