### ISSUE TITLE
Coordinator will spend a lot of time(many hours) to assign segments when  a historical lost.

### ISSUE THREAD

**Issue by licl2014** [apache/druid#10242]
Coordinator will spend a lot of time(many hours) to assign segments when  a historical(has  a lot of segments)  lost and realtime task can't complete handoff.
`replicationThrottleLimit` and `maxSegmentsInNodeLoadingQueue`  has no effect.

### Affected Version

0.12.3

### Description

- The lost historical has 20T data
- Scheduling strategy is `cost`

**Comment by asdf2014** [comment]
Hi, @licl2014 . Can you provide more information? For example: What is the number of segments on the failed Historical node? Does the failed Historical node need to be offline permanently or just temporarily? Is the bottleneck in server resources (CPU, disk or network bandwidth)? Or the server resources are very idle, but the Coordinator is time-consuming to calculate the allocation strategy?

**Comment by licl2014** [comment]
The historical has about 1 million segments, after it lost(whatever offline permanently or just temporarily), coordinator will  assign replicate segments  to other active historicals in the next round scheduling,  but `cost algorithm` is time-consuming ,`replicationThrottleLimit`  and `maxSegmentsInNodeLoadingQueue`  has no effect(historicals load segment faster than coordinator assign segment),so coordinator will hang for hours.
`Cachingcost` has no such problem,because cachingcost algorithm is very efficient and coordinator assign segment faster than historicals load segment, so `maxSegmentsInNodeLoadingQueue` and `replicationThrottleLimit` has effect. @asdf2014

**Comment by asdf2014** [comment]
@licl2014 It sounds like the bottleneck is in the calculation of the allocation strategy, but if you switch to the `cachingCost` allocation strategy, you need to be aware that memory consumption may increase.

**Comment by licl2014** [comment]
We should control coordinator's scheduling time in one round when we use `cost` strategy ,otherwise the realtime tasks hand off will be affected. @asdf2014
