### ISSUE TITLE
Druid configuration for HA cluster

### ISSUE THREAD

**Issue by soumyajose0784** [apache/druid#10249]
We have requirement to setup Druid cluster with 2 coordinator-overlord nodes, 8 historical nodes and 4 query nodes. Could I get reference to the configurations for setting up this cluster in high availability mode.

**Comment by FrankChen021** [comment]
Druid cluster is scalable and fault tolerant. You can follow the [doc](https://druid.apache.org/docs/latest/tutorials/cluster.html) for cluster deployment.

**Comment by averma111** [comment]
Thanks @FrankChen021 . We want to setup the same cluster in GCP using kubernetes and multi region setup. Could you please help us .

**Comment by AdheipSingh** [comment]
@averma111 to run on k8s use this https://github.com/druid-io/druid-operator
Please feel free to open issues in the above repo :)
