### ISSUE TITLE
Cannot use virtual columns in groupby dimensions

### ISSUE THREAD

**Issue by phakudi** [apache/druid#10246]
Hi There,

We are trying to use virtual columns for grouping by. And it does not work.

```
{
  "queryType": "groupBy",
  "dataSource": "trace_info",
  "granularity": "none",
  "virtualColumns": [
    {
      "type": "expression",
      "name": "tenant",
      "expression": "replace(array_offset(tags, array_offset_of(tagNames, 'tenant')), 'tenant:', '')"
    },
    {
      "type": "expression",
      "name": "rc",
      "expression": "replace(array_offset(tags, array_offset_of(tagNames, 'row_count')), 'row_count:', '')"
    }
  ],
  "dimensions": [
    "tenant"
  ],
  "aggregations": [
    {
      "type": "longSum",
      "name": "trc",
      "fieldName": "rc"
    }
  ],

...
...
...

  "intervals": [
    "2020-08-04T10:00:00.000/2020-08-04T11:00:00.000"
  ]
}
```

Druid version is 0.18.1

**Comment by phakudi** [comment]
The documentation is not awfully clear.on how to use virtual columns as group by dimensions. I could be wrong here too. Please help.

Thanks!
Phani

**Comment by dylwylie** [comment]
No issues stand out in your query apart from there's no specified outputType so the default will be float.

Could you elaborate on what's not working? What response do you get? Do you've any corresponding log messages on the historical or broker nodes?

**Comment by phakudi** [comment]
Hi @dylwylie thanks for your response. Yes. I fixed the outputType and it started working. You can close this issue.

**Comment by dylwylie** [comment]
great newss - thanks for the update @phakudi
