### ISSUE TITLE
Regression: Indexer nodes dont announce realtime segments in 0.19

### ISSUE THREAD

**Issue by pdeva** [apache/druid#10258]
### Affected Version

0.19

### Description

To reproduce, use indexer nodes with kafka ingestion and upgrade cluster to 0.19 from 0.18.1.

You will notice that none of the queries in realtime time range return any results. Distributed Tracing will show you that broker never sends query to indexer nodes.

Downgrading indexer node to 0.18 (while keeping rest of cluster in 0.19) makes the problem go away.

**Comment by dlyoungerman** [comment]
@pdeva - Thank you. Your workaround worked for us.

**Comment by gianm** [comment]
#10631 should fix this.

**Comment by jihoonson** [comment]
Closing as #10631 is merged. Please feel free to reopen if you still see the same issue.
