### ISSUE TITLE
SSO capability in Druid

### ISSUE THREAD

**Issue by soumyajose0784** [apache/druid#10250]
Druid version 0.18.0 had enabled SSO authentication(using pac4j) for unified console. Are there any enhancement to the pac4j/SSO capability in latest version(0.19.0). We are looking for SSO authentication for other APIs.

**Comment by himanshug** [comment]
that extension added OIDC support which is meaningful only for interactive web console use from browser (as there is "redirect" step involved where user has to provide his username/pwd to authenticate with auth server such as okta)

do you mean enabling that for programatic access? I don't know/think if OIDC is meant to be used for that.... LDAP is the most common thing used I see across different places.
