### ISSUE TITLE
DruidInputSource ignores dimensionsSpec when dimensions is set

### ISSUE THREAD

**Issue by jihoonson** [apache/druid#10266]
### Affected Version

Since 0.17

### Description

When `dimensions` is set in `DruidInputSource`, it doesn't respect dimensionsSpec. Instead, it uses `dimensions` in the inputSource. This results in a wrong schema of the reingested datasource. To fix this bug, `InputRowSchema` should be passed to `DruidSegmentReader`, so that it can use `MapInputRowParser.parse()` instead of creating `MapBasedInputRow` directly. Note that `dimensionExclusions` should be ignored when `dimensions` is set in `DruidInputSource`.

**Comment by jon-wei** [comment]
Fixed by [#10267](https://github.com/apache/druid/pull/10267)
