### ISSUE TITLE
How to redirect process logs to STDOUT?

### ISSUE THREAD

**Issue by behdadkh** [apache/druid#10281]
Hello, 

Could you please point me to the direction to be able to redirect the logs to STDOUT? 

I'm running Druid services within individual Docker containers and each of them are launched by:
`bin/run-druid SERVICE_NAME conf/druid/cluster/SERVICE_NAME`

So far, I've figured by by-passing Druid `supervise` script I can take over STDOUT and set AWS Log as my container log driver. This way, I can redirect the logs to Cloudwatch without configuring a process to do the forwarding for me.

But, is this the correct way to achieve this? did I miss something in the docs?

Also, there are lots of bootstrapping happening in Druid `supervise` script which I rather not to miss.

**Comment by tj---** [comment]
@behdadkh did you find a solution to this? (without skipping the use of `supervise`)

**Comment by behdadkh** [comment]
@tj--- Sorry for late reply! no, not really.. I am still delivering the logs with the above approach.
