### ISSUE TITLE
Reindexing of One Datasource using another Input Datasource gives 0 Hyperloglog values

### ISSUE THREAD

**Issue by mounikanakkala** [apache/druid#10297]
I am facing an issue with reindexing a datasource (which involves HLL Metrics using Datasketches HLLSketch) using another datasource.

Original_Datasource - Dimensions D1,D2,D3,D4. Metrics - M1, M2, M3, M4
Cardinality_Datasource - Dimensions D1, D2. Metrics - D3Cardinality, D4Cardinality using HLLSketch. (I want to maintain cardinality of dimensions D3 and D4 for each combination of D1 and D2).

I want to reindex Cardinality_Datasource using Original_Datasource, using the following spec

```
{
  "type": "index_parallel",
  "spec": {
    "dataSchema": {
      "dataSource": "Cardinality_Datasource",
      "timestampSpec": {
        "column": "_time",
        "format": "auto"
      },
      "dimensionsSpec": {
        "dimensions": [
          "D1",
          "D2"
        ]
      },
      "metricsSpec": [
        {
          "name": "D3Cardinality",
          "type": "HLLSketchBuild",
          "fieldName": "D3"
        },
        {
          "name": "D4Cardinality",
          "type": "HLLSketchBuild",
          "fieldName": "D4"
        }
      ],
      "granularitySpec": {
        "type": "uniform",
        "segmentGranularity": "hour",
        "queryGranularity": "hour"
      }
    },
    "ioConfig": {
      "type": "index_parallel",
      "inputSource": {
        "type": "druid",
        "dataSource" : "Original_Datasource",
        "interval": "2020-08-11T00/2020-08-11T01"
      }
    },
    "tuningConfig": {
      "type": "index_parallel",
      "maxNumConcurrentSubTasks": 3
    }
  }
}
```

With this specification, I can see D1 and D2 dimensions in Cardinality_Datasource table but D3Cardinality and D4Cardinality values are all 0. Can someone please help me with this issue?

**Comment by mounikanakkala** [comment]
May I know if anyone can help me on this issue?

**Comment by abhishekagarwal87** [comment]
You may be running into https://github.com/apache/druid/issues/9914

**Comment by mounikanakkala** [comment]
Thank you for sharing the link. That helped!
