### ISSUE TITLE
All ingestion task failed and druid failed to ingestion any data

### ISSUE THREAD

**Issue by qphien** [apache/druid#10311]
### Affected Version

apache-druid-0.16.1-incubating

### Description

I have 150+ KIS and each KIS launches 1~2 ingestion task, each task has PT3600S taskDuration.
when ingestion task runs about 1 hour and succeeds to publish segments, task log and middle manager log shows that this task's status is success like below:

`Task log`
[task.log](https://github.com/apache/druid/files/5113605/task.log)

`MiddleManager.log`
[MiddleManager.log](https://github.com/apache/druid/files/5113608/MiddleManager.log)

But from log of overlord, task index_kafka_push_register_43d787f78c74374_cfcibngo  failed.

`Overlord.log`
[Overlord.log](https://github.com/apache/druid/files/5113609/Overlord.log)

I tried to restart middleManager and overlord but nothing worked.

I also submitted an index_parallel task to my overlord cluster, but the task still failed.

What's wrong with my druid cluster? 

Can anyone give me some suggestions on how to solve this problem?

**Comment by qphien** [comment]
I start up druid with supervise and i just check middleManager log specified by log4j2.xml. In supervise log, i find the exception:
`
INFO [forking-task-runner-3] org.apache.druid.indexing.overlord.ForkingTaskRunner - Exception caught during execution
org.apache.hadoop.ipc.RemoteException: The directory item limit of /user/druid/indexing-logs is exceeded: limit=1048576 items=1048576
        at org.apache.hadoop.hdfs.server.namenode.FSDirectory.verifyMaxDirItems(FSDirectory.java:1147)
`

The number of indexing log is upper to hdfs limitation. After deleting old indexing logs, everything works fine.

However, why exception log only printed to supervise log and not in middleManager log specified by log4j2.xml?
Is there any parameter to control druid to delete indexing log periodically?

Thanks

**Comment by FrankChen021** [comment]
1. The default log4j2.xml outputs log to the console, which then be redirected to log files by `supervise` script.

2. Task logs can be automatically cleaned by setting [`druid.indexer.logs.kill.enabled`](https://druid.apache.org/docs/latest/configuration/index.html#task-logging) to `true`

**Comment by qphien** [comment]
@FrankChen021 Great! Thanks for your reply.
