### ISSUE TITLE
 I use  Druid Connection pool that met  a question

### ISSUE THREAD

**Issue by AnswerNo2** [apache/druid#10310]
environment: Springboot  +   mybatis + postgresql   + Druid 

when you send a parameter to mybatis , if  parameter's key is  'orderBy'  , then ，that problem is coming:
 SQL will be wrong ！ 
![QQ图片20200822141132](https://user-images.githubusercontent.com/22674332/90950483-91bb2b00-e484-11ea-9513-c71618cbc230.png)
![QQ图片20200822141251](https://user-images.githubusercontent.com/22674332/90950488-97187580-e484-11ea-83b4-f04aa3167aba.png)

**Comment by FrankChen021** [comment]
The Druid connection pool you use is not the Apache Druid here. The first refers to **Alibaba Druid**, you should ask question there : https://github.com/alibaba/druid
