### ISSUE TITLE
Extension druid-kafka-extraction-namespace not been loaded

### ISSUE THREAD

**Issue by jgoodman8** [apache/druid#10326]
When setting up the following configuration for extensions: 
`druid.extensions.loadList=["druid-hdfs-storage", "druid-kafka-indexing-service", "druid-datasketches", "postgresql-metadata-storage", "druid-parquet-extensions", "druid-lookups-cached-global", "druid-kafka-extraction-namespace"]`
The "druid-kafka-extraction-namespace" extension is not been loaded and the extension is placed on its corresponding route. 
Any suggestion?

**Comment by netixx** [comment]
Hello, did you solve your problem ? I am having the same issue: the plugin is configured, I can see it loaded in the logs, but it does not appear in the console (and I cannot configure kafka lookups).

It states here in the doc that the druid-kafka-extraction-namespace depends on the namespace extensions, but it is nowhere to be found on this page: https://druid.apache.org/docs/latest/development/extensions.html
