### ISSUE TITLE
Group By V2 query should use the Query/result level cache, if enabled at Broker.

### ISSUE THREAD

**Issue by hrishikeshk** [apache/druid#10344]
### Description
Simply have Group By V2 use the Query/Result level cacheif it is enabled at Broker. I did not see a reason why it does not (it is documented alright). After all, Group By V1 benefits from it.

### Motivation
I  have a number of Group By queries and using Group By V2 because it is indeed faster than V1 (10 sec in V2 versus 28 sec in V1).
If I use segment level caching (at Historicals), the benefit is not as much. Timings reduce to 8 sec in V2.
However, we have many repeated queries and data loads do not interfere. Result level caching has potential to bring down query time to 1 sec.

**Comment by elukey** [comment]
I am wondering if the same holds for TopN queries, since I am struggling to find why my Brokers don't cache anything (even if result level cache is enabled, I only see cache miss in the metrics). Is there a list of query types not supported for caching somewhere that I can check?

**Comment by abhishekagarwal87** [comment]
Fixed via #11595
