### ISSUE TITLE
Druid data loader does not work with input time column name - '__time' 

### ISSUE THREAD

**Issue by AshishKapoor** [apache/druid#10349]
Druid data loader does not work with input time column name - '__time' 

### Affected Version

The Druid version where the problem was encountered.
v0.19.0

### Description

Please include as much detailed information about the problem as possible.
- Cluster size: NA
- Configurations in use `paste data`

- Steps to reproduce the problem
Use this dataset, go to druid console, `load data` -> `paste data` -> paste following data- 
```
{ "__time": "2013-08-31T01:02:33Z", "page": "test" }
```

- The error message or stack traces encountered. Providing more context, such as nearby log messages or even entire logs, can be helpful.
```
unparseable
Found unparseable columns in row: [org.apache.druid.indexing.overlord.sampler.SamplerInputRow@487bb21f], exceptions: [could not convert value [2013-08-31T01:02:33Z] to long,]
Original row: { "__time": "2013-08-31T01:02:33Z", "page": "test" }
```
### Screenshot
<img width="1328" alt="Screenshot 2020-09-04 at 12 39 21 AM" src="https://user-images.githubusercontent.com/5203107/92156761-1889e380-ee47-11ea-9f19-6897f5033ee3.png">

- Any debugging that you have already done
NA

Sincerely
Ashish Kapoor

**Comment by FrankChen021** [comment]
`__time` is a reserved name representing time column of the segment. Currently it requires a value of of unix epoch. You could change the property name of `__time` in json to another name.

**Comment by AshishKapoor** [comment]
> `__time` is a reserved name representing time column of the segment. Currently it requires a value of of unix epoch. You could change the property name of `__time` in json to another name.

I've noticed it works with other databases.
