### ISSUE TITLE
Using `LIMIT 0` in SQL SELECT query causes `sqlOuterLimit` to be ignored

### ISSUE THREAD

**Issue by vogievetsky** [apache/druid#10369]
### Affected Version

The Druid version 0.19.0, 0.18.0

### Description

When issuing a `SELECT` (no `GROUP BY`) query with `LIMIT 0` the `sqlOuterLimit: 100` context value is ignored and all rows are returned.

Good:

![image](https://user-images.githubusercontent.com/177816/92535949-46777b00-f1ed-11ea-96a6-a93f8fb9aa91.png)

Bad:

![image](https://user-images.githubusercontent.com/177816/92535998-6a3ac100-f1ed-11ea-8f42-848d6b4b8a1e.png)

Another simpler example:

```sql
SELECT * FROM (
  SELECT * FROM "wikipedia" LIMIT 200
) LIMIT 0
```

![image](https://user-images.githubusercontent.com/177816/92536191-dfa69180-f1ed-11ea-9def-a3082f1dbc76.png)

Side note: setting `LIMIT 0` on a GROUP BY query results in 'could not build plan' which is fair enough

**Comment by gianm** [comment]
I think #10279 fixed this: https://github.com/apache/druid/pull/10279/files#diff-190f8eaf9dd09e8d7ae0564804286afcR6536

Can you check if the bug is still there in master?

**Comment by vogievetsky** [comment]
This has indeed been fixed
