### ISSUE TITLE
Coordinator fails to create meta tables in PostgreSQL

### ISSUE THREAD

**Issue by dsx** [apache/druid#10361]
Coordinator fails to create meta tables in PostgreSQL (see log). It looks like option `druid.metadata.storage.connector.createTables=true` is not idempotent and doesn't use `IF EXISTS` clause.

### Affected Version

0.18.0
0.19.0

### Description
[log.txt](https://github.com/apache/druid/files/5178518/log.txt)

**Comment by averma111** [comment]
**ERROR: relation "druid_config" already exists** already exists in your DB. Please login and check PostgreSQL

**Comment by dsx** [comment]
@averma111 it's a run on a completely empty database. relation has been created by coordinator earlier, see log entry that says `[INFO ] 2020-09-05 19:08:56.748 [main] SQLMetadataConnector - Creating table[druid_config]`.

**Comment by dsx** [comment]
Later in my experiments I watched tables being created. If I drop `druid_config`, coordinator can continue. However, after restart if `druid.metadata.storage.connector.createTables=true` is still in effect it can't start again, failing to create already existing tables. It seems to me that it is reasonable to expect schema creation to be re-entrant and idempotent operation.

**Comment by dsx** [comment]
Figured out that DB user lacks some permissions, however it is not clear yet what exactly is missing. Is there any info on what permissions are needed?
