### ISSUE TITLE
Vectorized Queries Failing in VectorMatch#copyFrom as src array cannot fit into dest array

### ISSUE THREAD

**Issue by capistrant** [apache/druid#10374]
### Affected Version

0.18.1

### Description

I am in the beginning steps of troubleshooting this and I will add more details as I find out how to reproduce the issue consistently. I am currently seeing queries fail in vectorization code when VectorMatch#copyFrom tries to copy a VectorMatch into another where the src VectorMatch selection array is too big to fit in to the destination selection array. This violates the Preconditions check and causes a query failure.

I am currently only able to reproduce with one query on my cluster. This query is a timeseries query with a deeply nested or filter on a dimension value. When I flip this filter to use `IN` instead of `or`, the query runs successfully. The query also runs successfully as a non-vectorized query. This leads me to believe there may be a bug in the OrFilter code leading to these query failures.

I wanted to get this issue up on the board now so I can see if anyone else has been hitting it. As I said, I will revamp the problem report as soon as I can reproduce this consistently allowing for more thorough analysis and documentation.

**Comment by clintropolis** [comment]
Seems possibly related to #9994, either that issue (fixed in 0.19) or maybe a similar style of bug somewhere else since it sounds filter related.

**Comment by capistrant** [comment]
Wow thanks @clintropolis ... Patched up my fork  with #9994 and this did the trick for the query that I had to reproduce the issue. Since I am not able to trigger any more issues for vectorization, I will go ahead and close this. Definitely an easy patch for those who are not able to upgrade to druid 19 at this time.
