### ISSUE TITLE
Bug in configure uri in the new version of 0.19  lookup ui 

### ISSUE THREAD

**Issue by tarunparackal** [apache/druid#10436]
The lookup UI has been updated from 0.18 to 0.19  version. In the older version we could specify the json  defenenition for the lookup . But in the later version lookup UI has been updated with the UI to specify each paramter .  
Issue 1 : 
With the new UI for type uri, it is not possible to specify the  complete uri . only uri prefix and  file regex can be configured. 
Issue 2: 
if the lookup is created in older version(0.18)  and upgraded  to new version , it is not possible to edit the uri. At the same time if we need to be change the uri to uriprefix  then  UI   send the old uri and  also the uriprefix . 
A sample request object is given as below. 
{
	"version": "2020-09-25T11:43:27.056Z",
	"lookupExtractorFactory": {
		"type": "cachedNamespace",
		"extractionNamespace": {
			"type": "uri",
			"namespaceParseSpec": {
				"format": "csv",
				"columns": ["key", "value"],
				"keyColumn": "key",
				"valueColumn": "value"
			},
			"uri": "file:/Users/apple/lookup.csv",
			"uriPrefix": "file:/Users/apple/",
			"fileRegex": "lookup.csv"
		}
	}
}

### Affected Version

0.19

**Comment by suneet-s** [comment]
Closing as fixed by linked #10461
