### ISSUE TITLE
Tasks fail without and there are no error logs for it

### ISSUE THREAD

**Issue by abejoe** [apache/druid#10498]
Tasks keep failing but there are no error logs in the worker task's log file
### Affected Version
0.14.2-incubating

### Description
I have set up druid locally for testing an ingestion spec file. The aim is to ingest avro format messages into druid. I have installed schema registry and kafka locally with 1 partition and replication factor 1. 

There is a crash log in overlord.log. Its because the task failed and connection gets refused. But I couldn't find any logs for why the task failed.

I'm producing messages to the topic and I could verify that using a kafka-avro-console-consumer. I suspect it is something wrong with the setup or configuration. Any help is greatly appreciated.

I'm starting druid using the command `bin/supervise -c quickstart/tutorial/conf/tutorial-cluster.conf`
I have also added extensions `druid-kafka-indexing-service` and `druid-avro-extensions` in `quickstart/tutorial/conf/druid/_common/common.runtime.properties`

I'm attaching ingestion spec file and the log files of overlord, middle manager and worker task as .txt files
[ingestion_spec.txt](https://github.com/apache/druid/files/5353876/ingestion_spec.txt)
[index_kafka_vision-conformed_5db6b6f8757a0ab_cfcibngo.txt](https://github.com/apache/druid/files/5353878/index_kafka_vision-conformed_5db6b6f8757a0ab_cfcibngo.txt)
[middlemanager.txt](https://github.com/apache/druid/files/5353881/middlemanager.txt)
[overlord.txt](https://github.com/apache/druid/files/5353883/overlord.txt)

**Comment by FrankChen021** [comment]
It seems that peon can't connect to zk from the task log you gave

> 2020-10-09T07:14:19,582 INFO [main] org.apache.druid.guice.JsonConfigurator - Loaded class[class org.apache.druid.curator.ExhibitorConfig] from props[druid.exhibitor.service.] as [org.apache.druid.curator.ExhibitorConfig@476fe690]
2020-10-09T07:14:49,639 INFO [main] org.apache.curator.utils.Compatibility - Running in ZooKeeper 3.4.x compatibility mode
2020-10-09T07:14:49,641 WARN [main] org.apache.curator.retry.ExponentialBackoffRetry - maxRetries too large (30). Pinning to 29

But the exception in the overlord does not match the task log above,  according to the log of overlord, it is  `index_kafka_vision-conformed_5db6b6f8757a0ab_bebmfiod`. Maybe there're something useful in that file.

**Comment by abejoe** [comment]
Well I have been looking at the task logs and it all had the same content. Hence I didn't really emphasise on the exact corresponding task log. I will make another attempt and post the corresponding log files.

**Comment by abejoe** [comment]
Hi @FrankChen021 
I tried the tutorial given here (https://druid.apache.org/docs/0.14.2-incubating/tutorials/tutorial-kafka.html) for streaming data from kafka. The tasks fail the same way as posted earlier. 

Attaching the overlord.log and a few corresponding task log files. 

There are repated crash logs at the beginning of overlord.log file `Error connecting to server localhost on port 1,527 with message Connection refused (Connection refused)`. Not sure if that's expected or that is the real cause of this problem
[index_kafka_wikipedia_59dcea86b30dcdf_bebmfiod.txt](https://github.com/apache/druid/files/5362285/index_kafka_wikipedia_59dcea86b30dcdf_bebmfiod.txt)
[index_kafka_wikipedia_59dcea86b30dcdf_cfcibngo.txt](https://github.com/apache/druid/files/5362286/index_kafka_wikipedia_59dcea86b30dcdf_cfcibngo.txt)
[index_kafka_wikipedia_59dcea86b30dcdf_koghokai.txt](https://github.com/apache/druid/files/5362287/index_kafka_wikipedia_59dcea86b30dcdf_koghokai.txt)
[overlord.txt](https://github.com/apache/druid/files/5362288/overlord.txt)
