### ISSUE TITLE
[BUG] [Indexing Task 0.16.0]  Update metadata failed after indexing task empty running  with few data out of time widnow

### ISSUE THREAD

**Issue by QingdongZeng3** [apache/druid#10497]
Please provide a detailed title (e.g. "Broker crashes when using TopN query with Bound filter" instead of just "Broker crashes").

### Affected Version

0.16.0

The Druid version where the problem was encountered.

0.16.0

### Description

Please include as much detailed information about the problem as possible.
- Cluster size   
12 nodes    

- Configurations in use      
indexer.runner.type = httpRemote   
storage metadata with mysql , store segments in hdfs.  
segmentGranularity = 1 Hour  
TaskDuration = 1 Hour          
lateMessageRejectionPeriod = 1800s           
earlyMessageRejectionPeriod = 1800s    

- Steps to reproduce the problem
1.  Use my configurations ，run a datasource , produce  some data , general some segments  .(It's very nomal)   
2. In a whole index Task running lifecycle （start new index task --> finish  index task，in my configuration,its 1 Hour），just
produce a few data ,all of those data are out of time .( they will be thrown away，and no new segments generated，so partation-offset  metadata will not update in mysql，but update in overlord)       
3.  After task  in step 2 finished，and new task is running.（New task will use new checkpoint from overlord to general segments ,but when it try to publish segment，it will faied because of begin-checkPoint not equals with mysql）      
 4. ERROR when update metadata   
https://github.com/apache/druid/blob/master/server/src/main/java/org/apache/druid/metadata/IndexerSQLMetadataStorageCoordinator.java#L1135   

- The error message or stack traces encountered. Providing more context, such as nearby log messages or even entire logs, can be helpful.
I‘m sorry but I can not upload picture of error log because of company secret protection.

- Any debugging that you have already done
In my opinion，this problem caused by "only update metadata in mysql when publish segment ,but update checkpoint in overlord in fixed time by async from index task , so when task finished and checkpoint change，but no segment generated，this problem happened".

**Comment by QingdongZeng3** [comment]
![image](https://user-images.githubusercontent.com/70745826/95554898-8bd4d580-0a43-11eb-956a-7fb7844bf196.png)

**Comment by QingdongZeng3** [comment]
To solve this problem，we colud check metadata after indexing task succeed ,even there is no new segment.

**Comment by QingdongZeng3** [comment]
@jihoonson @leventov @gianm @FaxianZhao  @QiuMM   Hi, contributors of IndexerSQLMetadataStorageCoordinator.java  , could you  take a look at this problem ？Thanks！

**Comment by QingdongZeng3** [comment]
Hi all,
Is there someone take a look at this problem ？

**Comment by QingdongZeng3** [comment]
阿西吧！没人啊！bug啊！

**Comment by asdf2014** [comment]
Hi, @QingdongZeng3 . Have you tried using the [latest version](https://github.com/apache/druid/releases/latest) and will it still reproduce the problem?

**Comment by QingdongZeng3** [comment]
> Hi, @QingdongZeng3 . Have you tried using the [latest version](https://github.com/apache/druid/releases/latest) and will it still reproduce the problem?

oh，I didn't try it.But through code，this problem seems still exisit
