### ISSUE TITLE
Overlord Dynamic Configuration  not work

### ISSUE THREAD

**Issue by qianxinxu** [apache/druid#10504]
description: I use http  http://<OVERLORD_IP>:<port>/druid/indexer/v1/worker  to post a  JSON  request,but response is:
 "  textStatus: error

连接网络时发生异常： http://c4-miui-ad-druid-small03.bj:8753/druid/indexer/v1/worker "

how to settle the issue?

**Comment by FrankChen021** [comment]
dynamic configuration works fine in my cluster(0.16). According to error message, it seems that the host is not reachable. Are you sure you're using the right host address and port ?

**Comment by qianxinxu** [comment]
> dynamic configuration works fine in my cluster(0.16). According to error message, it seems that the host is not reachable. Are you sure you're using the right host address and port ?

I‘m sure that host and address is right.  GET method work ok and response normal,But POST method response error. My druid cluster is 0.13.0

**Comment by qianxinxu** [comment]
I update  post json to settle the issue!!
