### ISSUE TITLE
Druid UI Load Data -> Edit Spec text area redundant reinsert

### ISSUE THREAD

**Issue by egor-ryashin** [apache/druid#10520]
### Affected Version

0.19.0

### Description

Druid Edit Spec text area doesn’t allow to replace spec simply. If you delete it then it will be reinserted automatically defying your purpose to start from the clean slate. If you select it and hit paste the example spec will be appended to the tail sneakily. That’s counter-intuitive and error-prone, and annoying :slightly_smiling_face:

**Comment by vogievetsky** [comment]
This has been fixed in master. It is already released as part of Imply 2020.11 and will be in the 0.21.0 Druid release.
