### ISSUE TITLE
Ingesting to same Datasource from 2 different Kafka clusters with exact same topic name/specs overwrites previous Supervisor

### ISSUE THREAD

**Issue by klDen** [apache/druid#10522]
### Affected Version
0.20.0

### Description
Ingesting to same Datasource from 2 different Kafka clusters with exact same topic name/specs overwrites previous Supervisor.

- Steps to reproduce the problem
1. Create 1st Kafka spec and submit;
2. Create 2nd Kafka spec and submit with exact same spec as 1st, but w/ different Kafka brokers.

Expected results: 2 Supervisors ingesting from 2 different Kafka clusters w/ same topic name to same Datasource

**Comment by klDen** [comment]
Perhaps a solution is to specify a unique ID in the specs to differentiate them?

**Comment by klDen** [comment]
Seems like specifying the same Datasource using a different topic overwrites the previous Supervisor as well.

**Comment by FrankChen021** [comment]
Current design requires datasource as a unique key which means there's no way to create more than two supervisors with the same data source name.

Could you describe why you want to ingest from different kafka clusters instead of one to a same data source?

**Comment by klDen** [comment]
Hello @FrankChen021!

For latency reasons, I currently have multiregion Kafka clusters that receives data based on location of users.
The data is sent to the proprer cluster depending on location.

For my tests, I wanted to ingest the data from those different Kafka clusters into 1 data source in Druid.

**Comment by FrankChen021** [comment]
If multiple kafka clusters are needed, there's a way that I come up with to solve your problem, that is by using Kafka Mirror or uReplicator to duplicate data from source kafka clusters into one target kafka cluster from which druid ingest data

**Comment by julienlafont-tabmo** [comment]
As a workaround, you can ingest into 2 different data-source, and run the query over the union of both datasource (available in both native and SQL queries)

**Comment by klDen** [comment]
Thank you for the suggestions @FrankChen021, @julienlafont-tabmo . 
I think the simplest solution would be to use the union query as proposed by @julienlafont-tabmo .
