### ISSUE TITLE
Druid Lookups Auditing

### ISSUE THREAD

**Issue by mounikanakkala** [apache/druid#10521]
Hello Everyone,

We have lookups being updated once in 4 hours to Druid sending POST request for Update, whose size goes up to 50 MB. We are not adding extra set of 50 MB sized lookups in every run. Rather, we may end up updating the same lookup in every run. We do this periodically so that the list is most recent.
We have observed that every time there is an update, Druid audits those entries in druid_audit metadata table.

1. Are those audits of any significance to Druid? Especially the ones which are older than recent n entries, say n = 4 ?
If we are updating 50 MB worth data once in 4 hours, that metadata would become GBs in few days. We want to prune this audit.
2. Is there a possibility of adding a config to not audit lookups so that this config would automatically not add in the audit table?

Please let us know if you need additional information. Thank you for your time.

**Comment by FrankChen021** [comment]
AFAIK, there's no such config to suppress audit log. I think currently you have to delete these logs by some code executing a delete sql periodically.

I don't know the background of audit function. I guess Druid keeps these configuration in audit log in case of rolling back of a previous configuration.  @gianm could you give us more info about it ?

**Comment by a2l007** [comment]
@mounikanakkala We have similar use cases internally for which we've been working on a configurable option to periodically remove older lookup-related audit entries. I'll raise the PR once it is complete with adequate testing.

**Comment by mounikanakkala** [comment]
Thank you @a2l007

**Comment by k3kenan** [comment]
Hi, Is this issue going to be fixed? While lookup audit is written into metadata storage (postgresql), druid become inaccessible by saying Cannot load metadata.
