### ISSUE TITLE
io.druid

### ISSUE THREAD

**Issue by averma111** [apache/druid#10565]
Hi Team,

I just want to know why Maven central hai io.druid API which belong to 0.12.3 version. Do we have any latest API or the package name is changed.

Thanks,
Ashish

**Comment by asdf2014** [comment]
Hi, @averma111 . You should try https://mvnrepository.com/artifact/org.apache.druid .

**Comment by averma111** [comment]
Thanks I got that.

**Comment by asdf2014** [comment]
@averma111 You are welcome.
