### ISSUE TITLE
Delete data from Kafka after ingestion

### ISSUE THREAD

**Issue by amirvaza** [apache/druid#10566]
Hi All,

Would love a little help as I can't find a proper solution anywhere at the docs or google.

We are using a Kafka cluster with 100 partitions, and 10 middle managers.

All works good until Kafka disks are starting to get full.

I tried using the api /druid/indexer/v1/supervisor/data_source/status in order to get the currentOffsets and to tell Kafka to delete all prior those offsets, but then we get OffsetOutOfRangeException.

What is the correct way to advance the Kafka offsets in order to delete ingested data?

Thanks.

**Comment by FrankChen021** [comment]
We don't manually delete kafka records by offsets as you did but  I think I can share you something we do to avoid such a problem.

1st, it's better to set shorter log retention period for such a large topic to avoid disk shortage. For example, the `log.retention.hours` in our kafka clusters are usually set to 12 hours for high traffic topics however the default configuration is 168 hours(7 days).

2nd, it's also better to enable `LZ4` compression and a reasonable `ling.ms` at producer side which would both greatly benefit the network traffic, and disk storage at kafka broker side.

**Comment by amirvaza** [comment]
Thanks for the answer, thats what I eventually did, set the retention to one hour, but, what do I do in case I need to take my consumers down during migration or any unplanned reason such as consumer failures.

In such case, the retention will pass before the consumers will be able to consume the data which will cause loss of data.

Increasing the retention will make me use huge disks which I don't really need.

Something feels off, isn't there a better way to control it?

**Comment by FrankChen021** [comment]
I don't know what the migration you mentioned is.  But I think 1 hour is a little bit short. Default segment granularity is hour, and once there's any failure, druid has to re-ingest data from the last offset which might be one hour ago.

BTW, how many replicas do you have for these topics ?  For a typical kafka cluster, 3 replicas is recommended, but for such scenario, 2 replicas are enough for us to keep high availability while keeping lower disk consumption.

**Comment by amirvaza** [comment]
Thanks for the help, I guess its a more kafka than a druid question.
Reading a lot more on Kafka made me a little sense.
