### ISSUE TITLE
longSum/Max aggregation in metricsSpec is ignored when setting inputSource type=druid

### ISSUE THREAD

**Issue by panpur** [apache/druid#10570]
Tested in druid 0.20.0 with `druid.generic.useDefaultValueForNull=false`
I have exising druid datasource:
![druid](https://user-images.githubusercontent.com/5415285/98630138-0d729880-234d-11eb-8078-f5e7e480aac1.png)

Then I tried to aggregate using ingestion spec
`{
    "type": "index_parallel",
    "spec": {
        "dataSchema": {
            "dimensionsSpec": {
                "dimensions": [{
                        "name": "MONITOR_ID",
                        "type": "long"
                    }]
            },
            "metricsSpec": [{
                    "fieldName": "L3",
                    "name": "L3",
                    "type": "longSum"
                }, {
                    "name": "CNT",
                    "type": "count"
                }],
            "granularitySpec": {
                "segmentGranularity": "day",
                "queryGranularity": "hour"
            },
            "timestampSpec": {
                "column": "POLL_TIME",
                "format": "millis"
            },
            "dataSource": "z_3600000_0"
        },
        "ioConfig": {
            "appendToExisting": true,
            "inputSource": {
                "interval": "2020-11-10T03:26:00.000Z/2020-11-10T03:31:00.000Z",
                "type": "druid",
                "dataSource": "z_60000_0"
            },
            "type": "index_parallel"
        }
    }
}`

The longSum result for L3 is null
![druid_aggr](https://user-images.githubusercontent.com/5415285/98630337-7823d400-234d-11eb-88ec-9b6aa7584a50.png)

Is this a bug or am I missing something?

**Comment by abhishekagarwal87** [comment]
It may be the same problem as https://github.com/apache/druid/issues/9914. There is a workaround mentioned in that ticket.

**Comment by panpur** [comment]
The workaround works fine.
Thanks!
