### ISSUE TITLE
Clickjacking on druid

### ISSUE THREAD

**Issue by sajithms05** [apache/druid#10580]
Please provide a detailed title (e.g. "Broker crashes when using TopN query with Bound filter" instead of just "Broker crashes").

### Affected Version

Every druid version is affected with these vulnerability

### Description
 Druid application is vulnerable to clickjacking. As of now i can't find a solution for this.

If someone has a solution please help me.

**Comment by a2l007** [comment]
If you're using a custom druid security extension, one way to handle this is to add the `X-Frame-Options: SAMEORIGIN` header along with responses.

**Comment by sajithms05** [comment]
@a2l007 Do I have to add X-Frame-Options: SAMEORIGIN to the common runtime properties file ?

**Comment by a2l007** [comment]
@sajithms05 No that won't help. Core druid doesn't support adding custom headers via runtime.properties file. I was suggesting to add the header via a custom extension. If you have a custom druid security extension, you could add a filter that adds this security header. Something like this:

```public class SecureFilter implements Filter
{
@Override
  public void doFilter(
      ServletRequest servletRequest, ServletResponse servletResponse, FilterChain filterChain
  )
  {
     servletResponse.addHeader("X-Frame-Options", "SAMEORIGIN");
     filterChain.doFilter(servletRequest, servletResponse);
 }
}
```

**Comment by sajithms05** [comment]
@a2l007 Hi, Thank you for your suggestion. Could you suggest which custom extention do I have to select and where to add the filter.

**Comment by a2l007** [comment]
You could either create a new security extension from scratch using [this extension](https://github.com/apache/druid/tree/master/extensions-core/druid-basic-security) as a reference or add the SAMEORIGIN header to the [auth filter](https://github.com/apache/druid/blob/fe693a4f01a60d5a93dfa9225bf7f6c33fae7843/extensions-core/druid-basic-security/src/main/java/org/apache/druid/security/basic/authentication/BasicHTTPAuthenticator.java#L154) present in the extension and recompile it. I haven't tested out the latter approach with the basic security extension, but it may be worth a try.
