### ISSUE TITLE
New metrics are 0 on Druid parallel reingestion

### ISSUE THREAD

**Issue by irwvanroosmalen** [apache/druid#10596]
I have a problem that's reminiscent of the following issue: 

https://github.com/apache/druid/issues/5277

When I'm reingesting data into a new datasource using a druid inputSource, all new metrics seem to have value 0, except my count metric. Based on the older issue above, it seems like this might be desired behavior, but I'm wondering if there's a flag I can set here to support new aggregates, like the "useNewAggs" flag you have for hadoop reingestion.

We're currently on version 0.19.0

--UPDATE: I noticed it works when I include the original dimension field that the metrics are based in the new dimensionSpec, but that defeats the purpose of using roll-up, since those original dimension values are too granular and we would prefer them rolled-up in a new metric.

**Comment by smic-datalabs-von** [comment]
I am encountering this as well. Is there already a solution for this? It will be disappointing if the only solution is to ingest it again from the raw source.

**Comment by smic-datalabs-von** [comment]
I found a [workaround solution](https://github.com/apache/druid/issues/11410#issuecomment-874127584) for this. This bug has to be fixed since it's not intuitive and would waste someone's time.
