### ISSUE TITLE
Could I get some docs for TopN-query-processing?

### ISSUE THREAD

**Issue by achimbab** [apache/druid#10601]
Hello, 

Could I get some docs for TopN-query-processing of Druid?

I've read https://druid.apache.org/docs/latest/querying/topnquery.html, but I want to get more detailed information about TopN-query-processing.

Or could you tell me source-trees for Broker, Middleware and Historicals?

If you give me some hint I would be happy and will try to read source-codes to get deeper understanding for TopN-query-processing.

Thank you.

**Comment by meimiao0730** [comment]
我想请教的是内嵌的TopN-Query是否只支持单纬度的，而不是类似于Hive中row-number那种多维的topN。

**Comment by achimbab** [comment]
I moved this issue to Druid Google Groups.
