### ISSUE TITLE
Whether HDFS Dependencies Can Be Removed in the Future Development of Druid？

### ISSUE THREAD

**Issue by Mrxiashu** [apache/druid#10626]
In the production environment, HDFS occupies some resources. If HDFS features (such as data ingestion) are not used, is HDFS optional in future design?

**Comment by jihoonson** [comment]
This has been my wish for a long time. Ideally, HDFS dependencies should be included only when you include Hadoop-related extensions. However, I don't think it could be done easily since it will require restructuring and refactorying lots of code. I don't think it could be done anytime soon.

**Comment by himanshug** [comment]
curious about what/how-much resources are being consumed (assuming you don't add `hdfs-storage` to extensions list anyways) ?

**Comment by pan3793** [comment]
Since Parallel Index has been introduced, is there a plan to decouple the `indexing-hadoop` and `indexing-service`? What I'm decouple is inverse the dependence of them and make `indexing-hadoop` optional, even move `indexing-hadoop` to extensions module resemble `kafka-indexing-service`
