### ISSUE TITLE
Segments present in historical local cache but not queryable - index_parallel

### ISSUE THREAD

**Issue by cosmic-chichu** [apache/druid#10652]
Segments present in historical local cache (Segment cache) but not queryable. 

### Affected Version 
0.19.0

### Description

- Cluster size: 2 routers, 4 brokers, 2 overlords, 2 coordinators, 6 historicals, 20 middlemanagers (m5.2xlarge)
Background: After a successful ingestion using index_parallel, I find that for a particular interval (2020-11-18T17:00:00.000Z_2020-11-18T18:00:00.000Z) the UI shows that the segments are used, published and available 
<img width="1654" alt="DRUID_10652" src="https://user-images.githubusercontent.com/1590782/101415425-bc4abb80-389c-11eb-8dab-14d0894d8374.png">

Issue: Although the segments are available I am not able to query data in this interval and it returns empty results. The native segment metadata query for this interval also returns no data. I dug into the historical logs to find interesting events but found none. I'm curious as to what causes this behavior, as it is a potential data loss.

Here's a gist that shows [logs](https://gist.github.com/shrivardhan92/6205640fab3a12442d76532bbf254d66) on different druid processed for a particular segment that belongs to the interval in question.

**Comment by shrivardhan92** [comment]
After some debugging I was able to find out that segments that belong to the particular which are missing. Looking into the [logs](https://gist.github.com/shrivardhan92/1ac94b3c93f007e0e838138fe0b438e1) of the subtask that processed these segments, I find that the subtask failed.

I'm trying to debug the reason for the subtask failure, meanwhile here are some questions:
- why was the task not retried?
- how to track and alert on missing segments, especially for index_parallel jobs?
