### ISSUE TITLE
Support Confluent Schema Registry for Protobuf

### ISSUE THREAD

**Issue by josephglanville** [apache/druid#10665]
### Description

Support looking up Protobuf schemas from the Confluent Schema Registry during streaming ingestion.

### Motivation

This is currently supported for Avro using the Confluent Avro Kafka encoding. Supporting this for Protobuf would ease setup of Druid for those that have already adopted the schema registry and transparently handle schema updates without needing to mirror the proto definition in the ingestion spec or on-disk on the Druid nodes.

**Comment by bananaaggle** [comment]
Hi. I wonder this feature is implemented or just in planning. Can I use this feature in next release?

**Comment by cartermckinnon** [comment]
This is supported, please see: https://github.com/apache/druid/blob/master/docs/development/extensions-core/protobuf.md#when-using-schema-registry

**Comment by josephglanville** [comment]
Indeed, closing as fixed by #10839
