### ISSUE TITLE
Compressed Big Decimal

### ISSUE THREAD

**Issue by senthilkv** [apache/druid#10668]
### Description

Currently in Druid for  aggregation of currency based calculations has to be done using longSum, doubleSum or floatSum.  Especially doubleSum and floatSum could create issues on currency based aggregations such as rounding, truncation etc and cannot be relied up on precision and accuracy which could lead to potential loss in money on aggregation. 

### Motivation

Compressed Big Decimal  is an extension which provides support for Mutable big decimal value that can be used to accumulate values without losing precision or reallocating memory. This type helps in absolute precision arithmetic on large numbers in applications, where  greater level of accuracy is required, such as financial applications, currency based transactions.  This helps avoid rounding issues where in potentially large amount of money can be lost.  Compressed big decimal is an absolute number based complex type based on big decimal in Java. This supports all the functionalities supported by Java Big Decimal.

The extension will be submitted for review in the coming week.

**Comment by 8823Senior** [comment]
Can not found the extension that support big decimal value . Can someone give the document link? 
In addition, when the LongSum exceeds the maximum value, a negative number is obtained. That's not good. How did you deal with this situation?

**Comment by shopee-jin** [comment]
> Can not found the extension that support big decimal value . Can someone give the document link?
> In addition, when the LongSum exceeds the maximum value, a negative number is obtained. That's not good. How did you deal with this situation?


out of curiosity, may I have a look at your bank account  2^63 / 10^6 = 9 trillion VND
