### ISSUE TITLE
Why? I started ues Deep storage is Cassandra ，when i  change Deep storage  For local disk , compact error

### ISSUE THREAD

**Issue by beepupa** [apache/druid#10674]
my conf
![image](https://user-images.githubusercontent.com/36186038/101989332-a09b4700-3cda-11eb-92b5-d68d9e47aace.png)
error
![image](https://user-images.githubusercontent.com/36186038/101989337-ac870900-3cda-11eb-9c18-f914641e0484.png)
![image](https://user-images.githubusercontent.com/36186038/101989350-caed0480-3cda-11eb-9b51-4ff45b7ecd8f.png)

**Comment by beepupa** [comment]
![image](https://user-images.githubusercontent.com/36186038/101989405-13a4bd80-3cdb-11eb-85d9-0d83e9df1f04.png)

**Comment by FrankChen021** [comment]
As @abhishekagarwal87 stated, Cassandra extension must be kept in the `druid.extensions.loadList` in your conf so that old segments could be loaded from Cassandra.

**Comment by beepupa** [comment]
> 使用Cassandra创建的分段作为深度存储，在其负载规格中仍引用Cassandra的位置。当压缩在这些旧段上运行时，由于无法扩展Cassandra路径，因此德鲁伊尝试读取其负载规格并失败。
Thank you for your advice. I'll try

**Comment by beepupa** [comment]
> 如@ abhishekagarwal87所述，必须将cassandra扩展名保留在`druid.extensions.loadList`conf中，以便可以从Cassandra加载旧段。

Thank you for your advice
