### ISSUE TITLE
install mysql problem

### ISSUE THREAD

**Issue by 1findyou** [apache/druid#10673]
### Affected Version

The Druid version 0.18.1.
Mysql: 5.6

### Description

when i run start shell 'start-cluster-master-no-zk-server' , the log says :
Specified key was too long; max key length is 767 bytes [statement:"null", located:"null", rewritten:"null", arguments:null]
and can't visit port 8888

i can't solve this problem, I will be very grateful if you can give me some suggestion.

**Comment by cryptoe** [comment]
I also ran into a similar issue. 
There are multiple approaches mentioned here: https://stackoverflow.com/questions/1814532/mysql-error-1071-specified-key-was-too-long-max-key-length-is-767-bytes

I found the upgrade to MySQL 5.7 the easiest.
