### ISSUE TITLE
Populate Old Segments From Deep Storage

### ISSUE THREAD

**Issue by smit-aterlo** [apache/druid#10684]
Hello,
How can I query old segments which are not available on the disk because of a space issue? I have 2 days' worth of data on the space and an extra 1-2GB of free space but what if I want to query data from 3 days before? All my data is stored on google cloud storage. Currently, I am not able to query any data which segments are not cached on the disk.

In my case data is not available because of space issues. Total data for 2 days comes to around 48GB and disk space is 50GB. This means it will store 2 days of data only on disk but in some cases, we need to query data from before 2 days. 

Thank you

**Comment by abhishekagarwal87** [comment]
This can be done now through Query from deep storage feature available since druid 27.0.0
