### ISSUE TITLE
TIME_CEIL/TIME_FLOOR SQL function throwing error when using origin/timezone

### ISSUE THREAD

**Issue by dayskipping** [apache/druid#10681]
Version 0.18.1

Services
3 overlords, 3 coordinators
3 routers, 3 brokers
8 historicals, 8 middle managers
192 peons
136 running supervisors

When attempting to run a SQL using the TIME_FLOOR/TIME_CEIL functions via the druid console, I am encountering 
an error message. It appears that the TIME_FLOOR/TIME_CEIL functions are not working properly or, quite possibly, I am using them incorrectly. The documentation does not have any specific examples as a guide.

Here is the SQL query:
`
SELECT "price"
            , TIME_FLOOR("__time", 'PT1D', TIMESTAMP '2015-01-01 00:00:00',  'US/Eastern')
            , "__time"
FROM "prod.market.trades.coinbase.validated"
`

Here is the exception:

`Unknown exception / Error while applying rule DruidQueryRule(SELECT_PROJECT), args [rel#256992919:LogicalProject.NONE.[](input=RelSubset#256992912,price=$6,EXPR$1=TIME_FLOOR($0, 'PT1D', 2015-01-01 00:00:00, 'US/Eastern'),__time=$0), rel#256992933:DruidQueryRel.NONE.[](query={"queryType":"scan","dataSource":{"type":"table","name":"prod.market.trades.coinbase.validated"},"intervals":{"type":"intervals","intervals":["-146136543-09-08T08:23:32.096Z/146140482-04-24T15:36:27.903Z"]},"virtualColumns":[],"resultFormat":"compactedList","batchSize":20480,"limit":9223372036854775807,"order":"none","filter":{"type":"selector","dimension":"raw_pair","value":"BTC/USD","extractionFn":null},"columns":["__time","base_asset_id","context","event_id","exchange","is_sell","price","quote_asset_id","raw_pair","sequence_id","time","volume"],"legacy":false,"context":{"sqlOuterLimit":100,"sqlQueryId":"81e37ac4-98a0-44bf-b109-bfa7bf20410a"},"descending":false,"granularity":{"type":"all"}},signature={__time:LONG, base_asset_id:STRING, context:STRING, event_id:LONG, exchange:STRING, is_sell:LONG, price:FLOAT, quote_asset_id:STRING, raw_pair:STRING, sequence_id:LONG, time:STRING, volume:FLOAT})] / java.lang.RuntimeException`

**Comment by FrankChen021** [comment]
In your SQL, `TIME_FLOOR("__time", 'PT1D', TIMESTAMP '2015-01-01 00:00:00', 'US/Eastern')`, the 2nd parameter should be `P1D`. `PT1D` is not a valid period string. See [Duration section](https://en.wikipedia.org/wiki/ISO_8601) in this article.

**Comment by dayskipping** [comment]
> In your SQL, `TIME_FLOOR("__time", 'PT1D', TIMESTAMP '2015-01-01 00:00:00', 'US/Eastern')`, the 2nd parameter should be `P1D`. `PT1D` is not a valid period string. See [Duration section](https://en.wikipedia.org/wiki/ISO_8601) in this article.

Thank you very much for the guidance. I feel silly having missed that detail. Much appreciated
