### ISSUE TITLE
Not closed! Object leaked from StupidPool{name=littleEndByteBufPool, objectsCacheMaxCount=2147483647, poolSize=555}. Allowing gc to prevent leak

### ISSUE THREAD

**Issue by liubo-it** [apache/druid#10706]
@AlexanderSaydakov @gianm @jihoonson

druid version  0.19

My current history node generates a large number of warning logs. Will this affect or is there a problem with my configuration?

![image](https://user-images.githubusercontent.com/58646393/103070233-13ba8c80-45fc-11eb-91a1-45664d6b2cdf.png)

**Comment by liubo-it** [comment]
In use historical jvm.config 

I hope you guys can help. Thx

![image](https://user-images.githubusercontent.com/58646393/103070356-43699480-45fc-11eb-9b2e-64a75b137295.png)

**Comment by AKarbas** [comment]
@liubo-it How was this solved? We're facing the same thing.

**Comment by Stephan3555** [comment]
Same for me, I see a couple of thousand log lines in the historical

**Comment by keminc** [comment]
I got the same, actions on the screenshot didnt help. Anybody fix it?
