### ISSUE TITLE
Redirect URI defaulting to http:// 

### ISSUE THREAD

**Issue by srikanthgunturu** [apache/druid#10703]
I am trying to connect my druid cluster (deployed on AWS) to Azure AD using druid-pac4j.

I had the following entry in runtime.properties in query -> broker

druid.extensions.loadList=["druid-pac4j”,…]
druid.auth.authenticatorChain=["pac4j"]
druid.auth.authenticator.pac4j.type=pac4j
druid.auth.pac4j.cookiePassphrase=passPhrase
druid.auth.pac4j.enableCustomSslContext=false
druid.auth.pac4j.oidc.clientID=xxxxxxxxxxxxxxxxxxxx
druid.auth.pac4j.oidc.clientSecret=xxxxxxxxxxxxxxxxxxx
druid.auth.pac4j.oidc.discoveryURI=https://login.microsoftonline.com/<tenant-id>/v2.0/.well-known/openid-configuration

I am getting the error "The reply URL specified in the request does not match the reply URLs configured for the application:" after authentication. The only issue I can spot is that the redirectURI sent from the application is "http" (Azure AD forces redirect URIs to be "https")
Is it because I have enableCustomSslContext set to false ?

**Comment by sholtoarmstrong-iot** [comment]
I am having the same issue any luck

**Comment by schmichri** [comment]
@srikanthgunturu @sholtoarmstrong-iot Did you succeed in the meanwhile? if yes can you share details?

**Comment by pagrawal10** [comment]
I am also facing a similar issue.

**Comment by vamsikg** [comment]
I have the same issue, where we are using Okta openid. 
cc @himanshug, any hints here?
