### ISSUE TITLE
DoubleFirstAggregatorFactory is not supported during ingestion for rollup

### ISSUE THREAD

**Issue by beepupa** [apache/druid#10702]
version:0.20
![image](https://user-images.githubusercontent.com/36186038/102840150-23d83d80-443d-11eb-9f19-bf687e009fca.png)

**Comment by FrankChen021** [comment]
According to the [doc](https://github.com/apache/druid/blame/master/docs/querying/aggregations.md#L137),
> (Double/Float/Long) First and Last aggregator cannot be used in ingestion spec, and should only be specified as part of queries.

But the web console DOES allow users to configure a metric aggregated as double/float/long first/last. 
![image](https://user-images.githubusercontent.com/6525742/102954111-c102a700-450d-11eb-9ea1-51fa632c77e2.png)

And from the current implementation of backend services, these aggregation are not supported. 

I checked the history of code, and didn't find the reasons why these aggregators are not supported during ingestion for rollup. 

Do you have more background information on this problem @gianm ?

**Comment by suneet-s** [comment]
@FrankChen021 there's some context in #7599 and #10332

The web console shouldn't offer these as options since they are not yet supported at ingestion time.

cc @vogievetsky

**Comment by FrankChen021** [comment]
@suneet-s I see. Are there any progress being made on long/double first/last ? If no, I'd like to take the chance to implement it.

**Comment by beepupa** [comment]
> According to the [doc](https://github.com/apache/druid/blame/master/docs/querying/aggregations.md#L137),
> 
> > (Double/Float/Long) First and Last aggregator cannot be used in ingestion spec, and should only be specified as part of queries.
> 
> But the web console DOES allow users to configure a metric aggregated as double/float/long first/last.
> ![image](https://user-images.githubusercontent.com/6525742/102954111-c102a700-450d-11eb-9ea1-51fa632c77e2.png)
> 
> And from the current implementation of backend services, these aggregation are not supported.
> 
> I checked the history of code, and didn't find the reasons why these aggregators are not supported during ingestion for rollup.
> 
> Do you have more background information on this problem @gianm ?

Thank you for answering my question

**Comment by beepupa** [comment]
> @FrankChen021 there's some context in #7599 and #10332
> 
> The web console shouldn't offer these as options since they are not yet supported at ingestion time.
> 
> cc @vogievetsky

Thank you for answering my question

**Comment by suneet-s** [comment]
> @suneet-s I see. Are there any progress being made on long/double first/last ? If no, I'd like to take the chance to implement it.

@FrankChen021 I'm not aware of anyone working on these issues. Feel free to pick it up - I reviewed the implementation for StringFirst/Last, and would be happy to review these as well
