### ISSUE TITLE
Javascript filter return true when the expression result is false

### ISSUE THREAD

**Issue by qinzhen353** [apache/druid#10719]
### Description
- When use javascript filter below, the result will contains all unit_id the data source has, like the js function always return true.
```json
{
  "type" : "javascript",
  "dimension" : "unit_id",
  "function" : "function(unit_id) { return ['89793647', '89794140'].includes(unit_id); }"
}
```
- But change the filter like below, the result is correct, only contains two unit_id in the js function.
```json 
{
  "type" : "javascript",
  "dimension" : "unit_id",
  "function" : "function(unit_id) { return ['89793647', '89794140'].includes(unit_id) == true; }"
}
```

**Comment by FaxianZhao** [comment]
It seems standard ECMA.
[toBoolean](https://developer.mozilla.org/en-US/docs/Mozilla/Projects/Rhino/Overview#ToBoolean)
