### ISSUE TITLE
Kafka index task is working, how can not found consumer groups 

### ISSUE THREAD

**Issue by zhangyouxun** [apache/druid#10720]
druid version: apache-druid-0.20.0
kafka version: kafka_2.12-2.6.0 

 druid index task is working and can ingest data, but can not found group id by command below
./bin/kafka-consumer-groups.sh --bootstrap-server localhost:9092 --list

**Comment by FrankChen021** [comment]
Druid implements exactly-once consumption by using low level api(such as `assign`, `seek`) of kafka consumer, which means there are no consumer groups created at the kafka broker side to keep the consumer offset.  If you want to check the offset, you could check the status of a supervisor, where 'current offset' and 'lag' are listed.

**Comment by LeeMo2K10** [comment]
How do I set the consumer group name？

"spec": {
    "ioConfig": {
      "type": "kafka",
      "consumerProperties": {
        "bootstrap.servers": "127.0.0.1:9092",
        "group.id": "cg_test"
      },
      "topic": "CLICK_LOG",
      "inputFormat": {
        "type": "json"
      },
      "useEarliestOffset": false
    }


group.id     Not effective, Not effective!!!

can you help me~

**Comment by zhangyouxun** [comment]
> How do I set the consumer group name？
> 
> "spec": {
> "ioConfig": {
> "type": "kafka",
> "consumerProperties": {
> "bootstrap.servers": "127.0.0.1:9092",
> "group.id": "cg_test"
> },
> "topic": "CLICK_LOG",
> "inputFormat": {
> "type": "json"
> },
> "useEarliestOffset": false
> }
> 
> group.id Not effective, Not effective!!!
> 
> can you help me~

consumer group can not be set
