### ISSUE TITLE
Misleading info about tsColumn in the lookups-cached-global docs

### ISSUE THREAD

**Issue by ivan-demchenkov** [apache/druid#10735]
According to the [docs](https://github.com/apache/druid/blob/master/docs/development/extensions-core/lookups-cached-global.md) the extension uses tsColumn to pull only new values:

> The JDBC lookups will poll a database to populate its local cache. If the tsColumn is set it must be able to accept comparisons in the format '2015-01-01 00:00:00'. For example, the following must be valid SQL for the table SELECT * FROM some_lookup_table WHERE timestamp_column > '2015-01-01 00:00:00'. If the tsColumn is set, the caching service will attempt to only poll values that were written after the last sync. If tsColumn is not set, the entire table is pulled every time.

But actually, it just checks if any records were modified using the tsColumn and then if so pulls the whole table anyway. See function **getLookupPairs** in the [code](https://github.com/apache/druid/blob/master/extensions-core/lookups-cached-global/src/main/java/org/apache/druid/server/lookup/namespace/JdbcCacheGenerator.java) - it doesn't use the tsColumn at all.

Not sure if it's a bug in the documentation or in the extension itself.

**Comment by FrankChen021** [comment]
I guess why `getLookupPairs` currently reload the whole table is that if there're records deletions in database, such a full reload could drop those deleted records from cache. Otherwise, if it loads records incrementally by tsColumn,  there must be extra code to check if records in cache have been deleted from database.

**Comment by ivan-demchenkov** [comment]
I thought, and, according to docs, the whole point of having tsColumn is to avoid full reload. Because then it's possible to have a situation when records were deleted, but nothing was modified and it won't reload data. And it's possible to achieve the full reload behavior just by avoiding the tsColumn setting.
