### ISSUE TITLE
Add missing tests and docs for modified query error codes

### ISSUE THREAD

**Issue by a2l007** [apache/druid#10756]
As a follow-up to #10746 , [additional unit tests](https://github.com/apache/druid/pull/10746#issuecomment-759843464) for `JsonParserIterator` are required as well as the query docs(https://druid.apache.org/docs/latest/querying/querying.html)  need to be updated with the latest error codes.
Supporting integration tests would be useful as well

**Comment by suneet-s** [comment]
Added milestone `0.21.0` to this issue, since #10746 is part of the 0.21.0 release
