### ISSUE TITLE
Can't change topic for Kafka supervisor

### ISSUE THREAD

**Issue by Laboltus** [apache/druid#10776]
I try to change Kafka topic in a supervisor specs, but after the change applied, all tasks for the datasource start to fail. 

### Affected Version

Druid 0.20.0

### Description

In the Overlord logs I see the following:

`[WARN] 2021-01-18 11:32:07,351 org.apache.druid.indexing.seekablestream.supervisor.SeekableStreamSupervisor warn - Topic/stream in metadata storage [OLD_TOPIC] doesn't match spec topic/stream [NEW_TOPIC], ignoring stored sequences`

In the metadata storage (mysql) I see the OLD_TOPIC in commit_metadata_payload field of druid_dataSource table.

**Comment by samarthjain** [comment]
You would need to call reset so that all the metadata entries are cleared up.

**Comment by samarthjain** [comment]
See - https://the-asf.slack.com/archives/CJ8D1JTB8/p1607029776321700?thread_ts=1606872457.285100&cid=CJ8D1JTB8

**Comment by Laboltus** [comment]
Unfortunately I have no access to this workspace in Slack.
As for the supervisor reset, I tried to delete old supervisor before send the new one. Should this cleared up the metadata entries ?

**Comment by Laboltus** [comment]
I performed a second Hard Reset when all tasks failed and this helped. Thanks.
