### ISSUE TITLE
Remove ColumnConfig from IndexIO and move column lookup caching decision into query adapter

### ISSUE THREAD

**Issue by xvrl** [apache/druid#1078]
Follow-up to #1076

**Comment by gianm** [comment]
@xvrl are you still interested in this one?

**Comment by xvrl** [comment]
@gianm I believe @cheddar was the one who had requested this as a follow-up but we never got around to it. If someone else wants to take it over, feel free.

**Comment by gianm** [comment]
Oops, hit close by accident.
