### ISSUE TITLE
Add a configuration to define the unified console context path

### ISSUE THREAD

**Issue by jbonofre** [apache/druid#10790]
### Description

Today there's no easy way to change the unified console context path. It would be helpful especially to "expose" the console behind a Apache HTTPd proxy.

### Motivation

It would be helpful especially to "expose" the console behind a Apache HTTPd proxy.

**Comment by ciukstar** [comment]
It would be helpful especially to "expose" the console behind a NGINX reverse proxy.

**Comment by FrankChen021** [comment]
@ciukstar If you're using nginx, you can leverage the NGINX's 'rewrite' to do that. 

For example

```
location ^~/your_context_path/ {
        rewrite ^/your_context_path/(.*)$ /$1 break;
        proxy_pass http://YOUR_DRUID_CONSOLE;
    }
```

**Comment by ciukstar** [comment]
@FrankChen021 Thank you for suggestion. 
But it doesn't work for all API requests (XMLHttpRequest, I guess) like "/status", "/proxy", "/assets/kafka.png", "/assets/s3.png", etc. Of course I handle these cases one by one, but I am not sure that all were resolved.
There are errors at least for "#load-data" and "Druid Doctor" -> "Analyze Druid cluster".
Thanks again.

**Comment by FrankChen021** [comment]
Oh, I get it, the front-end console is not aware of the context path.

**Comment by ciukstar** [comment]
Yes. It seems that Ajax requests are not aware of the context path. Also requests for static assets are not aware of the context path and may interfere with existing client applications (for instance, in my case, an Angular application which also publishes static resources at "/assets")
