### ISSUE TITLE
frontend-maven-plugin issue with mac M1 chip

### ISSUE THREAD

**Issue by AshishKapoor** [apache/druid#10804]
Please provide a detailed title (e.g. "Broker crashes when using TopN query with Bound filter" instead of just "Broker crashes").

### Affected Version

The Druid version 0.20.0 where the problem was encountered.

### Description

Please include as much detailed information about the problem as possible.
- Cluster size NA
- Configurations in use NA
- Steps to reproduce the problem 
  - try to build druid image on the new M1 mac

- The error message or stack traces encountered. Providing more context, such as nearby log messages or even entire logs, can be helpful.
```
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  26.638 s
[INFO] Finished at: 2021-01-27T12:31:39+05:30
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal com.github.eirslett:frontend-maven-plugin:1.6:install-node-and-npm (install-node-and-npm) on project druid-console: Could not download Node.js: Got error code 404 from the server. -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
[ERROR]
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <args> -rf :druid-console
```
- Any debugging that you have already done

**Comment by RomChig** [comment]
Hi everyone, also faced this issue on my mac with m1:
node 10.14.1(tried to use latest as well)
npm 6.4.1
frontend-maven-plugin 1.6
Could anyone suggest smth plz ?)
I'm not using any proxy
Error message: Failed to execute goal com.github.eirslett:frontend-maven-plugin:1.9.1:install-node-and-npm (install node and npm) on project : Could not download Node.js: Got error code 404 from the server.

**Comment by RomChig** [comment]
> Hi everyone, also faced this issue on my mac with m1:
> node 10.14.1(tried to use latest as well)
> npm 6.4.1
> frontend-maven-plugin 1.6
> Could anyone suggest smth plz ?)
> I'm not using any proxy
> Error message: Failed to execute goal com.github.eirslett:frontend-maven-plugin:1.9.1:install-node-and-npm (install node and npm) on project : Could not download Node.js: Got error code 404 from the server.

changing of frontend-maven-plugin version to 1.11.3 helped me

**Comment by asdf2014** [comment]
Closed by https://github.com/apache/druid/pull/11057
