### ISSUE TITLE
Add IPv6 SQL Functions

### ISSUE THREAD

**Issue by smit-aterlo** [apache/druid#10817]
### Motivation

Druid already has IPv4 Functions as follow:

- IPV4_MATCH: Check if IP address belongs to a subnet
- IPV4_PARSE: Convert string IP address to integer
- IPV4_STRINGIFY: Convert integer IP address to string

So adding IPv6 Functions makes it more usable with networking databases.

### Proposed changes

Adding IPv6 Function for SQL as follow:

- IPV6_MATCH: Check if IP address belongs to a subnet

Not adding function to convert into number as IPv6 represents 128bits.

### Rationale

The approach is achieving this by using the library https://github.com/seancfoley/IPAddress as `org.apache.commons.net.util.SubnetUtils` does not provide IPv6 support. I can help to achieve this functionality. If you have any better library to use please suggest.

Thank you

**Comment by gl** [comment]
In https://github.com/apache/druid/pull/11634 @abhishekrb19 has changed the IP library to use an IPv6-compatible one. 

Since then, has there been progress regarding the implementation of IPv6 functions for match & mask ?
