### ISSUE TITLE
Supervisors全部UNHEALTHY_TASKS

### ISSUE THREAD

**Issue by koupeng** [apache/druid#10838]
### Affected Version
**0.20.0**
### Description
{
  "dataSource": "ding_event_details_Ding",
  "stream": "ding_event_details_ding",
  "partitions": 1,
  "replicas": 1,
  "durationSeconds": 3600,
  "activeTasks": [
    {
      "id": "index_kafka_ding_event_details_Ding_868d9d16c5089f9_cjkphlnm",
      "startingOffsets": {
        "0": 8816093
      },
      "startTime": "2021-02-03T00:42:08.484Z",
      "remainingSeconds": 2649,
      "type": "ACTIVE",
      "currentOffsets": {
        "0": 8816093
      },
      "lag": {
        "0": 0
      }
    }
  ],
  "publishingTasks": [],
  "latestOffsets": {
    "0": 8816093
  },
  "minimumLag": {
    "0": 0
  },
  "aggregateLag": 0,
  "offsetsLastUpdated": "2021-02-03T00:57:37.824Z",
  "suspended": false,
  "healthy": false,
  "state": "UNHEALTHY_TASKS",
  "detailedState": "UNHEALTHY_TASKS",
  "recentErrors": [
    {
      "timestamp": "2021-02-03T00:41:02.880Z",
      "exceptionClass": "java.util.concurrent.ExecutionException",
      "message": "org.apache.druid.indexing.common.IndexTaskClient$TaskNotRunnableException: Aborting request because task [index_kafka_ding_event_details_Ding_868d9d16c5089f9_echfiadg] is not runnable",
      "streamException": false
    },
    {
      "timestamp": "2021-02-03T00:41:22.926Z",
      "exceptionClass": "java.util.concurrent.ExecutionException",
      "message": "org.apache.druid.indexing.common.IndexTaskClient$TaskNotRunnableException: Aborting request because task [index_kafka_ding_event_details_Ding_868d9d16c5089f9_hbimfaeb] is not runnable",
      "streamException": false
    },
    {
      "timestamp": "2021-02-03T00:41:42.981Z",
      "exceptionClass": "java.util.concurrent.ExecutionException",
      "message": "org.apache.druid.indexing.common.IndexTaskClient$TaskNotRunnableException: Aborting request because task [index_kafka_ding_event_details_Ding_868d9d16c5089f9_dihacmbj] is not runnable",
      "streamException": false
    }
  ]
}

**Comment by sub007** [comment]
I see the same issue as reported above. 

Here this is what I witnessed -
I've a supervisor running. The task duration is 60mins.
When I check the status of the supervisor, it's UNHEALTHY_TASKS.
The reason for that is (as shown in the supervisor status), some failed tasks in the past and not the recent past. The supervisor has moved on from the time when some tasks failed with concurrent execution exception and has created multiple tasks after that and those tasks have ingested data from corresponding kakfa topic for the task duration set and then terminated. 
But still - all those tasks show their corresponding status as failed. 
I checked the task logs - but I didn't see any errors in the task index logs. 
Nothing in the logs of any of the other services as well.
I understand that, for a Supervisor to move to UNHEALTHY_TASKS status, the successive 3 tasks should end up in failed state. And to return to HEALTHY state, the 3 successive tasks should end up in success.

So, there are two things 
1. Why are all the tasks ending up in failed state but no errors in logs.
2. When I look at the supervisor status, why does it list a set of 3 tasks which have failed with concurrent execution exception long time ago and doesn't list any of the latest failed tasks as the reason for its unhealthy state.
