### ISSUE TITLE
[Question] Some questions about Druid logics

### ISSUE THREAD

**Issue by Gummybearr** [apache/druid#10857]
While studying Druid, I got stuck with some questions. I read the docs a couple of times, but still couldn't come up with a good answer.

1. Druid uses bitmap indexes for query performances, but how does Druid actually parse those indexes? If the bit length becomes big enough, it would be longer than 64 bits, making it hard to use bitwise operation at once.
2. When using Kafka, does Druid make indexes for these data or does Kafka make indexes that Druid can use instead?

Have a great day:)

**Comment by abhishekagarwal87** [comment]
Hi Gummybearr,
1) Druid uses roaring (https://github.com/RoaringBitmap) and concise bitmap for bitmap indexes and these libraries have built-in implementations for and/or 
2) Druid makes these indexes by itself.

**Comment by Gummybearr** [comment]
Thanks a lot Abhishekagarwal87:)
