### ISSUE TITLE
Add RequestLogEvent to Kafka Emitter to Emitter the Request

### ISSUE THREAD

**Issue by coderappee** [apache/druid#10851]
### Description

Sine someone has contributed the basic Kafka Emitter, and Druid itself has implemented the RequestLogEvent to log/emit the request log(especially for the sql logging), it would be better to emit the sql(slow sql) down to kafka.

### Motivation

Enhance Kafka Emitter to emit the Request Logging for the following reasons:
- Emit down the request log to one place(kafka) from diff broker instances.
- Emit down the sql(especially the slow sql) for later analyze.

**Comment by JulianJaffePinterest** [comment]
It looks like you've already started implementing this, but if you're interested the code from #9428 (itself spruced up from #6493) might make this easier for you.
