### ISSUE TITLE
How to debug Peon process?

### ISSUE THREAD

**Issue by xiaohui0318** [apache/druid#10865]
```
cat conf/druid/single-server/micro-quickstart/middleManager/jvm.config 
-server
-Xms512m
-Xmx2048m
-XX:+HeapDumpOnOutOfMemoryError
-XX:HeapDumpPath=/Users/xiaohui/dmp/test/middlemanager/aa.hprof
-XX:+UseG1GC
-Duser.timezone=UTC+0800
-Dfile.encoding=UTF-8
-Djava.io.tmpdir=var/tmp
-Xdebug -Xrunjdwp:transport=dt_socket,server=y,address=8769
```
I added the MM Debug Port, but could not debug to the Peon process that handles index_kafka; Could you please tell me how to set it to debug；Tks !

**Comment by liuxiaohui1221** [comment]
简单点，直接修改_common目录下的日志文件级别就可以

**Comment by yuanlihan** [comment]
hi @xiaohui0318 , you can try [indexer process](https://druid.apache.org/docs/latest/design/indexer.html)

**Comment by xiaohui0318** [comment]
use KafkaIndexTaskTest class done,tks!!!
