### ISSUE TITLE
Is there simple way to get Metadata of Datasource?

### ISSUE THREAD

**Issue by yurim022** [apache/druid#10862]
hi, i'm trying to make some webpage using druid, and i want to get metadata of (dataSourceName, numOfColums, latestUpdate)
which show in imply datasource list. 

I searched druidAPI and what i can found was "/druid/coordinator/v1/datasources?full" .
this API get too much data - every segments of each datasource

so, i wonder if there are some ways to get  (dataSourceName, numOfColums, latestUpdate) with less data.

thank you

**Comment by FrankChen021** [comment]
I think '/druid/indexer/v1/supervisor/history' matches what you need. Its response contains a date formatted string as version and meta data of that version of datasource
