### ISSUE TITLE
Ingestion Data Failing

### ISSUE THREAD

**Issue by Hemant0601** [apache/druid#10873]
**Ingestion Status**

`{
  "id": "index_parallel_inline_data_cionejop_2021-02-10T07:21:02.264Z",
  "groupId": "index_parallel_inline_data_cionejop_2021-02-10T07:21:02.264Z",
  "type": "index_parallel",
  "createdTime": "2021-02-10T07:21:02.266Z",
  "queueInsertionTime": "1970-01-01T00:00:00.000Z",
  "statusCode": "SUCCESS",
  "status": "SUCCESS",
  "runnerStatusCode": "WAITING",
  "duration": 8743,
  "location": {
    "host": "172.31.4.250",
    "port": 8100,
    "tlsPort": -1
  },
  "dataSource": "inline_data",
  "errorMsg": null
}`

**Ingestion Payload**

`{
  "type": "index_parallel",
  "id": "index_parallel_inline_data_cionejop_2021-02-10T07:21:02.264Z",
  "groupId": "index_parallel_inline_data_cionejop_2021-02-10T07:21:02.264Z",
  "resource": {
    "availabilityGroup": "index_parallel_inline_data_cionejop_2021-02-10T07:21:02.264Z",
    "requiredCapacity": 1
  },
  "spec": {
    "dataSchema": {
      "dataSource": "inline_data",
      "timestampSpec": {
        "column": "created",
        "format": "auto",
        "missingValue": null
      },
      "dimensionsSpec": {
        "dimensions": [
          {
            "type": "string",
            "name": "devicetype",
            "multiValueHandling": "SORTED_ARRAY",
            "createBitmapIndex": true
          },
          {
            "type": "string",
            "name": "is_silent",
            "multiValueHandling": "SORTED_ARRAY",
            "createBitmapIndex": true
          },
          {
            "type": "string",
            "name": "key",
            "multiValueHandling": "SORTED_ARRAY",
            "createBitmapIndex": true
          },
          {
            "type": "string",
            "name": "room_name",
            "multiValueHandling": "SORTED_ARRAY",
            "createBitmapIndex": true
          }
        ],
        "dimensionExclusions": [
          "sum_tstamp",
          "tstamp",
          "created",
          "count",
          "siteid",
          "sum_siteid",
          "deviceid",
          "sum_deviceid"
        ]
      },
      "metricsSpec": [
        {
          "type": "count",
          "name": "count"
        },
        {
          "type": "longSum",
          "name": "sum_deviceid",
          "fieldName": "deviceid",
          "expression": null
        },
        {
          "type": "longSum",
          "name": "sum_siteid",
          "fieldName": "siteid",
          "expression": null
        },
        {
          "type": "longSum",
          "name": "sum_tstamp",
          "fieldName": "tstamp",
          "expression": null
        }
      ],
      "granularitySpec": {
        "type": "uniform",
        "segmentGranularity": "HOUR",
        "queryGranularity": "HOUR",
        "rollup": true,
        "intervals": null
      },
      "transformSpec": {
        "filter": null,
        "transforms": []
      }
    },
    "ioConfig": {
      "type": "index_parallel",
      "inputSource": {
        "type": "inline",
        "data": "key,created,deviceid,devicetype,is_silent,room_name,siteid,tstamp\n308-1603825436,2020-10-27 20.03,308,motion,False,TV rum,154,1603825436\n308-1603825721,2020-10-27 20.08,308,motion,False,TV rum,154,1603825721"
      },
      "inputFormat": {
        "type": "csv",
        "columns": [],
        "listDelimiter": null,
        "findColumnsFromHeader": true,
        "skipHeaderRows": 0
      },
      "appendToExisting": false
    },
    "tuningConfig": {
      "type": "index_parallel",
      "maxRowsPerSegment": 5000000,
      "maxRowsInMemory": 1000000,
      "maxBytesInMemory": 0,
      "maxTotalRows": null,
      "numShards": null,
      "splitHintSpec": null,
      "partitionsSpec": {
        "type": "dynamic",
        "maxRowsPerSegment": 5000000,
        "maxTotalRows": null
      },
      "indexSpec": {
        "bitmap": {
          "type": "roaring",
          "compressRunOnSerialization": true
        },
        "dimensionCompression": "lz4",
        "metricCompression": "lz4",
        "longEncoding": "longs",
        "segmentLoader": null
      },
      "indexSpecForIntermediatePersists": {
        "bitmap": {
          "type": "roaring",
          "compressRunOnSerialization": true
        },
        "dimensionCompression": "lz4",
        "metricCompression": "lz4",
        "longEncoding": "longs",
        "segmentLoader": null
      },
      "maxPendingPersists": 0,
      "forceGuaranteedRollup": false,
      "reportParseExceptions": false,
      "pushTimeout": 0,
      "segmentWriteOutMediumFactory": null,
      "maxNumConcurrentSubTasks": 1,
      "maxRetry": 3,
      "taskStatusCheckPeriodMs": 1000,
      "chatHandlerTimeout": "PT10S",
      "chatHandlerNumRetries": 5,
      "maxNumSegmentsToMerge": 100,
      "totalNumMergeTasks": 10,
      "logParseExceptions": false,
      "maxParseExceptions": 2147483647,
      "maxSavedParseExceptions": 0,
      "buildV9Directly": true,
      "partitionDimensions": []
    }
  },
  "context": {
    "forceTimeChunkLock": true
  },
  "dataSource": "inline_data"
}`

**Reports and Logs Show this**

`Request failed with status code 404`

**Comment by Hemant0601** [comment]
I have set the storage type to s3 and restarted my deployments on Kubernetes but still not success .


s3 configurations :

  druid_storage_type: s3 
  druid_storage_bucket: s3_bucket_URI
  druid_storage_baseKey: druid/segments
  druid_s3_accessKey: accesskey_value
  druid_s3_secretKey: secretkey_value

**Comment by sub007** [comment]
If you are worried about this -
> Reports and Logs Show this
>Request failed with status code 404

You shouldn't be. The reason that you see _Request failed with status code 404_ is for the GET request that you made to Druid to get the status.
What Druid does is while the ingestion is in progress, it keeps the logs in temp but once the ingestion completes (success/failure) pushes the logs to the location configured by you using `druid.indexer.logs.type` and the other correspoding `druid.indexer.logs.*` properties. You need to look for a log file something like _index_parallel_inline_data_cionejop_ (based on your logs above) at the location set using `druid.indexer.logs.s3Bucket` assuming you have set `druid.indexer.logs.type` as `S3`.
