### ISSUE TITLE
coordinator-overlord.log so large

### ISSUE THREAD

**Issue by liuchyi** [apache/druid#10879]
### Affected Version

apache-druid-0.20.0

### Description

- druid/single-server/medium

coordinator-overlord.log so large when run it a week later, how to avoid this or reduce the log file size, help please
![image](https://user-images.githubusercontent.com/6964441/107617913-aa660a00-6c8b-11eb-9ae1-305198d35390.png)

**Comment by Gabriel39** [comment]
refer to https://github.com/apache/druid/issues/10127 and https://github.com/apache/druid/pull/10147. Hope to be helpful

**Comment by suneet-s** [comment]
@liuchyi Did you look in the log file. What's filling it up? Is there a repeated error message or stacktrace?
