### ISSUE TITLE
[Question] About Zookeeper Dependency

### ISSUE THREAD

**Issue by jp707049** [apache/druid#10887]
Is there a roadmap for druid to remove zookeeper dependency completely. If so, what will zookeeper be replaced by?

**Comment by Gabriel39** [comment]
k8s, this feature is still experimental now. See more details: https://github.com/apache/druid/pull/10544

**Comment by jp707049** [comment]
- The link you gave is only for Druid Cluster deployed on K8s, right?
- What about a cluster deployed on bare-metal ?

**Comment by himanshug** [comment]
> What about a cluster deployed on bare-metal ?

for now, no. However, in theory, that work does enable writing the extension to support zookeeper-less deployments on non-k8s deployments too.
Caveat is, that would either require either depending on some other consensus system or building one specifically for this which is less desirable.
