### ISSUE TITLE
How can we delete an datasource(unused)?

### ISSUE THREAD

**Issue by catdruid1** [apache/druid#10916]
we can delete unused segments, but how can we delete the datasource?

**Comment by egor-ryashin** [comment]
I wonder if you see the datasource after you have deleted all the segments or it's smth else you're asking?

**Comment by catdruid1** [comment]
Now it is not important, though I can see datasource after I have deleted all the segments.Now I can manage the metadata










At 2021-05-22 03:22:10, "Egor Riashin" ***@***.***> wrote:

I wonder if you see the datasource after you have deleted all the segments or it's smth else you're asking?

**Comment by johnnyflute** [comment]
I think we should add api to delete datasource and all the segment belong to it
