### ISSUE TITLE
Broker throws QueryInterruptedException when querying MiddleManager for GroupBy queries

### ISSUE THREAD

**Issue by mounikanakkala** [apache/druid#10939]
### Affected Version

0.20.0

### Description

{
    "query/time": 60,
    "query/bytes": -1,
    "success": false,
    "identity": "allowAll",
    "exception": "QueryInterruptedException{msg=java.io.IOException: Connection reset by peer, code=Unknown exception, class=java.util.concurrent.ExecutionException, host=xx.xx.xx.xx:8105}",
    "interrupted": true,
    "reason": "QueryInterruptedException{msg=java.io.IOException: Connection reset by peer, code=Unknown exception, class=java.util.concurrent.ExecutionException, host=host=xx.xx.xx.xx:8105}"
}

- Cluster size configuration
    - 4 routers and 4 brokers processes, 6 middle managers instances. Each middle manager seems to be creating 4 peon tasks (although we haven't done any explicit configuration for this)
    
- Steps to reproduce the problem
    - Happens intermittently. 

- Series of events
![Peon Succeeded tasks Redacted](https://user-images.githubusercontent.com/15020965/109724692-ceb75700-7b64-11eb-8afc-b69580f77bd4.png)
    - Ingestion task started at 2021-03-02T00:31:44.995Z on middle manager host xx.xx.xx.xx:**8105**
    - GroupBy Query made to Druid at 2021-03-02T00:35:12.643Z. Intervals in the GroupBy query - "2021-03-01T12:35:12.632Z/2021-03-02T00:35:12.632Z"
    - GroupBy Query fails at Broker due to Connection issue with Middle manager xx.xx.xx.xx:**8105** (as described above)
    - After an hour as shown in the ingestion tasks screenshot, ingestion task completes.

We have seen this issue happen intermittently. Please help us on this issue.

**Comment by FrankChen021** [comment]
According to the exception, the underlying connection between broker and peon was aborted by peon. Have checked the task log to see if there're errors or exceptions at the peon side when query exception occurred ? If no errors occurred at the application layer, it might be caused by some network problems.

**Comment by mounikanakkala** [comment]
Hello @FrankChen021

Thank you for your response. I checked logs on the peon side and I didn't see any errors. Could not find Query ID on thhe peon logs. We received this kind of error 7 times from March 1st to March 8th. Our question is if this has anything to do with how peon tasks are destroyed and recreated (like we observe on the services page that peon task ports availability keeps changing). Or any other underlying design aspect.
