### ISSUE TITLE
Question: am I able to use `x-jackson-smile` over the SQL endpoint?

### ISSUE THREAD

**Issue by EwanValentine** [apache/druid#10931]
As the title says, I'm attempting to query the SQL v2 API endpoint, with `Accept: x-jackson-smile` set, however I get a `406` error. 

Apologies if this is a silly question, new to Druid.

Thanks in advance!

**Comment by FrankChen021** [comment]
The header should be `Accept:application/x-jackson-smile` according to the [doc](https://druid.apache.org/docs/latest/querying/querying.html)

> The Content-Type/Accept Headers can also take 'application/x-jackson-smile'.
> ```
>  curl -X POST '<queryable_host>:<port>/druid/v2/?pretty' -H 'Content-Type:application/json' -H 'Accept:application/x-jackson-smile' -d @<query_json_file>
> ```
> > If the Accept header is not provided, it defaults to the value of 'Content-Type' header.

**Comment by EwanValentine** [comment]
@FrankChen021 that's not for the SQL endpoint though is it?

**Comment by clintropolis** [comment]
Hmm, yeah it actually looks like the SQL endpoint doesn't accept or respond with Smile, https://github.com/apache/druid/blob/master/sql/src/main/java/org/apache/druid/sql/http/SqlResource.java#L85 (compare with native query endpoint: https://github.com/apache/druid/blob/master/server/src/main/java/org/apache/druid/server/QueryResource.java#L174).

I'm unsure if this is an oversight or if there is a reason it is like this.

**Comment by FrankChen021** [comment]
I am so curious that why you want to use smile encoding ?
