### ISSUE TITLE
Encryption and Decryption of data segments in Druid

### ISSUE THREAD

**Issue by averma111** [apache/druid#10959]
Hi Team,

I am looking for options as to have to encrypt and decrypt data segments in Druid. 

I work for the bank and they are looking forward for this encryption and decryption model.

Any help will be appreciated.

Thanks,
Ashish

**Comment by zhangyue19921010** [comment]
What kind of encrypt would you like to use? Batch ingest or Stream Ingest(Kafka/kinesis)?
Is that means Druid ingest encrypt data and decrypt it during ingestion?

**Comment by averma111** [comment]
Encryption of data when they are ingested  in segments and decryption should happen while querying the data either from presto and superset or any other reporting tool connecting to Druid.

**Comment by averma111** [comment]
Also its for both batch and streaming jobs.

**Comment by zhangyue19921010** [comment]
As far as I know, Druid maybe could not ingest and encrypt data after ingest and decrypt data during query. But I think you can use `druid-basic-security` extension to control access and protect your local data(https://druid.apache.org/docs/0.17.0/development/extensions-core/druid-basic-security.html).
As for data in DeepStorage you can enable `druid.storage.sse.type` for S3(https://druid.apache.org/docs/0.17.0/development/extensions-core/s3.html#server-side-encryption)

**Comment by soumyajose0784** [comment]
Does it support server side encryption for GCP bucket as well. Could you share any reference?

**Comment by egor-ryashin** [comment]
Google cloud storage encrypts all data at rest, when you send/recieve data to GCS it's SSL encrypted. To encrypt data during querying you can setup TLS https://druid.apache.org/docs/latest/operations/tls-support.html
