### ISSUE TITLE
How change supervisor' state from UNHEALTHY_TASKS to RUNNING

### ISSUE THREAD

**Issue by 8823Senior** [apache/druid#10972]
have a supervisor of kafka. all is normal. just the kafka' topic have no more message, and the supervisor change to UNHEALTHY_TASKS automatically. 
But, one task of the supervisor is RUNNING, it seem that the task deal with new kafka' message correctly.
What shoud i do so that the supervisor change state from UNHEALTHY_TASKS to RUNNING ?

**Comment by 8823Senior** [comment]
And, the task is running normally and getting correct aggregate value if application product new message to kafka. 
send four message totally, but the supervisor is still UNHEALTHY_TASKS. 
What shoud i do so that the supervisor change state from UNHEALTHY_TASKS to RUNNING ?

**Comment by sub007** [comment]
When a supervisor is posted, it creates a corresponding task(s). In your case, looks like the tasks have failed in the past. 

The supervisor moves to `UNHEALTHY_TASKS` status when the last `druid.supervisor.taskUnhealthinessThreshold` consecutive tasks have all failed. 
The default value for `druid.supervisor.taskUnhealthinessThreshold` is 3. 

The supervisor moves back to HEALTHY status when druid.supervisor.taskHealthinessThreshold consecutive tasks result in success.
The default value for `druid.supervisor.taskHealthinessThreshold` is 3. 

You can try updating the value of druid.supervisor.taskHealthinessThreshold.
