### ISSUE TITLE
Loading local files from UI with Docker image

### ISSUE THREAD

**Issue by Threynaud** [apache/druid#10982]
Hi and thank you for building and maintaining such a great product.

Is it possible to load a file located on my local filesystem from the UIwhen running the docker image? I am using using the `docker-compose.yml` shipped. I would like to experiment with the different options available for the ingestion but I can't manage to make it work on files other than the one used in the quickstart. I guess I have to change how the volumes are mounted but there might be another way.

Thank you very much!

**Comment by sub007** [comment]
@Threynaud : You need to put the files that you want to load at the location mounted in your container usually /opt/data/.
For eg., Location on the host is say /my-data/ loaded to /opt/data/ on the container using docker mount option. Place the file under /my-data/ and refer to the files using /opt/data/.
