### ISSUE TITLE
Option to disable default load options in unified console

### ISSUE THREAD

**Issue by soumyajose0784** [apache/druid#11034]
We have a business requirement to limit load options only to kafka and 'Local' and disable all other options. Is there an option to disable load options 'Reindex from Druid', 'Paste Data' & 'http' from unified console without code change in version 0.18.1?

**Comment by FrankChen021** [comment]
As far as I know, there's no such option to customize these entries at web-console side. 

Even if the options are tailored at web-console side, users could still use task APIs to create tasks to bypass the UI limitation.

**Comment by soumyajose0784** [comment]
thanks for the update @FrankChen021 . 

We were also looking to for option not to show server details in services tab. We tried around restricting role privilege to 'STATE' resource type, that gives 403 on datasources tab too as STATE config controls many endpoints. Is there an option to restrict access only to serverlist?
