### ISSUE TITLE
Error when push data through api 

### ISSUE THREAD

**Issue by quanghuynguyen1902** [apache/druid#11035]
org.apache.druid.java.util.common.ISE: Failed to get locks for intervals[[2021-03-01T00:00:00.000Z

How can I solve the problem ?

**Comment by tanrikut** [comment]
I got the same problem. I submit multiple tasks that will update similar timestamps maybe that is causing this problem but shouldnt druid must handle this?

**Comment by 0xmyk** [comment]
How did you fix the issue?

**Comment by abhishekagarwal87** [comment]
if you are using the latest version and your tasks are appending the data to an interval, you can set `useSharedLock` to `true` in the task context. That way, appending tasks won't compete for the lock for the same interval.

**Comment by deepak6446** [comment]
I did try to implement using multiple retry.
