### ISSUE TITLE
Can provide an API to manually commit an index task?

### ISSUE THREAD

**Issue by xjiaqing** [apache/druid#11050]
### Description
I want to deploy my druid cluster on a spot instance, and my druid cluster uses kafka ingestion. The problem now is that when the spot instance is interrupted, I can only call the API `/druid/indexer/v1/task/{taskId}/shutdown` to manually end the task, which will cause the task to fail. The segment generated by this task will not be submitted.

After the peon is re-created, the previous Kafka data needs to be re-consumed to run the calculation, which is undoubtedly a waste of computing resources

### Motivation

- Is it possible to provide a finish API to enable us to manually commit index task

**Comment by egor-ryashin** [comment]
I wonder if lesser handoff period can help as an alternative solution?
