### ISSUE TITLE
Docker image is broken if container runtime is Containerd

### ISSUE THREAD

**Issue by youngwookim** [apache/druid#11054]
### Affected Version

Druid version <= 0.20.2

### Description

Current docker image created a symlink for the home directory ```/opt/druid``` This causes ```CrashLoopBackOff``` on kubernetes cluster that has the Containerd as a container runtime. Got error messages from pod:

```
(snip)

mkdir: cannot create directory ‘var/tmp’: Permission denied
mkdir: cannot create directory ‘var/druid’: Permission denied
mkdir: cannot create directory ‘var/druid’: Permission denied
mkdir: cannot create directory ‘var/druid’: Permission denied
mkdir: cannot create directory ‘var/druid’: Permission denied
mkdir: cannot create directory ‘var/druid’: Permission denied
```
I've tested with GKE, kubernetes 1.18 + Containerd as a container runtime.

**Comment by FrankChen021** [comment]
Resolved by #11299
