### ISSUE TITLE
Please clear up old Incubator resources

### ISSUE THREAD

**Issue by sebbASF** [apache/druid#11067]
Please remove the following directories:

https://dist.apache.org/repos/dist/release/incubator/druid/
https://dist.apache.org/repos/dist/dev/incubator/druid/

**Comment by clintropolis** [comment]
@sebbASF Sorry about that, I cleared out all of the contents, is there anything else to do to close this out?

**Comment by sebbASF** [comment]
Thanks. The directories are now empty; please also remove them.

**Comment by clintropolis** [comment]
should be good now i think

**Comment by sebbASF** [comment]
Yes, thanks for dealing with this promptly.
