### ISSUE TITLE
Query regarding ingestion rules

### ISSUE THREAD

**Issue by Imran2687** [apache/druid#11072]
### Affected Version

The Druid version where the problem was encountered.
Druid-0.20.1

### Description

Hi,
I am trying to use Druid . I have one question. Suppose there are fields as below

Amount   userName  transactionId

Now i want to ingest data based on sum of amount group by user, but i want store all transaction id as well like . T1,T2,T3... after aggregation. Is it possible to do it in druid?

For example:

Amount   userName  transactionId

10             abc            12
20             abc            13
10             bcd            14

After ingestion row shd be like this

Amount   userName  transactionIds
30             abc              [12,13]
10             bcd              14

**Comment by FrankChen021** [comment]
If you want to keep transaction id,  rollup should be disabled during ingestion. And sum of amount could be got by SQL as  
```
SELECT SUM(Amount), userName FROM you_data_source GROUP BY userName
```

**Comment by suneet-s** [comment]
This would be a nice feature request - to be able to aggregate a string dimension by combining them. I don't believe Druid has this functionality today on either ingestion or query time.

**Comment by Imran2687** [comment]
Thanks @FrankChen021 and @suneet-s , I was going through some query related to this. I believe this feature is still not implemented. @FrankChen021 yes whatever you said i could have done that, i wanted to explore if druid provide such option it can be used by us.

**Comment by FrankChen021** [comment]
@Imran2687 what's your motivation that the transaction ids should be combined together for one user?

**Comment by Imran2687** [comment]
@FrankChen021 : Suppose there are use case where you compute profit and loss of the user. So what i do is i calculate sum of all credits and sum of all debits and find profit and loss. Using rollup it becomes easier we just rollup on the basis of dimension username and transaction Type(credit/debit) , metrics is sum of amount and it works. but doing this we should not consider transaction id as its unique and if we consider it it will be not rolled up. But suppose if we find that the profit and loss is not correct and if we have feature like this to store transaction id(as a concat string or arrays) we can look upon it and calculate easily.This can help us to check correctness.
