### ISSUE TITLE
Is it okay to run overlord service in coordinator?

### ISSUE THREAD

**Issue by jp707049** [apache/druid#11118]
Hello,

- I was going through config files (for `0.20.2`) and saw that by default the `overlord` service runs in the `coordinator` process?
- Same implementation is carried when using `docker`
- Is it okay to run overlord and coordinator in same process or should we keep them separate? 

I'm going through Docker implementation and trying to figure out how to separate this two processes.

**Comment by wangxiaobaidu11** [comment]
You can deploy Overlord and Cooridnator separately
for example：
overlord configuration
![1](https://user-images.githubusercontent.com/24448732/115356301-174ad280-a1ee-11eb-98e1-fbc22d1b6fb3.png)
coordinator configuration
![2](https://user-images.githubusercontent.com/24448732/115356329-216cd100-a1ee-11eb-856f-778c5b00963d.png)

**Comment by jp707049** [comment]
Thanks @wangxiaobaidu11

**Comment by utsavjha** [comment]
@wangxiaobaidu11 Is the Overlord supposed to run on the same port as Coordinator, or on port 8090?

**Comment by FrankChen021** [comment]
> @wangxiaobaidu11 Is the Overlord supposed to run on the same port as Coordinator, or on port 8090?

If `druid.coordinator.asOverlord.enabled` is turned on, overload is also running inside the coordinator process on the same port which is 8081 by default.

**Comment by utsavjha** [comment]
Thats obvious with the bundled run-setting. I meant, if they are running as seperate processes, is the port still required to be the same? That sounds a little fishy to me.

**Comment by FrankChen021** [comment]
It's not required to be the same.

**Comment by shinebayar-g** [comment]
I have a same question. Is it necessary to run Overlord as a standalone process? I was planning to deploy every druid process in a separate node, can't decide whether I should deploy overlord in a separate node or not..

**Comment by utsavjha** [comment]
It's not necessary, but offers greater resilience to your deployment if
seperated. Like mentioned above, just enable the necessary configs and you
can deploy your Overlord and coordinator seperately.
