### ISSUE TITLE
Query like Support for Array_agg

### ISSUE THREAD

**Issue by SwapnaRavi21** [apache/druid#11122]
Is there a way DruidSql supports array_agg or group_concat or listagg operations where the rows can be combined as a comma separated string based on the conditions?

**Comment by jihoonson** [comment]
Hi @SwapnaRavi21, array aggregation will be supported once https://github.com/apache/druid/pull/11104 is merged. I think it will be included in the 0.22 release.

**Comment by SwapnaRavi21** [comment]
Thanks, do you know by when 0.22 release is expected?
