### ISSUE TITLE
Druid Router UI throwing 504 when there are too many tasks

### ISSUE THREAD

**Issue by bharadwajrembar** [apache/druid#11140]
### Affected Version

0.19.1

### Description

We have this use case where we submit 10k+ tasks per day. When loading the Router UI, it usually throws a 504 when loading the `Tasks` tile after a while of waiting. The same happens when we open the `Ingestion` tab as well. 

![Screen Shot 2021-04-21 at 5 59 18 PM](https://user-images.githubusercontent.com/16136496/115553760-67e42d80-a2cb-11eb-9789-06d0703ded78.png)

![Screen Shot 2021-04-21 at 6 13 59 PM](https://user-images.githubusercontent.com/16136496/115555681-661b6980-a2cd-11eb-9c57-e251199467aa.png)

Is there a way to prevent the Router from loading all tasks at once, and rather just lazy load? 

A workaround is to set `druid.indexer.storage.recentlyFinishedThreshold` to a lower value. But we were wondering if there is a better way of doing this.

**Comment by bharadwajrembar** [comment]
The main problem here is that, there is no easy way to get number of tasks by status. We can query the `druid_tasks` table in PostgreSQL but that only gives active tasks by the datasource level and not actually the status [`SUCCESS`, `RUNNING`, `PENDING`, `WAITING`, `FAILED`].

```
\d druid_tasks
                        Table "public.druid_tasks"
     Column     |          Type          | Collation | Nullable | Default
----------------+------------------------+-----------+----------+---------
 id             | character varying(255) |           | not null |
 created_date   | character varying(255) |           | not null |
 datasource     | character varying(255) |           | not null |
 payload        | bytea                  |           | not null |
 status_payload | bytea                  |           | not null |
 active         | boolean                |           | not null | false
Indexes:
    "druid_tasks_pkey" PRIMARY KEY, btree (id)
    "idx_druid_tasks_active_created_date" btree (active, created_date)
```


```
select datasource, count(*) from druid_tasks where active=true group by 1;
```

Is it possible to get the task status without having to parse the `status_payload` or `payload` field?

**Comment by FrankChen021** [comment]
Could you do a test as the comment I left in  #11042 ?

**Comment by bharadwajrembar** [comment]
I believe the `LIMIT/OFFSET` feature is only available from `0.20.0` onwards right?

**Comment by FrankChen021** [comment]
Yeah, I forgot that. 

I checked the code, and think that LIMIT/OFFSET might have nothing to do solve the problem. 

Web console issues a SQL to Druid router to get all tasks, and that SQL would be translated into a HTTP call to overlord to get ALL tasks, and then overlord searches the `druid_tasks` table in metadata storage. During this process, the LIMIT/OFFSET is not passed down to narrow the search range on metadata storage, which means a full scan on metadata storage , and `payload`, `status_payload` deserialization on all returned rows are performed.



Based on the current logic, I need more information from you to make sure deserialization is the bottle neck.
1. how many records in your druid_tasks?
2. how many records  in druid_tasks table where create_date > now() -  druid.indexer.storage.recentlyFinishedThreshold AND active = 0
3. how long will it take if we execute the sql to get all fields on druid_tasks based on the condition given in 2 above ?

**Comment by jasonk000** [comment]
I have done some profiling on our stack here, my analysis follows. We are configured with `HeapMemoryTaskStorage`.

By issuing repeated SQL requests against broker (such as with `ab`) we can see the workload increase on `overlord`. Taking a CPU profile of the overlord host and focusing on the CPU related to the `/tasks` endpoint gives a view that over 50% of the CPU load is in `HeapMemoryTaskStorage::getTasks`, and only a small % of time in serialization.

Notice specifically in the before/after below that the % of time (width of bar) of `getCompletedTaskInfo...` (highlighted in a magenta-ish colour), and that the bulk of the time is in `sortedCopy`.

Before

![image](https://user-images.githubusercontent.com/3196528/118732397-258d0e00-b7ef-11eb-9234-e7f05a40d874.png)

After changes, `getCompletedTaskInfo...`  is significantly reduced as a % of the overall CPU time, so much that serialization is now far larger than the query time.

![image](https://user-images.githubusercontent.com/3196528/118732369-13ab6b00-b7ef-11eb-995b-0be5c9900d12.png)

**Comment by jasonk000** [comment]
@bharadwajrembar regarding your ticket, could you confirm which `druid.indexer.storage.type` was in use in your environment?

@FrankChen021 I have not investigated any metadata store based task storage. Scanning code briefly I do not see any obvious points of contention, however there may be indexing or other query opts required. Perhaps best if we track down if this really is the same issue or a different one, and if it was can they test using the additional fix. (If not, I suppose I'd open a new issue to track heap memory task issue against).

As you say, the [quickstart samples do show that metadata is used for task storage](https://github.com/apache/druid/blob/master/examples/conf/druid/single-server/large/coordinator-overlord/runtime.properties#L33). However, it also seems that the `druid.indexer.storage.type` [documented here](https://druid.apache.org/docs/latest/configuration/index.html#overlord-operations) `local` would be used by default if none other configured.

**Comment by FrankChen021** [comment]
> As you say, the [quickstart samples do show that metadata is used for task storage](https://github.com/apache/druid/blob/master/examples/conf/druid/single-server/large/coordinator-overlord/runtime.properties#L33). However, it also seems that the `druid.indexer.storage.type` [documented here](https://druid.apache.org/docs/latest/configuration/index.html#overlord-operations) `local` would be used by default if none other configured.

You're right. Let's wait to see what storage type is used in this issue.

**Comment by jihoonson** [comment]
Hi @jasonk000, I would like to ask you if there is any reason for using `HeapMemoryTaskStorage`? It has been there mostly for internal testing of other modules that require `TaskStorage` because it's easier to set up than other `TaskStorages` based on databases. AFAIT, it has some flaws that might be a blocker for using in production, such as that it forgets all task history when you restart the overlord.

**Comment by jasonk000** [comment]
@jihoonson To be honest I don't have an answer for this - I'd have to check with @samarthjain.

**Comment by samarthjain** [comment]
@jihoonson - this is probably an artifact of us using the default setting for `default.indexer.storage.type`. You are right that task history is erased on overlord restarts. We have been lucky that we don't have to frequently restart overlord processes. I would assume by using database backed task storage would require its own tuning.  In the past, we have had to tune our RDS a few times for handling segment metadata load.

**Comment by jihoonson** [comment]
I haven't heard of a lot of issues about task storage performance, but think it depends on your ingestion workload. I would suggest switching to a database-backed task storage because you will lose not only task history but also task locks of the tasks currently running. Perhaps losing task history might be forgivable, but losing task locks will make all your tasks failed whenever you restart the overlord.

**Comment by FrankChen021** [comment]
The only performance problem of task storage I heard is about the poor performance when loading tasks from web console task UI as stated in this issue. 

@jihoonson , I think we should make the doc clear that `local` is not suggested in production.

**Comment by jihoonson** [comment]
> @jihoonson , I think we should make the doc clear that `local` is not suggested in production.

It sounds good to me :+1:

**Comment by bharadwajrembar** [comment]
Hey @jasonk000 we're using Postgres on AWS RDS as our `druid.indexer.storage.type` ,ie, `metadata`
