### ISSUE TITLE
sql count(*) returns no results instead of 0 when no rows meet filter

### ISSUE THREAD

**Issue by benkrug** [apache/druid#11145]
A select count(*) will return nothing rather than 0, if no rows pass the WHERE conditions.

Eg, load wikipedia.

`select count(*) from wikipedia`  - returns 24433 (for me, in my load)

`select count(*) from wikipedia where channel = 'abc'`  - returns nothing, not 0.

This is true running in the console, or using the API.  There I get `[{"EXPR$0":24433}]` for the first query, and `[]` for the second.

**Comment by karthikbhat13** [comment]
Hey, can I take this up if it isn't a problem?

**Comment by clintropolis** [comment]
>Hey, can I take this up if it isn't a problem?

Oops, I think I have solved this with #11188, which I just did as an offshoot of #11157 before I noticed this ticket. I hope you didn't get too far into working on this, my apologies for not searching open issues before hacking on stuff.
