### ISSUE TITLE
Docker docker image Error 

### ISSUE THREAD

**Issue by mail2shobz** [apache/druid#11177]
I have tried pulling the docker image via this docker file from the docker registry which is mentioned in the docker compose 
but it says like "MANIFEST FILE NOT FOUND"

Please provide a detailed title (e.g. "Broker crashes when using TopN query with Bound filter" instead of just "Broker crashes").

### Affected Version

The Druid version where the problem was encountered.

### Description

Please include as much detailed information about the problem as possible.
- Cluster size
- Configurations in use
- Steps to reproduce the problem
- The error message or stack traces encountered. Providing more context, such as nearby log messages or even entire logs, can be helpful.
- Any debugging that you have already done

**Comment by FrankChen021** [comment]
which version of docker images did you pull ?

**Comment by mail2shobz** [comment]
From the master branch 

Image : **apache/druid:0.22.0**

**Comment by mail2shobz** [comment]
This is the error which i was getting  when trying to pull ."Error response from daemon: manifest for apache/druid:0.22.0 not found: manifest unknown: manifest unknown"

**Comment by FrankChen021** [comment]
0.22.0 have not been released.

You should use the docker-compose.yml file on any released branches. 
Note: there's a problem about docker images in 0.21.0, see its [release note](https://github.com/apache/druid/releases/tag/druid-0.21.0) for more information.

**Comment by mail2shobz** [comment]
Could you please letme know which is the stable version. also what is the minimum hardware requirement for running it in a docker container

**Comment by FrankChen021** [comment]
you could use 0.20.2. And see the [doc](https://druid.apache.org/docs/latest/tutorials/docker.html) for memory requirement
