### ISSUE TITLE
404 Not Found for Kubernetes Extension Docs `0.21.0`

### ISSUE THREAD

**Issue by jp707049** [apache/druid#11175]
Hello
@jihoonson , @himanshug 

- Getting 404 Not found error for Kubernetes Extension docs.
- Link got from release notes (https://github.com/apache/druid/releases/tag/druid-0.21.0)
- Also I cannot see extension in https://druid.apache.org/docs/latest/development/extensions.html
https://druid.apache.org/docs/latest/development/extensions-core/kubernetes.html

Thank you

**Comment by jp707049** [comment]
There is no options for `extensions-core` under `development` in docs.
![image](https://user-images.githubusercontent.com/26424594/116344774-7cad4d80-a804-11eb-9077-cdef6fdffe2d.png)

**Comment by jp707049** [comment]
Found the issue.

In `kubernetes.md` the current `id` is `druid-kubernetes` and following link is working
https://druid.apache.org/docs/latest/development/extensions-core/druid-kubernetes.html

For this link (https://druid.apache.org/docs/latest/development/extensions-core/kubernetes.html) to work `id` should be `kubernetes`

**Comment by jihoonson** [comment]
Thanks! I temporarily modified the link in the release notes.

**Comment by himanshug** [comment]
thanks @jp707049  and @jihoonson

**Comment by jihoonson** [comment]
I updated docs.
- https://druid.apache.org/docs/latest/development/extensions.html
- https://druid.apache.org/docs/latest/development/extensions-core/kubernetes.html
