### ISSUE TITLE
docker-compose try to pull 0.22 which is not available

### ISSUE THREAD

**Issue by sujeshchirackkal** [apache/druid#11305]
```
$ docker-compose up -d
Creating network "docker_default" with the default driver
Pulling coordinator (apache/druid:0.22.0)...
ERROR: manifest for apache/druid:0.22.0 not found: manifest unknown: manifest unknown
```

**Comment by FrankChen021** [comment]
Please use the docker-compose.yml on a released version(e.g. 0.20.0, 0.21.0).

**Comment by sujeshchirackkal** [comment]
Thanks @FrankChen021 . However, there is another error coming up. It is attempted with 0.21 branch.

entrypoint script is trying to create a few directories inside the container, as user druid and seems there is permission issue. Am I doing something wrong here ??

router           | Setting druid.metadata.storage.connector.password=FoolishPassword in /tmp/conf/druid/cluster/query/router/runtime.properties
router           | Setting druid.emitter.logging.logLevel=debug in /tmp/conf/druid/cluster/query/router/runtime.properties
router           | mkdir: can't create directory 'var/tmp': Permission denied
router           | mkdir: can't create directory 'var/druid/': Permission denied
router           | mkdir: can't create directory 'var/druid/': Permission denied
router           | mkdir: can't create directory 'var/druid/': Permission denied

**Comment by FrankChen021** [comment]
0.20.2 is recommended. This is a bug of 0.21.0, it has been addressed on the master branch , and a bug fix release is on the way. See #11166

**Comment by sujeshchirackkal** [comment]
Thanks @FrankChen021 `0.20.2` is working fine
