### ISSUE TITLE
Facing problem in configuring druid to query data

### ISSUE THREAD

**Issue by tejaskumar-cm** [apache/druid#11371]
Hi Team,
We are extracting and storing events in druid. In a day there will be nearly **6 million records**, which is of size **9GB/day**, and there are around **200 columns** in the table.

We are storing the data directly connecting to kafka and facing no problems in storing the data in druid.
But when we are trying to retrieve this data using Druid SQL query, we are getting error and **not even able to query 1 million record** at a time.
We tried different druid configuration as per the doc, but nothing helped us.

**Can anyone guide us through the master, query and data server capacity required to handle this much of data, and also the druid configuration of each servers respectively?**

I tried to find solution in different forum and didn't get any solution and hence I am posting a message here.
Below I have attached some error I saw when I ran the query.

1) Console error
![image](https://user-images.githubusercontent.com/57861380/122509475-788df700-d021-11eb-8ba3-f147b0c2a999.png)
![image](https://user-images.githubusercontent.com/57861380/122509500-85124f80-d021-11eb-9972-d8fc58d6dfb9.png)

2) Druid broker.log
![image](https://user-images.githubusercontent.com/57861380/122509540-98251f80-d021-11eb-95fe-2dab7ba5cf2f.png)
![image](https://user-images.githubusercontent.com/57861380/122509564-9f4c2d80-d021-11eb-84f1-8eef72574dab.png)

3) historical.log
![image](https://user-images.githubusercontent.com/57861380/122509589-ac691c80-d021-11eb-9162-04a08301c96d.png)

**Comment by FrankChen021** [comment]
the log that you attached is related to the first console error or the 2nd ? And could you attach more log from historical ?

For the 2nd error, I think you cold narrow down the search time range, say 1 hour interval, to see if this error still exist. If not exist, you should turn up those two parameters given in the exception message.

**Comment by tejaskumar-cm** [comment]
Hi @FrankChen021 
Thanks for the reply.

The log I attached is related to 1st console error, and apart from that there are no error in any log file.

Regarding second console error when I narrow down the time range, I am not getting the error. I will look into those parameters.

But my major concerns is I am not able to query even a single day data completely.
So, I wanted to understand the server capacity required and the configuration I should look into to query mentioned data size.

**Comment by FrankChen021** [comment]
For the 1st problem, does this problem occur every time the query is issued ? You could try to issue a query from any http client tool to druid brokers directly to see if the problem still there. 
For the 2nd problem, obviously the default configurations do not suit for you. groupBy queries consume more resources, you could also check the [groupBy query doc](https://druid.apache.org/docs/latest/querying/groupbyquery.html) for more information.

**Comment by tejaskumar-cm** [comment]
For the 1st problem, I tried using both SQL and http client. In both the cases, whenever I am running the query i am getting the error.
This is the first time I am using and configuring druid db. So, wanted to understand and try to get a benchmark to understand for the data I am handling how much should be my server capacity and what and all the configurations I should change to tune druid for that server.
Any help on this will help me a lot.

**Comment by FrankChen021** [comment]
For the 1st problem, I have no idea why this happen and the historical log shows no more information to pinpoint where and why the exception occurs. Since the SQL in the 2nd problem could be executed successfully( at least the SQL is executed to reach internal resource limit), I'm wondering if this problem is only related to this `mriprodstream` data source ?
