### ISSUE TITLE
Security on a Druid Datasource

### ISSUE THREAD

**Issue by Murthy7587** [apache/druid#11383]
Hi All,

I needed to know if we can have a security layer for a datasource in Druid.

We have a scenario where we need to restrict a user to access a datasource. Any idea how we can achive that ?

Regards,
Akhilesh

**Comment by jp707049** [comment]
Hi,

Check this out - https://gist.github.com/davidagee/c0c839cd23f047b838e8a3ea73320346

Also go through official docs - https://druid.apache.org/docs/latest/development/extensions-core/druid-basic-security.html#usage
