### ISSUE TITLE
The job going in pending status in Druid. 5 jobs running and 4 peons available and 1 job in pending status

### ISSUE THREAD

**Issue by KPriya08** [apache/druid#11381]
I am streaming data from 5 kafka topics, but only 4 jobs run at a time and 1 go in pending status and it will start running when one of the jobs finishes. I checked in sys.tasks and see that for the pending task, the location and port is null and I see that only 4 ports are running. I confirmed from the services section on the druid web console that 4 peons are running. How can I make the pending job run? I need all my jobs to run parallely. By increasing the peons? But How can I increase the peons? Can I do this using druid.indexer.runner.ports ?
I have installed druid using helm charts and this config is not there in the values.yaml file. How can I set this if it can fix my problem. Otherwise, how can I fix this issue?

**Comment by FrankChen021** [comment]
It seems that `druid.worker.capacity` is set to 4. I don't know Helm Charts well, maybe @asdf2014 knows how to modify this configuration.

**Comment by KPriya08** [comment]
Thanks for that. But I am still looking for the right config at Helm charts. Can anyone help?

**Comment by asdf2014** [comment]
Hi, @KPriya08. You can modify the configuration of Helm Chart in the `values.yaml` file.
