### ISSUE TITLE
Not realy work on kubernetes

### ISSUE THREAD

**Issue by wemod123** [apache/druid#11391]
Awesome Project, and  titled as scalable etc. key feature,

But until now I didn't find a robust way to deploy druid really work on kubernetes.

What I had tried:
1. Deploy with helm chart, with [helm incubator druid chart](https://github.com/helm/charts/tree/master/incubator/druid), but not work, cannot even create pod, error happend as [this issue](https://github.com/apache/druid/issues/11305#issuecomment-849310118)
    Update the image tag from default 0.19.0 to latest 0.21.1, the above error disappeared, and everything seems ok, by can not run task, the segments available is always [0.0% available], I check over logs with limited knowledge, but didn't find proper logs, e.x. under var/druid/*, or /opt/druid/*  dirs  

2. Depoly with [chart under repo](https://github.com/apache/druid/tree/master/helm/druid), almost get same results as above.

3. Check the  [official document](https://druid.apache.org/docs/latest/development/extensions-core/kubernetes.html#configuration), didn't really get it running, and it say EXPERIMENTAL, mean not ready for kubernetes?

4. Check the [druid operator](https://github.com/druid-io/druid-operator), but there is no really full documentation, just some test, mean this is in test phase?

Any one really succeed to run druid on kubernetes in production?
Please help if you have the succeed experience.

**Comment by AdheipSingh** [comment]
as far as the druid operator is concerned it is production ready. Documentation is present to get started and deployed.
https://github.com/druid-io/druid-operator/tree/master/docs
