### ISSUE TITLE
helm chart fix/update

### ISSUE THREAD

**Issue by oliverdding** [apache/druid#11421]
### Description

As you can see, druid's helm chart was migrated from [incubator](https://github.com/helm/charts/tree/master/incubator/druid) which has been deprecated since Nov 13, 2020, and migration is not down yet, making it not easy to use.

### Motivation

1. [x] Remove licence comment at the beginning of template files, which make chart not deployable. [reference](https://stackoverflow.com/a/63383447/13760009).
2. [x] Remove sub-charts. Helm chart offered by official should include minimal dependency, and others should be tailored by user themself.
3. [x] Remove some configs that has default value. Example: `druid.processing.numMergeBuffers`. It's default value is `max(2, druid.processing.numThreads / 4)`, which is calculated in the code if user does not offer it, but in this chart it is given, which forces user to give a specific value.
4. [x] Move `druid.segmentCache.locations` default value to the mounted path.
5. [x] Add hdfs's mount point in historical node and middlemanager node.

I would like to commit my fix to it, if permitted.

**Comment by asdf2014** [comment]
Hi, @oliverdding. These are all excellent ideas, and I agree with you.
