### ISSUE TITLE
Batch ingestion fails for CSV's embedded newline characters

### ISSUE THREAD

**Issue by n4j** [apache/druid#11491]
When CSV files contains new line characters (wrapped in quotes), Druid is not able to handle it properly and the ingestion fails, this issue is similar to https://github.com/apache/druid/issues/3376

### Affected Version

0.19.0

### Description
We ingest several CSVs into Druid and often these CSVs have new line in the row values e.g.

```
__time,first_name,last_name
2020-01-01,"shah","nee
raj"
```
While all CSV parsers (Jackson for example) and Spreadsheet tools (Excel) are able to parse it correctly, Druid treats it as two rows which leads to inconsistent state. If `fail on parse` is enabled then Druid throws an exception similar to shown below
```
org.apache.druid.java.util.common.parsers.ParseException: Unparseable timestamp found! Event: 
{__time=raj, first_name=null, last_name=null}
```

cc: @bharadwajrembar

**Comment by bananaaggle** [comment]
Actually, Druid will separate input as lines by '/n' first, then it use `com.opencsv` library to parse line. This process is the same both in `parser` and `inputformat`.

**Comment by aclwitt** [comment]
> Actually, Druid will separate input as lines by '/n' first, then it use com.opencsv library to parse line.

Is this intended, or are there any workarounds? Loading CSVs with an embedded newlines (wrapped in quotes) seems like a reasonable use-case.

**Comment by FrankChen021** [comment]
> > Actually, Druid will separate input as lines by '/n' first, then it use com.opencsv library to parse line.
> 
> Is this intended, or are there any workarounds? Loading CSVs with embedded newlines (wrapped in quotes) seems like a reasonable use-case.

I think when the CSV parser is designed, it is not expected that a row spans multiple lines. Even though the underlying parser that is used by Druid supports data in multiple lines, due to the highly abstraction of parser, it's a little bit difficult to make changes to current CSV parser to support such feature.
