### ISSUE TITLE
Non leaders of Coordinator and Overlord should proxy HTTP requests to the leader.

### ISSUE THREAD

**Issue by didip** [apache/druid#11512]
### Description

Non leaders of Coordinator and Overlord should proxy all HTTP requests to the leader and proxy back the HTTP response instead of performing redirections.

### Motivation

If this feature exists, end users can put a regular load balancer such as Nginx on top of Coordinator and Overlord.

**Comment by FrankChen021** [comment]
Druid's router routes requests to leader coordinator and overlord, but this requires router deployed. Since router is optional, such proxy from non-leader nodes to leader nodes makes sense.
