### ISSUE TITLE
Druid SQL returns way less data than what's on S3.

### ISSUE THREAD

**Issue by didip** [apache/druid#11535]
### Affected Version

0.21.1

### Description

I see that we have way more data on the S3 folders but this query returns way less number of days. 

I should already have the full July dates but many of them are missing in my query.

```sql
SELECT DATE_TRUNC('day', "__time") as "day", SUM("count") as "count"
FROM "mytable" GROUP BY DATE_TRUNC('day', "__time") order by DATE_TRUNC('day', "__time") DESC
```

**Table:**
... Where's the rest of the days? ...
2021-07-15T00:00:00.000Z    00000000001979009692
... Where's the rest of the days? ...
2021-07-11T00:00:00.000Z    00000000001693378623
... Where's the rest of the days? ...

I also unchecked these 3, but the result is the same:
<img width="353" alt="Screen Shot 2021-08-02 at 4 48 18 PM" src="https://user-images.githubusercontent.com/72918/127937122-c35fa40a-d420-441c-bb45-e438f7b8db86.png">

All my tables are shown as "Fully Available"

**Comment by bananaaggle** [comment]
Is this data loaded by batch job? If it was a batch job, `appendToExisting` in IOConfig is true or false?

**Comment by didip** [comment]
Data is loaded by batch job, I will check the IOConfig.

**Comment by didip** [comment]
`appendToExisting` is not defined, so by default it's `false`.

**Comment by bananaaggle** [comment]
> `appendToExisting` is not defined, so by default it's `false`.

I think some data is overwrited, you can set it be `true` and test.

**Comment by didip** [comment]
This problem seems to happen when user sets `maxNumConcurrentSubTasks` really high, for example: 100 or 200.

**Comment by didip** [comment]
Tried `appendToExisting: true`. The ingestion is successful but data is still not queryable.

Forgot to mention, the `partitionSpec` is `dynamic`.

**Comment by bananaaggle** [comment]
Is there some error log in ingestion or query process? Can you reproduce it stably?

**Comment by didip** [comment]
Yes, this has been happening the last 3 weeks actually. Every ingestion is successful, data appears on S3, but unquery-able.
The input data is huge, 3.5TB per day, this is why we desperately need high number of parallelism to have an acceptable SLA.

When the task UI was working, every single log from index_parallel and sub_tasks are clean, they all finished successfully.

I am currently unable to load the tasks UI because there are way too many druid_tasks records in the DB, thus I cannot get the latest logs.

**Comment by didip** [comment]
if you can produce fake data with > 4000 parquet files and run ingestion with 200 parallelism, I think you can reproduce this issue.

**Comment by bananaaggle** [comment]
Can you set 'reportParseExceptions` be true in you tunningConfig? It will allow you catch exception when some trouble happened.

**Comment by didip** [comment]
Thank you for the suggestion, will try it asap

**Comment by didip** [comment]
I rebuilt my middle managers, deleted everything inside druid_tasks, druid_tasklocks, druid_tasklogs, deleted the local files in middle manager hosts, starting only 1 index_parallel task with 200 parallelism.

So far, I do not see a single error in some of the sub_task logs that I randomly picked, the index_parallel logs looked good so far as well, not a single error.

**Comment by bananaaggle** [comment]
What is the result? SQL returned less data again?

**Comment by didip** [comment]
The `index_parallel` job finished in 6 hours. This is good, that means 200 parallelism works to speed up ingestion.

The log is super clean. Unfortunately I saw this in the log:
```
2021-08-11T05:01:18,381 WARN [task-runner-0-priority-0] org.apache.druid.indexing.common.task.batch.parallel.ParallelIndexSupervisorTask - maxParseExceptions is not supported yet
2021-08-11T05:01:18,381 WARN [task-runner-0-priority-0] org.apache.druid.indexing.common.task.batch.parallel.ParallelIndexSupervisorTask - logParseExceptions is not supported yet
```
But everything finished successfully.
```
2021-08-11T11:19:17,142 INFO [task-monitor-0] org.apache.druid.indexing.common.task.batch.parallel.TaskMonitor - [4000/4000] tasks succeeded
```

**Comment by didip** [comment]
wow, data appeared on that timestamp! (20210807). So, if I trace my steps backward, it seems to me the cause of this issue is Overlord and Middle Managers instability:
* Not enough ram for Overlord for a while.
* druid_tasks table was too big.

**Comment by bananaaggle** [comment]
It sounds like system resource limit cause some stability trouble, but I'm not sure about it. If you meet this problem again, you can record it in this issue.

**Comment by bananaaggle** [comment]
> The `index_parallel` job finished in 6 hours. This is good, that means 200 parallelism works to speed up ingestion.
> 
> The log is super clean. Unfortunately I saw this in the log:
> 
> ```
> 2021-08-11T05:01:18,381 WARN [task-runner-0-priority-0] org.apache.druid.indexing.common.task.batch.parallel.ParallelIndexSupervisorTask - maxParseExceptions is not supported yet
> 2021-08-11T05:01:18,381 WARN [task-runner-0-priority-0] org.apache.druid.indexing.common.task.batch.parallel.ParallelIndexSupervisorTask - logParseExceptions is not supported yet
> ```
> 
> But everything finished successfully.
> 
> ```
> 2021-08-11T11:19:17,142 INFO [task-monitor-0] org.apache.druid.indexing.common.task.batch.parallel.TaskMonitor - [4000/4000] tasks succeeded
> ```

It's my fault. `index_parallel` doesn't support `maxParseExceptions` and `logParseExceptions`.
