### ISSUE TITLE
Ability to run integration tests without tls

### ISSUE THREAD

**Issue by churromorales** [apache/druid#11564]
Right now integration tests can't run against an existing cluster that doesn't have tls.  Although it states in the README.md that running against the quickstart cluster with additional configurations can do so, that doesn't seem to be the case. 

It would be a really useful feature to have the integration tests be able to run against an existing druid cluster one may have.  With or without tls enabled. 

The offending module is the `SSLContextModule`, when this gets loaded you are forced to go into tls mode.  If we comment out the configure method, then we can run without tls, but seems like it would be nice to have this built into the integration test framework itself.

Druid Version Tested: 0.21.2

**Comment by maytasm** [comment]
What command are you using to run the integration test? You should be able to specify individual test group.

**Comment by churromorales** [comment]
`mvn verify -P int-tests-config-file -Dgroups=quickstart-compatible`  (Did this because docs said they could run without tls)

also added to my config: `*_tls_url` to be the same as my service url.  I noticed SSLContextModule seems to load no matter what params I passed, is there something I am missing or doing wrong here. 

Thank you

**Comment by maytasm** [comment]
Do you mean that the SSLContextModule is loaded on your Druid cluster?

**Comment by churromorales** [comment]
No, from what I saw, the test framework is loading it when creating an http client to communicate with the configured druid cluster.

**Comment by maytasm** [comment]
I was able to run the integration test as per the instruction.
Here is the command I use to run from {DRUID_HOME} root directory:
`mvn -B verify -pl integration-tests -P int-tests-config-file -Dgroups=quickstart-compatible -Djvm.runtime=8 -Pskip-static-checks -Ddruid.console.skip=true -Dmaven.javadoc.skip=true`
Can you try run with that command? If you still see the same error, can you attach the log from the test console? Thanks
