### ISSUE TITLE
index_parallel ingested Iceberg's Parquet files successfully but I don't see any data on S3 and PostgreSQL

### ISSUE THREAD

**Issue by didip** [apache/druid#11571]
### Affected Version

0.21.1

### Description

I was running a small index_parallel to consume 400 Parquet files inside Iceberg's S3. The ingestion finished successfully in less than 20 minutes. But I see no data files on S3 and PostgreSQL. What could possibly happen here?

The ingestion logs looks clean.

**Comment by bananaaggle** [comment]
I guess parse failed. Set `reportParseExceptions` and `logParseExceptions` be true may help find out what happened.
