### ISSUE TITLE
Query with COUNT(*), nested sub-query returns no results

### ISSUE THREAD

**Issue by paul-rogers** [apache/druid#11586]
Query with COUNT(*), nested sub-query returns no results

### Affected Version

Version: 0.21.

### Description

Consider the "stock" Wikipedia data source and stock Docker Druid cluster.

The query is designed to identify the number of rows that would result from building a new roll-up table with just three of the dimensions:

```sql
SELECT COUNT(*)
FROM (
  SELECT hr, channel, page, COUNT(*) AS cnt
  FROM (
    SELECT
      DATE_TRUNC('hour', __time) AS hr,
      channel,
      page
    FROM "wikiticker-2015-09-12-sampled"
  )
  GROUP BY hr, channel, page
)
```

The query returns zero rows.

However, replace the `count(*)` with `*` and we get many rows of results. (The rows give the expected number of rows per group in the new roll-up datasource.) Since a `SELECT *` query returns rows, expected the `COUNT(*)` to count those rows.

A workaround is to use the form which works, and to count the rows in the client.

**Comment by SharuBob** [comment]
@paul-rogers did you find any solution for the above issue. Looks like I have reported more or less same issue [here](https://github.com/apache/druid/issues/11603)

**Comment by paul-rogers** [comment]
@SharuBob, thanks for pointing out the related issue. As it turns out, the query I'm using has no `HAVING` clause. In my case, the issue seems related to the nested queries. However, you may be right that both are symptoms of the same underlying issue, perhaps in the Calcite planner.

The solution I used is simply to omit the outer `COUNT(*)` and have the client do the counting. Doing so is inefficient, and may not scale to huge data sets. But, it was a quick & dirty work-around for my specific use case.

**Comment by SharuBob** [comment]
@paul-rogers Thank you for the reply again. Even I have made more or less same short term work around, will still use subquery to fetch one of the columns and then do the len(array) at client side to get the count. 

Hope this will be addressed in the coming days. 🙏

**Comment by kxbin** [comment]
**I found that if the dataset is 0 rows**

**The result of count(*) is not 0, but returned no data.**

![image](https://user-images.githubusercontent.com/17782922/150307077-85e8b016-5464-4113-a8aa-f11f0d77c9cc.png)
