### ISSUE TITLE
Project Structure of Apache Druid

### ISSUE THREAD

**Issue by jp707049** [apache/druid#11599]
Hi,

The current structure for druid project is like following:
```
druid
    |- core
    |- indexing-service
    |- processing
    |- server
    ...
    ...
```
Is there is reason why the above project structure was done in particular?
<hr/>

Can't we have the following project structure for druid?
```
druid
    |- historical
        |- package/modules related to historical
    |- broker
        |- package/modules related to broker
    |- coordinator
        |- package/modules related to coordinator
    |- extensions-*
    ...
    ...
```

Any background information would be great to know, how the project structure layout was decided.

Thank you

**Comment by jp707049** [comment]
@jihoonson Any thoughts on above question would be greatly appreciated.

**Comment by johnnyflute** [comment]
The project structure confuse me too

**Comment by jp707049** [comment]
@johnnyflute , Here is the [link](https://lists.apache.org/thread.html/rb3d9658b70ed21aba4a1d8e2b88745daddac9aa37254a1fc3b017350%40%3Cdev.druid.apache.org%3E) to dev list for the same question asked and got a reply from Gian.
