### ISSUE TITLE
Druid hadoop version supports hadoop3.2.1 version

### ISSUE THREAD

**Issue by wangxiaobaidu11** [apache/druid#11616]
### Description

Our hadoop version has been upgraded from 2.7.3 to 3.2.1, so we modified druid hadoop verson to fit  hadoop cluster.

**Comment by bananaaggle** [comment]
I think guava is one of barrier of this action. [10964](https://github.com/apache/druid/pull/10964) mentioned it.

**Comment by wangxiaobaidu11** [comment]
Thank you for your tip. I have updated a version  and  tested it. [https://github.com/apache/druid/pull/11667](url)
