### ISSUE TITLE
TRIM help broken in Console SQL Editor

### ISSUE THREAD

**Issue by techdocsmith** [apache/druid#11625]
Relates to #11619 . The syntax for TRIM was broken in the docs & didn't display in the UI. The change in #11619 displays in the console, but it renders the HTML `<code>` tag as text instead of translating to HTML/`|` as in the docs.:

<img width="503" alt="Screen Shot 2021-08-23 at 11 20 12 AM" src="https://user-images.githubusercontent.com/44787917/130497289-03f10832-8023-466c-b2ca-014313d121c9.png">

### Affected Version

0.22.0

**Comment by bananaaggle** [comment]
I fix it in [11628](https://github.com/apache/druid/pull/11628). But I'm not sure this change is safe.
