### ISSUE TITLE
Why middlemanager termination does not commit the data

### ISSUE THREAD

**Issue by madan522** [apache/druid#11629]
I have S3 storage and druid setting that all tasks commits data to S3 once in an hour. 
For some reason, if middlemanager restarts, I get all tasks in FAILED state and data not commited to s3. 
Is there a way that make sure that data is commited to s3 if middlemanagers wants to terminate?

**Comment by spinus** [comment]
@madan522 does it ends up in data loss or middlemanager persist data in temporary storage and you can restart tasks later?
