### ISSUE TITLE
Cannot see the logs of FAILED Task

### ISSUE THREAD

**Issue by FernandoDorado** [apache/druid#11661]
During data ingestion from kafka, some of the tasks are in FAILED status, but when I try to see the log of why they failed to debug I get the following error: Request failed with status code 404. I have accessed inside the container to see the logs of that task, but I don't see any folder for that ID the tasks that have failed, which happens with the tasks that have been successful. 

### Affected Version
apache/druid:0.21.1

### Description

Please include as much detailed information about the problem as possible.
Docker implementation using containers
- 3 zookeeper nodes using BITNAMI image
- 2 coordinators nodes using micro HW profile
- 2 broker nodes using micro HW profile
- 2 historical nodes using micro HW profile
- 3 middlemanager nodes using small HW profile

- Steps to reproduce the problem: Ingest data from kafka into druid and see the logs in FAILED task using docker 
- The error message or stack traces encountered:  Request failed with status code 404
- Any debugging that you have already done: Acess the OS system and analyse the folders of the task. There is no folder for failed tasks (it can be found for SUCESS task).

**Comment by maytasm** [comment]
The task may have failed to start at all hence, there is no task log. Have you tried searching the middle manager and overlord logs for the task id?

**Comment by FernandoDorado** [comment]
Sorry, I entered this answer in the forum and did not look at this issue. Yes, I have looked at the logs, but what I find strange is that I can see the logs of the tasks that go well, and of the failed tasks I have not detected anything strange by analysing the logs.
