### ISSUE TITLE
Why the loaded datasource availability is 0.0%?

### ISSUE THREAD

**Issue by ardiantovn** [apache/druid#11731]
I have installed apache druid using docker. I have put the json file in the /opt/shared folder. I have also successfully loaded the data. However, why does the loaded data show 0.0% availability? Is there a way to make it 100%?
![druid](https://user-images.githubusercontent.com/16162415/134315032-17e3daca-e33a-4927-a1cc-dc8afec775c3.png)

**Comment by maytasm** [comment]
Do you see any error in historical log?
