### ISSUE TITLE
duplicate data by loading from S3 with Batch

### ISSUE THREAD

**Issue by Z08JBECH** [apache/druid#11745]
On our production cluster, we load parse data from s3 bucket with 8 subtasks.
We have a problem when we load data.

**Sometimes druid create us a segment with 2 partitions, from example : 
f_stock_mouvement_api_2021-09-26T00:00:00.000Z_2021-09-27T00:00:00.000Z_2021-09-27T13:03:00.661Z
f_stock_mouvement_api_2021-09-26T00:00:00.000Z_2021-09-27T00:00:00.000Z_2021-09-27T13:03:00.661Z_1

The 2 partitions contains the same data, so we have doublons.**

It seems that the process run in parallel in different subtask. 

when I check the log from all substask i found this in two substasks. 
-------------------------------
mycompany",
          "path" : "cds/f_stock_mouvement_api/year=2021/month=9/day=26/0027_part_00.gz"
        }, {
          "bucket" : "mycompany",
          "path" : "cds/f_stock_mouvement_api/year=2021/month=9/day=26/0028_part_00.gz"
        }, {
          "bucket" : "mycompany",
          "path" : "cds/f_stock_mouvement_api/year=2021/month=9/day=26/0029_part_00.gz"
        }, {
          "bucket" : "mycompany",
          "path" : "cds/f_stock_mouvement_api/year=2021/month=9/day=26/0030_part_00.gz"
        }, {
          "bucket" : "mycompany",
          "path" : "cds/f_stock_mouvement_api/year=2021/month=9/day=26/0031_part_00.gz"
        }
....
---------------------------
So druid loads some data 2x in the same parallel process with 2 different subtasks. 

**My version is 0.21**

Do you know about this problem ?

**Comment by morrifeldman** [comment]
It sounds similar to what we saw here with data duplication after task failures.  Were there task failures?
https://github.com/apache/druid/issues/11719

**Comment by Z08JBECH** [comment]
> It sounds similar to what we saw here with data duplication after task failures. Were there task failures? #11719

No, task are ok but some data are duplicated.
I found the problem but i think it is a Druid bug

To solve the problem I have to set the s3 prefix path in order
Like that :
cds/f_stock_mouvement_api/year=2021/month=9/day=25
cds/f_stock_mouvement_api/year=2021/month=9/day=26
cds/f_stock_mouvement_api/year=2021/month=9/day=27
cds/f_stock_mouvement_api/year=2021/month=9/day=28

etc

if the path are like that some data are loaded 2 times. 
cds/f_stock_mouvement_api/year=2021/month=9/day=26
cds/f_stock_mouvement_api/year=2021/month=9/day=10
cds/f_stock_mouvement_api/year=2021/month=9/day=13
cds/f_stock_mouvement_api/year=2021/month=9/day=11
