### ISSUE TITLE
Druid task cleaner needs to be a lot better.

### ISSUE THREAD

**Issue by didip** [apache/druid#11764]
### Description

First of all, I am aware of indexer's kill setting. We are using it right now to prune everything older than 24 hours.

But I am afraid that is not good enough. When using `index_parallel`, if all of your input data are huge, then you need to configure each of your ingestion task with high `maxNumConcurrentSubTasks` (between 100-300).

When you have such settings, indexer generates a ton of trash inside `druid_tasks` table: Thousands of `sub_task` with `state = SUCCESS`. And once these things piled up to more than 10000, it breaks Druid.

### Suggestions

1. Druid needs to refactor the `druid_tasks` table to stop dumping blobs into it. That table needs proper columns and indices.

2. The indexer needs to have a setting to specifically clean the `sub_task`. Users legitimately want to keep old records of `index_parallel` for debugging, but the successful `sub_task` should be able to be cleaned aggressively.

**Comment by xvrl** [comment]
seems to be related to #5994

**Comment by xvrl** [comment]
also https://github.com/apache/druid/issues/11173

**Comment by maytasm** [comment]
Druid also has automatic cleanup of the task log and task metadata using the config `druid.indexer.logs.kill.*`. See more details at https://druid.apache.org/docs/latest/configuration/index.html#log-retention-policy.
The limitation of this is that you cannot selectively choose certain task types to be deleted or not deleted. The cleanup will delete everything owner than configured time.
