### ISSUE TITLE
Persisting Druid Peon Task Logs

### ISSUE THREAD

**Issue by pchang388** [apache/druid#11780]
We have our middle manager and historical proceeses running on the same VMs. When trouble shooting, we take a look at the druid peon logs in `{druid_base_dir}/var/druid/tasks/index_kafka_*/log`. 

After the task is done (success or fail), the directory in the tasks dir gets cleaned up instantly and the log file is no longer present. This can make it hard to troubleshoot since you can't look at past peon logs.

Is there a configuration option to retain these logs for a longer period of time or is the recommendation to use it's own log4j file to log to the common `var/sv` directory? I tried looking through the configuration reference but was unable to determine if there was something specific for this. I appreciate any help!

**Comment by ludun624** [comment]
You actually have a few decent options here if you are ok with persist logs externally, you can find the config [here](https://druid.apache.org/docs/latest/configuration/index.html#task-logging), I tried s3 and it works, please update here if that solved your problem @pchang388

**Comment by pchang388** [comment]
Hi @ludun624 - thanks for the response. My goal is to actually use a log shipping agent like splunk/log stash to a remote store or querying/alerting but I also want the ability to troubleshoot locally if needed (in case of shipping issues, etc.).

So S3 or remote would not be preferred. Using local files are okay and I'm looking to see how we can persist these peon tasks logs for a few hours/days after completion instead of being deleted right after.

But I appreciate the input you gave.
