### ISSUE TITLE
Add support for hadoop 3 

### ISSUE THREAD

**Issue by cryptoe** [apache/druid#11791]
### Motivation
As more and more clusters are getting created with Hadoop 3.x.x,  druid will have to eventually support hadoop3 as a first-class citizen. 

Currently, It causes developers a lot of pain to support multiple Hadoop 3.x.x versions as it required changes across the board. Both in pom files as well as java files. This proposal is an attempt to lessen it in a way that both Hadoop 2 and Hadoop 3 changes can coexist. 

### Proposed changes

We use a combination of maven profiles and resource filtering to achieve this.  
Maven profiles allow us to pick which dependencies/configurations to choose from.
[Resources filtering](https://maven.apache.org/plugins/maven-resources-plugin/examples/filter.html) allows us to create templates that are populated based on the correct dependency version which come from pom.xml.

Hadoop2 is supported as a default profile and a new maven profile with the name hadoop3 is created. This will allow the user to select the Hadoop distribution he wants to pick while not breaking backward compatibility.
Each extension which requires has specific dependencies based on the profile. 
For example the avro pom.xml looks like this. 
```
<profiles>
    <profile>
      <id>hadoop2</id>
      <activation>
        <activeByDefault>true</activeByDefault>
      </activation>
      <dependencies>
        <dependency>
          <groupId>org.apache.hadoop</groupId>
          <artifactId>hadoop-client</artifactId>
          <version>${hadoop.compile.version}</version>
          <scope>provided</scope>
        </dependency>
        <dependency>
          <groupId>org.apache.hadoop</groupId>
          <artifactId>hadoop-mapreduce-client-core</artifactId>
          <version>${hadoop.compile.version}</version>
          <scope>provided</scope>
          <exclusions>
            <exclusion>
              <groupId>org.slf4j</groupId>
              <artifactId>slf4j-api</artifactId>
            </exclusion>
          </exclusions>
        </dependency>
        <dependency>
          <groupId>org.apache.hadoop</groupId>
          <artifactId>hadoop-common</artifactId>
          <version>${hadoop.compile.version}</version>
          <scope>provided</scope>
          <exclusions>
            <exclusion>
              <groupId>org.slf4j</groupId>
              <artifactId>slf4j-api</artifactId>
            </exclusion>
          </exclusions>
        </dependency>
      </dependencies>
    </profile>
    <profile>
      <id>hadoop3</id>
      <dependencies>
        <dependency>
          <groupId>org.apache.hadoop</groupId>
          <artifactId>hadoop-client-api</artifactId>
          <version>${hadoop.compile.version}</version>
          <scope>provided</scope>
        </dependency>
        <dependency>
        <groupId>com.sun.jersey</groupId>
        <artifactId>jersey-core</artifactId>
        <scope>test</scope>
        </dependency>
        <dependency>
          <groupId>org.apache.hadoop</groupId>
          <artifactId>hadoop-client-runtime</artifactId>
          <version>${hadoop.compile.version}</version>
          <scope>test</scope>
        </dependency>
      </dependencies>
    </profile>
  </profiles>
``` 

Agreed, it will not help in the Hadoop dependency problems but does enable our users to use druid with multiple flavors of Hadoop.

### Rationale

Discusion [thread](https://lists.apache.org/thread.html/r9e867429b44a694a77ff62351a0e92a4ca06c3f0184b8d9d5019c517%40%3Cdev.druid.apache.org%3E)

### Operational impact

This section should describe how the proposed changes will impact the operation of existing clusters. It should answer questions such as:

- Is anything going to be deprecated or removed by this change? How will we phase out old behavior?
  We will phase out hadoop2 eventually and change the default profile to hadoop3.
- Is there a migration path that cluster operators need to be aware of?
  Existing clusters will not be impacted, 
- Will there be any effect on the ability to do a rolling upgrade, or to do a rolling _downgrade_ if an operator wants to switch back to a previous version?
  Don't think so. It should have any impact. 

### Test plan (optional)
Ut's and integration tests should pass

### Future work (optional)
We will phase out hadoop2 eventually and change the default profile to hadoop3. 
Each release can have 2 Hadoop builds. One with hadoop_2.xx and the other with hadoop_3.xx like most of the other OSS projects like flink, spark.
Also with hadoop3, as @clintropolis mentioned, the dependencies come pre-shaded so we significantly reduce our effort in solving the dependency problems. Eventually, we want to solve the dependency problems on the ingestion side. If druid is built with hadoop_3.0.0, we should still be able to ingest data if the job has hadoop_3.1.x dependencies.

**Comment by abhishekagarwal87** [comment]
Thank you @cryptoe. can you clarify what is "resource filtering" here?
