### ISSUE TITLE
Unable to negating filter expressions involving nulls

### ISSUE THREAD

**Issue by suhassumukh** [apache/druid#11813]
This query - 
```sql
select * from foo where dim is null or dim='a'
```
is translated to (just the `filter` part)- 
```json
"filter": {
    "type": "in",
    "dimension": "dim",
    "values": [
      null,
      "a"
    ]
}
```
which looks good.

However, the translation for this query - 
```sql
select * from foo where not (dim is null or dim = 'a')
```

is - 
```json
"filter": {
    "type": "not",
    "field": {
      "type": "selector",
      "dimension": "dim",
      "value": "a",
      "extractionFn": null
    }
}
```

The `null` condition is lost in the translation and rows with `dim=null` are returned. This is not the expected outcome.
The expected query plan is thus,
```json
"filter": {
    "type": "not",
    "field": {
      "type": "in",
      "dimension": "dim",
      "values": [
          null,
          "a"
      ]
    }
}
```

Affected Version(s):
Apache Druid 0.19.0

**Comment by kfaraz** [comment]
Negation with `IS NULL` is typically problematic because of how the expression `dim IS NULL` is evaluated.
That is why we have `IS NOT NULL`

Try re-writing your query like this:
```
select * from foo where dim is not null and dim <> 'a'
```

**Comment by suhassumukh** [comment]
@kfaraz 
After rewriting my query to -
```sql
select * from foo where dim is not null and dim <> 'a'
```

The query plan is still - 
```json
 "filter": {
    "type": "not",
    "field": {
      "type": "selector",
      "dimension": "dim",
      "value": "a",
      "extractionFn": null
    }
  }
```

Replacing `<>` with `!=` doesn't change anything either.
