### ISSUE TITLE
Druid GCS Parquet Ingestion stopped working

### ISSUE THREAD

**Issue by smit-aterlo** [apache/druid#11852]
### Affected Version
0.22.0

The Druid version where the problem was encountered.

### Description

We are using parquet ingestion for some part of our data. It was working fine until I upgraded the Druid to 0.22.0 since then all the tasks are a success no issue inside the logs but I don't see any segments getting generated in deep storage. 

Kafka ingetion is not affected

Thank you

**Comment by emetselaar** [comment]
Is this still the case for you @smit-aterlo ? I am a bit hesitant to upgrade now because of this issue.

**Comment by smit-aterlo** [comment]
I installed 0.22.1 and it is working all good.

**Comment by emetselaar** [comment]
Thanks for your quick answer. 
That sounds promising. I will give it a try this week.
