### ISSUE TITLE
Druid docker-compose failing for docker compose V2

### ISSUE THREAD

**Issue by jansonjc** [apache/druid#11875]
### Affected Version

`0.22.0`

### Description

Druid's [docker compose ](https://github.com/apache/druid/blob/master/distribution/docker/docker-compose.yml) fails with the below error when using [Docker Compose V2](https://docs.docker.com/compose/cli-command/).

`unexpected character "\"" in variable name near "\"druid-datasketches\"`

There are two potential solutions.

1. Change the environment file by replacing all double quotes with single quotes and by wrapping these environment variables with a double quote ([example](https://github.com/jansonjc/druid/blob/master/distribution/docker/environment) - works with V2 as well as V1.x)
2. Disable Docker Compose V2 in Docker Preferences > General > Uncheck "Use Docker Compose V2" or by running the command `docker-compose disable-v2`

**Comment by FrankChen021** [comment]
Thank you for pointing out this. You gave the explanation to my previous issue #11859. I checked Docker Desktop for mac, docker compose v2 is enabled on 4.1.1.

**Comment by FrankChen021** [comment]
See comments in #11876
