### ISSUE TITLE
INFORMATION_SCHEMA.COLUMNS missing data

### ISSUE THREAD

**Issue by FY92** [apache/druid#11901]
I am using version 0.22.0 of Druid,
 I imported a table with a total size of 6TB, We have 50 servers with 80 cores and 500 memory。
I found that the metadata for the table at information_schema.columns is missing. 
Currently, I can query this table successfully through the RESTAPI, but I can't find it through the SQL query.

I have no idea at this point. Does anyone know why

**Comment by FY92** [comment]
![image](https://user-images.githubusercontent.com/37091146/141072978-4153b573-608c-4e85-89ab-ee5dabba3654.png)

**Comment by FrankChen021** [comment]
Maybe you can check the logs of broker/coordinator to see if there're any errors

**Comment by FY92** [comment]
> Maybe you can check the logs of broker/coordinator to see if there're any errors

I have determined that all metadata of the INFORMATION_SCHEMA.COLUMNS about the DataSource has been lost 。
information_schema.table and sys.sagement have this DataSource.  I can't find any useful logs,Only when a DSQL query is used does the broker report an error: the table cannot be found, but the native REST JSON query is fine
