### ISSUE TITLE
Web console defaults to out of range page when displaying query result

### ISSUE THREAD

**Issue by rupeshkhandelwal** [apache/druid#11921]
Druid web console returns no results for a count query on a data source. I eventually noticed that the results pane defaulted to the page number last used when viewing previous query results. It seems that the query returned no results. 

### Affected Version
apache-druid-0.21.0

### Description

Please include as much detailed information about the problem as possible.
- Cluster size 
  - 4 data servers, 1 query server
- Configurations in use
- Steps to reproduce the problem
  - Issue a query that results in more than one page. 
  - Navigate to any page greater than 1. I was on page 5. 
  - Issue a count query.
  - No result is shown in the results pane
- The error message or stack traces encountered. Providing more context, such as nearby log messages or even entire logs, can be helpful.
- Any debugging that you have already done
  - Workaround - manually go to page 1

<img width="1026" alt="Screen Shot 2021-11-15 at 7 44 19 PM" src="https://user-images.githubusercontent.com/13180428/141922384-10044f7f-4ae1-4783-a257-abac3f9b7188.png">

**Comment by vogievetsky** [comment]
I believe https://github.com/apache/druid/pull/11158 fixed that. (specifically https://github.com/apache/druid/pull/11158/files#diff-895be0cf470fe5da15b15478fcdfe078ac49271d056fd56fe224290417655553R105)

**Comment by rupeshkhandelwal** [comment]
Excellent! Thanks @vogievetsky
