### ISSUE TITLE
Kafka Auto Scaling configuration does not persist between restarts of coordinator/overlord

### ISSUE THREAD

**Issue by kumachanz** [apache/druid#11942]
### Affected Version

Druid 0.22.0

### Description

We have kafka auto scaling configuration set up and working correctly.
We have 2 instances of coordinator running configured also as overlord.

When we restarted the coordinator, the kafka ingestion tasks were started but we noticed lag started to increase over time.
Auto scaling was no longer happening and there was only one kafka task running.
In Druid Console, checked the payload for the supervisor task and can see

`"autoscalerConfig": null`

I pushed our original supervisor task again with the following:

`    "autoScalerConfig": {
      "enableTaskAutoScaler": true,
      "taskCountMax": 6,
      "taskCountMin": 1,
      "scaleOutThreshold": 10000000,
      "scaleInThreshold": 500000,
      "scaleInStep": 1,
      "scaleOutStep": 1,
      "scaleActionPeriodMillis": 1800000
    }`

and it now shows in the supervisor task payload, and task scaling is happening again.

**Comment by ThomasBarach** [comment]
Hello, it also happens when you edit Supervisor without updating `taskCount` to 1
