### ISSUE TITLE
ERROR [task-runner-0-priority-0] org.apache.druid.indexing.common.task.IndexTask - Encountered exception in BUILD_SEGMENTS

### ISSUE THREAD

**Issue by liubo-it** [apache/druid#11944]
@asdf2014  @fjy  @jihoonson  
Hello, I'm using compact task to compress segment. I found an error, memory overflow, but I don't know what caused it. Can you give me a direction?

### compact task 

![image](https://user-images.githubusercontent.com/58646393/142386976-5aae28e7-b499-4fc9-a9bf-ea62cbf63542.png)

### Affected Version

0.19.0

### Task error logs
![image](https://user-images.githubusercontent.com/58646393/142386664-e2130687-7e5c-4dd2-b7c1-06fa574fedbb.png)

**Comment by a2l007** [comment]
@liubo-it What is the total size of all the segments for that datasource for the interval `2021-08-19 to 2021-08-20`? Also could you please let us know why is `maxBytesInMemory` set to -1? Is it because you have sketch aggs? 
I suspect that the maxRowsPerSegment might be too large in this case which might be using up all the heap.

**Comment by liubo-it** [comment]
@a2l007 `2021-08-19 to 2021-08-20` we have about `40G` to `50 G` of data
![image](https://user-images.githubusercontent.com/58646393/142582144-b14ca40b-0df1-4cf4-8a84-d474f60bbc55.png)
yes !  `MaxBytesInMemory`  is set to -1 because our dataSource Metrics has many Sketch fields,I'm not sure if I set the `MaxRowsPerSegment` too big, should I make `Xmx` big enough? You still need to adjust the `off-heap` memory?  thx

**Comment by a2l007** [comment]
What is your average segment size at the moment and how many rows per segment does it have on an average? If there are multiple sketch fields with atleast 8k in size, 13M rows per segment can create very large segments which might not be the goal. 
You could always throw more heap at the compaction tasks proportional to the total segment size it is trying to compact but it would be useful to first estimate how big of a segment would 13M rows create and if this estimated size is within the recommended size for segments.

**Comment by liubo-it** [comment]
I think I know what to do. I'll keep trying. Thx
