### ISSUE TITLE
ERROR org.apache.curator.framework.imps.EnsembleTracker 214 processConfigData- Invalid config event received: {server.1=192.168.0.19:2888:3888:participant, version=100000000, server.0=192.168.0.18:2888:3888:participant, server.2=192.168.0.20:2888:3888:participant}

### ISSUE THREAD

**Issue by meicool** [apache/druid#11971]
My zookeeper version is 3.5.5，My druid version 0.22.0:

WARN org.apache.druid.java.util.common.logger.Logger 130 warn - Batch processing mode argument value is null or not valid;[null],defaulting to[CLOSED_SEGMENTS]
WARN org.eclipse.jetty.server.handler.gzip.GzipHandler 958 setMinGzipSize of 0 is inefficient for short content,break even is size 23
ERROR org.apache.curator.framework.imps.EnsembleTracker 214 processConfigData- Invalid config event received: {server.1=192.168.0.19:2888:3888:participant, version=100000000, server.0=192.168.0.18:2888:3888:participant, server.2=192.168.0.20:2888:3888:participant}

This is my zookeeper config:
tickTime=2000
dataDir=/zookeeper/data/zookeeper1
initLimit=5
syncLimit=2
clientPort=2791
server.1=192.168.0.18:2888:3888:participant
server.2=192.168.0.19:2888:3888:participant
server.3=192.168.0.20:2888:3888:participant

My Druid nodes can connect to ZooKeeper,but when I commit the supervise task,the task is always failed,prompt the above error,someone say it is a curator-client bug,This bug was fixed in version 5.2,but I found the curator-client version in druid lib directory 
is 4.3.0
How can I solve it，thank you

**Comment by aorith** [comment]
Does this config solve the problem? `clientPort` seems to be deprecated:

```
tickTime=2000
dataDir=/zookeeper/data/zookeeper1
initLimit=5
syncLimit=2
server.1=192.168.0.18:2888:3888:participant;2791
server.2=192.168.0.19:2888:3888:participant;2791
server.3=192.168.0.20:2888:3888:participant;2791
```

**Comment by liuzhuang2017** [comment]
@aorith @meicool ，Thanks for this pr，I think this is an Apache Curator bug, see https://issues.apache.org/jira/browse/CURATOR-526 for details.
