### ISSUE TITLE
Auto-reload tls certs for druid endpoints

### ISSUE THREAD

**Issue by santosh-d3vpl3x** [apache/druid#12064]
More often than not, the certs are refreshed quite frequently. The refresh also takes care of java store files. Druid has capability to work with these files. I would like to know how druid addresses this change at the moment. From what I see in the source code and test/integration cases, druid doesn't support it yet [please correct me if I am missing something]. 

Jetty has `KeyStoreScanner` which is capable of reloading the certs based on changes in cert files. This implementation could be very useful here. 

I have done some preliminary implementation but before I publish the PR [struggling with test cases for this particular feature], I would like to know what community thinks about this idea.

**Comment by FrankChen021** [comment]
You can raise a PR to submit this feature. Contribution is welcome.
