### ISSUE TITLE
Auto compaction errors after attempting 0.22.0 upgrade and downgrading to 0.20.0

### ISSUE THREAD

**Issue by callumj** [apache/druid#12098]
Hello,

We recently performed an upgrade to 0.22.0 but had to perform a downgrade to 0.20.0 after we found some incompatibilities with some of our custom extensions. We now have lost auto compaction due what I am guessing is an invalid compaction spec across all our data sources. Looking at our logs, we see this:

```
59:59,936 WARN [qtp1922859107-120] org.apache.druid.metadata.SQLMetadataStorageActionHandler - Encountered exception[Could not resolve type id 'compaction' as a subtype of `org.apache.druid.indexing.common.task.batch.parallel.ParallelIndexTuningConfig`: known type ids = [index_parallel, realtime] (for POJO property 'tuningConfig')
```

What would be the remediation task for get compaction back online?

Thank you (and Happy Holidays!)

**Comment by callumj** [comment]
Turns out from the upgrade we had a stuck task that could not be killed (API operations would fail with same error) - we had to go into the backing store (MySQL DB) and delete these tasks. Might be something worth documenting.

**Comment by FrankChen021** [comment]
There is a refactoring on compaction configuration in #10676. 
I think you need to delete the compaction configuration and re-create it after downgrading to the lower version.

**Comment by callumj** [comment]
Thanks @FrankChen021, that makes sense - we tried nuking the compaction config and that didn’t work. Deleting (manually via MySQL cli) the WAITING compaction task that was created in 0.22 but never finished was the only way to restore auto compaction in our (now) 0.20 cluster.

Under release notes this might be noted as a breaking change those that need to downgrade.

**Comment by FrankChen021** [comment]
You're right, I think we don't realize the compatibility of downgrading.
