### ISSUE TITLE
druid-spring-boot-starter 你们官方的源代码链接是哪一个呢？

### ISSUE THREAD

**Issue by su787910081** [apache/druid#12110]
druid-spring-boot-starter 你们官方的源代码链接是哪一个呢？

**Comment by asdf2014** [comment]
你问错地方了… 去这里看看吧
https://github.com/alibaba/druid/tree/master/druid-spring-boot-starter/

**Comment by su787910081** [comment]
> 你问错地方了… 去这里看看吧 https://github.com/alibaba/druid/tree/master/druid-spring-boot-starter/

好的，谢谢。
