### ISSUE TITLE
add more info for UNABLE_TO_CONNECT_TO_STREAM error or a pointer to the logs

### ISSUE THREAD

**Issue by lrosenman** [apache/druid#12154]
### Description

I'd like to see in the router ui (port 8888) either bubble up the error from the supervisor, or a link to the supervisor log somewhere in the row for that supervisor.

### Motivation
I had the occasion to have approximately 50% of my kafka ingest jobs fail with UNABLE_TO_CONNECT_TO_STREAM and it took me hours to find the actual cause, which was kafka missing the data due to insufficient retention. 

It would be nice to have a more direct way to find this information.

**Comment by sergioferragut** [comment]
Perhaps something like a tooltip on the error status text that contains the exception message? or maybe as another column in the table?
