### ISSUE TITLE
ITIndexerTest.testGetLockedIntervals seems to be flaky

### ISSUE THREAD

**Issue by abhishekagarwal87** [apache/druid#12171]
ITIndexerTest.testGetLockedIntervals seems to be flaky. Here is one sample run - https://app.travis-ci.com/github/apache/druid/jobs/556115018

### Affected Version

Master branch

### Description

The test has likely failed because of a reason unrelated to the change in PR. I can't get the actual reason since we get another exception while unloading the data. This other exception is masking the original problem.

**Comment by jihoonson** [comment]
@abhishekagarwal87 thank you for making this issue. I have the same problem in https://app.travis-ci.com/github/apache/druid/jobs/556115018 for https://github.com/apache/druid/pull/12169.

**Comment by abhishekagarwal87** [comment]
this has been fixed already.
