### ISSUE TITLE
Load dropped segment from deep storage (s3)

### ISSUE THREAD

**Issue by azadsagar** [apache/druid#12193]
I have data worth 2 TB in deep storage. However my cluster seems to have dropped the segments and only showing replicated data not more than ~110 GB. Is it possible to load the data from deep storage ?

**Comment by abhishekagarwal87** [comment]
Yes, it is possible. You may not have enough disk capacity on the
historical or the load rules are not configured correctly. That will result
in data not getting loaded from deep storage.

**Comment by azadsagar** [comment]
I have enough space on my historical nodes. 3TB per node and 10 historical nodes. How can I restore data from deep storage ? 
![2022-01-24_19-54](https://user-images.githubusercontent.com/8531843/150800999-c9c944fa-1b4e-42ab-a6cd-0a97b760a795.png)

**Comment by LakshSingla** [comment]
Is it possible that the load and drop rules for your cluster are configured not to ingest the data that is not getting loaded? For example, the rules specify to not ingest before a certain time period, and the data which is not ingested belongs to that time period?
