### ISSUE TITLE
Query context timeout setting not working

### ISSUE THREAD

**Issue by cp2587** [apache/druid#12197]
### Affected Version

0.21.1

### Description

it seems that the query context timeout setting is not well respected. Using pyhton requests library to run an http SCAN query request with stream=True (to have a streaming request and not load in memory the whole response), druid stops the query well before the theorical timeout.

`2022-01-25 12:24:49 rune.exceptions.RuneException: [Rune version 10.9.0b2] Unexpected end of stream for query [9838466c-2a93-490e-b317-e235f41a70ae], spent 21.73s for a 30s timeout setting,`

and the related druid log for this query

![image (2)](https://user-images.githubusercontent.com/5306537/150991029-1ed61fe5-50bc-42a6-9936-0afaf7031086.png)

How does the timeout works on the broker ? Is it possible for druid to stop the stream before the timeout value ?

**Comment by machine424** [comment]
Hello,

I've done some digging and I came across this:

We first set the absolute timeout like this:

https://github.com/apache/druid/blob/ef006fd2571228984b04b95f3a3e2b03d930dce3/processing/src/main/java/org/apache/druid/query/scan/ScanQueryRunnerFactory.java#L94-L97

But we keep shrinking it here:

https://github.com/apache/druid/blob/ef006fd2571228984b04b95f3a3e2b03d930dce3/processing/src/main/java/org/apache/druid/query/scan/ScanQueryEngine.java#L190-L194

I don't understand why, especially that the timeout check is:

https://github.com/apache/druid/blob/ef006fd2571228984b04b95f3a3e2b03d930dce3/processing/src/main/java/org/apache/druid/query/scan/ScanQueryEngine.java#L176-L178


Am I missing something? After commenting out `Lines 190 to 194`, the query's `timeout` (As I understand it) seems to be respected. Of course it's always possible to exceed it (while in `rowsToList` for example if the `batchSize` is big) but this is another subject which is discussed in https://github.com/apache/druid/issues/1415.

Maybe @jihoonson
