### ISSUE TITLE
Measuring Disk Storage / Compression Ratio

### ISSUE THREAD

**Issue by AbdelouahabKhelifati** [apache/druid#12245]
I am interested in Druid's compression performance. I used Druid to create a datasource and I loaded my data in it (5GB _csv_ formated time series data), here's the dashboard: 

<img width="1410" alt="image" src="https://user-images.githubusercontent.com/15266242/153200539-b244bdf3-6aa1-4705-9155-724ef1ba89f6.png">

The dashboard shows that the storage size of _bafu_ datasource is: 1.5GB which doesn't seem to be realistic. 

Am I looking at the compression in the right place? How could I measure the disk stored size of the datasource?

**Comment by a2l007** [comment]
Yes that would be the stored size of the datasource without replication.Based on the cardinality of the dimensions and query granularity, this level of compression can be reasonable.
