### ISSUE TITLE
prometheus-emitter for peons can't be configured as pushGateway

### ISSUE THREAD

**Issue by tanisdlj** [apache/druid#12242]
### Affected Version

0.22.1

### Description

In [prometheus-emitter documentation saids that should always use default strategy (`exporter`) except peon tasks](https://druid.apache.org/docs/latest/development/extensions-contrib/prometheus.html#:~:text=Only%20peon%20task%20(short%2Dlived%20jobs)%20need%20to%20use%20pushgateway%20strategy.).
Question is: How do I setup peons to have a different strategy than the middlemanager?
I can't see any druid.indexer.runner.emitter.prometheus.strategy in the documentation or any way to specify a different strategy for peons. If there is not, then I guess is a missing feature.

**Comment by henriquekops** [comment]
@tanisdlj have you tried to prefix the config with `druid.indexer.fork`? 

You can find more [at the docs](https://druid.apache.org/docs/latest/configuration/index.html#additional-peon-configuration).

I think this particular configuration would be set as `druid.indexer.fork.druid.emitter.prometheus.strategy=pushgateway`.

**Comment by holyachon** [comment]
Hello. I think configuration would be set as
`druid.indexer.fork.property.druid.emitter.prometheus.strategy=pushgateway`
`.property` is also in prefix.
