### ISSUE TITLE
【Docs】The description of config item `druid.worker.globalIngestionHeapLimitBytes` in the indexer general configration is incorrect.

### ISSUE THREAD

**Issue by keepmeup** [apache/druid#12265]
Please provide a detailed title (e.g. "Broker crashes when using TopN query with Bound filter" instead of just "Broker crashes").

### Affected Version
druid-0.22.0
The Druid version where the problem was encountered.

### Description
The description of config item `druid.worker.globalIngestionHeapLimitBytes` in the indexer general configration is incorrect.

The description of the configuration item is 60%.
![image](https://user-images.githubusercontent.com/41229600/154439054-5bc9ae5c-f847-4b1f-9481-2ecfec24ad88.png)

But it's actually 1/6 in the code.
code:org.apache.druid.indexing.worker.config.WorkerConfig#globalIngestionHeapLimitBytes
![image](https://user-images.githubusercontent.com/41229600/154439354-c807bd52-51e7-402f-8924-c23a3e38e786.png)

**Comment by FrankChen021** [comment]
Thank you for pointing out this. When the #8255 was submitted, it forgot the change above. 
Could you open a PR to help us improve the doc?

**Comment by keepmeup** [comment]
> Thank you for pointing out this. When the #8255 was submitted, it forgot the change above. Could you open a PR to help us improve the doc?

I will do it

**Comment by FrankChen021** [comment]
Thank you

**Comment by hevansDev** [comment]
Fixed by https://github.com/apache/druid/pull/16654

**Comment by techdocsmith** [comment]
Per @hevansDev , fixed
