### ISSUE TITLE
In quickstart with docker docs, I think declared in docs is better when the macOS startup docker-compose shoulds configure "Docker Resource memory size"

### ISSUE THREAD

**Issue by MarcelLeon** [apache/druid#12275]
Druid has a perfect document, follow the docs I understand Druid fast, but it's blocked when I deploy Druid in Docker.
My enviroment is macos11, I follow this doc:  https://druid.apache.org/docs/latest/tutorials/docker.html
when I execute commands
```
docker-compose up -d  
docker-compose logs -f
```
it reports:
```
....
broker exited with code 137
historical exited with code 137
.....
```

Then I try tune file 'enviroment', decrease memory like MaxDirectMemorySize. It not works.I still get same results.
```
If you experience any processes crashing with a 137 error code you likely don't have enough memory allocated to Docker. 6 GiB may be a good place to start.
```
And I found code 137 means memory is not enough, I closed all big occupying memory applications in mac. It does not work too.

Finally, this mail fixed my problem: https://groups.google.com/g/druid-user/c/cbayyeNvpAQ/m/99SDXx2RAgAJ
I tune my Docker Resource 2GB -> 8GB, it works.

I'm not familiar with Docker(macOS), "don't have enough memory allocated to Docker" is ambiguous.
So I suggest it is declared in docs is better, when the macOS startup docker-compose should configure "Docker Resource". It is 2GB by default. 
<img width="1004" alt="image" src="https://user-images.githubusercontent.com/17470121/155257405-1ac1ef70-aeb2-4cfe-86a1-ad7e4ea94745.png">

**Comment by FrankChen021** [comment]
You can open a PR to help us optimize the doc to make it more instructive and clear.

**Comment by MarcelLeon** [comment]
> You can open a PR to help us optimize the doc to make it more instructive and clear.

Thanks for your reply, I am glad to contribute this optimization, but I found the familiar PR: #11827 had been merged...I hope can contribute next time.
