### ISSUE TITLE
Can not find any druid tables after restarting all nodes in cluster

### ISSUE THREAD

**Issue by yulei0824** [apache/druid#12287]
Can not find any druid tables after restarting all nodes in cluster

### Affected Version

0.21.1

### Description

Cluster information: 1 router, 2 coordinators, 3 brokers, 6 historicals (12 HDD disks), more than 900 tables.
Each historical caches more than 300000 segments.
Use the following procedures to restart this cluster:
1. stop all nodes.
2. start all historicals after setting property druid.segmentCache.lazyLoadOnStart to be true.
3. start all coordinators.
4. start all brokers.
5. start one router.

I cannot find any druid tables when opening the query page of router, and cannot run successfully any SQL queries.
I get the following exception information when running "select * from t1 limit 10": 
org.apache.calcite.runtime.CalciteContextException: From line xxx, column xx to line xx, column xx: Object 't1' not found org.apache.calcite.tools.ValidationException

I find the many exceptions at the broker logs:
WARN [DruidSchema-Cache-0] org.apache.druid.sql.calcite.schema.DruidSchema - Metadata refresh failed, trying again soon. org.apache.druid.query.QueryTimeoutException: url[http://historical-ip:8083/druid/v2/] timedout........

**Comment by FrankChen021** [comment]
Did you check if there's any exception or error in the log historical nodes?

**Comment by wanglihui-git** [comment]
> Did you check if there's any exception or error in the log historical nodes?

![639b57c55592742252a84f2b98fcbb6](https://user-images.githubusercontent.com/41256589/161372373-0c800fa9-ac43-4bf9-b9fe-4512dab0f95a.png)
There are a lot of Java stack-related log information in the directory of my historical node. Have you ever encountered this situation? The error may be related to the too many segments. Is there any parameter that can be modified? Thank you.

**Comment by abhishekagarwal87** [comment]
what do these logs have? It seems like there is an error on the historical side. You should search the logs to narrow down the error.
