### ISSUE TITLE
Db2 keyword resolution error

### ISSUE THREAD

**Issue by lpt9** [apache/druid#12285]
I encountered the following error when Druid was parsing SQL:
![图片](https://user-images.githubusercontent.com/45647323/155695935-cc74f018-a288-4475-9881-159763c34d8b.png)

### Affected Version

The Druid version is` 1.1.10` , I also tried the latest version(`1.2.8`)

### Description
The code I execute is as follows:
`jdbcTemplate.execute("CREATE TABLE TRACE_LOG_BK AS (SELECT * FROM TRACE_LOG) DEFINITION ONLY ");`

**Comment by FrankChen021** [comment]
Ask your question there: https://github.com/alibaba/druid
