### ISSUE TITLE
S3 compatible with minio

### ISSUE THREAD

**Issue by aishee** [apache/druid#12286]
###
Hello,
I'm having problem configuring Deep Storage to use Minio S3, now I'm having it with the new Druid version.
Does anyone have any ideas on this?

Thanks and Regards

**Comment by renatocron** [comment]
I know a few people are using with minio, and it's working

can you paste your config for us? 

there's some hints that can help you here 
https://www.druidforum.org/t/error-when-using-deepstorage-s3-from-b2-backblaze-s3-compatible/7244/6
