### ISSUE TITLE
RemoteTaskRunner leak memory 

### ISSUE THREAD

**Issue by happy5035** [apache/druid#12305]
In my test environment, there was a total of 3500supervisor(index_kafka,task count:1, replicas:1)，task is pending

The runPendingTasksExec thread pool in RemoteTaskRunner contains 50 million tasks.

![image](https://user-images.githubusercontent.com/13789954/156723605-8d138d61-92a8-4cf4-8d25-8cfcb587929d.png)

![image](https://user-images.githubusercontent.com/13789954/156723746-f843c753-cbde-4384-95d0-a632cd452e60.png)

![image](https://user-images.githubusercontent.com/13789954/156723954-87fb04dd-94fe-4820-b229-c3db0e7e940a.png)

### Affected Version

0.21.1

### Description

Please include as much detailed information about the problem as possible.
- Cluster size
master*2
query*3
historical*21
middlemanager * 16
indexers * 5

**Comment by sergioferragut** [comment]
Could you provide a bit more context. 
How did the cluster arrive at this state?
3500 seems like a lot, what are you expecting to see and why?

**Comment by happy5035** [comment]
> 

I'm testing how many datasources and supervisors a druid cluster can run at the same time. Supervisor tasks are KIS, so there are many streams.

**Comment by happy5035** [comment]
> I'm testing how many datasources and supervisors a druid cluster can run at the same time. Supervisor tasks are KIS, so there are many streams.

**Comment by happy5035** [comment]
> Could you provide a bit more context.
How did the cluster arrive at this state?
3500 seems like a lot, what are you expecting to see and why?
I'm testing how many datasources and supervisors a druid cluster can run at the same time. Supervisor tasks are KIS, so there are many streams.
