### ISSUE TITLE
No brokerServiceName found for datasource X intervals Y. Using default[druid/broker] should be an INFO or NOTICE, not an error

### ISSUE THREAD

**Issue by tanisdlj** [apache/druid#12328]
https://github.com/apache/druid/blob/6ba6b16786eca5a25ebad2f00df4b2a265861b01/server/src/main/java/org/apache/druid/server/router/TieredBrokerHostSelector.java#L236-L244

Since it means there are no tiered brokers and it is going back to default behaviour but still properly working, it shouldn't be an error.
```java
 if (brokerServiceName == null) { 
   log.info( 
       "No brokerServiceName found for datasource[%s], intervals[%s]. Using default[%s].", 
       query.getDataSource(), 
       query.getIntervals(), 
       tierConfig.getDefaultBrokerServiceName() 
   ); 
   brokerServiceName = tierConfig.getDefaultBrokerServiceName(); 
 } 
```

**Comment by FrankChen021** [comment]
You can open a PR to improve this.
