### ISSUE TITLE
LDAP Auth fails with special character in password using druid-basic-security 

### ISSUE THREAD

**Issue by schmichri** [apache/druid#12379]
### Affected Version
0.22.1

### Description

Using a valid and working LDAP Authenticator Configuration following your guides https://github.com/apache/druid/blob/master/docs/development/extensions-core/druid-basic-security.md 
the basic auth doesn't work on using special char ':' or '*' within the password under the following circumstances: 

* It fails if you try to login User/password on the router & coordinator but without any error in the logs
* It also fails if you use the User/password as in `druid.escalator.internalClientUsername` with UNAUTHORIZED errors in the logs
* It doesn't fail if you setup the User/password in `druid.auth.authenticator.ldap.credentialsValidator.bindUser`

Unfortunately I don't have the stacktrace anymore nor I'm not in an environment where I can change the password often enough. 

As far as I remember the exceptions have been thrown from the jetty servlet. To reproduce just setup a User/password with special characters ':' in `druid.escalator.internalClientUsername`

**Comment by schmichri** [comment]
Is there some more information I can provide to drive this issue?

**Comment by abhishekagarwal87** [comment]
@schmichri - You can pass your password as below
```
druid.escalator.internalClientPassword={"type":"default","password":"{%thisisreallymypassword"}
```
instead of passing it like below
```
druid.escalator.internalClientPassword={%thisisreallymypassword
```

Special characters in username should not cause a problem. can you confirm if that is not the case?

**Comment by trtg** [comment]
Confirming that Druid 26.0.0 still does not support the use of the colon character in an LDAP password, I suspect that perhaps it is doing some inappropriate escaping or something when sending to the LDAP server because I can see that the password sent from the druid UI password dialog to the druid backend seems fine but in the druid logs it says that the LDAP server replies that the password is invalid. I confirmed that this error appears when the password contains a colon character and is resolved when the password does not contain a colon character. Has anyone taken a look at this? @abhishekagarwal87

**Comment by abhishekagarwal87** [comment]
Are you providing the password the way I recommended in my previous comment? Did that not work?

**Comment by schmichri** [comment]
@abhishekagarwal87 I never answered back in the past (sorry for that) but I remember I've changed the password. The behavior @trtg describes (seeing the logs) I can confirm. 
I remember as well, that the password with the `:` in it was my personal password and not the internalClientPassword nor the initialAdminPassword. 
As far as I understood it, it wasn't a configuration issue rather an issue with the escaping of basic auth itself because it looked like that the internal urls had the following pattern `http://<user>:<password>@host:port/` and not used an basic authorization header. 
An `:` in url based basic auth would been misinterpreted. 

Let me know if I can provide more information. (this time I will answer)

**Comment by trtg** [comment]
@abhishekagarwal87 I'm dealing with a druid instance that I don't manage (i.e. I can't change any backend configuration), all I have access to is the graphical username/password dialog that appears when I login to druid, so I can't really change the way in which I provide the password. Where exactly were you proposing the usage of druid.escalator.internalClientPassword as a JSON blob?

**Comment by abhishekagarwal87** [comment]
Fixed here - https://github.com/apache/druid/pull/15109/files
