### ISSUE TITLE
Test Cases are using the print instead of Assert in testing

### ISSUE THREAD

**Issue by Codegass** [apache/druid#12399]
## Description
When I am running the test for [DataGenerator](https://github.com/apache/druid/blob/b86f2d4c2e935346d600e51b22403150ebd1501d/processing/src/test/java/org/apache/druid/segment/generator/DataGeneratorTest.java), I noticed that some test cases in this test class don’t have any Assert from JUnit:

* [testLazyZipf](https://github.com/apache/druid/blob/b86f2d4c2e935346d600e51b22403150ebd1501d/processing/src/test/java/org/apache/druid/segment/generator/DataGeneratorTest.java#L424)
* [testRealUniform](https://github.com/apache/druid/blob/b86f2d4c2e935346d600e51b22403150ebd1501d/processing/src/test/java/org/apache/druid/segment/generator/DataGeneratorTest.java#L334)
* [testNormal](https://github.com/apache/druid/blob/b86f2d4c2e935346d600e51b22403150ebd1501d/processing/src/test/java/org/apache/druid/segment/generator/DataGeneratorTest.java#L291)
* [testEnumerated](https://github.com/apache/druid/blob/b86f2d4c2e935346d600e51b22403150ebd1501d/processing/src/test/java/org/apache/druid/segment/generator/DataGeneratorTest.java#L262)
* [testZipf](https://github.com/apache/druid/blob/b86f2d4c2e935346d600e51b22403150ebd1501d/processing/src/test/java/org/apache/druid/segment/generator/DataGeneratorTest.java#L207)
* [testRoundedNormal](https://github.com/apache/druid/blob/b86f2d4c2e935346d600e51b22403150ebd1501d/processing/src/test/java/org/apache/druid/segment/generator/DataGeneratorTest.java#L164)
* [ testDiscreteUniform ](https://github.com/apache/druid/blob/b86f2d4c2e935346d600e51b22403150ebd1501d/processing/src/test/java/org/apache/druid/segment/generator/DataGeneratorTest.java#L99)
* [testSequential](https://github.com/apache/druid/blob/b86f2d4c2e935346d600e51b22403150ebd1501d/processing/src/test/java/org/apache/druid/segment/generator/DataGeneratorTest.java#L49)

These test cases are all using the [`printStuff`](https://github.com/apache/druid/blob/b86f2d4c2e935346d600e51b22403150ebd1501d/processing/src/test/java/org/apache/druid/segment/generator/DataGeneratorTest.java#L529) function to print out the related information for manual verification. There is no JUnit Assert function in these test cases. Based on my understanding, these cases require manual checking of the printed information to verify whether the test cases pass or fail. 

Also, The [testIntervalBasedTimeGeneration()](https://github.com/apache/druid/blob/b86f2d4c2e935346d600e51b22403150ebd1501d/processing/src/test/java/org/apache/druid/segment/generator/DataGeneratorTest.java#L375) test case does not have print info. It's hard for new contributors to tell whether it passes or fails.

I am curious about why these test cases are designed without Assert. And if adding the assert is helpful, I would be more than happy to try submit a PR.

**Comment by xvrl** [comment]
Hi @Codegass feel free to submit a PR to improve some of those things. The printing in test cases might be a relic of someone debugging some of these things. To the extent that things have to be checked as part of the test, I agree it's useful to use test assertions instead. For other things that are there for information, we could probably replace them with debug statements instead

**Comment by AlbericByte** [comment]
@FrankChen021 i could work on this if no other work on this already.

**Comment by FrankChen021** [comment]
@AlbericByte Thank you for picking this up. As far as I know, there's no one working on it.

**Comment by AlbericByte** [comment]
Thanks @FrankChen021 and @xvrl , please help to have a look when you have time.
