### ISSUE TITLE
update pac4j due to cve

### ISSUE THREAD

**Issue by pjfanning** [apache/druid#12495]
See https://github.com/pjfanning/druid/pull/5 - https://github.com/advisories/GHSA-xhw6-hjc9-679m

Related but separate to #12260

**Comment by a2l007** [comment]
Pac4j v5.x is on java 11 now: https://www.pac4j.org/blog/what_s_new_in_pac4j_v5.html
and looks like there are some compatibility issues with upgrading Druid to 5.x since we are on JDK 8.
