### ISSUE TITLE
How to send an array as a parameter?

### ISSUE THREAD

**Issue by oolmoshe** [apache/druid#12502]
Trying to build a query with an array as a parameter for a IN statement

### Affected Version

0.22.1

### Description

Trying to execute this query using SQL API found that is not allowed to have an array as a parameter, used in this case to filter with an IN statement: 
`"query":"select * from table where param1 IN (?)","resultFormat":"array","header":true,"context":{"sqlOuterLimit":101},"parameters":[{"type": "VARCHAR", "value": ["value1","value2","value3"]}]}`

We have try as a VARCHAR because is what we understand in the documentation, but this is what we got:

`{"error":"Unknown exception","errorMessage":"cannot convert [value1, value2, value3] (class java.util.ArrayList) to STRING","errorClass":"java.lang.IllegalArgumentException","host":null}%`

But there aren't a parameter type for ARRAY objects.

**Comment by renatocron** [comment]
I've ended up creating the query with multiple ? and passing each value

you are using nodejs, here the implementation + tests https://gist.github.com/renatocron/f68d37bd40103bf873b1844db177923a
