### ISSUE TITLE
LoadForever Data Retention 

### ISSUE THREAD

**Issue by ashneg** [apache/druid#12505]
Hi, I have configured data retention to load forever but still, segments are becoming inactive(only 2.5% in this case). I want it to be 100% at all time.

Thanks for help

![Screenshot 2022-05-09 at 3 38 56 PM](https://user-images.githubusercontent.com/44631967/167389038-e9fc1d0f-fc6e-4e69-88ca-8fcf0731ce71.png)

**Comment by abhishekagarwal87** [comment]
@ashneg - Apache druid slack channel https://apachedruidworkspace.slack.com/archives/C0309C9L90D is the best place to seek help for troubleshooting.
