### ISSUE TITLE
sql select query - concatenate all the column values in one row

### ISSUE THREAD

**Issue by NikitaElmanov** [apache/druid#12604]
Hello!
Can I get one row with all values from column?
For example:
I hava table:
```
table name: | some_text|
columns:    |   text   |
values:     |   aaaa   |
            |     bbbb |
            |    ccc   |
            |    ....  |
```
And in the same way I'd like to receive the next output:
_aaaa, bbbb, ccc_

Please, prompt me, how must select query be look like?

**Comment by abhishekagarwal87** [comment]
@NikitaElmanov - Druid slack (https://apachedruidworkspace.slack.com/archives/C0309C9L90D) or druid forum (https://www.druidforum.org/) will be the right place to post this question.

**Comment by NikitaElmanov** [comment]
@abhishekagarwal87, thanks for answer!

> Druid slack (https://apachedruidworkspace.slack.com/archives/C0309C9L90D) or druid forum (https://www.druidforum.org/) will be the right place to post this question.

create topic in druidforum: https://www.druidforum.org/t/sql-select-query-concatenate-all-the-column-values-in-one-row/7400

However can you answer my question? Maybe in the forum.
