### ISSUE TITLE
QUANTILE FUNCTIONS DOES NOT WORK? 

### ISSUE THREAD

**Issue by NikitaElmanov** [apache/druid#12699]
Hello!
I’d like to count 99 percentile by using sql druid query. There’s no enough info about function in documentation.

Now I have the next query:

```
SELECT
  __time as "time",
  AVG(sla) as " ", --!!!!!!!!!!!!!!!!!!!!!!!!!!
  name as "service"
FROM SYTESTER_DRUID
WHERE ('${service}' = 'Show All' OR name in (${service:sqlstring}))
AND __time >= MILLIS_TO_TIMESTAMP(${__from}) AND __time <= MILLIS_TO_TIMESTAMP(${__to})
GROUP BY __time, name
```
But I need to apply 99 percentile instead of arithmetic mean. In my opinion, query must looks like:

```
 SELECT
  __time as "time",
DS_GET_QUANTILE(sla, 0.99) as " ", --!!!!!!!!!!!!!!!!!!!!!!!!!!
  name as "service"
FROM SYTESTER_DRUID
WHERE ('${service}' = 'Show All' OR name in (${service:sqlstring}))
AND __time >= MILLIS_TO_TIMESTAMP(${__from}) AND __time <= MILLIS_TO_TIMESTAMP(${__to})
GROUP BY __time, name
```
What function from:

_TDIGEST_QUANTILE
DS_GET_QUANTILE
APPROX_QUANTILE
DS_QUANTILE_SUMMARY_
should I use?
And can you share with me with druid sql examples with …QUANTILE… functions?

**Comment by NikitaElmanov** [comment]
Sql query 
`select DS_GET_QUANTILES(select sla from SYTESTER_DRUID where __time >= '2022-06-17T10:03:11.000Z' and  __time < '2022-06-17T10:05:15.000Z' GROUP BY __time, 0.99)`
does not work as well(

**Comment by suneet-s** [comment]
@NikitaElmanov you can get percentiles by using the `APPROX_QUANTILES_DS` function in sql. See https://druid.apache.org/docs/latest/querying/sql-aggregations.html#quantiles-sketch-functions for the list of aggregations. I think your query would look like

```
SELECT
  __time as "time",
APPROX_QUANTILES_DS(sla, 0.99) as " ", --!!!!!!!!!!!!!!!!!!!!!!!!!!
  name as "service"
FROM SYTESTER_DRUID
WHERE ('${service}' = 'Show All' OR name in (${service:sqlstring}))
AND __time >= MILLIS_TO_TIMESTAMP(${__from}) AND __time <= MILLIS_TO_TIMESTAMP(${__to})
GROUP BY __time, name
```

**Comment by NikitaElmanov** [comment]
@suneet-s hi!
Forgot to mention I use 0.22.1 druid version and sla has double type.
Your advice is not working. I've got output:
_Error: Plan validation failed
org.apache.calcite.runtime.CalciteContextException: From line 32, column 3 to line 32, column 32: No match found for function signature APPROX_QUANTILES_DS(<NUMERIC>, <NUMERIC>)
org.apache.calcite.tools.ValidationException_ 

Also I tried DS_GET_QUANTILE(sla, 0.99) instead of APPROX_QUANTILES_DS(sla, 0.99) and got the same error(

**Comment by suneet-s** [comment]
@NikitaElmanov have you loaded the datasketches extension in your cluster as mentioned in https://druid.apache.org/docs/latest/development/extensions-core/datasketches-extension.html?

You could use the APPROX_QUANTILE function instead, if it is not possible to load the datasketches extension for some reason, but you'll get better accuracy with the extension as mentioned in the docs

**Comment by NikitaElmanov** [comment]
> have you loaded the datasketches extension in your cluster as mentioned in

Yes, I have this extension in common.runtime.properties file. In /libs dir I have:
_./datasketches-memory-1.3.0.jar
./datasketches-java-2.0.0.jar_
Also in /extensions dir I have only:
 _druid-histogram/druid-histogram-0.22.1.jar_
I suppose it's not enough and I must have some extra lib in /libs dir or/and some extra jar file like druid-sketchers.jar.
I think so cause there's no sketchers extension in druid UI:
<img width="1191" alt="Снимок экрана 2022-06-24 в 09 13 58" src="https://user-images.githubusercontent.com/39399744/175474043-5839400f-5e14-4fe8-a286-87c092f292f4.png">

**Comment by NikitaElmanov** [comment]
@suneet-s please tell me, what jar file do I have to upload in /extensions and /libs dir?
_https://mvnrepository.com/artifact/org.apache.druid.extensions.contrib/druid-momentsketch/0.22.1_
or maybe
_https://mvnrepository.com/artifact/org.apache.druid.extensions.contrib/druid-tdigestsketch/0.22.1_
?

**Comment by NikitaElmanov** [comment]
> have you loaded the datasketches extension in your cluster as mentioned in

Yes, I have this extension and in UI it's shown:
<img width="1147" alt="Снимок экрана 2022-06-24 в 09 33 17" src="https://user-images.githubusercontent.com/39399744/175476719-88086c41-67a3-445e-81f8-f7ee6e69bc28.png">

Reduced all unneed code in sql query and 
```
SELECT
 DS_GET_QUANTILE(sla, 0.99) as "q",
  name as "service"
FROM SYTESTER_DRUID
```
returns for me:
_Error: Unknown exception

Error while applying rule DruidQueryRule(SELECT_PROJECT), args [rel#33886:LogicalProject.NONE.[](input=RelSubset#33885,q=DS_GET_QUANTILE($4, 0.99:DECIMAL(3, 2))), rel#33896:DruidQueryRel.NONE.[](query={"queryType":"scan","dataSource":{"type":"table","name":"SYTESTER_DRUID"},"intervals":{"type":"intervals","intervals":["-146136543-09-08T08:23:32.096Z/146140482-04-24T15:36:27.903Z"]},"virtualColumns":[],"resultFormat":"compactedList","batchSize":20480,"order":"none","filter":null,"columns":["__time","message","name","rnd","sla","status","value"],"legacy":false,"context":{"sqlOuterLimit":101,"sqlQueryId":"3d87fef6-4c5c-4044-9227-f5c681c24ed6"},"descending":false,"granularity":{"type":"all"}},signature={__time:LONG, message:STRING, name:STRING, rnd:LONG, sla:DOUBLE, status:LONG, value:STRING})]

java.lang.RuntimeException_

And this query:
```
SELECT
 APPROX_QUANTILE(sla, 0.99) as "q",
  name as "service"
FROM SYTESTER_DRUID
```
returns:
_Error: Plan validation failed
org.apache.calcite.runtime.CalciteContextException: From line 28, column 2 to line 28, column 27: No match found for function signature APPROX_QUANTILE(\<NUMERIC>, \<NUMERIC>)
org.apache.calcite.tools.ValidationException_

**Comment by NikitaElmanov** [comment]
SELECT
  __time as "time",
DS_GET_QUANTILE(DS_QUANTILES_SKETCH (sla), 0.99) as " ds_sla", 
  name as "service"
FROM SYTESTER_DRUID
WHERE ('${service}' = 'Show All' OR name in (${service:sqlstring}))
AND __time >= MILLIS_TO_TIMESTAMP(${__from}) AND __time <= MILLIS_TO_TIMESTAMP(${__to})
GROUP BY __time, name
works!!!
