### ISSUE TITLE
Improve documentation around granularities

### ISSUE THREAD

**Issue by kfaraz** [apache/druid#12726]
The possible types of granularities that can be used are only mentioned within the querying section here:
https://druid.apache.org/docs/latest/querying/granularities.html

It's possible to use the same set of granularities as segment granularity during ingestion. We need to clarify this in the docs. Maybe just update the title of this page and link to it from segment granularities too?

**Comment by hildebrando001** [comment]
I'm ingesting data from kafka.
I'd like to know if durring the ingestion process, when I set "segment granularity" to daily, all data in kafka corresponding to this period of time will be compacted or Druid will take a aleatory data from kafka. I could not found it in documetation. 
https://druid.apache.org/docs/latest/tutorials/tutorial-kafka.html

Obs.: If these data are compacted in a single line in Druid, I'd like to know if it is possible to add 5 minutes and 30 minutes to the  segment granularity options.

**Comment by hevansDev** [comment]
Picking this up after a chat with @techdocsmith about how we can link to the documentation about granularities under querying from the documentation on storage and ingestion to clarify ingestion granularity.
