### ISSUE TITLE
Add druid_service and host_name labels to Prometheus exporter

### ISSUE THREAD

**Issue by amirabbas8** [apache/druid#12731]
Some labels are missing from the Prometheus exporter. They were in the Statsd exporter, such as druid_service and host_name, Which makes the result of Prometheus exporter incompatible with the stated exporter.

It would be great to have the below configs also for Prometheus.
```
druid.emitter.statsd.includeHost
druid.emitter.statsd.dogstatsdServiceAsTag
```

**Comment by FrankChen021** [comment]
The prometheus extension is a community contributed extension, you're welcome to do it by yourself or you have to to wait for someone volunteer to do it.

**Comment by liujianhuanzz** [comment]
> Some labels are missing from the Prometheus exporter. They were in the Statsd exporter, such as druid_service and host_name, Which makes the result of Prometheus exporter incompatible with the stated exporter.
> 
> It would be great to have the below configs also for Prometheus.
> 
> ```
> druid.emitter.statsd.includeHost
> druid.emitter.statsd.dogstatsdServiceAsTag
> ```

<img width="596" alt="image" src="https://user-images.githubusercontent.com/11659811/178106016-13d371ff-78e8-4e16-ba3e-df9834ce23f0.png">

@amirabbas8  Is this the result you want？

**Comment by amirabbas8** [comment]
Yes. Also, it would be preferable that label names be like Statsd exporter.

following is an example of a metric in our stated exporter:
```
druid_jvm_bufferpool_capacity{bufferpoolName="direct",druid_service="druid/router",hostname="i002.kandoo.com:8888"}
```
@liujianhuanzz
