### ISSUE TITLE
Ingestion Task Shows SUCCESS status, but Pushed 0 segments

### ISSUE THREAD

**Issue by mounikanakkala** [apache/druid#12803]
### Affected Version
0.22.1.61

### Description
Hi Everyone,

We have observed a scenario where the Ingestion Task Shows SUCCESS status but the logs showed that it pushed 0 segments. 

**Background**
We have the following inputFormat
```
"inputFormat":{
            "type":"tsv",
            "findColumnsFromHeader":true,
            "delimiter": "|"
         }
```
And our input files are of the extension `.csv.gz` usually. This extension works fine as expected (meaning ingestion succeeds and segments are created)

**Problem**
We were accidentally creating files without the `.csv.gz` extension. That's when the ingestion status showed SUCCESS but the logs showed that it pushed 0 segments and 0 bytes. Is that an expected behavior?

Can Druid fail or provide a different Status instead of SUCCESS when it did not push any segments because current behavior is misleading.

**Comment by a2l007** [comment]
It's possible that Druid ignored the unparseable rows. Please check the task reports corresponding to the ingestion task to see if there were unparseable records encountered. If you require tasks to fail on unparseable rows, an option is to set `reportParseExceptions` to true in your ingestion `tuningConfig`.
