### ISSUE TITLE
ERROR: manifest for apache/druid:0.24.0 not found: manifest unknown: manifest unknown

### ISSUE THREAD

**Issue by smunveruddin-mwb** [apache/druid#12823]
Hi Team,

Upon cloning and running the docker containers via "docker-compose -f distribution/docker/docker-compose.yml up" . It shows up an error like the below.

"**ERROR: manifest for apache/druid:0.24.0 not found: manifest unknown: manifest unknown**".

Could you guys please help me on this, am trying to get started with Druid with docker image. Thanks !!!

Regards
Shabeer

**Comment by abhishekagarwal87** [comment]
You should be using the file from release tag - https://github.com/apache/druid/blob/0.23.0/distribution/docker/docker-compose.yml
