### ISSUE TITLE
Upgrade Quickstart Python Scripts to Python 3

### ISSUE THREAD

**Issue by michaelli321** [apache/druid#12824]
### Description

Currently the quickstart scripts are using Python 2. For example, [this syntax](https://github.com/apache/druid/blob/master/examples/bin/post-index-task-main#L35) in the post-index-task-main script, is using Python 2 syntax. These scripts should be upgraded to Python 3.

**Comment by xvrl** [comment]
I believe this has been addressed by https://github.com/apache/druid/pull/12841
