### ISSUE TITLE
Querying for data in newly announced segment (sometimes) gives no results.

### ISSUE THREAD

**Issue by KenjiTakahashi** [apache/druid#1291]
When a node is queried for data in new segment _almost_ immediately after it arrives, it sometimes behaves like it's not there yet.

At first I've noticed it in our dev environment and thought it was something with broker<->realtime communication maybe. But I am able to reproduce it when querying realtime directly as well.

I've made a script for testing this: https://gist.github.com/KenjiTakahashi/c1fdb5cffdf2332792f8.
When ran (see comment in gist) with `python druid_test.py <6/7> p` on an empty node, it should yield `1`, but sometimes it gives `0`.
Yet I can see the data being added and if there's a little `sleep` between push and query, it seems to work OK.

Reproduced in both 0.6.171 and 0.7.1.1 with following configs, respectively: https://gist.github.com/KenjiTakahashi/e3ddb3be80690bfe21be, https://gist.github.com/KenjiTakahashi/f3d97f27c9ac2adc3872.

Note that this only happens on new segments, when adding subsequent items to segment, it returns them all all right.

I understand that it's probably a pretty strange use case on a system like this (it is a corner in ours as well, we do mostly use Druid like it's supposed to :-)). But I wonder if there is any way to mitigate the problem? Preferably without polling on our side ;-).

**Comment by drcrallen** [comment]
I'm not overly familiar with RabitMQ's pika internals, but if you turn on any of the [mandatory delivery](http://pika.readthedocs.org/en/latest/examples/blocking_publish_mandatory.html) or [delivery confirmation](http://pika.readthedocs.org/en/latest/examples/blocking_delivery_confirmations.html) stuff does it still exhibit this behavior?

**Comment by KenjiTakahashi** [comment]
Thanks for the hints. I've tried both options (and also a combination of both). Delivery confirmation seems to improve the situation a bit, but it still happens, although kinda less often.
Still looking for a reliable solution :-).

On a side question (but maybe related). Do you know why elements sometimes do not appear in "basePersistDirectory"? They are shown in logs in processed and I can query for them, but they're not in the dir. And apparently they are also still sitting in rabbit. Could it be some problem with rabbit firehose? [Dunno if this is true in 0.7, spotted in 0.6 only so far.]

**Comment by nishantmonu51** [comment]
when events are ingested they are added to an in memory buffer first, 
these events are then persisted to disk i.e basePersistDirectory either periodically (configured by intermediatePersistPeriod) or hitting a threshold on number of rows in memory (configured via rowFlushBoundary), its fine to not see events getting written to disk as soon as they are getting ingested but they are made queryable from in memory buffer.

**Comment by KenjiTakahashi** [comment]
That makes sense, must have been sleepy yesterday. And copies are probably left in the queue to prevent data loss in case node fails to flush to disk for some reason. Yeah, makes sense, thanks for the explanation. So the OT section is closed for now :-).

**Comment by xvrl** [comment]
Thanks @KenjiTakahashi, I'm going to close this for now, please reopen if the issue pops up again

**Comment by KenjiTakahashi** [comment]
Oh, I think I've been misunderstood a bit here. The issue is still here. Hint from @drcrallen made it a bit less frequent, but I can still reproduce it without much problem in our dev environment. The "closed" part was only related to the question about intermediatePersist behaviour.

BTW: Apparently I cannot reopen issues if closed by someone else, @xvrl :-(.
