### ISSUE TITLE
Text box search in the Status pop-up window is broken in 0.23.0.

### ISSUE THREAD

**Issue by abhishekrb19** [apache/druid#12921]
Typing into the search box in the "Status" pop-up window in the Druid console doesn't return any result.

Please see the attached gif:
![CleanShot 2022-08-18 at 11 42 26](https://user-images.githubusercontent.com/8687261/185470527-53282556-e422-45c4-9eed-164783868c1e.gif)

This is found in 0.23.0.

/cc: @vogievetsky

**Comment by vogievetsky** [comment]
I am happy to report that this was fixed (and improved) as part of https://github.com/apache/druid/pull/12919

<img width="1084" alt="image" src="https://user-images.githubusercontent.com/177816/186831734-4eab9c9b-f892-43cb-a182-4bbb4365c303.png">

And:

<img width="1084" alt="image" src="https://user-images.githubusercontent.com/177816/186831777-fb38e730-3ca7-40b7-a8eb-3814abc0d005.png">
