### ISSUE TITLE
[Flaky IT] ITKafkaIndexingServiceNonTransactionalParallelizedTest.testKafkaIndexDataWithWithAutoscaler is flaky

### ISSUE THREAD

**Issue by abhishekagarwal87** [apache/druid#13093]
This test often fails. Here is one such example - https://app.travis-ci.com/github/apache/druid/jobs/582859601 
The changes in the PR are unrelated.

**Comment by 599166320** [comment]
When I test, I often see this failure, which has nothing to do with my PR.  https://app.travis-ci.com/github/apache/druid/jobs/584966730
