### ISSUE TITLE
Wrong version format? 24.0.0 vs. 0.24.0

### ISSUE THREAD

**Issue by GElkayam** [apache/druid#13129]
Hi @abhishekagarwal87
I see version "24" was release and marked as 24.0.0 as the version before it was 0.23.0.
Did the format officially change, or that was a typo?
https://github.com/apache/druid/releases/tag/druid-24.0.0
https://github.com/apache/druid/releases/tag/druid-0.23.0

**Comment by FrankChen021** [comment]
It's not wrong. The version scheme has been changed since this version.
See: https://lists.apache.org/thread/w7phy1kz52lq3p9mty597tmtd3br858m

**Comment by abhishekagarwal87** [comment]
Yes. The versioning change is intentional. Druid's versioning scheme was so far `0.major.minor`. In this release, we switched to `major.minor.patch` scheme. There is more context in the email link that Frank has shared.
