### ISSUE TITLE
docker pull not working for apache druid

### ISSUE THREAD

**Issue by sc-aniagr** [apache/druid#13139]
While running docker pull apache/druid, i am getting the below error 

![image](https://user-images.githubusercontent.com/108719736/191913302-c1bfa0f1-7640-4053-be81-1b9d721d02ae.png)

**Comment by FrankChen021** [comment]
The error message is very clear.

Druid does not provide docker images with the 'latest' tag. You need to specify a tag when you pull the image. You can find all tags on docker hub. The latest is 24.0.0
