### ISSUE TITLE
CPU broker 100% after upgrade to 24.0 

### ISSUE THREAD

**Issue by Z08JBECH** [apache/druid#13145]
Hello,

We had to do a rollback from druid 24.0.0 to druid 0.23.0

We have a prblem with druid 24.0.0 and avatica.

some requests increase the CPU to 100% of the broker nodes and it comes down only if you restart the service
When the broker node reach 100% we have timeout on all our jdbc request from our api with jdbc driver.

I tried with java 8 and 11 and it is the same problem.

A simple request like select * from, from my dbeaver tool with avatica driver create the problem.

No problem after the rollback.

**Comment by abhishekagarwal87** [comment]
There isn't any known issue that I am aware of. If it's just the broker nodes, you can take thread dumps when the CPU is 100%. They will help a lot in pinning down the problem.
