### ISSUE TITLE
The Etag format of s3-extensions may cause errors in some environments.

### ISSUE THREAD

**Issue by hnakamor** [apache/druid#13166]
### Affected Version

Druid 24.0.0

### Description

I noticed that s3-extensions uses the getETag() value directly in MatchingETagConstraint().
https://github.com/apache/druid/blob/275f834b2a9f23cec59dfeeb9ab44ac9081620fe/extensions-core/s3-extensions/src/main/java/org/apache/druid/storage/s3/S3TaskLogs.java#L98

Since getEtag() returns the value with leading and trailing quotes removed, using this value as is will result in an error response of "HTTP/1.1 412 Precondition Failed" in some s3 applications.
https://github.com/minio/minio-go/issues/687

In environments where this error is returned, you will not be able to view Druid task reports or task logs from the Overlord API or the web console.

Why not follow RFC7232 and add leading and trailing quotation marks?

**Comment by FrankChen021** [comment]
I'm not familiar with this part. But if current behavior does not follow the standard, a PR is welcome to improve it.
