### ISSUE TITLE
Compaction tasks fails with index_parallel task type but passes when task type is index

### ISSUE THREAD

**Issue by sachidananda007** [apache/druid#13199]
### Affected Version

The Druid version where the problem was encountered.
0.19.0
### Description
Compaction tasks fails for a specific datasource and specific interval with index_parallel task type but passes when task type is index

we have a specific datasource and for a specific interval (MONTH)
compaction tasks are submitted as **index_parallel** task. It started failing with all subtasks not showing any log in druid ui and 404 status.

for testing we submitted the same compaction task (for same datasource and interval)with **index** type and it passed with out any error.

To add to the above, we manually validated the existence of SegmentIDs(from compaction task spec generated by sruid) in the Druid metadata table to rule out presences of non-existent segment in the single_phase_sub_task compaction spec generated by Druid. And all the segments were found

**Comment by tejaswini-imply** [comment]
Hi, Thanks for raising the issue. Could you please share the spec for which the compaction task is failing?
