### ISSUE TITLE
SQL-based ingestion cannot generate daily segments taking time zone into account.

### ISSUE THREAD

**Issue by hnakamor** [apache/druid#13230]
Hi all,

The SQL-based ingest by MSQ is a great feature. I have tried it and in my environment it has roughly doubled the data ingestion speed.

However, it seems that all segment granularity and specific intervals, which are possible with Native Batch Ingestion, are not possible with MSQ.
Thus, it is not possible to generate daily segments that take time zones into account.

The following is an example of specifying with Navite Batch Ingestion.
```
{
  "spec": {
    "dataSchema": {
      "granularitySpec": {
        "segmentGranularity": "all",
        "intervals": [
          "2000-01-01T15:00/2000-01-02T15:00"
        ]
      }
    }
  }
}
```

Confirmed on 25.0.0-SNAPSHOT and 24.0.0。

It would be useful if MSQ could generate daily segments that take time zones into account.
Considering the overwrite, in my timezone, the only partition option in MSQ is HOUR.

**Comment by LakshSingla** [comment]
It is great to hear that you are having positive results with the new MSQ based ingestion 😃 

Based on the `granularitySpec` that you mentioned in the issue, does filtering the data and then ingesting it like the following query work? 

```sql
INSERT INTO
...
WHERE WHERE __time >= TIMESTAMP '2000-01-01 15:00:00' AND __time < TIMESTAMP '2000-01-02 15:00:00'
PARTITIONED BY ALL
```

**Comment by gianm** [comment]
Alternatively, what if we supported something like `PARTITIONED BY TIME_FLOOR('P1D', '-09:00')`, or perhaps `PARTITIONED BY TIME_FLOOR('P1D', 'America/Adak')`?

**Comment by hnakamor** [comment]
@gianm Thank you for your response.
Your idea is great.
And it would be even more useful if we could apply the "sqlTimeZone" context.
Here is the first query and context I tried.
````
INSERT INTO inline_data
WITH ext AS (SELECT *
FROM TABLE(
  EXTERN(
    '{"type": "inline", "data":"{\"time\":\"2000-01-01T15:00:00\"}"}',
    '{"type": "json"}',
    '[{"name": "time", "type": "string"}]'
  )
))
SELECT TIME_PARSE("time") AS __time
FROM ext
PARTITIONED BY DAY
````
```
{
  "sqlTimeZone":"+09:00"
}
```
The above result was `2000-01-02T00:00:00.000Z/2000-01-03T00:00:00.000Z`, but I expected `2000-01-01T15:00:00.000Z/2000-01-02T15:00:00.000Z` or `2000-01-02T00:00:00.000+09:00/2000-01-03T00:00:00.000+09:00`.

**Comment by darkbaby** [comment]
Any updates on this issue?

I face this problem too and want this use case to be real.

Many thanks
