### ISSUE TITLE
use thetaSketch when index hadoop , a little  mertic of thetaSketch values is null. So I can not upgrade druid from 0.20.2 to 24.0

### ISSUE THREAD

**Issue by Maplejw** [apache/druid#13264]
When I uprage druid from 0.20.2 to 24.0.
broker can not launch successfully, it's log
![image](https://user-images.githubusercontent.com/24646597/197926859-47f5f3ed-dfed-4b41-badf-d15c90d5fdfc.png)

It means some datasources the device_id_sketch is null, so I check my datasource and ingestion spec
![image](https://user-images.githubusercontent.com/24646597/197926531-4e919175-9d61-4712-ac9a-4b88447ca34d.png)

this is my ingestion spec about metricsSpec
```
"metricsSpec": [
      {
        "type": "longSum",
        "name": "behavior_total_times",
        "fieldName": "behavior_total_times",
        "expression": null
      },
      {
        "type": "thetaSketch",
        "name": "device_id_sketch",
        "fieldName": "device_id",
        "size": 16384,
        "shouldFinalize": true,
        "isInputThetaSketch": false,
        "errorBoundsStdDev": null
      }
    ]
```

So why my device_id is not null, but device_id_sketch is null,and why 0.20.2 it run well,but upgrate 24.0,it fails

**Comment by abhishekagarwal87** [comment]
Hi - what is your order of upgrade? can you try upgrading historicals first before the broker and see if that resolves the issue?

**Comment by Maplejw** [comment]
> Hi - what is your order of upgrade? can you try upgrading historicals first before the broker and see if that resolves the issue?
Thank you for your answer.
To use prometheus-emitter,it supports 0.22.0 Minimum version.
Ok,I try to upgrade historicals first.
But I still  have a question,why the device_id_sketch is null,but device_id is not null?

**Comment by Maplejw** [comment]
upgrade to 0.22.0 and upgrade historicals first,upgrade broker finally,it works.
