### ISSUE TITLE
Druid doesn't cancel the query request explicitly

### ISSUE THREAD

**Issue by nisart007** [apache/druid#13284]
### Affected Version

Druid Version :0.22.1

### Description

In my usecase I am using Druid data on dasboard with UI cancel option, so that user can cancel the request explicitly and run the next query.

I was testing the way mentioned on the Druid doc  https://druid.apache.org/docs/latest/querying/sql-api.html#cancel-a-query

### Test 1
Long running POST request:
`curl --request POST 'https://router:8888/druid/v2/sql' \ --header 'Content-Type: application/json' \ --data-raw '{"query" : "SELECT COUNT(*) from MyDataSource", "context" : {"sqlQueryId" : "myQuery01"}}'`

Cancel Request:
`curl --request DELETE 'https://router:8888/druid/v2/sql/myQuery01'`

I was expecting as soon I run the Cancel curl request then long running request should be interupted. But nothing happening.
Cancel request always return **404** http status, I was expecting **202** as per the doc.

Where as following endpoint always return **202** even the query is not running or queryid is not present in druid system as well, which is wrong too.
`curl --request DELETE 'https://router:8888/druid/v2/myQuery01'`
(Removed /sql from the URL)

### Test 2
To be more precise I have added timeout 60 seconds also in the query context and run cancel/delete request many times before 60 seconds.

Long running POST request:
`curl --request POST 'https://router:8888/druid/v2/sql' \ --header 'Content-Type: application/json' \ --data-raw '{"query" : "SELECT COUNT(*) from MyDataSource", "context" : {"sqlQueryId" : "myQuery01", "timeout": 60000}}}'`

Finally long running request query timeout happend and I got:

```
{
"error": "Query timeout",
"errorMessage": "Query [cacb33d5-f575-44c0-8672-de364e827382] timed out!",
"errorClass": "org.apache.druid.query.QueryTimeoutException",
"host": "[10.10.10.10:8083](http://10.10.10.10:8083/)"
}

```
**Still cancel request always returning 404.**

**Comment by rohangarg** [comment]
@nisart007 : Thanks a lot for the investigation and reporting of the issue! Cancellation for SQL queries was added a part of 0.23.0 release (ref : https://github.com/apache/druid/issues/12510#0.23.0-new-features-sql-cancel-api-for-sql-queries).
Could you please try with latest Druid version 24.0 and see if that works for you?

**Comment by nisart007** [comment]
@rohangarg Thanks for your help.

Yes, you are right!! It is working fine version in 24.0 for SQL Query and native Query.

Let me conclude Cancel API testing:

### Native query

Long running POST request:

   `curl --request POST 'https://router:8888/druid/v2/sql' \ --header 'Content-Type: application/json' \   --data-raw '{"queryType":"timeseries","dataSource":{"type":"table","name":"myDataSource"},"intervals":{"type":"intervals","intervals":["2022-09-01T00:00:00.000Z/146140482-04-24T15:36:27.903Z"]},"granularity":{"type":"all"},"aggregations":[{"type":"longSum","name":"a0","fieldName":"sum_Views"}],"context":{"sqlOuterLimit":1001,"queryId":"nativeQueryId"}}'`

Cancel Request:  

`curl --request DELETE 'https://router:8888/druid/v2/nativeQueryId'`

Cancel request returns 202 Accepted and it was successfully cancelled.


### SQL query (Support Druid version >=0.23.0 )
Long running POST request:

`curl --request POST 'https://router:8888/druid/v2/sql' \ --header 'Content-Type: application/json' \ --data-raw '{"query" : "SELECT COUNT(*) from MyDataSource", "context" : {"sqlQueryId" : "sqlQueryId"}}'`

Cancel Request:  

`curl --request DELETE 'https://router:8888/druid/v2/sql/sqlQueryId'`

Cancel request returns 202 Accepted and it was successfully cancelled.

#### Both Test Long Running POST response after cancel: 

    {
    "error": "Query cancelled",
    "errorMessage": "Future.cancel() was called.",
    "errorClass": "java.util.concurrent.CancellationException",
    "host": "10.10.10.10:8083"
    }

This is not an issue hence closing it.

**Comment by nisart007** [comment]
SQL query cancel was added in the Druid version 0.23.0. Teste in version 24.0 for SQL Query and native Query.
