### ISSUE TITLE
./bin/dsql Can't run in Docker 'router' Container

### ISSUE THREAD

**Issue by Qwtdgh** [apache/druid#13350]
Please provide a detailed title (e.g. "Broker crashes when using TopN query with Bound filter" instead of just "Broker crashes").

### Affected Version

apache/druid 24.0.0
ubuntu 18

### Description

-Containers I have
router broker historical middlemanager coordinator zookeeper postgress

- Cluster size 

- Configurations in use
`docker-compose.yml` & `envrionment`

- Steps to reproduce the problem
Fisrt I run `docker-compose up -d`
and see containers in  docker as above

- The error message or stack traces encountered. Providing more context, such as nearby log messages or even entire logs, can be helpful.
then, run `docker exec -it router bash` in router cluster
last, run `./bin/dsql` to try begin druid sql
but iti show me error as follow
```
./opt/druid/bin/dsql: /opt/druid/bin/dsql-main: /usr/bin/env: bad interpreter: No such file or directory
./opt/druid/bin/dsql: line 28: /opt/druid/bin/dsql-main: No error information
```

- Any debugging that you have already done
i try to see `/usr/bin/`,and find that there don't have `env` dictionary
and i was denied to create `env` dic.

Please help me

**Comment by gianm** [comment]
From your report, it sounds like the issue is that the `dsql` script depends on `/usr/bin/env`, but that is not present in the Docker container. So we'd need to either change the `dsql` script or the Docker container.

**Comment by gianm** [comment]
As a workaround, try changing `#!/usr/bin/env python` to `#!/usr/bin/python` at the first line of `/opt/druid/bin/dsql-main`. I am not sure if this will work, as I don't have a Docker environment handy, but it will if `python` is present in the container.

**Comment by Qwtdgh** [comment]
tks
