### ISSUE TITLE
Different auto-compaction configs based on the age of the data segments

### ISSUE THREAD

**Issue by remizyaka** [apache/druid#13362]
### Description
It would be good  to have several auto compaction tasks for one datasource based on segment age. 

### Motivation

If for example I want to have  Hour granularity for last 30 days, Day granularity and less dimensions for 30-365 days, Year granularity and only several dimensions left for 365+ days. As usually for older data we only need to have some general overview and not detailed reports.

**Comment by gianm** [comment]
Sounds like a useful feature!

cc @paul-rogers for fyi: we can consider this when autocompaction is integrated into the catalog (#12546).

**Comment by OurNewestMember** [comment]
Not sure if this is what others had in mind, but supporting this workflow could be helpful:
- operator defines zero or more compaction configs per data source (like retention rules)
- (per existing behavior) coordinator lists segments for compaction
- compaction tasks for an interval are created using the matching compaction config (if they haven't already been compacted with that compaction spec)

Other notes
- it would help to also support a no-op compaction config so the operator can effectively exclude intervals
    - The assumption is that this could work with the existing mechanisms to mark the segments as "already compacted" so they can be skipped subsequently
