### ISSUE TITLE
SocketUtil.findOpenPort does not always find a desired port correctly for unit tests

### ISSUE THREAD

**Issue by drcrallen** [apache/druid#1341]
There are numerous places in unit tests that `localhost` is used when querying the unit test services. When this is used in conjunction with `io.druid.common.utils.SocketUtil#findOpenPort`, lots of unexpected behavior can happen. Specifically, there seem to be many cases where jetty services will bind to `0.0.0.0:SOME_PORT` but `localhost:SOME_PORT` may already be bound by another process. So unit tests will fail.

**Comment by drcrallen** [comment]
An example of this is if a VirtualBox instance is running which has port forwarding on `SOME_PORT`, then `SocketUtil` will not find it bound, but any attempts to connect to `localhost:SOME_PORT` can go through the port forward to the VM instead of to the desired bound port in the JVM

**Comment by tan31989** [comment]
@fjy is this ticket still up for fix?
