### ISSUE TITLE
Unauthorized call to /druid/indexer/v1/supervisor returns 200

### ISSUE THREAD

**Issue by wiegandf** [apache/druid#13507]
### Affected Version

0.23.0

## Description

The get endpoint for `/druid/indexer/v1/supervisor` seems to require more than just read permissions. With missing those permissions, the API returns a 200 with an empty list. I would expect a 401 Unauthorized. When authorized, the API returns all the data required. 

So basically I see two issues:
- The API should respond with 401 for unauthorized calls
- Why does the list supervisor operation require write permissions?

This behavior breaks e.g. https://github.com/opstree/druid-exporter/blob/master/collector/druid.go#L50-L67. 

### Configurations in use
druid-basic-security

```
  druid_auth_authenticatorChain: '["MyBasicMetadataAuthenticator"]'
  druid_auth_authenticator_MyBasicMetadataAuthenticator_type: basic
  druid_auth_authenticator_MyBasicMetadataAuthenticator_authorizerName: MyBasicMetadataAuthorizer
  druid_auth_authorizers: '["MyBasicMetadataAuthorizer"]'
  druid_auth_authorizer_MyBasicMetadataAuthorizer_type: basic
  druid_escalator_type: basic
  druid_escalator_internalClientUsername: druid_system
  druid_escalator_authorizerName: MyBasicMetadataAuthorizer
```

### Steps to reproduce the problem
-  Have one user with the following permissions: 
    ```json
    [
	    {
		    "resource": {
			    "name": ".*",
			    "type": "DATASOURCE"
		    },
		    "action": "WRITE"
	    },
	    {
		    "resource": {
			    "name": ".*",
			    "type": "CONFIG"
		    },
		    "action": "WRITE"
	    },
	    {
		    "resource": {
			    "name": ".*",
			    "type": "STATE"
		    },
		    "action": "WRITE"
	    },
	    {
		    "resource": {
			    "name": ".*",
			    "type": "DATASOURCE"
		    },
		    "action": "READ"
	    },
	    {
		    "resource": {
			    "name": ".*",
			    "type": "CONFIG"
		    },
		    "action": "READ"
	    },
	    {
		    "resource": {
			    "name": ".*",
			    "type": "STATE"
		    },
		    "action": "READ"
	    }
    ]
    ```
- Another one with just
  ```json
  [
	{
		"resource": {
			"name": ".*",
			"type": "DATASOURCE"
		},
		"action": "READ"
	},
	{
		"resource": {
			"name": ".*",
			"type": "CONFIG"
		},
		"action": "READ"
	},
	{
		"resource": {
			"name": ".*",
			"type": "STATE"
		},
		"action": "READ"
	}
  ]
  ```

**Comment by abhishekagarwal87** [comment]
The supervisor is responsible for ingesting the data and that's why supervisor operations require write access. what operation are you referring to?

**Comment by wiegandf** [comment]
But the endpoint is just a get endpoint and doesn't ingest anything, right? So according to https://druid.apache.org/docs/latest/operations/security-user-auth.html#http-methods it should only require read permissions?

**Comment by kfaraz** [comment]
@wiegandf , that's correct, this is just a GET endpoint. So you are authorized to hit the API itself, but the result of the API is the list of supervisors to which you have WRITE access.

So you can always hit the API successfully, even if you don't have WRITE access to any supervisor. In that case, as you observed, you would get back an empty list. Hope that clarifies the confusion.

As for the docs,
> GET requests require READ permissions, while POST and DELETE requests require WRITE permissions.

This does hold true for the API in question as you are successfully able to hit the API even when you don't have WRITE permissions.
