### ISSUE TITLE
MILLIS_TO_TIMESTAMP function discards the millisecond part

### ISSUE THREAD

**Issue by jeclarke** [apache/druid#13509]
When calling MILLIS_TO_TIMESTAMP any milliseconds do not appear in the produced timestamp. The produced timestamp always has .000 for milliseconds.

### Affected Version
0.23.0

### Description

To reproduce this issue run the following SQL:
````
SELECT MILLIS_TO_TIMESTAMP(1670325506528) AS my_timestamp
````

The output is:
````
my_timestamp
2022-12-06T11:18:26.000Z
````

I expected the output to be:
````
my_timestamp
2022-12-06T11:18:26.528Z
````

**Comment by k-haley1** [comment]
@abhishekagarwal87 are there plans to fix this bug?

**Comment by LakshSingla** [comment]
I tested this out on the latest master, and it is producing the expected result. I am on the latest master branch. Can you please check if upgrading to the newest version 25.0.0 resolves this bug?

<img width="1241" alt="Screenshot 2023-01-30 at 10 15 08 PM" src="https://user-images.githubusercontent.com/30999375/215540329-771f6bb7-74e5-462c-92af-f56ce27ae5e8.png">

**Comment by abhishekagarwal87** [comment]
Thank you @LakshSingla for verifying.

**Comment by sergei3000** [comment]
Sorry about writing in this closed thread.

Did this also fix the problem that I can see in my Druid instance when `SELECT TIME_PARSE('2023-10-19T09:29:58.613Z')` results in `2023-10-19T09:29:58.000Z` cutting off the milliseconds part (I run this in Druid's web UI)? I expect the result to be `2023-10-19T09:29:58.613` keeping the milliseconds and not cutting them off.

Also filtering like `WHERE __time >= '2023-10-19T09:29:58.613Z'` returns records with timestamps above `09:29:58.000` but below `09:29:58.613` for me which seems to be related to the `TIME_PARSE` problem.

**Comment by sergei3000** [comment]
Turns out it was a bug and it was fixed. I installed version `27.0.0` locally and `TIME_PARSE` returns milliseconds now and filtering seems to account for milliseconds as well.
