### ISSUE TITLE
kafka stream request timeout

### ISSUE THREAD

**Issue by sc-aniagr** [apache/druid#13504]
I struggle with setting timeout while streaming data from the Kafka topic to druid ingestion. I want to do this at frequent intervals automatically and want to increase timeout interval as this topic is supposed to have a lot of data, thus fails during streaming.

**Comment by AmatyaAvadhanula** [comment]
Hi @sc-aniagr 
Are you referring to the kafka consumer poll timeout? 
It can be increased in the supervisor spec by setting `pollTimeout`
https://druid.apache.org/docs/latest/development/extensions-core/kafka-supervisor-reference.html#kafkasupervisorioconfig
