### ISSUE TITLE
issue in building from source code

### ISSUE THREAD

**Issue by Jithin2867** [apache/druid#13528]
When i try to build it from source code 
it showing some console error and the building process gets killed.  please help 
![Screenshot (15)](https://user-images.githubusercontent.com/91589047/206354397-535fc44d-c609-4230-8d44-2f7814a346c0.png)
![Screenshot (16)](https://user-images.githubusercontent.com/91589047/206354418-d6b0d3f2-8bcb-4eae-b496-bd871e664f8f.png)

**Comment by vogievetsky** [comment]
These are not build blocker these are warnings that get generated on every build (see the `[info]` tag). What is the actual error that stops the build?. Also, separately, what is your version of node? (run `node --version`)

**Comment by Jithin2867** [comment]
node --version
v16.18.1

**Comment by cryptoe** [comment]
```json
"volta": {
    "node": "16.17.0",
    "npm": "8.15.0"
  }
```
  I recommend you to install volta 
  https://volta.sh/
