### ISSUE TITLE
Remove python installation instructions / update quickstart

### ISSUE THREAD

**Issue by techdocsmith** [apache/druid#13607]
The quickstart now requires python. #13365 included instructions to install python. This should not be maintained in the Aapche Druid docs since it is well documented. Links should reference an external document.

The quickstart specifically instructs you to download the current version, then says you need Druid 24 or higher. Then provides instructions that only work with 25. Remove the 24 or higher requirement. If the person is downloading the bits per the instructions, they should be on the latest.

**Comment by hevansDev** [comment]
Does this still need doing? Looks like `docs/operations/python.md` has already been removed

**Comment by techdocsmith** [comment]
Done
