### ISSUE TITLE
Druid stable release & helm repo

### ISSUE THREAD

**Issue by Mutantt** [apache/druid#13643]
Hi
I've searched for helm repo to add with "helm repo add" command for druid and I couldn't find any,is there any repo ?
Also please let me know what is the latest stable release for helm.is  25.0.0 the latest ?because I can't find it too!
thanks

**Comment by EylonLevy** [comment]
There is a helm chart for the operator, after that, you can install a druid cluster with a single yaml file containing the CR.

**Comment by hagaibarel** [comment]
We're still interested in this

**Comment by asdf2014** [comment]
@Mutantt @EylonLevy @beobest2 @hagaibarel Thanks for your contribution. As mentioned in PR [https://github.com/apache/druid/pull/15904](https://github.com/apache/druid/pull/15904), we have migrated the Helm Chart to a [new repository](https://github.com/asdf2014/druid-helm), you are welcome to raise up new one there and we can maintain the Druid Helm Chart together in new repository. And this PR will closed soon. Thank you again for your understanding and collaboration.
