### ISSUE TITLE
0.16.1 No known server / java.lang.RuntimeException

### ISSUE THREAD

**Issue by laglangyue** [apache/druid#13658]
Please provide a detailed title (e.g. "Broker crashes when using TopN query with Bound filter" instead of just "Broker crashes").

### Affected Version

0.16.1
### Description
I use these files to start druid by `docker-compose up -d`
docker-compose.yml
environment
but there are some exception
![image](https://user-images.githubusercontent.com/35491928/211796858-cec23866-986f-4222-9096-f7bcbbbed322.png)

**Comment by cryptoe** [comment]
@laglangyue 0.16.1 is quite an old version of druid. Suggest you try with the latest version 25.0 and see if you run into the same issue.

**Comment by laglangyue** [comment]
> @laglangyue 0.16.1 is quite an old version of druid. Suggest you try with the latest version 25.0 and see if you run into the same issue.

yes，the 24.0.1 is ok, and 0.17.0 is so on. And my customer uses this version. I just want to deploy this version to test my code

**Comment by laglangyue** [comment]
Do you know how to solve it

**Comment by laglangyue** [comment]
In fact, once I modify the port mapping, this error will occur

**Comment by acherla** [comment]
Without logs for the broker we cant really assist here as it seems like you are describing two different problems in your issue statement.  
1. Is cluster instability (broker) crashing when running topN queries
2. Cluster setup when using docker-compse (Services likely either not being deployed or crashing) resulting in the error you are receiving

**Comment by laglangyue** [comment]
> Without logs for the broker we cant really assist here as it seems like you are describing two different problems in your issue statement.
> 
> 1. Is cluster instability (broker) crashing when running topN queries
> 2. Cluster setup when using docker-compse (Services likely either not being deployed or crashing) resulting in the error you are receiving

You can reproduce this problem on your local computer，just The recurrence step is to deploy version 0.16.1 using docker-compose up - d.
After deployment, open router(web console), and these exceptions will appear.

**Comment by laglangyue** [comment]
> @laglangyue Initially with version 25.0.0 i was not having any problem but when i siwtched to mysql this problem arised any solution?

sorry, I don't know, In my opinion, I think it caused by docker host addressing.
