### ISSUE TITLE
Exited docker containers: can't create directory 'var/druid/': Permission denied

### ISSUE THREAD

**Issue by ppopovpoly** [apache/druid#13656]
Docker containers (middlemanager, historical, broker, router, coordinator) status - Exited

### Affected Version

druid:25.0.0
Debian 10
Docker version 20.10.17, build 100c701
Docker Compose version v2.6.0

### Description

Druid install with Docker
docker-compose.yml - https://github.com/apache/druid/blob/25.0.0/distribution/docker/docker-compose.yml
environment - https://github.com/apache/druid/blob/25.0.0/distribution/docker/environment

1. docker compose up -d
[+] Running 8/8
 ⠿ Network druid_default    Created
 ⠿ Container postgres       Started
 ⠿ Container zookeeper      Started
 ⠿ Container coordinator    Started
 ⠿ Container router         Started
 ⠿ Container broker         Started
 ⠿ Container historical     Started
 ⠿ Container middlemanager  Started
 
2. docker ps -a
apache/druid:25.0.0             "/druid.sh router"       6 minutes ago   Exited (1) 6 minutes ago    router
apache/druid:25.0.0             "/druid.sh historical"   6 minutes ago   Exited (1) 6 minutes ago   historical
apache/druid:25.0.0             "/druid.sh broker"       6 minutes ago   Exited (1) 6 minutes ago   broker
apache/druid:25.0.0             "/druid.sh middleMan…"   6 minutes ago   Exited (1) 6 minutes ago    middlemanager
apache/druid:25.0.0             "/druid.sh coordinat…"   6 minutes ago   Exited (1) 6 minutes ago    coordinator

3. docker compose logs middlemanager (and other container with status Exited)
mkdir: can't create directory 'var/tmp': Permission denied
mkdir: can't create directory 'var/druid/': Permission denied

**Comment by acherla** [comment]
Can you provide your docker-compose configuration (with the password masked).  I am unable to reproduce this issue in either docker-compose or as a part of deploying image version 25.0.0 using the kubernetes operator.

**Comment by ppopovpoly** [comment]
This problem was solved by granting rights to the directories created after the launch.
