### ISSUE TITLE
Data migration from MongoDB to Apache Druid

### ISSUE THREAD

**Issue by sc-aniagr** [apache/druid#13679]
Need help with data migration from mongoDB to apache druid. If anyone has done this previously or planning to do so, and can guide with the process, it would be a great help. The data is bulky thus looking to build a script to achieve the same, so if anyone has any information in this context, then would appreciate the help.

**Comment by abhishekagarwal87** [comment]
is the data getting updated continuously? If not, maybe you can export data from MongoDB to cloud storage. And then ingest the data from cloud storage to Druid. Druid supports multiple data formats for ingestion.

**Comment by sc-aniagr** [comment]
hi @abhishekagarwal87 the data is getting countiously update and data is bulky -- 300M ++. Exporting is taking a lot of time.

**Comment by abhishekagarwal87** [comment]
There isn't a direct way to get data into druid. If the data is getting streamed, then you can start realtime ingestion on druid from the same source. The old data has to be backfilled through a 2-step migration process.
