### ISSUE TITLE
JSON flattener should respect druid null handling config (druid.generic.useDefaultValueForNull) for arrays

### ISSUE THREAD

**Issue by davidgmonical** [apache/druid#13685]
Currently when ingesting json data with multivalue fields, druid parses the input source with logic that includes removing `null` values from the individual arrays. This happens as part of the json flattening [here](https://github.com/apache/druid/blob/22630b0aabbaf683748b65a698ccbf966e1a54a4/core/src/main/java/org/apache/druid/data/input/impl/JsonLineReader.java#L70). An example, supposed we try to ingest:
```
{"list":[0.5, 0.2, null],"timestamp":"2023-01-11T22:57:44.270035398Z"}
```
We end up with a table that looks like (note the lack of `null` in the multivalue field):
<img width="979" alt="Screen Shot 2023-01-17 at 12 06 32 PM" src="https://user-images.githubusercontent.com/22461273/213000830-20ccc51d-c663-4c19-8f1b-5f1dd81bef34.png">

The `null` removal occurs [here](https://github.com/apache/druid/blob/22630b0aabbaf683748b65a698ccbf966e1a54a4/core/src/main/java/org/apache/druid/java/util/common/parsers/JSONFlattenerMaker.java#L177-L179) when we are parsing the individual entries in the multivalue json fields. It's unclear from any documentation that I could find that this is intended behavior. It seems to me like if druid respects `null` values for single-value fields (with regards to `druid.generic.useDefaultValueForNull`), then it should also respect `null` entries in multivalue fields.

**Comment by clintropolis** [comment]
I've also noticed this recently when working in this area; its not just limited to JSON, but also at least Avro also has this behavior. I'm unsure about the other nested formats (ORC, Parquet, Protobuf), an initial look seems like they might be ok.

I was planning to try to fix this in the near future since I agree it doesn't really make sense for the values to be removed here, or am happy to review if you've already got a fix underway.

**Comment by davidgmonical** [comment]
Nothing underway but happy to take a stab at it. Would love a review once I have it up thank you!

**Comment by somu-imply** [comment]
The same issue happens with Avro too. I have set up #13712 to tackle both
