### ISSUE TITLE
Druid Version 0.22.1 - Long Coordinator handoff times

### ISSUE THREAD

**Issue by acherla** [apache/druid#13692]
Hi Druid team,
We manage a cluster that has over 3K+ peons (116 middle managers) and 200+ historical nodes (4-5 million segments) with two masters configured as both coordinator/overlord.  We run close to around 400+ streaming ingest jobs into druid and we noticed that many of our peon tasks are getting stuck via "Coordinator handoff scheduled - Still waiting for handoff for X segments".  This handoff can take anywhere from a few minutes to 30+ minutes depending on the configured completionTimeout period (Job Fails, but its still marked as success in the logs).  

In order to optimize our druid cluster we began modifying the following parameters which did help the performance of the coordinator/overlord, but we are still seeing handoff times taking 20-30 minutes at times.
1. Decreased percentOfSegmentsToConsiderPerMove from 70 percent down to 10 percent.  
2. Modified our tasks to create larger and fewer segments to bring down the overall segment count. 
3. increased the number of pendingSegment threads on the coordinator/overlord from 1 to 10 to handle handing off multiple segments.

Some of the optimization done in 25.0.0 should assist this via the batch segment allocation parameter, but im wondering prior to 25.0.0 if there are strategies that can be employed to improve the segment handoff time on the coordinator?

2nd question is even if a task does not complete within the completionTimeout window I am assuming the segment isnt just dropped, since internally in the logs the task is marked as successfull but the segment will likely not be served for queries until the handoff internally is completed by the coordinator -> historical (meaning the peon will not serve requests either for that segment as the task has been terminated once completionTimeout window has elapsed).  Is this a correct assumption?

**Comment by abhishekagarwal87** [comment]
Wow. that's a pretty impressive scale. 

I would definitely recommend upgrading to 25.0. However, that alone won't be sufficient. There are some config changes required to make the best use of optimizations that are added in 25.0. 

Switching to round-robin assignment for segment assignment will definitely help with long handoff time (https://github.com/apache/druid/pull/13367). That strategy is not available in 24.0 release. You should also turn on
 - druid.indexer.tasklock.batchSegmentAllocation 
 - chatAsync (https://github.com/apache/druid/pull/13491/files)
 
 I have seen these settings work well in large scale clusters and would likely be turned on by default in future releases.

**Comment by abhishekagarwal87** [comment]
Also tagging @kfaraz and @AmatyaAvadhanula if they have some more suggestions.

**Comment by AmatyaAvadhanula** [comment]
1. Could you also please share how long your coordinator runs take and which duty takes the most time as well? (`coordinator/time` metric)
2. Which cost balancer strategy does the cluster use and what is the coordinator dynamic config?
3. How do the sums of the metrics `ingest/segment/count` and `segment/assigned/count` look like over intervals of 5 minutes? 

> 2nd question is even if a task does not complete within the completionTimeout window I am assuming the segment isnt just dropped, since internally in the logs the task is marked as successfull but the segment will likely not be served for queries until the handoff internally is completed by the coordinator -> historical (meaning the peon will not serve requests either for that segment as the task has been terminated once completionTimeout window has elapsed). Is this a correct assumption?

Yes, the segments aren't dropped and will eventually be served by the historicals

**Comment by happy5035** [comment]
Do you use cachingCost to accelerate balance calculation?

**Comment by AmatyaAvadhanula** [comment]
cachingCost can help if both run rules (loading - dropping) and balancing are slow. 
If balancing is significantly slow while run rules are not, segment selection for balancing is likely the culprit. Please try using batched segment sampling in the coordinator dynamic config in that case

**Comment by acherla** [comment]
> cachingCost can help if both run rules (loading - dropping) and balancing are slow. If balancing is significantly slow while run rules are not, segment selection for balancing is likely the culprit. Please try using batched segment sampling in the coordinator dynamic config in that case

Caching cost was configured on the onset, ultimately lowering percentOfSegmentsToConsiderPerMove yielded the best benefit, potentially at the cost of hot spots on the cluster.  

Either way we will be upgrading to 25.0.0 by next week as we've seen the performance significantly improve after some of the new optimizations were pushed in.

**Comment by acherla** [comment]
Re-opening this just to provide updates to folks who are running large druid clusters.  This thread might help them

So we ran a few performance tests here based on 25.0.0 and we are finding some interesting results.
1. segment handoff time did improve, however enabling chatAsync lead to the Overlord getting flooded with requests that would result in thousands of task failures.  We tested this under extreme load (close to 3K Peons) running just Kafka Indexing jobs, it seems likely due to the number of chat requests that are flooding the overlord with requests and the overlord would completely stall out (CPU usage would spike to 80-90% or higher) to the point where it was inaccessible from the management console.  

We are currently exploring two options:
1. Federating the coordinator/overlord to separate machines, right now we are running the active/backup as a coordinator/overlord combo.  We are planning to federate out the overlord and coordinator going forward to separate machines
2. setting druid.indexer.server.maxChatRequests to 1 to throttle the chattiness of peons to the overlord (does this potentially have negative consequences?  IE longer handoff times?)
3. Setting chatAsync to false, we noticed a huge number of task failures due to the overlord throwing jetty connection refused exceptions when it was enabled potentially due to the number of chat requests flooding the overlord due to the number of peons we are running.

@AmatyaAvadhanula any other tips you might be able to recommend.

**Comment by acherla** [comment]
> The chat requests are going from Overlord to the workers. Surprising that it's causing Overlord CPU to become high. When you see spike in Overlord CPU usage, can you check through thread dumps where are Overlord threads spending their time? Maybe it is something else.
> 
> We have also seen segment allocation cause significant overhead at that scale. This overhead can be reduced by enabling batch segment allocation. `druid.indexer.tasklock.batchSegmentAllocation` needs to be set to `true` on Overlord.

Thanks we've enabled batchSegmentAllocation on the overlord since the 25.0 upgrade and increased the batchsegment interval to 10 seconds.  

Attached a copy of the flamegraph we took from the overlord during this period when it stalls out

[druid-flame-117758.zip](https://github.com/apache/druid/files/11178605/druid-flame-117758.zip)

**Comment by abhishekagarwal87** [comment]
Those handoffs shouldn't cause overlord to stall. Looking at the flame graphs, the supervisor threads seem to be busy on db calls. I would recommend increasing the number of connections to db and see if that resolves the issues you are seeing.

**Comment by IgorBerman** [comment]
@abhishekagarwal87 Hi
I'm a bit late for this thread, but can you give a reference how to increase number of db connections for metadata storage? (mysql in my case)

**Comment by acherla** [comment]
> @abhishekagarwal87 Hi I'm a bit late for this thread, but can you please give a reference how to increase number of db connections for metadata storage? (mysql in my case)

Missed this but here is an example:
```
#druid.metadata.storage.connector.dbcp.initialSize=2
#druid.metadata.storage.connector.dbcp.maxTotal=20
#druid.metadata.storage.connector.dbcp.maxIdle=20
#druid.metadata.storage.connector.dbcp.minIdle=2
#druid.metadata.storage.connector.dbcp.url={{druid_metadata_storage_connector_connectURI}}
#druid.metadata.storage.connector.dbcp.username={{druid_metadata_storage_connector_user}}
#druid.metadata.storage.connector.dbcp.password={{druid_metadata_storage_connector_password}}
#druid.metadata.storage.connector.dbcp.driverClassName=com.mysql.jdbc.Driver
```

Handoff times are still pretty long in druid even in 27.0.0 based on our internal tests and its not due to the DB performance.  Longest queries we have are against the druid_segments table from the coordinator taking 3-5 minutes, but thats largely because we have 4Mil+ segments in our cluster (its massive).
