### ISSUE TITLE
when installing druid on k8s

### ISSUE THREAD

**Issue by dev2back-hjyoon** [apache/druid#13702]
When installing druid on top of k8s, we set middlemanager and historical to come up on the same node. After that, when proceeding with the volume setting, will additional settings be required?
For example, set the same path of the volume

**Comment by EylonLevy** [comment]
each pod acts as its own machine, as long as you have a zookeeper they will register themselves. Look at the Druid operator, it makes the process much more straightforward. Notice that having multiple replicas under one service will only act as one server and could cause problems.
