### ISSUE TITLE
Cluster Deployment Router Port

### ISSUE THREAD

**Issue by box-lin** [apache/druid#13723]
### Description
Was not able to get druid web running with router port 8088, but after changed it to 8888 it works. 

link: https://druid.apache.org/docs/latest/tutorials/cluster.html

![image](https://user-images.githubusercontent.com/57877290/215657191-13f53e6f-7cc6-495e-9b74-55a0e5ac5c98.png)

**Comment by LakshSingla** [comment]
This seems like an error in the documentation. Can you raise a PR for the same?
