### ISSUE TITLE
Problem with SELECT COUNT(DISTINCT __FIELD__))

### ISSUE THREAD

**Issue by albertojarabo** [apache/druid#13743]
I wonder why Apache Druid 25.0.0 generates different results when executing two queries that apparently should return the same results. The queries have been executed with the same data in the table involved:

Query 1: 
<img width="311" alt="select_distinct_1_druid" src="https://user-images.githubusercontent.com/7034464/216316988-b2a23e75-dc7e-49d4-8e91-7d012164ac62.PNG">

Query 2:
<img width="345" alt="select_distinct_2_druid" src="https://user-images.githubusercontent.com/7034464/216317044-be399b4a-3a7b-40f2-b0b2-ee8b8418adb3.PNG">

On HIVE tables with the same data, the result obtained with both queries is the same as Query 2 in Druid. I suspect that there is some problem when executing the query with COUNT(DISTINCT __FIELD__))

**Comment by abhishekagarwal87** [comment]
Its because one query is using approximate distinct count while the second one is using exact distinct count. You can disable approximate in the query context (click on "..." next to Engine)
