### ISSUE TITLE
Helm chart forces zookeeper hosts to be set even if using druid-kubernetes-extensions

### ISSUE THREAD

**Issue by jwitko** [apache/druid#13745]
### Affected Version
Apache Druid Helm chart 0.3.2

### Description
If a user deploying via the Apache Druid helm chart is while using `druid-kubernetes-extensions` then there is no need to set a zookeeper host however the helm chart will fail if the user does not.

**Comment by imSanko** [comment]
**I can help me with the problem so can I help you with that if you assign this issue to me**

**Comment by jwitko** [comment]
> **I can help me with the problem so can I help you with that if you assign this issue to me**

Thanks but I created the issue because I already had a PR to solve the problem. https://github.com/apache/druid/pull/13747
