### ISSUE TITLE
Native Query for Druid Through Java

### ISSUE THREAD

**Issue by sc-aniagr** [apache/druid#13818]
I want to make native timeseries query (Json format) example : 

{
   "queryType":"timeseries",
   "dataSource":"xyz",
   "intervals":[
      "2022-12-18T00:00:00.000/2022-12-19T23:59:59.000"
   ],
   "granularity":"day",
   "aggregations":[
      {
         "type":"doubleSum",
         "name":"count",
         "fieldName":"pqr"
      }
   ],
   "context":{
      "skipEmptyBuckets":"false"
   }
}

I want to put this type of query to druid through java springboot application. Can someone suggestions how can this be achieved? i tried through feign client SQL broker but that did not help. Suggestion would be appreciated.

**Comment by Hikamare** [comment]
You can just send the query via POST request to `YOUR_DRUID_INSTANCE/druid/v2` with the query itself being a JSON with the request body :)
