### ISSUE TITLE
Cluster.md requirements refer to Python 2 which is EOL

### ISSUE THREAD

**Issue by techdocsmith** [apache/druid#13843]
https://github.com/apache/druid/blob/master/docs/tutorials/cluster.md refers to the option to use Python 2, should this be removed since Python 2 is EOL.

Question from @paul-rogers in PR https://github.com/apache/druid/pull/13647/ 
cc: @findingrish

**Comment by gianm** [comment]
I don't see why. We support both with the start scripts, in case someone only has python 2 available. Not very common but not unheard of.
