### ISSUE TITLE
Proposal: Druid extension to read and ingest Iceberg data files

### ISSUE THREAD

**Issue by a2l007** [apache/druid#13923]
### Introduction
Apache Iceberg is a high-performance format for large analytic tables which presently has well-supported connectors for Spark, Flink, Trino, Hive and Impala. For ingesting Iceberg tables into Druid, the existing mechanism is either:
- using a separate workflow to scan the iceberg catalog, identify the underlying data file paths followed by submitting a Druid ingestion spec with these paths
-  or querying the Iceberg catalog using Trino/Spark SQL and then writing the data to a separate store for Druid to ingest it.

### Description

This issue intends to propose a Druid extension that ingests Iceberg tables into Druid. Given a catalog, Iceberg table name and namespace, the extension creates an Iceberg driver that connects to the configured catalog, initiates an iceberg table scan and fetches the underlying plan files for the latest snapshot. This retrieves a list of data files which are essentially Parquet, AVRO or ORC files which are then fed into an `InputSource` and native batch indexing takes care of the rest. 
To decouple the iceberg catalog reads from the inputsources, the proposal is to have an `InputSelector` that provides extensible APIs to connect to iceberg catalogs. The `InputSelector` interface could look like this:

```
 @JsonTypeInfo(use = JsonTypeInfo.Id.NAME, property = InputFormat.TYPE_PROPERTY)
 @JsonSubTypes(value = {
     @JsonSubTypes.Type(name = DefaultInputSelector.TYPE_KEY, value = DefaultInputSelector.class)
 })
 public interface InputSelector
 {
   List<String> chooseFiles();

 }
```

The proposed extension is an implementation of the `InputSelector` interface that connects to the configured catalog and retrieves the data files as mentioned above.
Each `InputSource` would then have a handler method that implements what it wants to do with the data files provided by the `InputSelector` and this handler is called by `AbstractBatchIndexTask` before constructing the input source reader. The `InputSource` would essentially mutate its list of paths by appending the file paths provided by the `InputSelector`.

The native ingestion spec would look something like this:
```
"ioConfig": {
      "type": "index_parallel",
      "inputSelector": {
        "type": "hive",
        "tableName": "logs",
        "namespace": "webapp",
        "partitionColumn": "event_time",
        "intervals": ["2023-01-26T00:00:00.000Z/2023-02-18T00:00:00.000Z"]
      },
      "inputFormat": {
        "type": "parquet"
      },
      "inputSource": {
        "type": "hdfs"
      }
}
```
The inputSelector optionally accepts a timestamp based partition column which can be used to filter the range of iceberg data files being scanned.

At its present state, the iceberg driver always reads from the latest table snapshot and only supports reading from tables that handles row creates and/or updates. 

**Features yet to be evaluated/implemented:**
- MSQ integration
- Iceberg deletes and delete file handling
- Reads from older iceberg snapshots
- Support for filtering on multiple partition columns

While this extension has been working as expected in internal clusters, this proposal is to understand if there are major design concerns and also to gauge if there is any interest in the extension in its present state.

**Comment by gianm** [comment]
Very cool! I have heard a lot of people asking about Iceberg integration, so I think this kind of capability would be very interesting to the community.

One question I have is whether it makes sense to do this as purely an InputSource? Like:

```
"ioConfig": {
      "type": "index_parallel",
      "inputSource": {
        "type": "iceberg",
        "tableName": "logs",
        "namespace": "webapp",
        "partitionColumn": "event_time",
        "intervals": ["2023-01-26T00:00:00.000Z/2023-02-18T00:00:00.000Z"]
      }
}
```

I'm imagining that the IcebergInputSource goes out and finds the data backing the table, then delegates (internally) to the appropriate InputSource and InputFormat. In your example it'd internally delegate to HdfsInputSource to compute splits. For formatting, it would return `false` from `needsFormat`, then internally it would use ParquetInputFormat on calls to `reader`.

As to MSQ integration, unless the implementation is doing something weird, it should work out of the box with `EXTERN`. EXTERN lets people use any InputSource and any InputFormat. We can add nicer SQL syntax for it in a future patch, but there is that fallback method.

@maytasm was asking about this on Slack recently so might be interested as well.

**Comment by a2l007** [comment]
@gianm Thank you for taking at look. Designing this as an `InputSource` is something I'd considered but my concern is that wouldn't it create a dependency across extensions? If the IcebergInputSource implicitly identifies that it needs to delegate to HdfsInputSource, wouldn't the hdfs extension need to be available to the iceberg extension in compile-time?

Or are you suggesting that `IcebergInputSource` would be similar to a `CombiningInputSource` design where the delegate input source is also specified in the spec like:

"ioConfig": {
      "type": "index_parallel",
      "inputSource": {
        "type": "iceberg",
        "tableName": "logs",
        "namespace": "webapp",
        "partitionColumn": "event_time",
        "intervals": ["2023-01-26T00:00:00.000Z/2023-02-18T00:00:00.000Z"],
       "delegateInputSource" : "hdfs"
      }
}

**Comment by gianm** [comment]
Ah, I hadn't thought about the cross-extension dependency. I had imagined the `iceberg` source literally delegating to the `hdfs` one, but yeah, that wouldn't be available as a Java object.

I think we can fix this though. Even though InputSources from other extensions aren't available as Java objects, they're still available from class registries that may be created in core, such as the ObjectMapper deserializers. So, you could create the JSON in Java code, then use Jackson to turn it into an InputSource and use it that way. This is what allows, for example, the `druid-multi-stage-query` extension to use any kind of InputSource from any extension, without depending on those extensions.

Wonder if this is a good path or if it's too weird?

If too weird, it'd also be an option to create a different kind of registry instead of using ObjectMapper. `ComplexMetricSerde` could be a model here.

**Comment by gianm** [comment]
Hi, I'm wondering if you're still interested in contributing this? There's certainly plenty of community interest.

**Comment by gianm** [comment]
Hi, I'm wondering if you're still interested in contributing this? There's certainly plenty of community interest. Btw, if you're interested in chatting live and then bringing the discussion back here, many of us are on Slack in the `#dev` channel: https://druid.apache.org/community/join-slack?v=1

**Comment by a2l007** [comment]
@gianm Sorry for the delay in getting back on this. I was able to reuse the core class registries for accessing the input sources without having to add them as a dependency. We ran into a couple of bugs in our internal clusters, but they're good now. I hope to find some cycles in the next couple of weeks to put up a PR. 
One question though, would we need to provide hadoop 2.x compatibility for this extension? Currently the hive metastore dependencies that it uses only works with hadoop 3.x. Maybe it will be a good motivation for users on hadoop 2.x to migrate off of it :)

**Comment by abhishekagarwal87** [comment]
@a2l007 - is it that the extension will only work with Hadoop 2.x or is will the extension also require dependency upgrades in core druid? As in, is the extension dependency going to conflict with any core dependency such as Guava?

**Comment by a2l007** [comment]
@abhishekagarwal87 The extension currently only works with hadoop 3.x because of a hive metastore dependency that has some issues with hadoop 2.8. I'm looking to see if there is a way around this but to answer your question, no I haven't had to upgrade any of the core dependency versions to get this working.

**Comment by gianm** [comment]
I don't think hadoop 2.x compatibility for this work is important. We just wouldn't want to break hadoop 2.x compatibility for existing cases. (Yet 🙂. I'd like to break it one day…)
