### ISSUE TITLE
how to mograte data from one historical to another in the same cluster

### ISSUE THREAD

**Issue by HistoryGift** [apache/druid#13979]
I meet one problem, but I can't find any reference file .
I want migrate data from one historical to another in the same cluster ,because one historical node need to down

if I  shutdown historical service directly, will the segments on historical lose ? and will the  statement of segment on ZK  result in new istorical cannot load those segemnt?

**Comment by kfaraz** [comment]
1. Segments are permanently stored in deep storage (e.g. S3). If a historical goes down, nothing is lost permanently and the missing segments can always be loaded on a different historical.
2. When a historical goes down, the segments being served by that historical would become under-replicated or even unavailable if the segment had only 1 copy in the cluster.
3. When segments are unavailable, queries would not return data for that segment.
4. As soon as the new historical loads these missing segments, the data is available for query again.

If you don't want data to be unavailable at any point, the method of doing this right now is to mark the historical as "decommissioning". The Druid coordinator would then move all segments on this "decommissioning" historical to other active historicals. Once all segments are removed from the "decomissioning" historical, it can be safely terminated.

Please refer to the configuration in the docs here for example usage of "decomissioning":
https://druid.apache.org/docs/latest/configuration/index.html#dynamic-configuration
