### ISSUE TITLE
dsql throws error: ModuleNotFoundError No module named 'urllib2'

### ISSUE THREAD

**Issue by techdocsmith** [apache/druid#14027]
Updating the querying tutorial:https://github.com/apache/druid/pull/14026
Trying to update the `dsql` section and get the following error:

```
  25.0 bin/dsql
Traceback (most recent call last):
  File "/Users/charlessmith/sandbox/druid/25.0/bin/dsql-main", line 36, in <module>
    import urllib2
ModuleNotFoundError: No module named 'urllib2'
```

Python version: 
```
  25.0 python --version
Python 3.11.1
```

Mac OS: 12.6.3

### Affected Version

25.0 But probably existed earlier

**Comment by tripend** [comment]
I downloaded python2 and it seemed to fix it.
