### ISSUE TITLE
Druid 25.0.0 creates a nested array rather than standard array when using string_to_array vs STRING_TO_MV 

### ISSUE THREAD

**Issue by acherla** [apache/druid#14194]
When applying string_to_array(Str, Delimiter) druid incorrectly converts the value to a nested array construct.  This is different compared to STRING_TO_MV which properly transforms the delimited string value to a proper array.  This is resulting in some array functions not working with array functions when using string_to_array.  

![image](https://user-images.githubusercontent.com/3893684/235563086-52b90ebe-3a64-4f7b-a8ee-4c0f38fe75e2.png)

### Affected Version

25.0.0

### Description

N/A not necessary

**Comment by abhishekagarwal87** [comment]
I think it's fixed already. I can't reproduce this on master. You can try once 26.0 is out.
