### ISSUE TITLE
Incorrect result returned by join query

### ISSUE THREAD

**Issue by pussyWang** [apache/druid#14213]
Druid version:24.0.1

Query sql:
`SELECT t1.id, t1.time, t1.count FROM my_table t1 JOIN (SELECT id, MAX(time) AS latest_time FROM my_table WHERE id IN ('fwa12s3-dfwr2sg6-9k7g6', '123asd1-sdfqwe23-wqr23') GROUP BY id) t2 ON t1.id = t2.id AND t1.time = t2.latest_time`

The desired result is the data of the maximum time for each id，
But in the result set, the data of one id and two times were found，The result is as shown below：
![image](https://user-images.githubusercontent.com/16094315/236393140-3539794d-e52c-4484-afef-aabbcecd350e.png)

**Comment by pussyWang** [comment]
This inner join query is equivalent to：
`SELECT id, time,count FROM my_table where id in ('fwa12s3-dfwr2sg6-9k7g6','123asd1-sdfqwe23-wqr23') AND time in (1682438400000,1682352000000)`

This is wrong, resulting in unexpected query results

**Comment by pussyWang** [comment]
> and you don't have multiple entries for that (id, time) combination in your raw table?


No, there are, but according to my query conditions, one id should not have multiple time query results

**Comment by abhishekagarwal87** [comment]
why will that be? if t1 has multiple entries and t2 has one entry, the join will produce as many results as there are in t1.

**Comment by pussyWang** [comment]
I agree with the join will produce as many results,My problem is its result should only have data for id1-time1 and id2-time2,There should be no data for id1-time2

**Comment by abhishekagarwal87** [comment]
ah I see now. I think it should be fixed by https://github.com/apache/druid/pull/14151/files. In any case, can you share your native query plan? You can get it by doing "Explain query" through web-console. The fix will be available in 26.0.

**Comment by abhishekagarwal87** [comment]
Scratch that. it's a bug in our join implementation. As a workaround, if you include t2.latest_time in your select, the query will return the correct results. We will fix it.

**Comment by abhishekagarwal87** [comment]
We are converting the join condition in this query to a wrong filter. The filter that the condition coverts to is
```
(user_id IN (#en.wikipedia, #sv.wikipedia) && __time IN (1466989200000, 1466992800000))
```
however it should be
```
(user_id = #en.wikipedia && __time == 1466989200000) || (user_id = #sv.wikipedia && __time = 1466992800000))
```

**Comment by pussyWang** [comment]
> We are converting the join condition in this query to a wrong filter. The filter that the condition coverts to is
> 
> ```
> (user_id IN (#en.wikipedia, #sv.wikipedia) && __time IN (1466989200000, 1466992800000))
> ```
> 
> however it should be
> 
> ```
> (user_id = #en.wikipedia && __time == 1466989200000) || (user_id = #sv.wikipedia && __time = 1466992800000))
> ```

As I thought. Thank you very much for your prompt response to this issue
