### ISSUE TITLE
The resources are sufficient, but the following errors are still reported

### ISSUE THREAD

**Issue by galenliu6** [apache/druid#14218]
WARN [Coordinator-Exec--0] org.apache.druid.server.coordinator.rules.LoadRule - No available [cold] servers or node capacity to assign primary segment [serverlog_event_em_2023-03-04T00:00:00.000Z_2023-03-05T00:00:00.000Z_2023-03-05T^C

**Comment by abhishekagarwal87** [comment]
can you share more details? is it complaining about a particular tier? are the segments not available?

**Comment by galenliu6** [comment]
These segments are available and what are th
![Uploading 1654486890462716.png…]()
e reasons for this problem
