### ISSUE TITLE
Unable to load custom authenticator and authorizer

### ISSUE THREAD

**Issue by van-vothanh** [apache/druid#14221]
I'm getting the below error while trying to load a custom authenticator and authorizer that I'm implementing.

```
Please make sure to load all the necessary extensions and jars with type 'saml' on 'druid/broker' service. Could not resolve type id 'saml' as a subtype of `org.apache.druid.server.security.Authenticator` known type ids = [allowAll, anonymous, basic, pac4j, trustedDomain]
```

### Affected Version

25.0.0

### Description
I get the error when loading my custom authenticator and authoriser on a locally hosted druid instance. Below is my security configuration (in `common.runtime.properties`)

```
druid.auth.authenticatorChain=["saml"]

druid.auth.authenticator.saml.type=saml
druid.auth.authenticator.saml.authorizerName=saml
druid.auth.authenticator.saml.metadataDocumentURI=http://localhost:3000/
```

I do have my custom `Authenticator` and `Authorizer` annotated with `JsonTypeName("saml")` and the jar copied to the `extensions` folder, and I can see it being loaded at startup. I suspect I might have missed some configuration/setup steps, there is no documentation available on how to implement, configure custom authenticators (and authorizers)

Any help would be greatly appreciated. 

Thank you

**Comment by abhishekagarwal87** [comment]
is it being loaded on the broker as well? Also did you register your custom authenticator / authorizer in guice module?

**Comment by van-vothanh** [comment]
Thanks for the comment, I got the same error in the broker too, and yes I do have the authenticator and authorizer defined in a DruidModule. 

Do we have a sample/tutorial with instructions on how to implement custom authenticator/authorizer?
