### ISSUE TITLE
SQL input source (multiple databases)

### ISSUE THREAD

**Issue by ilyakitaev** [apache/druid#14243]
Hi, I got Druid cluster with metadata stored in postgresql. So I want to ingest data from MSSQL with SQL-based ingestion. According to documentation I have to load sqlserver-metadata-storage (but I already have postgresql-metadata-storage loaded), but only one could be loaded. If I try to load both there is error:

`A binding to com.google.common.base.Supplier<org.apache.druid.server.audit.SQLAuditManagerConfig> was already configured at org.apache.druid.guice.JsonConfigProvider.bind(JsonConfigProvider.java:151) (via modules: com.google.inject.util.Modules$OverrideModule -> org.apache.druid.metadata.storage.sqlserver.SQLServerMetadataStorageModule).
`

The same thing with officially supported mysql and postgresql simultaneously

How do I get I want?

**Comment by abhishekagarwal87** [comment]
I am not 100% sure if it will work. But you can try to load only postgresql-metadata-storage extension on master nodes and only sqlserver-metadata-storage on ingestion nodes (Middlemanager)

**Comment by ilyakitaev** [comment]
> I am not 100% sure if it will work. But you can try to load only postgresql-metadata-storage extension on master nodes and only sqlserver-metadata-storage on ingestion nodes (Middlemanager)

Metadata storage is defined on every node in _common? I was thinking about it. Is Middlemanager not using it?

**Comment by abhishekagarwal87** [comment]
No. Only the master nodes talk to metadata store.
