### ISSUE TITLE
Implemention of new metric

### ISSUE THREAD

**Issue by BigSecret1** [apache/druid#14253]
As there are many metrics are available which apach druid exposes, I would like to propose one in addition to that which allows us to monitor each running task memory consumption.
This task can be index/compaction/kill so and so and by use of this metric we should in situation to understand the memory consumption of each task. We can observe a particular task for particular data source by this and if there are memory enhancement required we can do a proper analysis for that particular data source and do a proactive monitoring.

I would like to contribute on this, little bit guidance would be really helpful for me.

**Comment by FrankChen021** [comment]
Hi @BigSecret1 are you still working on this?

**Comment by BigSecret1** [comment]
@FrankChen021 Nope I am not working on this as of know

**Comment by FrankChen021** [comment]
@BigSecret1 BTW, Druid provides memory metric like _jvm/mem/used_ , what's the difference betwen this metric and your proposal?

**Comment by BigSecret1** [comment]
@FrankChen021 but does this metric gives the memory consumption of each running task? That's where I came up with proposal

**Comment by FrankChen021** [comment]
this metric shows the used heap memory of each druid process, including ingestion tasks.

**Comment by BigSecret1** [comment]
In our project it was a need to track this and eventually found we don't have any metrics as of now

**Comment by BigSecret1** [comment]
@FrankChen021 okay then it should be enough if it provides those details.

Also I want to start contributing on compaction side. Where I can find src related to compaction in druid repo?

**Comment by FrankChen021** [comment]
For compaction, you can get started from the `CompactSegments` which is running on coordinator to submit compaction task periodically, and the `CompactionTask` which is scheduled on middle managers to run the compaction task.

**Comment by FrankChen021** [comment]
I will close this issue. If you find that the _jvm/mem/*_ metrics don't meet your need, you can open a new issue or PR. Thank you @BigSecret1
