### ISSUE TITLE
'json' and 'auto' columns improperly handle case where all rows are empty objects

### ISSUE THREAD

**Issue by clintropolis** [apache/druid#14339]
### Affected Version

26.0.0+

### Description

'json' columns improperly classify this column as a `STRING` type, which results in scan queries being broken (e.g `select * from table`) with errors of the form:

 ```Cannot coerce [java.util.LinkedHashMap] to VARCHAR```

'auto' columns consider this case incorrectly as `null`, and so will write out a null column instead of preserving the empty objects, which is incorrect, though there is likely very low use for preserving them, it does change the original data, which is counter the purpose of 'auto'.

Both of these cases should instead recognize that the empty object is a 'nested' structure and consider the type `COMPLEX<json>`.

**Comment by hardikbajaj** [comment]
Hey @clintropolis , can I take this up?

**Comment by clintropolis** [comment]
> Hey @clintropolis , can I take this up?

oops, just noticed this, i've already got a fix in progress, I created the issue in case anyone ran into it before the fix was ready. I think i could probably dig up some stuff to help with if you're interested, let me get back to you on that

**Comment by hardikbajaj** [comment]
Hey @clintropolis , not problem. I took up a SysMonitor issue. Here's a [PR](https://github.com/apache/druid/pull/14359) for that. Please review it. It's facing some license issue for new library, I'm trying to find a fix for that, If you know the fix, please let me know :)

**Comment by sanel** [comment]
Hey guys, is this issue supposed to be fixed in 27.0? I'm currently running version 27 and have a column with `COMPLEX<json>` type. All rows are empty (or `{}`) and Druid will report this error after `select * from table`:

```
Error: INVALID_INPUT

Cannot coerce field [ResponseHeaders] from type [java.util.LinkedHashMap] to type [VARCHAR]
```

Is there a way to make a workaround for this? The only way I could make it working is to ignore this column completely during ingestion.

**Comment by abhishekagarwal87** [comment]
@sanel - Yes. It should have been fixed in 27. @clintropolis - any idea what might be going on?

**Comment by sanel** [comment]
Thanks @abhishekagarwal87 for your fast response. Here is how to replicate the issue (I started druid with `start-micro-quickstart` script):

 1. Load data down below, using `Load Data > Batch - SQL > Paste data`. Leave `trouble` field as `COMPLEX<json>` type, which was correctly recognized by Druid.
 2. After data was loaded, try running `select * from inline_data`, it will show:
 ```
 Error: INVALID_INPUT

 Cannot coerce field [trouble] from type [java.util.LinkedHashMap] to type [VARCHAR]
 ```

Sample data:

```
{"field": "data1", "field2": "data2", "trouble": {}}
{"field": "data1", "field2": "data2", "trouble": {}}
```

**Comment by clintropolis** [comment]
Ah, I only fixed this issue for 'auto' columns, which is the next version of 'json', because at the time I thought I was going to be consolidating them for Druid 27 release (which did not happen).

**Comment by sanel** [comment]
Thanks @clintropolis! Maybe I'm missing something, but how to set `auto` in this ingestion query:

```sql
REPLACE INTO "inline_data" OVERWRITE ALL
WITH "ext" AS (SELECT *
FROM TABLE(
  EXTERN(
    '{"type":"inline","data":"{\"field\": \"data1\", \"field2\": \"data2\", \"trouble\": {}}\n{\"field\": \"data1\", \"field2\": \"data2\", \"trouble\": {}}"}',
    '{"type":"json"}'
  )
) EXTEND ("field" VARCHAR, "field2" VARCHAR, "trouble" TYPE('COMPLEX<json>')))
SELECT
  "field",
  "field2",
  "trouble"
FROM "ext"
PARTITIONED BY ALL
```
Setting "trouble" TYPE('auto'), AUTO or `TYPE('COMPLEX<auto>')` does not work.

**Comment by clintropolis** [comment]
>Thanks @clintropolis! Maybe I'm missing something, but how to set auto in this ingestion query:

Ah, this is the MSQ query context thing I was referring to, adding `{"useAutoColumnSchemas": true}` to the query context is required in this case, you leave the type definition as `COMPLEX<json>`. 'auto' and 'json' can both produce the `COMPLEX<json>` logical type, however internally they use different physical formats in the segment files, and by default `COMPLEX<json>` still maps to the older 'json' version so the flag is necessary to get the new version.

One thing to be aware of, when using `useAutoColumnSchemas`, all built-in types will be written with the 'auto' column writers, which will make some differences when the flag is not set, the main difference is that numeric types like `LONG`/`BIGINT` will be written out with value indexes, which will make the segments larger, but enable faster filtering. Currently the flag is 'all or nothing', but in the future we will probably introduce some additional control over this in one way or another, still working out some of the details.

**Comment by abhishekagarwal87** [comment]
@sanel tl;dr - You should set `useAutoColumnSchemas` to `true` in the context of your REPLACE query. Do let us know how it went.
