### ISSUE TITLE
Add ability to shutdown historical tier with replication factor 1 without having temporary data outages

### ISSUE THREAD

**Issue by drcrallen** [apache/druid#1440]
Currently if a historical tier has a replication factor of 1 (meaning only 1 copy of the data across the tier) then any particular node cannot be shut down for planned maintenance without temporarily loosing the ability to query data which was hosted there.

As a user of Druid, I would like my queries to always return all the data even during planned maintenance or planned node shutdowns provided there is enough overall tier capacity to hold the data.

**Comment by gianm** [comment]
Would a "controlled shutdown" type thing work here? Like, a way to tell the coordinator that you want to move all the segments from some particular node somewhere else, and to stop assigning new segments to that node. The end result being that the node will be running with no data and you can shut it down.

**Comment by drcrallen** [comment]
@gianm  That would work. There would also need to be a way to detect that either there are no more segments on a node, or that each segment is replicated at least X times somewhere else.

**Comment by Jhors2** [comment]
We are looking to do something similar here, however we have 2 ECS clusters of historical nodes.  Would it also be possible to load the same segments with the same priority on the historical servers across two tiers?  In effect this creates two replicas of the data that you round robin to correct?

**Comment by egor-ryashin** [comment]
I suppose this one is a duplicate of https://github.com/apache/incubator-druid/issues/3247, right?
