### ISSUE TITLE
Bulk segment kill

### ISSUE THREAD

**Issue by jasonk000** [apache/druid#14634]
### Description

Bulk segment kill when supported will be a significant improvement to long-running kill tasks.

In the case of eg: [S3DataSegmentKiller](https://github.com/apache/druid/blob/77e0c16bce04fc0f9503d323accdbbe14691c9a2/extensions-core/s3-extensions/src/main/java/org/apache/druid/storage/s3/S3DataSegmentKiller.java#L76-L86), each segment is `deleteObject()`ed from S3 one-at-a-time. If there are hundreds, or thousands of segments to remove, there is significant latency. This can be converted to run as a single bulk `deleteObjects()` for a large number of tasks at a time.

No doubt other segment storage plugins would support the same.

### Motivation

Improvement to segment killing process.

**Comment by abhishekrb19** [comment]
@jasonk000, [this PR in review](https://github.com/apache/druid/pull/14131) adds the [bulk delete](https://github.com/apache/druid/pull/14131/files#diff-8fbb482081dfa982285efaa4602d16e9bbbcf0a69e1199a58826938eaca6e119R151) functionality for unused S3 segments that you're describing in this issue.

**Comment by jasonk000** [comment]
Great - @maytasm pointed out same offline!

**Comment by abhishekrb19** [comment]
Closing this issue as it's completed by https://github.com/apache/druid/pull/14131
