### ISSUE TITLE
Telegraf Plugin For Druid

### ISSUE THREAD

**Issue by arunkumarck** [apache/druid#14873]
https://github.com/influxdata/telegraf

They have opensource plugins to write from a RabbitMQ or Kafka Topic to the Influx, Postgresql or other opensource databases.
A lot of apache druid users would want a plugin written to output data to Apache Druid like this.
The best people to write the plugin are Apache Druid People.

This will make life easy for a lot of us. Especially in IoT scenarios, we use telegraf to persist data from topics of Kafka/RabbitMQ to the database

**Comment by abhishekagarwal87** [comment]
can you elaborate a bit more? We already have a native integration with Kafka. why can't you just connect Apache Druid to the Kafka topic directly?

**Comment by arunkumarck** [comment]
https://druid.apache.org/docs/latest/development/extensions-core/kafka-ingestion/

Get that. Will use the above.
Telegraf is written in Go and has better vertical scalability. Hence was checking
