### ISSUE TITLE
Suggest adopting a common style guide for documentation

### ISSUE THREAD

**Issue by techdocsmith** [apache/druid#14901]
### Motivation

The Druid docs have evolved with only a basic attention to documentation style. Some effort has been made to provide stylistic guidance in the documentation contribution guide: 
https://druid.apache.org/docs/latest/development/contribute-to-docs/ 

As the project matures, it makes sense to adopt a common style so that contributors have a common reference when composing and reviewing documentation.

### Proposed changes

Rather than create a new style, I recommend we follow the Google Developer Documentation Style Guide: https://developers.google.com/style. Open to other style guides if someone has a strong opinion.

Where the Google Developer Documentation Style Guide is not consistent with the goals of the Apache Druid documentation, we document the exception for clarity. One such example would be to avoid code font for SQL syntax which can make the documentation more difficult to read.

### Rationale

It is easier to adopt an existing style that aligns with the principal goals of the documentation (developer docs) rather than to attempt to create an exhaustive unique style

### Operational impact

Improved reference when creating and reviewing documentation.

### Future work (optional)

There will need to be ongoing maintenance of the style guide to keep it relevant.

**Comment by gianm** [comment]
The Google doc style guide seems pretty reasonable to me. And, it's helpful to have something to point to. So I am in favor of this.

Would you suggest removing the https://druid.apache.org/docs/latest/development/contribute-to-docs/#style-guide section and replacing it with a link to https://developers.google.com/style + any exceptions we have decided to adopt?

**Comment by petermarshallio** [comment]
@techdocsmith point of clarity – the Google SG refs to the MS SG, and thereby cites https://learn.microsoft.com/en-gb/style-guide/capitalization which differs from https://developers.google.com/style/capitalization. In adopting the Google SG, "How to eat data with Apache Druid" would be correct in a title or heading, and "How to Eat Data with Apache Druid" would be incorrect. Correct?

**Comment by techdocsmith** [comment]
@gianm , Yes, we would link to google style and call out notable exceptions. It might be nice to leave in a few common helpers styles there that contributors will run into frequently. but removing the suggestions altogether could also work if that seems like a better plan.

@petermarshallio : the docs already follow sentence case in most cases as specified in https://developers.google.com/style/capitalization . Note that Google says "If the preceding references don't provide explicit guidance", which in this case they do, "then see these third-party references, depending on the nature of your question."

**Comment by techdocsmith** [comment]
This is done: https://druid.apache.org/docs/latest/development/contribute-to-docs#style-guide
