### ISSUE TITLE
postgresql的SQL格式化后注释只保留了注释，/**/给去掉了

### ISSUE THREAD

**Issue by kviuff** [apache/druid#14960]
/*查询语句第一行*/
SELECT person.id, person.name, group.name
FROM person
	JOIN group ON person.group_id = group.id 
WHERE person.birthdat > '1980-01-01';
格式化后
查询语句第一行
SELECT person.id, person.name, group.name
FROM person
	JOIN group ON person.group_id = group.id
WHERE person.birthdat > '1980-01-01';

**Comment by kviuff** [comment]
代码：
StringBuffer sqlBuffer = new StringBuffer();
        sqlBuffer.append("/*查询语句第一行*/");
        sqlBuffer.append("SELECT person.id,person.name,group.name  FROM person JOIN group ON person.group_id = group.id WHERE person.birthdat > '1980-01-01';");
        sqlBuffer.append("/*查询语句1111*/");
        sqlBuffer.append("SELECT person.id,person.name,group.name  FROM person JOIN group ON person.group_id = group.id WHERE person.birthdat > '1980-01-01'");
        // sqlBuffer.append("SELECT * from aaa");

        List<SQLStatement> statementList = null;
        SQLStatementParser sqlStatementParser = SQLParserUtils.createSQLStatementParser(sqlBuffer.toString(), DbType.postgresql, true);
        statementList = sqlStatementParser.parseStatementList();
        String sqlResult = toSQLString(statementList, DbType.postgresql);
        System.out.println("格式化SQL：\n" + sqlResult);

**Comment by 2bethere** [comment]
Hey, sorry, the community is mostly talking in English, so if you want more expedient help, using English for posts will help a lot.
想说一下，这个社区现在主要是英文交流，如果你希望尽快得到帮助，请用英文提问。

关于注释的问题，因为Druid使用的SQL，所以正确的注释方式是`--`，不是 `/* */`。

**Comment by FrankChen021** [comment]
I think the user posted in a wrong repo. This issue should posted to this repo: alibaba druid.
