### ISSUE TITLE
jpa 使用durid 数据源断连 导致数据库事务提交失败问题

### ISSUE THREAD

**Issue by cs15110090989** [apache/druid#15001]
org.springframework.orm.jpa.JpaSystemException: JDBC begin transaction failed: ; nested exception is org.hibernate.TransactionException: JDBC begin transaction failed:

出现的原因 power job 调用jpa 的方法 批量操作时 一会儿就会断开连接 导致事务提交失败 
其他jpa方法能正常使用 这是power job调用 的方法 一直提示事务提交失败

**Comment by LakshSingla** [comment]
Druid doesn't use the Spring framework. Perhaps this question was directed toward the Alibaba/Druid repository.
