### ISSUE TITLE
Docker images: Support for the Java 17 runtime

### ISSUE THREAD

**Issue by layoaster** [apache/druid#15011]
Since Druid 27.0.0 [full support for Java 17](https://github.com/apache/druid/releases/tag/druid-27.0.0#27.0.0-highlights-java-17-support) was introduced and it's the [recommended version](https://druid.apache.org/docs/27.0.0/operations/java#selecting-a-java-runtime).

However, there doesn't seem to be a Docker image for Druid 27.0.0 with the Java 17 runtime available in [Docker Hub](https://hub.docker.com/r/apache/druid/tags?page=1&name=27).  

The [Dockerfile](https://github.com/apache/druid/blob/27.0.0/distribution/docker/Dockerfile) seems to have some parts dependent on Java11 (hardcoded versions)

I would expect to have a sort of tag like `27.0.0-java<java_major_version_number>`

Could you make it available? Is there any other way to get an official image with Java 17?

**Comment by FrankChen021** [comment]
Fixed by #15264
