### ISSUE TITLE
Content Spoofing - throwing error with user-supplied input

### ISSUE THREAD

**Issue by laxmikantbpandhare** [apache/druid#15022]
Druid Version 0.25

The Druid version is where the problem was encountered.

### Description

Please include as much detailed information about the problem as possible.

My Druid application is running and I am able to access with server IP and port

**ex: https://SERVER_NAME:PORT_NUMBER**

I tried spoofing it by adding some content at the end like below:

**https://SERVER_NAME:PORT_NUMBER/thiswebsitereditectto...https://www.attacker.com**

the druid console showed **404 Not Found error** with user-supplied input.

```
HTTP ERROR 404 Not Found
URI: /thiswebsitereditectto...https://www.attacker.com
STATUS: 404
MESSAGE: Not Found
SERVLET: default
```

It should not show the input added by the User to avoid content spoofing.

**Comment by FrankChen021** [comment]
Interesting. I think this is returned by the jetty instead of Druid application layer. Wondering how other applications handle this problem.
