### ISSUE TITLE
Druid helm chart support for AWS EKS 1.27

### ISSUE THREAD

**Issue by vikram-zopsmart** [apache/druid#15037]
Currently we are using Druid helm chart (incubator) to setup our druid infrastructure in AWS EKS 1.23.

Now, we are performing EKS upgrade for our Druid Infrastructure. But when we install the current helm chart in AWS EKS 1.27, we see below error:

Error encountered during the Druid installation is as follows:
Error: INSTALLATION FAILED: unable to build kubernetes objects from release manifest: resource mapping not found for name: "druid-zookeeper" namespace: "" from "": no matches for kind "PodDisruptionBudget" in version "policy/v1beta1"
ensure CRDs are installed first

Please suggest a solution for the current issue. As we are not able to proceed for AWS EKS upgrade due to druid Helm chart not available for AWS EKS above > 1.25

**Comment by liyaka** [comment]
Have the same problem here, any updates on it?

**Comment by vikram-zopsmart** [comment]
Yes solved it by using the zookeeper latest helm chart and changing the
apiversion in the zookeeper's helm chart.
