### ISSUE TITLE
Unable to pass dynamic values to time function

### ISSUE THREAD

**Issue by manasa-konidena** [apache/druid#15072]
Please provide a detailed title (e.g. "Broker crashes when using TopN query with Bound filter" instead of just "Broker crashes").

### Affected Version

The Druid version where the problem was encountered.

2023.01.4-lts-iap

### Description

I am not able pass `tz` (has time zone data) in dynamic way to time_extract function

```
select ts, TIME_EXTRACT(MILLIS_TO_TIMESTAMP(ts), 'DOW', tz) from (
 SELECT
    _timestamp as ts,
    COALESCE(location_timezone, 'UTC') AS tz
  FROM
    podcastStreams
  WHERE
    DATE_TRUNC('day', MILLIS_TO_TIMESTAMP(_timestamp)) >= TIME_PARSE('2023-08-12')
    AND DATE_TRUNC('day', MILLIS_TO_TIMESTAMP(_timestamp)) <= TIME_PARSE('2023-08-31')
    AND MV_OVERLAP(podcast_id, Array['d2559f3c-54a3-11e9-85f3-4b0dc7ea6463']) = 1
    AND is_stream = 1
    AND location_timezone is not null
)
```

Please include as much detailed information about the problem as possible.
- Cluster size
- Configurations in use
- Steps to reproduce the problem
- The error message or stack traces encountered. Providing more context, such as nearby log messages or even entire logs, can be helpful.
- Any debugging that you have already done

**Comment by ellisandrews-toast** [comment]
Commenting here that I am also seeing this behavior:

Works passing timezone as a literal:
![timezone_problem_2](https://github.com/apache/druid/assets/75630537/e2952a03-de5b-4371-8169-5b38072943e5)

Does not work passing timezone dynamically:
![timezone_problem_1](https://github.com/apache/druid/assets/75630537/27a03b2f-f59a-43dc-b733-f95c66fe85b3)

**Comment by abhishekagarwal87** [comment]
@manasa-konidena - the tz has to be constant. However, adding support for dynamic value shouldn't be too complex if you are interesting in adding that feature.

**Comment by AlbericByte** [comment]
@FrankChen021 @abhishekagarwal87 submit a draft cr and welcome for any comments
