### ISSUE TITLE
Support secondary partitioning when ingesting from Kafka

### ISSUE THREAD

**Issue by m-ghazanfar** [apache/druid#15149]
### Description

We use druid to store and query telemetry data. We ingest data into Druid via Kafka. Our ingestion rate is around 1.7M messages per sec.
Our query load is about `1000` qps and most queries request for for data that's in the time range [now-5, now-8].

Since we have a high ingestion rate, we produce a lot of segments. And since our queries are for real-time data, Druid ends up querying all segments within that time chunk.

If you see the below graphs, you can see that `726` queries on the broker translate to about `66.25k` queries on the indexers. Which is a fanout of about `92`. We have `94` indexer nodes.

<img width="1651" alt="Screenshot 2023-10-13 at 10 54 56 AM" src="https://github.com/apache/druid/assets/88474681/844573ff-01cb-4f33-b7c0-a8f02a86d03a">
<img width="1657" alt="Screenshot 2023-10-13 at 11 56 17 AM" src="https://github.com/apache/druid/assets/88474681/9590b56a-96bf-49ed-93cc-3786e1d09f2c">

Our data has a `tenant` dimension. The `tenant` dimension is always used to filter when performing a query.
We want to perform secondary partitioning based on the `tenant` dimension - so that the broker can prune the segments which have to be queried.

Data of one `tenant` is limited to a few kafka partitions(about ~20~ 3). So, after having secondary partitioning, I would expect my fanout to be about ~20~ 3, as opposed  to the 92 that I am seeing now.

I know that this can be done via compaction - however, I can no make use of compaction because our queries are realtime

### Implementation
I do not have an implementation in mind but do wish to contribute the implementation myself. 

### Related
- https://github.com/apache/druid/issues/12929 : not the same as this because I don't want to add the kafka partition info
- https://imply.io/blog/multi-dimensional-range-partitioning/

**Comment by abhishekagarwal87** [comment]
I know I am the one who suggested something like this in the druid meetup. But thinking a bit more, what you probably need is https://github.com/apache/druid/pull/11307.  With the bitmap indexes in real-time, there is no need for broker pruning, as almost all the indexers would be able to quickly return the results if they don't have the data for the tenant being queried and there is a bitmap index on the tenant.

**Comment by m-ghazanfar** [comment]
Thanks @abhishekagarwal87 !
I will follow up and see what's required to merge #11307 

While I agree that #11307 will give me a lot of improvement, can you also help me understand why you think this is a better solution than pruning at the broker's side? Why even make the additional calls to the indexer nodes?

**Comment by abhishekagarwal87** [comment]
The pruning on the broker's side will require the real-time segment partitions to be generated with a particular shard spec. That is tricky to implement and would only work under strict conditions (Kafka topic has to be partitioned with the same key, and re-partitioning can lead to incorrect results). 

A HTTP call from broker to peon/indexer is not expensive but the query execution on the peons is not fast enough in the absence of indexes. Having a bitmap index is much more flexible from the operations point of view. The input topic can be re-partitioned without any issues, and having a bitmap would be useful in far more situations. 
- It would work with any streaming connector
- It would help optimize the queries even further if you have a filter on a dimension that input data is not partitioned on. 
- It doesn't necessarily require the input data to be partitioned in a specific way.

**Comment by m-ghazanfar** [comment]
Ah, makes sense. Thank you!

**Comment by etipton-splunk** [comment]
IMO the wording should be updated [here](https://druid.apache.org/docs/latest/ingestion/partitioning/#secondary-partitioning) to clarify that "secondary partitioning" isn't truly possible at all for Kafka or Kinesis _unless_ something else occurs sometime after initial ingestion (compaction). As currently worded, it seems as if all you need to do is partition things properly within your stream, but that won't really help with query performance if I understand correctly.
