### ISSUE TITLE
Allow to retain X amount of data on indexers at handoff

### ISSUE THREAD

**Issue by m-ghazanfar** [apache/druid#15167]
### Description
We use druid to store and query telemetry data. We ingest data into Druid via Kafka. Our ingestion rate is around 1.7M messages per sec.
Our query load is about `1000` qps and most queries request for for data that's in the time range `[now-5, now-8]`.

Since we have a high ingestion rate, we produce a lot of segments - about `2180` segments every hour. We have a segment granularity of `10` mins.
And since our queries are for real-time data, Druid ends up querying all segments within a time chunk - about `360` segments.

We have configured our Druid instance to hand off segments every `10` mins.

With this, we see a query count pattern across indexers and historicals like this,
<img width="1651" alt="Screenshot 2023-10-16 at 10 37 01 AM" src="https://github.com/apache/druid/assets/88474681/6d19fb00-a4e9-45ec-93b6-cd4c3d1db7d9">

Right after segment handoff our real-time queries go to both indexers and historicals. This is in line with the current behaviour of segment handoff - all data on the indexers gets handed-off when a handoff happens.

I would like to have a way to retain, say 10mins(or 10M rows) of data on indexers at all the times - so that I can avoid the periodic  increased load on the historicals.

Adding @kfaraz because I discussed this with him in person.

With some direction, I'd be happy to implement this myself.

**Comment by m-ghazanfar** [comment]
@abhishekagarwal87 do you have comments/opinions on this?

**Comment by m-ghazanfar** [comment]
@abhishekagarwal87 doesn't matter if you use `maxRowsPerSegment` or `maxTotalRows` - at handoff time, all segments on the indexer get handed-off. This will again result in increased load on the historicals.

Quoting from [here](https://druid.apache.org/docs/latest/development/extensions-core/kafka-supervisor-operations#deployment-notes-on-kafka-partitions-and-druid-segments),
> When the task reaches one of maxRowsPerSegment, maxTotalRows, or intermediateHandoffPeriod, it hands off all the segments and creates a new new set of segments will be created for further events


---
An increase in historical load is a problem because, I have to over-provision my historicals to be able to handle the additional load during the segment hand-off. If I can prevent this load on the historicals, I can move my historicals to cheaper instances or reduce their number.

**Comment by abhishekagarwal87** [comment]
You can still keep historical cheaper by introducing a tier that just
handles very recent data. This tier could be co-hosted with your indexer
processes. So any additional query load is really just moving to a
different process on same machine.

**Comment by m-ghazanfar** [comment]
> You can still keep historical cheaper by introducing a tier that just handles very recent data

We are already doing this and want to get rid of that tier. Our query load is pretty high, at peak we get about 1000 queries per sec on the broker, about 75% of which are for realtime data. Along with this, we also have a high ingestion rate.

Also, $0 is better than cheaper :D 

> This tier could be co-hosted with your indexer processes. So any additional query load is really just moving to a different process on same machine

The query load doesn't move - it expands to historicals along with indexers.

**Comment by abhishekagarwal87** [comment]
I would still consider it a "move" than "expansion" since there is less data being queried on historicals once handoff is done. 
But if you insist on hacking :), you could configure your cluster to delay the handoff intentionally. You can do this through some clever setting of load rules. The segment would continue to be served by real-time nodes till the handoff is complete. You should verify that delayed handoff doesn't affect the event processing. Again, this is still a hack :)
