### ISSUE TITLE
Option to change groupers count in ConcurrencyGrouper to avoid contention

### ISSUE THREAD

**Issue by takaaki7** [apache/druid#15228]
### Description
For my workload, ConcurrencyGrouper's `synchronized (subGrouper) {` causes many contention and becomes bottleneck.
https://github.com/takaaki7/druid/blob/37853f8de4ba801a5f6c429ccceeb58b58762109/processing/src/main/java/org/apache/druid/query/groupby/epinephelinae/ConcurrentGrouper.java#L290

It seems just increasing groupers can reduce contentions and improve the performance.

### Test description
Query
```sql
SELECT COUNT(*) AS (SELECT user_id, COUNT(*) AS cnt
FROM event_log
)
WHERE cnt > 100
```
Input: 600M rows
Intermediate grouping result rows: 20M rows(not filtered by WHERE clause)
Threads: 23 (24core machine)
Latency: 3-4sec

I debugged with `jstack` and many times threads are stopped at `synchronized (subGrouper) {` line.

**Comment by gianm** [comment]
Does it help if you set `mergeThreadLocal: true`? This removes the synchronization completely.

**Comment by takaaki7** [comment]
Now I tested and here is the result.
https://github.com/apache/druid/pull/15227#issuecomment-1784010907

mergeThreadLocal is faster, but the aggregation result is wrong.
