### ISSUE TITLE
Druid 28.0.0 breaks the whole-query cache for groupBy queries with multiple post-aggregate metrics.

### ISSUE THREAD

**Issue by hnakamor** [apache/druid#15393]
I have been using Druid 28.0.0 and found a new bug.
The whole-query cache for groupBy queries with multiple post-aggregation metrics is broken.
However, if there are no post-aggregation metrics or a single post-aggregation metric, this bug does not seem to occur.

This bug is probably caused by a new feature in https://github.com/apache/druid/pull/11595.

### Affected Version

Druid 28.0.0

### Description

Below is a description of what happens when the bug occurs.

Settings changed from default settings
- druid.broker.cache.useResultLevelCache=true
- druid.broker.cache.populateResultLevelCache=true

Query
```
SELECT
  "channel","cityName"
  ,COUNT(*) AS a1
  ,COUNT(*) * 2 AS a2
  ,COUNT(*) * 3 AS a3
FROM "wikipedia"
WHERE TIME_IN_INTERVAL("__time", '2015-09-12T00:00:00.000Z/2015-09-13T00:00:00.000Z')
GROUP BY 1,2
ORDER BY 3 DESC
LIMIT 1
```

No cache result
| channel | cityName | a1 | a2 | a3 | 
| -- | -- | -- | -- | -- |
| #en.wikipedia | null | 10,516 | 21,032 | 31,548 | 

Result level cache result
| channel | cityName | a1 | a2 | a3 | 
| -- | -- | -- | -- | -- |
| #en.wikipedia | null | 10,516 | 31,548 | NULL |

**Comment by abhishekagarwal87** [comment]
can you post your complete ingestion spec that you used to ingest the Wikipedia date?

**Comment by kgyrtkirk** [comment]
seems like this is caused by restoring all postaggs into the same index during [pullFromCache](https://github.com/apache/druid/blob/ba1b6fa5a937e2f676e3c18944f6edec5b04d328/processing/src/main/java/org/apache/druid/query/groupby/GroupByQueryQueryToolChest.java#L657)

**Comment by egor-ryashin** [comment]
That one is a showstopper for me now.

**Comment by hnakamor** [comment]
My ingestion spec is as follows. To add, this ingestion was done on Druid 27.0.0.
```
{
  "type": "index_parallel",
  "spec": {
    "ioConfig": {
      "type": "index_parallel",
      "inputSource": {
        "type": "local",
        "baseDir": "quickstart/tutorial",
        "filter": "wikiticker-2015-09-12-sampled.json.gz"
      },
      "inputFormat": {
        "type": "json"
      }
    },
    "tuningConfig": {
      "type": "index_parallel",
      "partitionsSpec": {
        "type": "dynamic"
      }
    },
    "dataSchema": {
      "dataSource": "wikipedia",
      "timestampSpec": {
        "column": "time",
        "format": "iso"
      },
      "dimensionsSpec": {
        "dimensions": [
          "channel",
          "cityName",
          "comment",
          "countryIsoCode",
          "countryName",
          "isAnonymous",
          "isMinor",
          "isNew",
          "isRobot",
          "isUnpatrolled",
          "metroCode",
          "namespace",
          "page",
          "regionIsoCode",
          "regionName",
          "user",
          {
            "type": "long",
            "name": "delta"
          },
          {
            "type": "long",
            "name": "added"
          },
          {
            "type": "long",
            "name": "deleted"
          }
        ]
      },
      "granularitySpec": {
        "queryGranularity": "none",
        "rollup": false,
        "segmentGranularity": "day"
      }
    }
  }
}
```

**Comment by hnakamor** [comment]
Thanks @kgyrtkirk, @abhishekagarwal87 and @LakshSingla for the correction. Appreciate the quick work.
