### ISSUE TITLE
Mysql-connector-java upgrade

### ISSUE THREAD

**Issue by mustajibmk** [apache/druid#15422]
I am working on upgrading mysql-connector-java to version 8.0.28 - [PR](https://github.com/apache/druid/pull/15408). This is needed to resolve security vulnerabilities. I creating this issue to discuss the obstacles that I am facing during the process. Please let me know if this is not the right place.

With the upgrade the `com.mysql.jdbc.NonRegisteringDriver#parseURL` method used in `org.apache.druid.utils.ConnectionUriUtils` is no longer available. So, I have resorted to instantiating `com.mysql.cj.conf.ConnectionUrlParser` with the connection string and then used the "getProperties" method to fetch the properties. This method is still not a like-to-like replacement as we do not get the response back in the earlier format.

Is `com.mysql.cj.conf.ConnectionUrlParser` the right way to proceed or should I write a custom parser based on the logic previous used or is there something else I should look at? Appreciate your help!

**Comment by liyaka** [comment]
@mustajibmk 
any update on this?

**Comment by FrankChen021** [comment]
The work has been done. it has been upgraded to 8.2 via #16024
