### ISSUE TITLE
What's the difference between messageGap and messageMaxGap ？

### ISSUE THREAD

**Issue by jiangjiguang** [apache/druid#15462]
messageMaxGap is 33567264ms and messageGap is 240ms,
Why is messageMaxGap so big ?  
As I see the code ,  the messageMaxGap will be bigger and bigger
![image](https://github.com/apache/druid/assets/12368495/9253e43a-3359-4588-83e8-346a6f8a488d)

@kaijianding can you help me ? thanks

**Comment by kaijianding** [comment]
eg: there are lots of rows in a 1min batch. Some rows are like 1 days behind, some rows are very close to current time.
`messageGap` is the min gap to current timestamp, `messageMaxGap ` is the max gap to the current timestamp.
It's about how rows being collected and a row with very old timestamp and just recived
