### ISSUE TITLE
Will Lookup's data be persisted? If so, where is it saved?

### ISSUE THREAD

**Issue by galenliu6** [apache/druid#15499]
Will Lookup's data be persisted? If so, where is it saved?

**Comment by acherla** [comment]
https://druid.apache.org/docs/latest/querying/lookups/#saving-configuration-across-restarts

druid.lookup.snapshotWorkingDir

**Comment by galenliu6** [comment]
> [https://druid.apache.org/docs/latest/querying/lookups/# saving-configuration-across-restarts](https://druid.apache.org/docs/latest/querying/lookups/#saving-configuration-across-restarts)
> 
> druid.lookup.snapshotWorkingDir

use  linux dir or database?

**Comment by acherla** [comment]
Linux dir
