### ISSUE TITLE
Remove unnecessary warning stack logs during normal exit of ingestion tasks

### ISSUE THREAD

**Issue by asdf2014** [apache/druid#15518]
### Affected Version

28.0.1

### Description

There are many of useless warning stack logs at the bottom of the ingestion task log, even these tasks exiting normally. We should eliminate these to avoid any misunderstanding.

![image](https://github.com/apache/druid/assets/8108788/78125c64-3d97-4352-8917-fe4dd2b6ccc8)

**Comment by fectrain** [comment]
Hi, @asdf2014  @yuanlihan,  I have added `kafkaEmitter.close()` in the unit test to simulate the behaviour of real task exit, so that the scheduler threads will throw the InterruptException before the main thread exit.
Kindly help review and approve the workflow, thanks.
