### ISSUE TITLE
Wrong property set up during start up by druid.sh

### ISSUE THREAD

**Issue by jreyeshdez** [apache/druid#15875]
With newer mm-less feature https://druid.apache.org/docs/latest/development/extensions-contrib/k8s-jobs/#custom-template-pod-adapter if a user wants to set up a specific podTemplate for `index_kinesis` or `index_parallel`, a specific property needs to be added: `druid.indexer.runner.k8s.podTemplate.{taskType}` where {taskType} is the name of the task type.

So if you have this property `druid_indexer_runner_k8s_podTemplate_index_kinesis` that gets replaced by `druid.indexer.runner.k8s.podTemplate.index.kinesis` as seen here https://github.com/apache/druid/blob/master/distribution/docker/druid.sh#L147 - that will replace `_` with `.` in the key, which is wrong as per above documentation

**Comment by georgew5656** [comment]
make sense, working on a fix

**Comment by georgew5656** [comment]
hmm i'm not sure if this is gonna be easy to fix, i guess runtime properties are not supposed to have _ in them.

is there anyway you can set the runtime prop without relying on the env variable parser?

**Comment by jreyeshdez** [comment]
> hmm i'm not sure if this is gonna be easy to fix, i guess runtime properties are not supposed to have _ in them.
> 
> is there anyway you can set the runtime prop without relying on the env variable parser?

mm not sure, I might do some tricks in pod lifecycle postStart and use sed to replace the wrong prop

**Comment by georgew5656** [comment]
actually i think this will probably work https://github.com/apache/druid/pull/15919
