### ISSUE TITLE
Peons uses base podTemplate for index tasks when specific podTemplate exists

### ISSUE THREAD

**Issue by jreyeshdez** [apache/druid#15886]
Peon uses base pod template even though specific task type templates exist for index_kinesis and index_parallel and proper configurations have been set up in coordinator.

### Affected Version

Druid version 28.0.1 and 26.0.0

### Description

- Cluster size: 3x brokers, 3x coordinators, 3x historical, 3x routers
- Configurations in use: mm-less and zk-less
- Steps to reproduce the problem

Follow steps in https://druid.apache.org/docs/latest/development/extensions-contrib/k8s-jobs/#custom-template-pod-adapter

Set up druid to be mm-less and zk-less. In coordinator set up following env variables:
```
- name: druid_indexer_runner_k8s_podTemplate_base
  value: "/opt/druid/conf/druid/basePodSpec.yaml"
- name: druid_indexer_runner_k8s_podTemplate_index_kinesis
  value: "/opt/druid/conf/druid/indexPodSpec.yaml"
- name: druid_indexer_runner_k8s_podTemplate_index_parallel
  value: "/opt/druid/conf/druid/indexPodSpec.yaml"
```

Regardless of the task_type being ejecutes in peons, the podTemplate used will be the one specified in `druid_indexer_runner_k8s_podTemplate_base`, mainly because the parsed env var looks like `druid.indexer.runner.k8s.podTemplate.{task.type}` instead of `druid.indexer.runner.k8s.podTemplate.{task_type}`.

List of tasks do not include index_kinesis, index_kafka, index_parallel when running unit tests for this line:
https://github.com/apache/druid/blob/master/extensions-contrib/kubernetes-overlord-extensions/src/main/java/org/apache/druid/k8s/overlord/taskadapter/PodTemplateTaskAdapter.java#L225

Linked issue https://github.com/apache/druid/issues/15875

**Comment by georgew5656** [comment]
this pr should address the problem, still need to test in a druid environment https://github.com/apache/druid/pull/15915
