### ISSUE TITLE
Ensure thread safety of ConstantExprs

### ISSUE THREAD

**Issue by gianm** [apache/druid#16021]
To my eyes, PR #15552 introduced some code that is questionable as to thread safety of ConstantExprs: https://github.com/apache/druid/pull/15552#issuecomment-1879849582. This was reverted for the 29 release branch, but is still present in master. To avoid any questionableness, we should address it somehow prior to releasing Druid 30. Some options:

- https://github.com/apache/druid/pull/15694
- https://github.com/apache/druid/pull/15743

**Comment by kgyrtkirk** [comment]
fixed in https://github.com/apache/druid/pull/15694
