### ISSUE TITLE
Druid prometheus-emitter does not emit all the metrics

### ISSUE THREAD

**Issue by tapojit047** [apache/druid#16148]
Druid [prometheus-emitter](https://druid.apache.org/docs/latest/development/extensions-contrib/prometheus/) does not emit all the metrics.

### Affected Version
`28.0.1`

### Description
I was trying to emit metrics from druid cluster deployed in k8s using druid `prometheus-emitter` extension. But there are many metrics provided here ([druid-metrics](https://druid.apache.org/docs/latest/operations/metrics/)) which are not available in the metrics emitted by the extension. I am providing two basic metrics, but there are many which I was not able to find:
- [Service Health](https://druid.apache.org/docs/latest/operations/metrics/#service-health)
- [zk-connected](https://druid.apache.org/docs/latest/operations/metrics/#zookeeper)

- FYI, I added the necessary [monitors](https://druid.apache.org/docs/latest/configuration/#metrics-monitors) for the metrics, I was trying to get.

**Comment by suneet-s** [comment]
@tapojit047 The [docs](https://druid.apache.org/docs/latest/development/extensions-contrib/prometheus/) mention a proerty `druid.emitter.prometheus.dimensionMapPath` that you can set to provide a custom file with the set of metrics and dimensions you want to report. The default list of metrics and dimensions that the prometheus emitter reports is listed in https://github.com/apache/druid/blob/master/extensions-contrib/prometheus-emitter/src/main/resources/defaultMetrics.json

I think it would be reasonable to add both the service health metrics and the Zookeeper metrics to the list of default metrics that are emitted. Would you like to make a PR for that?

**Comment by tapojit047** [comment]
So, I need to add the appropriate metrics in here. Right? @suneet-s 

 https://github.com/apache/druid/blob/master/extensions-contrib/prometheus-emitter/src/main/resources/defaultMetrics.json
