### ISSUE TITLE
[Proposal] : Better handling for *bad* worker nodes. 

### ISSUE THREAD

**Issue by nishantmonu51** [apache/druid#1615]
Problem : 
In case we have a bad worker having environment issues e.g disk issues and all tasks being assigned to that worker starts failing, If configured with FillCapacityWorkerSelectStrategy, Overlord keeps assigning new tasks to the bad worker since it is the most likely the one with the least used capacity. 

Solution :  

Approach 1 : Add periodic sanity check to the workers.
1) while starting up a worker will fork and run a sanity check task and announce itself if the task succeeds. If it fails it will retry it n (configurable) times and exits if the task fails repeatedly. 
2) worker will periodically run sanity checks on its own by forking a small test-task
3) If the dummy task fails repeatedly, the worker disables itself and overlord will not assign any more tasks to this. 

 Approach 2  : Make overlord smart to identify faulty workers and blacklist them. 
1) maintain a count of failed tasks, and blacklist a worker when it exceeds a configurable threshold. the counter will need to be reset when a task succeeds on a worker.
2) send a small NoOp dummy task to the worker before blacklisting it in order to distinguish between issues in task itself or worker environment. 
3) Optionally also verify all the newly added workers too by assigning a dummy task. 
4) Autoscaling should be able to replace the blacklisted worker. 

I like Approach 1 and I think its better to have the worker do sanity checks on itself instead of overlord asking workers to do it. 

Thoughts ? Suggestions?

**Comment by drcrallen** [comment]
I agree with #1, it fits in better with my Tiering proposal for tasks as well.

**Comment by gianm** [comment]
Just to be different, I like #2 because it would catch more problems. A worker that is broken in some other way than just all tasks immediately failing won't be caught by method #1. But either one is better than nothing so I am not picky.

**Comment by drcrallen** [comment]
IMHO the worker should be responsible for reporting its own status. And different types of workers would have different criteria for "healthy".

Obviously the overlord should have some level of "Can't even reach the middle manager" case handling.

**Comment by himanshug** [comment]
I like both. But, I would go for 1 because it is more self-contained within the worker and simpler to implement. Also, It will be great to increase the scope of 1 a little bit to track count of consecutive failures (for any tasks assigned to it and not just the sanity task, and disable itself if there were too many consecutive failures.
In future, We can evolve towards 2 if/when we notice cases not caught by 1.

**Comment by vogievetsky** [comment]
What is the status of this within the upcoming 0.15.0 release?

**Comment by himanshug** [comment]
sort of handled by https://github.com/apache/incubator-druid/pull/3643 and subsequent related changes.
