### ISSUE TITLE
How to configure Transparent Application Continuity (TAC) with Oracle JDBC Thin and druid connection pool?

### ISSUE THREAD

**Issue by Yanan906** [apache/druid#16751]
It looks like druid cannot directly implement the high availability Oracle specific feature "Transparent Application Continuity",
Can druid handle FAN events?
Oracle JDBC driver can transparently clean up orphaned connections and replay ongoing requests (using new connections) on surviving database instances; Is it possible to use the replay datasource oracle.jdbc.replay.OracleDataSourceImpl in DataSourceConfig class?

anyone can help me ?

**Comment by FrankChen021** [comment]
I think your question is related to Alibaba/druid project
