### ISSUE TITLE
不支持add column if not exists语法，解析会报错

### ISSUE THREAD

**Issue by squestc** [apache/druid#16802]
Please provide a detailed title (e.g. "Broker crashes when using TopN query with Bound filter" instead of just "Broker crashes").

### Affected Version
1.2.23
The Druid version where the problem was encountered.

### Description
解析sql的时，如果有add column if not exists语法会报错，但是sql是可以执行成功的
Please include as much detailed information about the problem as possible.
- Cluster size
- Configurations in use
- Steps to reproduce the problem
- The error message or stack traces encountered. Providing more context, such as nearby log messages or even entire logs, can be helpful.
- Any debugging that you have already done

**Comment by asdf2014** [comment]
Please report this to https://github.com/alibaba/druid
