### ISSUE TITLE
Can't use APPROX_QUANTILE/APPROX_QUANTILE_DS to calculate percentiles for sys.segments

### ISSUE THREAD

**Issue by liu1324871885** [apache/druid#16921]
When I want to perform some basic analysis on segments of a datasource in Druid, I am unable to use 
APPROX_QUANTILE/APPROX_QUANTILE_DS to calculate percentiles. However, using 
APPROX_QUANTILE/APPROX_QUANTILE_DS on tables in non-'sys' schemas does not result in an error.
Thanks a lot!
### Affected Version
25.0

### Description
Query:
SELECT "datasource", APPROX_QUANTILE("num_rows",0.95) as P95_rows
from "sys"."segments"   
GROUP BY 1

ERROR:
Error: SQL query is unsupported
Query not supported. Please check Broker logs for additional details. SQL was: SELECT "datasource", APPROX_QUANTILE("num_rows",0.95) as P95_rows from "sys"."segments" GROUP BY 1
org.apache.calcite.plan.RelOptPlanner$CannotPlanException

**Comment by gianm** [comment]
This happens because queries on `sys` tables do not run in Druid's own engine, they run using Calcite's Bindable interpreter. It doesn't support all of Druid's functions. We'd like to change this in the future so `sys` table queries do go through Druid's own engine.

**Comment by liu1324871885** [comment]
Get it, thanks for your reply!
