### ISSUE TITLE
Add diff function in the edit spec screen

### ISSUE THREAD

**Issue by sgaragan** [apache/druid#17018]
### Description

It would be very useful if a diff function could be added to the ingestion spec editor alongside the "Submit Spec" button.  I often do changes manually by editing the spec JSON and having the ability to do a diff before I submit would allow for checking that the changes being made are what was intended.  Sometimes, if there are several changes being done (e.g. updating/adding dimensions or transformations), a lapse in focus can result in not being sure about what has/has not been changed.  I have abandoned changes many times and had to restart because I was not positive about what changed before I submitted the updated spec

### Motivation

The ability to jump to an ingestion spec from the supervisor is one of the handier functions I use.  As well, the ability to do diffs between a version and the previous version has been useful for seeing if a mistake has been introduced.  Having that diff function be available before committing the change would help prevent some mistakes from being introduced, rather than going back to look for the error after things have gone wrong.

Thanks,
Sean

**Comment by funguy-tech** [comment]
It looks like this feature snuck in with this PR: #16696 

Seems like it's set to release with V31 - I'm running a V31 snapshot and have a `Diff with current supervisor spec` button. It parses the Supervisor name from the pasted spec, so it seems to work regardless of how you navigate to the data loader page.

<img width="1373" alt="image" src="https://github.com/user-attachments/assets/2a7cca74-0223-4c97-8555-f6ee65a4f4c5">

**Comment by asdf2014** [comment]
Closed by #16696
