### ISSUE TITLE
Apache Druid Historical Problems

### ISSUE THREAD

**Issue by cobanmuratcan** [apache/druid#17032]
Hello everyone,
Apache Druid restart takes 4-5 hours and during this time we wait for historical nodes. This time is too long but I don't know if it is normal? Also there are 4 historical nodes, is it advantageous for the general architecture to add more historical and add the data to more nodes? I think it is better to have fewer servers if there is no resource shortage since it will shuffle while querying the data. I wanted to ask you too. Can you help me?

**Comment by abhishekagarwal87** [comment]
I would suggest reaching out to the Apache Druid slack channel - https://app.slack.com/client/T0306CNUA90/C0309C9L90D - There could be different reasons depending on the nature of your setup.
