### ISSUE TITLE
Migrate commons-lang usages to commons-lang3

### ISSUE THREAD

**Issue by kgyrtkirk** [apache/druid#17130]
* Both `commons-lang` and `commons-lang3` is being used in Druid
* `commons-lang` does not get updates since [2011](https://mvnrepository.com/artifact/commons-lang/commons-lang)

I've started working on it a few months ago - I do remember there might be some stuff missing; but I wasn't able to get back to it; it would need to be merged with the current master - I guess there might be some new common-lang usages :)

my worktree is [here](https://github.com/kgyrtkirk/druid/tree/commons-lang3)

**Comment by shigarg1** [comment]
Hi @kgyrtkirk 
I would like to take this up. Will cherry-pick the commits from your tree and proceed from there.

**Comment by shigarg1** [comment]
https://github.com/apache/druid/pull/17156
@kgyrtkirk Can you please help to review

**Comment by kgyrtkirk** [comment]
#17156  is merged; thank you @shigarg1 !
I've opened/described the problem we have faced just before merging that PR #17208
