### ISSUE TITLE
Usage of maxSize in segmentCache 

### ISSUE THREAD

**Issue by vipul-mykaarma** [apache/druid#17167]
Hi all,
I am very new to druid , wanted to know what does maxSize define in the following property of historical component :  
druid.segmentCache.locations=[{"path":"var/druid/segment-cache","maxSize":"800g"}]

can we set it to lower and also do we need to increase this with growing usage of our systems ? and does the used segmentCache reduce or is it ever growing ?

**Comment by vipul-mykaarma** [comment]
<img width="1716" alt="Screenshot 2024-10-11 at 1 18 09 PM" src="https://github.com/user-attachments/assets/ee891853-99d7-45f2-a314-ec461d693dae">
our historical  segment size is ever growing can abyone tell me the ways to reduce the size

**Comment by cryptoe** [comment]
https://druid.apache.org/docs/latest/data-management/  and specifically automatic compaction is something you should look into.

**Comment by vipul-mykaarma** [comment]
it keeps on filling upto 100% how to ensure it remains below 80%
