### ISSUE TITLE
Upgrade commons-io to latest version

### ISSUE THREAD

**Issue by kgyrtkirk** [apache/druid#17220]
### Description

Seems like automated upgrade is failing with some compilation issue
https://github.com/apache/druid/pull/17122

**Comment by shigarg1** [comment]
In latest version of commons-io IOException is replaced with UncheckedIOException
Raised the PR - https://github.com/apache/druid/pull/17227

**Comment by kgyrtkirk** [comment]
fixed in #17227  ; thank you @shigarg1 !
