### ISSUE TITLE
AWS Glue Catalog for Iceberg ingest extension

### ISSUE THREAD

**Issue by Shekharrajak** [apache/druid#17352]
### Description

The Iceberg extension to connect to Glue Iceberg catalog. 

### Motivation

We have [Iceberg framework in AWS Glue](https://docs.aws.amazon.com/glue/latest/dg/aws-glue-programming-etl-format-iceberg.html#aws-glue-programming-etl-format-iceberg-enable), that would be helpful for Druid users to directly connect Iceberg table in Glue. 

The[ Iceberg Ingest extension](https://druid.apache.org/docs/latest/development/extensions-contrib/iceberg/) needs to be enhanced accordingly.

**Comment by Shekharrajak** [comment]
I'm currently exploring the feasibility of this feature and putting together a preliminary design and code draft for a PR. This will allow for a more concrete discussion. I'd appreciate any feedback or links to relevant discussions that could inform this process.

**Comment by abhishekrb19** [comment]
Hi @Shekharrajak, this would be a useful feature. Please see the REST-based catalog implementation for reference - https://github.com/apache/druid/pull/17124. The Glue API docs once you've the Glue dependencies added - https://docs.aws.amazon.com/glue/latest/dg/aws-glue-api-catalog-tables.html#aws-glue-api-catalog-tables-IcebergInput.

cc: @a2l007

**Comment by Shekharrajak** [comment]
Thanks, I am almost done with the basic version of it. I will share the PR soon for further discussion and testing.

**Comment by a2l007** [comment]
Thanks for working on this @Shekharrajak , looking forward to the PR!

**Comment by Shekharrajak** [comment]
I feel we should have modular API to choose catalog, something like (means every input source can have option to choose the catalog that input source supports): 

```
"inputSource": {
     "type": "iceberg",
     "tableName": "iceberg_spr_1_test_23sep",
     "namespace": "test",
     "catalog":
       { 
        "type" : "iceberg-catalog",
         "catalog-type" : "glue", // or hive, local, HDFS, JDBC, etc whatever iceberg supports
         "warehousePath": "<>",
         "catalogProperties" :
           {"<key>": "<value>"}
       },
      "icebergFilter":
       {
         ...
       },
   "warehouseSource": {
        ..
     }
   }
```

What do you guys think ? @a2l007 @abhishekrb19

**Comment by Shekharrajak** [comment]
Once we have such API then we can leverage Iceberg `CatalogUtil.buildIcebergCatalog` method that will returns the `org.apache.iceberg.catalog.Catalog`
