### ISSUE TITLE
Checkstyle in local setup - intelliJ

### ISSUE THREAD

**Issue by Shekharrajak** [apache/druid#17450]
I have setup intellij as per the doc: https://github.com/apache/druid/blob/master/CONTRIBUTING.md#how-to-contribute 

Imported code style settings xml: [druid_intellij_formatting.xml](https://github.com/apache/druid/raw/master/dev/druid_intellij_formatting.xml).

But I do not see the actual style error which is aligned with github action script output error in my PR: https://github.com/apache/druid/pull/17392/

Can anyone know what I am missing ? 

<img width="1578" alt="image" src="https://github.com/user-attachments/assets/f3cae8e6-6999-44a6-80a2-eae0b5492137">

**Comment by abhishekrb19** [comment]
Make sure you've imported the project as a "Maven project" in your Intellij, so the mvn steps use the correct project configurations; the checkstyle  config file should be `codestyle/checkstyle.xml`.  Fwiw, I’m seeing the same checkstyle errors as in your [PR](https://github.com/apache/druid/pull/17392):

<img width="744" alt="CleanShot 2024-11-05 at 08 55 21@2x" src="https://github.com/user-attachments/assets/1cc03b13-8378-4d1f-92f9-28d6f41b11d8">



If that doesn't still work, you can also run the `mvn checkstyle:checkstyle` command locally in your terminal.

**Comment by Shekharrajak** [comment]
> the checkstyle config file should be codestyle/checkstyle.xml

I just have to import the codestyle xml : [druid_intellij_formatting.xml](https://github.com/apache/druid/raw/master/dev/druid_intellij_formatting.xml) right ?

**Comment by Shekharrajak** [comment]
With the mvn checkstyle command I do not get the error details 
<img width="1684" alt="image" src="https://github.com/user-attachments/assets/7068e38d-0ebe-4cae-8936-3db939b1505e">
Can you please let me know what I am missing ?

**Comment by abhishekrb19** [comment]
What do you see above the "BUILD FAILURE" in red? It should list out the individual checkstyle errors.

>I just have to import the codestyle xml : [druid_intellij_formatting.xml](https://github.com/apache/druid/raw/master/dev/druid_intellij_formatting.xml) right ?

In addition to importing the code style settings, `druid_intellij_formatting.xml`, you'll need to open the druid repo as a new project by selecting the root level `pom.xml`. This is so your IDE recognizes that it's a maven project and you can run maven commands directly from it.

**Comment by Shekharrajak** [comment]
Somehow I only see this 
<img width="1556" alt="image" src="https://github.com/user-attachments/assets/2d138809-5ff8-4922-a554-9531737c73a7">

**Comment by abhishekrb19** [comment]
ah yes, you will see the errors if you [scroll](https://github.com/apache/druid/actions/runs/11678146016/job/32519860612) a bit above to the `druid-iceberg-extensions` project. We run checkstyle with the `--fail-at-end` mode, so the individual errors will be listed after each sub-project's checks, not in the end.  Hope that helps!
<img width="1556" alt="CleanShot 2024-11-05 at 10 41 56@2x" src="https://github.com/user-attachments/assets/df0dcacb-70d8-48ad-b2ad-c369693a93cb">

**Comment by Shekharrajak** [comment]
Thanks! Locally I am able to check in intelliJ. Although in CLI I am not sure, why the error details are missing for me.
