### ISSUE TITLE
Ability for extraction functions to operate on multiple columns (similar to aggregators)

### ISSUE THREAD

**Issue by xvrl** [apache/druid#1885]
This should also apply to extraction function filters as well

**Comment by gianm** [comment]
one use case: CONCAT(dim1, dim2) -- improvement on #1873

**Comment by vogievetsky** [comment]
Dammit. I wanted to file this issue. +1

**Comment by vogievetsky** [comment]
I believe the [expression](http://druid.io/docs/latest/misc/math-expr.html) effectively addresses this.
