### ISSUE TITLE
Add the ability to detect when lambda architecture has finished loading its batch portion

### ISSUE THREAD

**Issue by drcrallen** [apache/druid#1969]
As a user of Druid, I would like have a way to know when the data present is as accurate and reliable as possible. In general this means having a way to determine what interval for a data source has had the batch portion of the lambda architecture complete, and any real time segments have been evicted.

**Comment by drcrallen** [comment]
The suggested solution for this is to add an endpoint to `io.druid.server.http.DatasourcesResource` which can return the minimum timestamp for an interval where the segment metadata matches some filter.

In many use cases the realtime segments are generated with a Linear shard spec, and the batch jobs are created with a hash or unsegmented shard spec. It could be possible to setup a filter to look for the minimum timestamp for any matching segment (example: linear) and thereby determine what the earliest "realtime" data is still present in the system.

**Comment by gianm** [comment]
After #1745, we will likely start creating realtime segments as Numbered, although you can still tell they're from realtime because the partition number will be outside the core partition set.
