### ISSUE TITLE
Make TaskQueue more concurrent for overlord. 

### ISSUE THREAD

**Issue by nishantmonu51** [apache/druid#2026]
TaskQueue uses a giantLock to perform almost all the operations. 
Few operations like task shutdown, task log streaming can take a while and blocks the TaskQueue which causes overlord to be non-responsive to HTTP requests to add more tasks.

**Comment by vogievetsky** [comment]
I have not (as a user) encountered the overlord being non-responsive to HTTP requests recently (just playing with 0.15.0-pre-rc1) is this still an issue?
