### ISSUE TITLE
Spark Batch Indexer

### ISSUE THREAD

**Issue by drcrallen** [apache/druid#2089]
This ask is to have a spark batch indexer as a separate feature from the hadoop indexer.

**Comment by drcrallen** [comment]
Here's the status of the project so far:
* Memory problems.... Since the druid indexing task is very memory intensive, it is very easy to run out of heap memory. There are many tweaks in how spark operates that depend on if you're running stand-alone cluster, yarn, or mesos that greatly affect how to mitigate this risk. There are also a few tweaks in how druid handles memory pressure (though only at a pretty high level and in a "please let this work" kind of way). In general though, Spark batch indexing seems to take up notably more heap memory than the hadoop reducers.
* Limited input format support. Right now the project only supports string input (no druid segment input). It also only supports passing an explicit list of files instead of the multitude of file specifications supported by the hadoop version
It can produce binary identical output files compared to the hadoop job. (This should be a no-duh statement, but is a testament to the versatility of the basic indexing paradigm)
* Currently uses RDD, there is another community member who is investigating DataFrame support, but the first version will most likely just use RDDs
Assembly... I had to package the whole lot as an assembly because of horrible library/version problems between druid/spark/hadoop(spark depends on hadoop) and getting classloader craziness straightened out. And because of that...
* Its "big" (for a jar)... like about 100MB that needs distributed. If you're running in an fine grain mode where each task gets a copy of the jars for the job, you can easily fill up a drive much faster than you expected.
* Limited version support - It requires some patches not in druid stable (should be in 0.8.3), some spark patches not in spark stable (should be in 1.6.0)

**Comment by fjy** [comment]
@drcrallen if you submit the PR as a WIP, perhaps other community members can help look at the memory problems

**Comment by drcrallen** [comment]
@fjy I would like to have it running in prod for at least a week before releasing it to the wild :) otherwise the flurry of last-mile changes will be killer for outside adopters.

Right now I seem to have memory tunings reasonable for our data sets, but wanted to call out in the issue that it is non-trivial to tune memory parameters.

**Comment by spektom** [comment]
Hello @drcrallen, 

Is Spark indexer implementation you've mentioned available somewhere? We'd like to have a look at it, if that's possible. We have vast experience with tuning Spark for different workloads, and we have lots of data to test it, so we might help get it fixed.

Thanks!

**Comment by drcrallen** [comment]
@spektom Yep, getting you access.

**Comment by drcrallen** [comment]
By popular request, and since development is more on the spark side than the druid-extension side right now, I have made https://github.com/metamx/druid-spark-batch open to the public for general testing / alpha interest.

I would *not* consider it production ready yet, so please do not expect it to be free of corner cases or support easy upgrades. And version upgrades at this point have *zero* backwards compatibility guarantees (I'm *hoping* nothing will change, but not willing to stamp anything as a long term support yet).

My bandwidth for answering general support questions is severely limited, but will gladly make time to collaborate on improvements.

If you're trying to get it to work with arbitrary hadoop versions or spark versions I cannot lend assistance.  But if you have some changes that will help it work with arbitrary hadoop or spark versions I'm very happy to help get them in.

**Comment by drcrallen** [comment]
As a general update here, the extension is functioning fine so far internally. With the upgrades for 0.9.0 I have removed the requirement to have a big fat jar, instead allowing for spark to be specified loaded only in the local classpath as part of the hadoop coordinates.

**Comment by drcrallen** [comment]
Memory is still an issue, but I *think* some of the memory improvements in 0.9.0 should make that less of a concern. Testing is underway internally for verification of this.

**Comment by xvrl** [comment]
For those interested, a production-ready spark indexer is available for testing in https://github.com/metamx/druid-spark-batch
We have been using it in production for several months now. It lacks some of the features and configuration options of the hadoop indexer, but otherwise perfectly capable to handle large-scale tasks.

**Comment by giaosudau** [comment]
@xvrl 
Hi,
How do you config the job to run on mesos/yarn?
I tried the local mode but I can't change the executor memory?
Thanks.

**Comment by xvrl** [comment]
@giaosudau I believe @drcrallen is in a better position than me to answer this

**Comment by drcrallen** [comment]
We've done stand-alone and we've done mesos, but never yarn.

Mesos docs are http://spark.apache.org/docs/latest/running-on-mesos.html

**Comment by drcrallen** [comment]
You can specify spark properties in the `properties` field as per the example at https://github.com/metamx/druid-spark-batch

**Comment by giaosudau** [comment]
Thank you @drcrallen and @xvrl,
Actually, I had tried on Mesos but I couldn't get the task running due to the task couldn't acquire resource to run.
I tested an another spark job it works well on Mesos cluster (CPU 16 cores/RAM 16GB).
Could you give me some hints about the configuration? Where should I check?
Thanks.
Chanh
```
I1021 12:15:20.622898 41013 master.cpp:5725] Sending 1 offers to framework a1b942a2-87bc-4669-9371-d8942162afdc-0005 (com.ants.util.kafka.PersistenceData) at scheduler-b2294198-5d8d-4d67-905f-acce0f59087b@10.199.0.20:6480
I1021 12:15:20.632650 41013 master.cpp:3951] Processing DECLINE call for offers: [ a1b942a2-87bc-4669-9371-d8942162afdc-O1391 ] for framework a1b942a2-87bc-4669-9371-d8942162afdc-0005 (com.ants.util.kafka.PersistenceData) at scheduler-b2294198-5d8d-4d67-905f-acce0f59087b@10.199.0.20:6480
I1021 12:15:21.624099 41029 master.cpp:5725] Sending 1 offers to framework a1b942a2-87bc-4669-9371-d8942162afdc-0006 (index_spark_ad_statistics_history_2016-10-19T02:00:00.000Z_2016-10-19T03:00:00.000Z_2016-10-21T05:02:34.338Z) at scheduler-77c22048-fa7c-479e-bb25-a0fc7ab18f67@10.199.0.19:21447
I1021 12:15:21.624478 41029 master.cpp:5725] Sending 1 offers to framework a1b942a2-87bc-4669-9371-d8942162afdc-0005 (com.ants.util.kafka.PersistenceData) at scheduler-b2294198-5d8d-4d67-905f-acce0f59087b@10.199.0.20:6480
I1021 12:15:21.626126 41018 master.cpp:3951] Processing DECLINE call for offers: [ a1b942a2-87bc-4669-9371-d8942162afdc-O1392 ] for framework a1b942a2-87bc-4669-9371-d8942162afdc-0006 (index_spark_ad_statistics_history_2016-10-19T02:00:00.000Z_2016-10-19T03:00:00.000Z_2016-10-21T05:02:34.338Z) at scheduler-77c22048-fa7c-479e-bb25-a0fc7ab18f67@10.199.0.19:21447
I1021 12:15:21.626305 41018 master.cpp:3951] Processing DECLINE call for offers: [ a1b942a2-87bc-4669-9371-d8942162afdc-O1393 ] for framework a1b942a2-87bc-4669-9371-d8942162afdc-0005 (com.ants.util.kafka.PersistenceData) at scheduler-b2294198-5d8d-4d67-905f-acce0f59087b@10.199.0.20:6480
I1021 12:15:23.626958 41051 master.cpp:5725] Sending 1 offers to framework a1b942a2-87bc-4669-9371-d8942162afdc-0006 (index_spark_ad_statistics_history_2016-10-19T02:00:00.000Z_2016-10-19T03:00:00.000Z_2016-10-21T05:02:34.338Z) at scheduler-77c22048-fa7c-479e-bb25-a0fc7ab18f67@10.199.0.19:21447
```
```json
{
  "type": "index_spark",
  "dataSchema": {
    "dataSource": "ad_statistics_history",
    "parser": {
      "type": "string",
      "parseSpec": {
        "format": "tsv",
        "timestampSpec": {
          "column": "time",
          "format": "auto",
          "missingValue": null
        },
        "dimensionsSpec": {
          "dimensions": [
            "time_frame",
            "group_id",
            "network_id",
          ],
          "dimensionExclusions": [
          ],
          "spatialDimensions": []
        },
        "delimiter": ";",
        "columns": [
          "time",
          "time_frame",
          "group_id",
          "network_id",
          "user_sketches",
          "pageview"
        ]
      },
      "encoding": "UTF-8"
    },
    "metricsSpec": [
      {
        "type": "count",
        "name": "count"
      },
      {
        "type": "hyperUnique",
        "name": "user_sketches",
        "fieldName": "user_sketches"
      },
      {
        "type": "longSum",
        "name": "pageview",
        "fieldName": "pageview"
      }
    ],
    "granularitySpec": {
      "type": "uniform",
      "segmentGranularity": "HOUR",
      "queryGranularity": "HOUR",
      "intervals": [
        "2016-10-19T02:00:00.000Z/2016-10-19T03:00:00.000Z"
      ]
    }
  },
  "intervals": [
    "2016-10-19T02:00:00.000Z/2016-10-19T03:00:00.000Z"
  ],
  "paths": [
    "/ad-statistic-hourly-utc/pageview/2016-10-19-02",
    "/ad-statistic-hourly-utc/pageview-20/2016-10-19-02",
    "/ad-statistic-hourly-utc/viewable/2016-10-19-02",
    "/ad-statistic-hourly-utc/click/2016-10-19-02",
    "/ad-statistic-hourly-utc/conversion/2016-10-19-02"
  ],
  "properties": {
    "spark.ui.port": "4123",
    "spark.executor.uri": "hdfs://hadoop-master:9000/mesos-dependencies/spark-1.6.1-bin-hadoop2.6.tgz",
    "java.util.logging.manager": "org.apache.logging.log4j.jul.LogManager",
    "user.timezone": "UTC",
    "org.jboss.logging.provider": "log4j2",
    "file.encoding": "UTF-8"
  },
  "targetPartitionSize": 500000,
  "master": "mesos://mesos1:5050",
  "context": {},
  "indexSpec": {
    "bitmap": {
      "type": "concise"
    },
    "dimensionCompression": "lz4",
    "metricCompression": "lz4"
  },
  "hadoopDependencyCoordinates": [
    "org.apache.spark:spark-core_2.10:1.6.1"
  ],
  "dataSource": "ad_statistics_history"
}
```

![](http://i.imgur.com/gLTTlhl.png?1)

**Comment by drcrallen** [comment]
If a particular task fails to launch on a mesos agent too many times, spark can decline future offers from that agent, so be aware of that.

There are a lot of tuning parameters, most notably executor memory and maximum cores, that affect the resources that will be acquired. Also note that spark 2.0 changes how it does resource allocation in Mesos to be much more in line with how the stand-alone cluster functions. I highly recommend getting a migration plan to 2.0 if you haven't started already.

But please check the mesos master's task history first to see if there are failed tasks for that framework.
