### ISSUE TITLE
[Proposal] support for setting javaOpts per a task

### ISSUE THREAD

**Issue by jaehc** [apache/druid#2320]
Currently, there is an setting `druid.indexer.runner.javaOpts` for a overlord node to specify java options for child processes it forks. However, this option has the effect on every tasks it makes.
I think it would be useful to support setting javaOpts for a specific task like as that of MapReduce or YARN. Then we can control task's jvm more finely. And we can also attach a remote debugger to a specific task to give an example of its usecase.
I guess `tunningConfig` is a good place to put that option under if possible.

```
"tuningConfig": {
      "type": "index",
      "targetPartitionSize": 0,
      "rowFlushBoundary": 0,
      "javaOpts": "-server -Xmx256m"
    }
```

**Comment by nishantmonu51** [comment]
this is already supported by passing in druid.indexer.runner.javaOpts in task context.
 
{
"type" : "index"
"tuningConfig"  : {...}
 "context" : {
        "druid.indexer.runner.javaOpts" : "-server -Xmx256m"
 }
}
Its still undocumented I think, its probably worth adding docs for it if the community finds it useful.

**Comment by CHOIJAEHONG1** [comment]
@nishantmonu51 Thanks for your information.

**Comment by drcrallen** [comment]
What exactly are you trying to accomplish here?

My issue with adding or overriding java options is that it is very easy to screw up. Meaning that you have two configurations you have to keep in sync (default java options and task java options).

Even adding "extraJavaOpts" runs the risk of someone changing the origin javaOpts to have incompatible or weird flags.

Can you give an idea of the use cases you are trying to solve by exposing javaOpts?

**Comment by CHOIJAEHONG1** [comment]
@drcrallen I totally agree with your point. We should use it very carefully not to make a mess. But, there are still some useful usecases though. 

Here is my usecase. I want to attach my debugger to an IndexTask which is forked from a overlord. However, IndexTasks often finish it job too quickly to attach my debugger to it. So I want to put off the execution of IndexTask until my debugger has got a connection to the forked jvm. Giving `suspend=y` as a jvm option works out this issue as it delays the execution of code and wait for a debugger attachment. But, if I set this option in the overlord configurations, all the task forked from the overlord will be stuck waiting for the debugger attachment, which is not the situation I want.

```
-Xdebug -Xrunjdwp:transport=dt_socket,address=0.0.0.0:0,server=y,suspend=y
```

**Comment by drcrallen** [comment]
@CHOIJAEHONG1 Cool. once https://github.com/druid-io/druid/pull/2246 is done, I was hoping an extra feature to be able to add would be JVM modules in a "better" way, such that you could add things like the Debugger properties you mentioned, or enable jmxremote or other JVM level stuff. And the modules would have basic capacities to append to the javaOpts to configure the properties, AND be able to communicate any job resource needs that it adds (ex: more ports, more memory, more cpu load)

**Comment by drcrallen** [comment]
since the context javaOpts solves this for the short term, would something like what I described solve it for the longer term?

**Comment by CHOIJAEHONG1** [comment]
@drcrallen Context javaOpts is enough to solve the problem. It sounds good to have that features you mentioned, especially when it comes to handling the interactions with YARN or MESOS as per #2246.

**Comment by nishantmonu51** [comment]
@suhassumukhv: It still seems undocumented, A PR against the docs to add this info would be welcome.

**Comment by vsharathchandra** [comment]
Is there a way to do the same thing with kafka indexing service ? so that the real time ingestion peons of different datasources can be configured different memory.

**Comment by himanshug** [comment]
@vsharathchandra you can put same in kafka supervisor context and it would be propagated to all the launched KafkaIndexTasks

**Comment by vsharathchandra** [comment]
Thanks.Tried it it's working.
