### ISSUE TITLE
The behavior of excluded dimensions needs clarified.

### ISSUE THREAD

**Issue by drcrallen** [apache/druid#2478]
in https://github.com/druid-io/druid/blob/0.9.0/docs/content/ingestion/index.md it specifies

``` markdown
* Any column listed in the list of dimension exclusions is excluded as a dimension.
```

but https://github.com/druid-io/druid-api/blob/druid-api-0.3.16/src/main/java/io/druid/data/input/impl/MapInputRowParser.java#L48 seems to only consider excluded dimensions if an explicit set of dimensions is not specified.

This ask is that the documentation be updated, or MapInputRowParser be updated to clarify what is supposed to happen in the event an explicit list of dimensions is specified, and excluded dimensions are specified.

**Comment by bhrgv-bolla** [comment]
Great question, is it oneOf(dimensions, dimensionExclusions)? Please clarify.
