### ISSUE TITLE
Realtime handoff should be load/drop rule aware

### ISSUE THREAD

**Issue by gianm** [apache/druid#2696]
If the load/drop rules for a datasource prevent a particular segment from ever being loaded, then realtime indexers will wait forever for a load that will never happen. This is a potential issue for windowPeriod-y realtime but an even larger potential issue for windowPeriod-less-realtime (as it may create segments in a region where drop rules are not allowing loads).

**Comment by dclim** [comment]
Make sure Appenderator-based indexing tasks (i.e. KafkaIndexTask) are handled by the fix, see #3619
