### ISSUE TITLE
balancerComputeThreads does not scale linearly

### ISSUE THREAD

**Issue by drcrallen** [apache/druid#3275]
![balancercomputescaling](https://cloud.githubusercontent.com/assets/8213081/17034621/603e6320-4f38-11e6-857e-001170d97322.png)

For a very large number of segments with multiple replicas, there can be a lot of work the coordinator needs to do in order to compute the LoadRule. To parallelize this computation, `balancerComputeThreads` can be set as part of the coordinator dynamic configuration.

Unfortunately, this approach does not scale as well as desired. For this test I ran coordinators on r3.2xl, c4.4xl, and c4.8xl with core counts of 8, 16, and 36. The `balancerComputeThreads` was always set to one less than the number of cores.

In the plot above, the x-axis represents the fraction of cores "available" to the pool for balancer computations. The higher the fraction the more cores on the instance total (35/36 is closer to 1 than 7/8). The y-axis represents the mean 1-minute load-time during peak processing of the LoadRule (which takes many minutes, up to an hour depending on the system). An _ideal_ scaling would have the y-axis equal to the x-axis, yielding a slope of 1. But we see here we have a negative slope, meaning the parallelization of computing balancing during the LoadRule is not great. It also means that if we want to scale the number of segments in the cluster to the next order of magnitude, we will need to change the balancing approach to parallelize much better.

Delays in LoadRule processing cause delays in loading up segments into the cluster, including delaying handoff and causing backpressure on the overlord middle-managers due to them being unable to terminate their tasks effectively.

**Comment by leventov** [comment]
This might be due to the fact that each `computeCost()` call is delegated to the thread pool as a separate `Callable`, creating too much of `FutureTask` / queueing overhead. See #7143.
