### ISSUE TITLE
Selecting last based on max dimension value

### ISSUE THREAD

**Issue by rybex** [apache/druid#3373]
Hi,

Can I get value based on MAX of time dimension. In my posts data source I have uniq dimension read_time. Can I do something equivalent to:

Select *
From  posts
where read_time = (select max(read_time) from posts) LIMIT 1

Which query method is the best to do that? Thanks for answer.

**Comment by kaijianding** [comment]
I think you can try select query with descending=true

**Comment by vogievetsky** [comment]
Assuming you ingested `read_time` as the primary time column (`__time`) you could use the `stringLast` aggregator http://druid.io/docs/latest/querying/aggregations#stringlast-aggregator
