### ISSUE TITLE
[Proposal] Multi-column filtering, let DimensionSpec handle extraction functions exclusively

### ISSUE THREAD

**Issue by jon-wei** [apache/druid#3378]
# Multi-column filtering, let DimensionSpec handle extraction functions exclusively

To support filters that accept multi-column inputs, this proposal suggests that:
- DimensionSpec and ExtractionFn accept multiple dimensions, e.g. 
  - https://github.com/druid-io/druid/pull/3091
  - https://github.com/druid-io/druid/issues/2908
- Extraction function application is moved into DimensionSpec exclusively, out of the ColumnSelectorFactory implementations and Filter predicates.
- Filters will now accept a DimensionSpec instead of a dimension string and extraction function.
## DimensionSpec

The following methods are added to DimensionSpec:

```
Object getColumnValueSelector(ColumnSelectorFactory columnSelectorFactory);
ValueType getOutputType(ColumnSelectorFactory columnSelectorFactory);
BitmapIndex getBitmapIndex(BitmapIndexSelector selector);
```
- Change `DimensionSpec` to accept list of dimension names, instead of a single name
- Instead of using `ColumnSelectorFactory.makeDimensionSelector()`, column reading code will call `DimensionSpec.getColumnValueSelector(columnSelectorFactory)` and use `getOutputType()` to determine the type of the selector
- DimensionSpec uses ColumnSelectorFactory to create a view of a dimension ("virtual column"), represented as a `DimensionSelector`, `LongColumnSelector`, etc.
- The DimensionSpec creates a new "Column Value Selector" that composes `DimensionSelectors`, `LongColumnSelectors`, etc. for individual columns from the `ColumnSelectorFactory`, applying the extraction function, into a new "virtual column"
- If the output type is string, the returned object will be a `DimensionSelector`. If the output type is long, the returned object will be a `LongColumnSelector`.
- `decorate()` becomes a private method, wrapping a delegate selector when `getColumnValueSelector()` is called
- can remove `getExtractionFn()`, extractionFn is no longer needed by/exposed to reader code
- Use `ExtractionDimensionSpec` for grouping/filtering on "virtual columns" derived from multiple input columns, as well as any dimensions with extraction functions applied
- Use `DefaultDimensionSpec` for reading from the base columns without transformations
- `RegexFilteredDimensionSpec` and `ListFilteredDimensionSpec` can just pass new method calls to delegate spec
- `LookupDimensionSpec`: replace this usage with `ExtractionDimensionSpec` and the right extraction function?
- Bitmap retrieval is also moved to `DimensionSpec`, it can return null for cases where bitmap is not valid (e.g., with a multiple column extraction fn, or other extraction fn that makes the indexes unusable)
- For bitmap retrieval instead of calling `BitmapIndexSelector.getBitmapIndex(dimension)`, call `dimensionSpec.getBitmapIndex(BitmapIndexSelector)`
## ValueMatcherFactory

```
  public ValueMatcher makeValueMatcher(DimensionSpec dimensionSpec, Comparable value);
  public ValueMatcher makeValueMatcher(DimensionSpec dimensionSpec, DruidPredicateFactory predicateFactory);
```
- The methods above are changed to accept a DimensionSpec instead of a dimension name
- use `DimensionSpec.getColumnValueSelector()` instead of `ColumnSelectorFactory.makeDimensionSelector()`
## Query engines
- use `DimensionSpec.getColumnValueSelector()` instead of `ColumnSelectorFactory.makeDimensionSelector()`
## ColumnSelectorFactory

```
public boolean isDescending();
```
- Add `isDescending()` so ExtractionDimensionSpec can create SingleScanTimeDimSelector for __time
- Move extractionFn application out of ColumnSelectorFactory
- ColumnSelectorFactory is now responsible for returning single column selectors on real in-segment columns, with no value transformations
## Filters:
- Accept a `DimensionSpec` instead of a dimension name
- Instead of checking for the presence of an extraction function, filters use the `preservesOrdering` and `extractionType` properties of the DimensionSpec (e.g., for BoundFilter optimizations)
- Filter acts on the materialized "virtual column" expressed by the `DimensionSpec`
- Move extractionFn application outside of predicates, rely on DimensionSelector to have already applied value transformations instead
- Could write an arbitrary filter by using a multi-column extractionFn that returns a boolean value, use selector filter on "true"
- Could support extraction functions that return longs, floats, etc. in the future
## Related Topics/Issues/PRs:
- https://groups.google.com/forum/#!topic/druid-user/-MEsJOUX_5I - Timeseries query: how to filter events by a secondary time dimension at the bucket level
- https://github.com/druid-io/druid/issues/2187 - I would like JavaScript filters to be able to work on multiple columns
- https://github.com/druid-io/druid/pull/2210 - Javascript filter with multiple columns 
- https://github.com/druid-io/druid/pull/2217 - Support multi-dimensional filters
- https://github.com/druid-io/druid/pull/2511 - Support virtual column for select query
- https://github.com/druid-io/druid/issues/2908 - [Proposal] Support multiple dimensions in Dimension Spec
- https://github.com/druid-io/druid/pull/3091 - [WIP] Support multiple dimensions in Dimension Spec
- https://github.com/druid-io/druid/issues/3082#issuecomment-224397267 - [Proposal][QTL] unify lookup dimension spec, discussion about unifying ExtractionFn and DimensionSpec
- https://github.com/druid-io/druid/issues/1885 - Ability for extraction functions to operate on multiple columns (similar to aggregators)

**Comment by gianm** [comment]
Un-milestoning this from 0.10.0.

@jon-wei reading through this it looks like some of it has been done already as part of PRs in 0.10.0 and some of it has not. (And actually some of it it looks like we decided to go in a different direction: like filters not taking dimensionSpecs.)

Do you think we should keep it open and scope down to what still makes sense given what has already been done? Or close and reimagine and open new proposals?

**Comment by vogievetsky** [comment]
@jon-wei is this still needed given the [expression](http://druid.io/docs/latest/misc/math-expr.html) stuff that exists now?
