### ISSUE TITLE
Fix incorrect counts in ByteCountingLRUMap

### ISSUE THREAD

**Issue by sascha-coenen** [apache/druid#3384]
We noticed that the MapCache doesn't seem to respect the maximum byte limit configured for it.
One part of fixing this would be to correct the statistics that the ByteCountingLRUMap performs which uses  the "numBytes" member variable to keep track of the current cache size to make sure it doesn't surpass the configured maximum limit.

The "numBytes" and "evictionCount" members handled incorrectly:
Both are declared as volatile, but in the code they are incremented/decremented via += or -= operations.
However, this is not a permissible use for volatile variables as volatile is non-blocking and doesn't guarantee the consistency of read-update-write operations (http://www.javamex.com/tutorials/synchronization_volatile.shtml) One could use synchronize blocks or AtomicLongs instead.

**Comment by navis** [comment]
I can think of one more reason for that. Because LinkedHashMap only can remove one entry for one `put`, it can possibly exceed maximum bytes. If ever increasing sized object are to be added to it, it'll also grow ever.
