### ISSUE TITLE
Peon hangs in RealtimePlumber.finishJob()

### ISSUE THREAD

**Issue by leventov** [apache/druid#3720]
Apparently because `abandonSegment()` was not called for some segment. We've seen this after some rare kind of outage, so probably `abandonSegment()` or it's caller by chain should be called "safer" somewhere (e. g. in `finally` block)

```
Thread 100153: (state = BLOCKED)
 - java.lang.Object.wait(long) @bci=0 (Interpreted frame)
 - java.lang.Object.wait() @bci=2, line=502 (Interpreted frame)
 - io.druid.segment.realtime.plumber.RealtimePlumber.finishJob() @bci=181, line=511 (Interpreted frame)
 - io.druid.indexing.common.task.RealtimeIndexTask.run(io.druid.indexing.common.TaskToolbox) @bci=559, line=405 (Interpreted frame)
 - io.druid.indexing.overlord.ThreadPoolTaskRunner$ThreadPoolTaskRunnerCallable.call() @bci=90, line=436 (Interpreted frame)
 - io.druid.indexing.overlord.ThreadPoolTaskRunner$ThreadPoolTaskRunnerCallable.call() @bci=1, line=408 (Interpreted frame)
 - java.util.concurrent.FutureTask.run() @bci=42, line=266 (Interpreted frame)
 - java.util.concurrent.ThreadPoolExecutor.runWorker(java.util.concurrent.ThreadPoolExecutor$Worker) @bci=95, line=1142 (Interpreted frame)
 - java.util.concurrent.ThreadPoolExecutor$Worker.run() @bci=5, line=617 (Interpreted frame)
 - java.lang.Thread.run() @bci=11, line=745 (Interpreted frame)
```

**Comment by jihoonson** [comment]
Hi @leventov, do you have any log in addition to the stack trace?

**Comment by leventov** [comment]
@jihoonson no, unfortunately I didn't save it. Why it could be interesting?

**Comment by jihoonson** [comment]
Yes. I'm trying to be familiar with druid's internal, and in this case, related logs will be very helpful for me. I'll dig deeper. Thanks.

**Comment by leventov** [comment]
@jihoonson I can also suggest to review PRs which touch Druid internals, it's a great way to become familiar with them and also there is high demand for PRs in the project.

**Comment by jihoonson** [comment]
@leventov Right. Thanks for your advice.
