### ISSUE TITLE
Implement LookupExtractor.close() and avoid deleting off-heap cache while LookupExtractor is in use

### ISSUE THREAD

**Issue by leventov** [apache/druid#3771]
Addressing https://github.com/druid-io/druid/blob/78159d7ca442cf8d99ea356d39932ab3adb8e10f/extensions-core/lookups-cached-global/src/main/java/io/druid/server/lookup/namespace/cache/OffHeapNamespaceExtractionCacheManager.java#L122

Proposed solution: make `LookupExtractor` closeable, and remove the cache only after it is replaced by a newer cache via periodic updates, _and_ there are no open `LookupExtractor`s accessing this cache. (Implementation may require some kind of manual reference counting.)

Currently, because of #3663, while off-heap cache is not functional, so this issue is not important because "closing" on-heap cache while using it is harmless ("closing" is just cleaning references to it, the cache itself is unchanged.)

**Comment by drcrallen** [comment]
One reason this was not resolved in the initial release was I couldn't find the right "responsibility chain" to tie the closeable resource into. Essentially things that require closeable resources tend to have their own QueryRunner that closes the resources appropriately, and I didn't want to add yet another one without some significant thought regarding the best way to actually handle query resources.
