### ISSUE TITLE
Observed issues with connectionCount load balancing

### ISSUE THREAD

**Issue by gianm** [apache/druid#3777]
Recently I saw a cluster in a state that seemed to indicate a bug with connectionCount load balancing:

- It was clear from metrics that certain brokers were "preferring" certain historical nodes
- The brokers were configured to use connectionCount load balancing
- Restarting brokers didn't fix the imbalance, but did shift it around to different historical nodes
- Changing load balancing to "random" did fix the imbalance

**Comment by FaxianZhao** [comment]
I think you should consider the weight of segment count for each connection.

**Comment by FaxianZhao** [comment]
I think you should consider the weight of segments count for each connection.
Every query wanna use least connection, so it will chose the historical which has most segments.
