### ISSUE TITLE
Concurrent modification of responseContext in QueryRunners

### ISSUE THREAD

**Issue by leventov** [apache/druid#3803]
responseContext is a plain `HashMap`. It is accessed/modified concurrently without any synchronization in `AsyncQueryRunner`, `IntervalChunkingQueryRunner`, `ChainedExecutionQueryFactory`, etc.

We didn't notice this problem before, because `responseContext` had very limited use, but as part of #3798 I started to use responseContexts more extensively and got `ConcurrentModificationException`.

I quickly fixed this in this commit: https://github.com/metamx/druid/commit/54c2af24966e73d6f8c5951ec53e5c0407c653d2 but I don't like this solution, especially how it works in `AsyncQueryRunner` and `DirectDruidClient`, because it is super fragile and relies on what particular types of `QueryRunner`s call `AsyncQueryRunner` and called from `DirectDruidClient`. There are two main problems:
 - it is not specified how responseContext could and could not be used and when it is "finalized": after return from `QueryRunner.run()`, or after iteration over the returned `Sequence` is completed.
 - No difference between "sync" and "async" (lazy) QueryRunners/Sequences

I don't have an idea yet what a better solution would be.

**Comment by gianm** [comment]
How about making the response context thread-safe?

Currently, the response context is returned as an HTTP header, so it should be "finalized" after `QueryRunner.run` returns, _before_ iteration over the Sequence. But it might be more useful to allow it to be finalized _after_ iteration. #3319 and #3323 are considering changing the context return mechanism to allow this.

**Comment by himanshug** [comment]
also, please keep in mind that stuff in responseContext generated on historicals is transferred to brokers (ok, its kinda broken right now due to the header length limits but #3323 would fix that) , so it shouldn't have too much irrelevant stuff that does not need to be sent across.
goal of responseContext is to be able to pass through query execution contextual information to the end-user.
