### ISSUE TITLE
Add overlord monitor for monitoring leadership status.

### ISSUE THREAD

**Issue by drcrallen** [apache/druid#3835]
This ask is that a Monitor be put in place on the overlord (and probably coordinator) that reports the leadership status of that part of the service.

**Comment by fjy** [comment]
That should be there already.

/leader

**Comment by fjy** [comment]
@drcrallen do you mean a separate monitor vs an http endpoint? what's the use case?

**Comment by drcrallen** [comment]
I mean a `com.metamx.metrics.Monitor` that emits information about if the node is currently leader. We're seeing some leadership issues when the zk connection has problems. And having information about if a node thinks it is leader would have been helpful.
