### ISSUE TITLE
Optimized TopN query execution when dimension has only one value

### ISSUE THREAD

**Issue by leventov** [apache/druid#4065]
TopNs frequently have just one value (usually `Null`). For this case, we can add an optimized aggregation method to `BufferAggregator` class, which aggreates into a single local variable and returns it. Such methods could be compiled much more efficiently (likely vectorized!) by Java than the more generic `scanAndAggregate()` versions, which assume many dimension values and store aggregates in indexed ByteBuffer.

**Comment by gianm** [comment]
Is there any reason not to use the bytebuffer anyway? It's already allocated for the query whether we use it or not, and if we use it, then we don't need an additional implementation of aggregation. It seems like this optimization could be done by making changes just to the topN engine and not to BufferAggregator.

**Comment by leventov** [comment]
@gianm I'm almost sure Hotspot won't be able to vectorize loop, which writes to ByteBuffer on each iteration. However to allow to write a really concise loop and vectorization this optimization should also be integrated with Cursor, it should be checked that cursor is not filtering and goes though the continuous chunk of memory.

**Comment by leventov** [comment]
Also since now we can use `default` methods in interfaces, it's not a problem to add such new method(s) to `BufferAggregator`, they could have default implementation:
```java
ByteBuffer bb = allocate(aggSize());
init(bb);
for (value : cursor) {
  aggregate(bb, value);
}
return get(bb);
```

**Comment by gianm** [comment]
Oh, thanks for the example code, now I understand what you mean. Earlier I thought you meant this new method would process just one row. But it looks you meant to process the entire cursor.

Alternatively what do you think of vectorizing the cursor, so it can advance in chunks at a time and we can have aggregators aggregate over a whole chunk? Then they can still use a bytebuffer for storage without too much overhead, by extracting the aggregator state, aggregating a chunk into it, and then writing it back. "aggregating a chunk into it" will be the hot loop. Could also be nicer when aggregating multiple columns in the same query.

**Comment by leventov** [comment]
@gianm sounds good

**Comment by leventov** [comment]
And for `CountBufferAggregator`, it is not even a loop, it's O(1) getting the size of the block or the cardinality of the cursor.
