### ISSUE TITLE
Use async-http-client instead of metamx/http-client?

### ISSUE THREAD

**Issue by leventov** [apache/druid#4124]
We can leverage actively community-supported https://github.com/AsyncHttpClient/async-http-client instead of "own" https://github.com/metamx/http-client.

Why:
 - Support: metamx/http-client is stuck with Netty 3.9 and no-one seems to want/have resources to migrate it to Netty 4.1, async-http-client uses the very latest version of Netty already.
 - At least in it's own source async-http-client doesn't use locks, `synchronized` and blocking synchronization primitives, unlike metamx/http-client.
 - A project with 3500 commits presumably has higher overall quality and less bugs, than a project with 218 commits. Also I suppose that async-http-client is battle-tested at least not worse than metamx/http-client.

BTW @cheddar's original implementation of metamx/http-client was probably based on async-http-client: https://github.com/AsyncHttpClient/async-http-client/tree/51c6b46d2587301c40216e6ff7bb41d228eafb77

cc #3393

**Comment by sascha-coenen** [comment]
here's another one from Apache: 
https://hc.apache.org/httpcomponents-asyncclient-4.1.x/index.html

**Comment by drcrallen** [comment]
Does it support http/2?

**Comment by sascha-coenen** [comment]
the newest version supports it, but it isn't in a final release state yet:
https://hc.apache.org/news.html
