### ISSUE TITLE
If response is too large for memcache, no response is returned at all.

### ISSUE THREAD

**Issue by sixtus** [apache/druid#4156]
Expected behavior:

druid just doesn't cache, but returns the response.

Instead I get a 500:
```
{
	"error": "Unknown exception",
	"errorMessage": "Cannot cache data larger than 5242880 bytes (you tried to cache a 5661827 byte object)",
	"errorClass": "java.lang.IllegalArgumentException",
}
```

That's not very nice.

**Comment by mgastel** [comment]
I'd put a +1 on this.   I've never enabled caching for group by's because I don't want to have my users potentially get an error.   I would also prefer "just doesn't cache" and maybe keep a stat or something

**Comment by gianm** [comment]
I believe #5108 works around this enough that it shouldn't be an issue in practice (the default maxEntrySize is smaller than 5MB). So I don't think it needs to be in 0.13.0. What do y'all think?

**Comment by fjy** [comment]
@gianm Agree.
