### ISSUE TITLE
Move from com.sun.jersey to org.glassfish.jersey

### ISSUE THREAD

**Issue by leventov** [apache/druid#4310]
`com.sun.jersey` groupID seems to be legacy and not going to be updated anymore. See https://github.com/jersey/jersey

**Comment by pjfanning** [comment]
@FrankChen021 could this be marked as a security issue - jersey v1 depends on jackson v1 which has security issues

**Comment by FrankChen021** [comment]
Oh god, so old this issue is.

**Comment by FrankChen021** [comment]
From this hint on this [page](https://mvnrepository.com/artifact/com.sun.jersey/jersey-json), jersey-json is moved to [org.glassfish.jersey.core](https://mvnrepository.com/artifact/org.glassfish.jersey.core). But I don't see such artifact under that group id.

I have not looked through the CVEs yet. To upgrade the jersey-json, which jersey version are you suggestting to use? The latest [3.0.4](https://mvnrepository.com/artifact/org.glassfish.jersey.core/jersey-server/3.0.4)?

I don't if it's easy for us to upgrade from current 1.19.4 to 3.0.4. @pjfanning

**Comment by pjfanning** [comment]
Fair enough. There are some risks in not upgrading but I appreciate there is effort involved. This page describes how JSON support works in jersey v2 - https://cassiomolin.com/2016/08/10/using-jackson-as-json-provider-in-jersey-2x/
