### ISSUE TITLE
RTR can blacklist workers after task shutdowns

### ISSUE THREAD

**Issue by gianm** [apache/druid#4620]
The RTR doesn't know the difference between tasks that failed on their own, and tasks that were manually shut down. So if you shutdown a bunch of tasks all at once, workers can get blacklisted.

**Comment by gianm** [comment]
Fixed by #4619.

**Comment by gianm** [comment]
Sorry, not fixed by #4619. That fixed a bunch of similar sounding things but not this one.

**Comment by jihoonson** [comment]
Would you please use the full name in the title? I think it's not really intuitive for the people who are not familiar with the indexing service.

Also, I think it makes sense to move this to 0.13.1. What do you think?
