### ISSUE TITLE
Index merging without garbage

### ISSUE THREAD

**Issue by leventov** [apache/druid#4622]
### Current state

Currently the data in several partial (or just one - for transformations) indexes is transformed during merged in the following way:

0) Iterator < TimeAndDims + Object[] metrics (entry in `IncrementalIndex`) >
--> sorting dimension value indexed, aka unsortedToSorted
1) Iterator < Rowboat (Object[] dims, Object[] metrics) >
--> optionally, reordering dims
2) Iterator < Rowboat (Object[] dims, Object[] metrics) > 
   // here array elements are the same objects as at the previous step, but `Object[]` arrays are new, if reordering or dims and/or metrics is actually required <br>
--> another one reindexing, based on merged dictionary
3) Iterator < Rowboat (Object[] dims, Object[] metrics) >
--> final merge.

Here, `Object[]` elements are either `int[]` (DimensionSelector), `Long`, `Double` or `Float` (numeric ColumnValueSelectors, correspondingly).

So in the process of merge, each entry generates 2-3 extra `Rowboat` objects, 4-7 new `Object[]` arrays, and N (the number of string dimensions) * 2 new `int[]` arrays, and new boxed primitive objects, if merging is done with `QueryableIndex` as a source.

### Garbage-free approach

`Rowboat` contains an array of *ColumnValueSelector* objects, representing the stream of dimensions, and another array of ColumnValueSelector objects, representing a stream of metrics, both "under cursor". When `QueryableIndex`is used as source for merging, the existing `Cursor` and `ColumnValueSelectorFactory` infrastructure is reused with minimal modifications.

0->1 and 2-3 conversions, as described above, implemented as ColumnValueSelector transformations, without creating new arrays, boxed primitives, etc. 1->2 transformation is essentially a no-op: create a Rowboat object with array of ColumnValueSelectors, ordered differently.

**Comment by gianm** [comment]
Thank you for summarizing the motivation.

Can you quantify the benefit from this series of patches?

Could you also please lay out what backwards-incompatible API changes (if any) are expected as part of this series of patches?

**Comment by leventov** [comment]
I don't know how much space and time it will save, because this series of patches is not finished yet, and not tested.

Aggregations in extensions, which are supposed to be used for indexing rollup, must implement `AggregatorFactory.makeAggregateCombiner()`: https://github.com/druid-io/druid/pull/4676/files#diff-90e2d51a725b4d59f09e2f8b740b7f37R70
