### ISSUE TITLE
Ability to blacklist historical node

### ISSUE THREAD

**Issue by akashdw** [apache/druid#4665]
We had an issue where some historical nodes(with root partition filled up with the request logs) were not able to download segments and coordinator was keep assigning new segments to those historical nodes.
It would be nice if coordinator can blacklist historical nodes.
 
Blacklisting could be based on segment download status. Currently historical nodes don't pass segment load success/fail information to coordinator, in both cases historical deletes the loadQueue for the segment. Passing segment load status to coordinator will be useful to figure out if the problem is with the segment itself(say broken deep storage path) or with the historical node (disk issues), if it is with historical then blacklist historical node. 

Haven't figured out the full details of the above approach and open for suggestions. what do you think @gianm @cheddar @himanshug @leventov ?

**Comment by niketh** [comment]
This might become easier after @himanshug work of replacing ZK based coordination with HTTP. After that PR goes through, Coordinator can keep a count of failures from each historical and use that information for more "intelligent" processing

**Comment by himanshug** [comment]
i think @niketh is right in saying that "segment assignment migration to HTTP" ( partially done in #2368 ) will fix the problem that load success/fail status would get propagated to coordinator and coordinator would be able to act appropriately.

that said, once a historical is blacklisted, will user need to take some action to "un-blacklist" it or will it be something of a temporary blacklisting ?

**Comment by gianm** [comment]
> that said, once a historical is blacklisted, will user need to take some action to "un-blacklist" it or will it be something of a temporary blacklisting ?

I think ideally, there should be some backoff. So let's say a node is blacklisted when it has some problems, and then after some time has passed, we'll let it load a few segments (applying a throttle) as a test. If it can do those, then take off the throttle and return it to full service. If it can't do those, then return it to a full blacklist for another while.

**Comment by himanshug** [comment]
yeah, i would prefer temporary blacklisting aka backoff instead of permanently marking a node blacklisted.
