### ISSUE TITLE
More accurate dictionary size estimation in RowBasedKeySerde

### ISSUE THREAD

**Issue by jihoonson** [apache/druid#4768]
The original discussion is https://github.com/druid-io/druid/pull/4704#discussion_r137852424.

```RowBasedKeySerde``` currently builds a dictionary at query time. To avoid using too many memory, the dictionary size is limited by user configuration. However, the current dictionary size estimation is based on a rough calculation.

JOL might be an alternative for more accurate dictionary size estimation if its overhead is not so large.

**Comment by leventov** [comment]
What do you mean by "overhead" here? I thought the only concern with it might be that it only supports HotSpot JVM (though I'm not sure). But it could be fine, if Druid doesn't really aim to support other JVMs. Other than that, it should be perfectly fine to use it.

**Comment by leventov** [comment]
Ok, and another issue could be the license, because JOL is GPL.

**Comment by jihoonson** [comment]
I meant the overhead to get the size of each string in dictionary because it will be a very frequent operation. 

> Ok, and another issue could be the license, because JOL is GPL.

This is a really sad news..

**Comment by leventov** [comment]
@jihoonson see #4771

**Comment by leventov** [comment]
Or, if still using this approach, `byte-buddy-agent` library could be used to [obtain `Instrumentation` instance](http://static.javadoc.io/net.bytebuddy/byte-buddy-agent/1.7.5/net/bytebuddy/agent/ByteBuddyAgent.html#install--), and then calling [`Instrumentation.getObjectSize()`](https://docs.oracle.com/javase/8/docs/api/java/lang/instrument/Instrumentation.html#getObjectSize-java.lang.Object-).

**Comment by jihoonson** [comment]
https://github.com/druid-io/druid/pull/5583 might be related as well.

**Comment by jihoonson** [comment]
Still relevant.
