### ISSUE TITLE
Apply techniques from JCTools to reduce false and true sharing in StreamingMergeSortedGrouper

### ISSUE THREAD

**Issue by leventov** [apache/druid#4802]
http://psy-lob-saw.blogspot.com.co/p/lock-free-queues.html, https://github.com/JCTools/JCTools

**Comment by jihoonson** [comment]
JCTools looks to provide several types of concurrent queues, but rows are stored in ByteBuffer in StreamingMergeSortedGrouper. How are you thinking to use the queues of JCTools for data StreamingMergeSortedGrouper? Does it provide an off-heap queue?

**Comment by leventov** [comment]
This is not about using the library, this is about applying the same techniques as used in that library to optimize StreamingMergeSortedGrouper.

**Comment by jihoonson** [comment]
Ok, it sounds good.
