### ISSUE TITLE
Lookup configs get big and silently truncate

### ISSUE THREAD

**Issue by drcrallen** [apache/druid#4838]
We have lots of lookups, which are stored in a payload field in the coordinator dynamic configuration table.

Unfortunately we finally had enough to where mysql silently truncated our data ([maybe related](http://blog.andrewkoebbe.com/blog/2016-03-10.mysql-truncate)). 

The solution was to curl the lookup definitions off of one of the query nodes at the `/druid/listen/v1/lookups` endpoint, and use that as the basepoint for re-building the json which was posted to the coordinator.

The field in the druid config database was also updated from `BLOB` to `LONGBLOB` with

```sql
ALTER TABLE `config_table_name_here` MODIFY payload LONGBLOB;
```

It looks like the payload storage is currently `LONGBLOB` as of https://github.com/druid-io/druid/commit/92afd1094750dbcdb08b34f94fbfe9789331788c#diff-14bfc16ec3b414d57d3d019dd9657d06L119 

Which means anyone who was running druid before the 0.7.0 release probably needs to update their database to make sure the correct payload types are used for the config payload column.

**Comment by himanshug** [comment]
thanks, good to know. I think we should put that in druid 0.11.0 release notes too.

That said, I think proper way to fix this is to have a separate "druid_lookups" table for storing lookups instead of using config table and have separate rows for separate lookups in DB like we do for segments, tasks etc.

**Comment by drcrallen** [comment]
Whoops, missed this one in prior release notes. Next one should probably include it and close out the issue.
