### ISSUE TITLE
Loading only in-demand segments on historical node startup

### ISSUE THREAD

**Issue by egor-ryashin** [apache/druid#4975]
Right now cache loading on startup could take significant time. To alleviate the problem a _historical_ node could accumulate statistics about frequently used intervals (that stats could be persisted locally) and use it to load only "hot" segments during startup. Other segments will be loaded on the first relevant query.

**Comment by licl2014** [comment]
Yep, it doesn't speed up although increase the value of **numLoadingThreads**
