### ISSUE TITLE
"Code coverage" badge is broken

### ISSUE THREAD

**Issue by leventov** [apache/druid#5116]
Always shows 100%

**Comment by asdf2014** [comment]
Hi, @leventov . The status icon of Teamcity is also broken. Maybe the administrator should follow 
 some steps in http://www.mikeobrien.net/blog/setting-up-teamcity-status-badges-with-shields-io to make it correct.

![image](https://user-images.githubusercontent.com/8108788/42369364-4e130394-813c-11e8-8893-1bcdb806356b.png)

**Comment by leventov** [comment]
Currently, it shows Coverage|unknown

**Comment by ccaominh** [comment]
This is fixed by https://github.com/apache/druid/pull/8388
