### ISSUE TITLE
Make druid Null handling behave like SQL standard by default and deprecate older behaviors

### ISSUE THREAD

**Issue by nishantmonu51** [apache/druid#5160]
With the changes in https://github.com/druid-io/druid/pull/4754 druid can now handle nulls as per SQL standard, this task is to make this default standard behavior and remove legacy code/tests related to old behavior. 

NOTE: - This change will *NOT* be backwards compatible

**Comment by leventov** [comment]
`SchemalessTestSimpleTest.testFullOnTopN()` needs to be re-enabled maybe

**Comment by nishantmonu51** [comment]
Also look into https://github.com/druid-io/druid/issues/5169 before enabling it by default.
