### ISSUE TITLE
hadoop ingesting problem of segmentGranularity when moving from UTC to UTC+8

### ISSUE THREAD

**Issue by pphust** [apache/druid#5291]
I am trying to move my druid segments from UTC to UTC+8. And my druid cluster is 0.9.1.1
The original segments are generated with UTC and queryGranularity is HOUR. And I hope my new segments is based on UTC+8 and queryGranularity is DAY.

I create one ingesting file to submit hadoop ingesting job.
1. The original data setting defined in inputSpec of ioconfig looks like:
            "inputSpec": {
                "type": "dataSource",
                "ingestionSpec": {
                    "dataSource": "p4p_t1",
                    "intervals": [
                        "2017-07-01T00:00:00.000+08:00/2017-08-01T00:00:00.000+08:00"
                    ]
                }
            }
2. The target data setting defined in granularitySpec of dataSchema looks like:
        "dataSchema": {
            "dataSource": "p4p_t2",
            "granularitySpec": {
                "intervals": [
                    "2017-07-01T00:00:00.000+08:00/2017-08-01T00:00:00.000+08:00"
                ],
                "queryGranularity": "day",
                "segmentGranularity" : "day",
                "type": "uniform"
            }

3. I have setup map-reduce job properties looks like:
            "jobProperties": {
                "mapreduce.input.fileinputformat.split.maxsize": "134217728",
                "mapreduce.job.reduce.slowstart.completedmaps": "0.10",
                "mapreduce.map.java.opts": "-Xmx3072m -Duser.timezone=Asia/Shanghai -Dfile.encoding=UTF-8",
                "mapreduce.map.memory.mb": "8192",
                "mapreduce.reduce.java.opts": "-Xmx6144m -Duser.timezone=Asia/Shanghai -Dfile.encoding=UTF-8",
                "mapreduce.reduce.memory.mb": "8192"
            }

4. The job is submitted looks like:
nohup /home/appops/java/bin/java -Xmx512m  -Dfile.encoding=UTF-8 -Duser.timezone=Asia/Shanghai -cp  /home/appops/druid/conf/druid/_common:/home/appops/hadoop-2.5.2/etc/hadoop:lib/* io.druid.cli.Main index hadoop ./p4p_compress.json  &

All looks good and the query result  of granularity=DAY are same  from original data(p4p_t1) and target data(p4p_t2):
    "granularity": {
        "type": "period",
        "period": "P1D",
        "timeZone": "Asia/Shanghai"
    }

But when I change "segmentGranularity" from day to month. The query result based on target data(p4p_t2) are strange. 
When I set timeZone as Asia/Shanghai in query, the result looks like:
[ {
  "timestamp" : "2017-07-28T00:00:00.000+08:00",
  "result" : {
    "requestCount" : 237233228
  }
}, {
  "timestamp" : "2017-07-29T00:00:00.000+08:00",
  "result" : {
    "requestCount" : 202405477
  }
}, {
  "timestamp" : "2017-07-30T00:00:00.000+08:00",
  "result" : {
    "requestCount" : 202900972
  }
}, {
  "timestamp" : "2017-07-31T00:00:00.000+08:00",
  "result" : {
    "requestCount" : 169106818
  }
} ]

When I set timeZone as UTC in query, the result looks like:
[ {
  "timestamp" : "2017-07-28T00:00:00.000Z",
  "result" : {
    "requestCount" : 237233228
  }
}, {
  "timestamp" : "2017-07-29T00:00:00.000Z",
  "result" : {
    "requestCount" : 202405477
  }
}, {
  "timestamp" : "2017-07-30T00:00:00.000Z",
  "result" : {
    "requestCount" : 202900972
  }
}, {
  "timestamp" : "2017-07-31T00:00:00.000Z",
  "result" : {
    "requestCount" : 169106818
  }
} ]

You can see the requestCount of UTC DAY and UTC+8 DAY are same but it is not the truth.  Actually it always return  requestCount of UTC DAY even I set timeZone as Asia/Shanghai in query context.
It is very strange because I only change segmentGranularity from day to month then I can merge the small segments per day. 
Is there any suggestion for me?

**Comment by haixuan8192** [comment]
How did you solve this problem?

**Comment by ppanagiotis** [comment]
Any update on this? I have the same problem.
