### ISSUE TITLE
Coordinator datasources endpoint returns nonsensical `servers`

### ISSUE THREAD

**Issue by drcrallen** [apache/druid#5368]
`/druid/coordinator/v1/datasources/${DATASOURCE}/intervals/${INTERVAL}?full`

is supposed to return a `servers` field which lists the hosts which are serving that segment. But when the interval covers more than one segment granularity on our cluster the returned server list is way beyond what is actually hosting segments. When limiting the interval to even boundaries of the segment granularity (ex: only one hour) it seems to behave as expected.

**Comment by vvc11** [comment]
hi @drcrallen , I'd like to fix this issue but I'm unable to replicate it though. Can you please provide an example to help me understand better?
Thanks

**Comment by vvc11** [comment]
Hi @drcrallen , I tried to check the behaviour with the test cases that were written in DatasourceResourceTest. The returned result seems consistent with the expected one. Here's the [link](https://github.com/vvc11/druid/pull/1/commits/b35545e291d222c9f3db948eddfe286bbc79cb83) to the commit. Please let me know if anything's missing
Thanks

**Comment by drcrallen** [comment]
dang, its too bad it is not reproducible. I'd like to leave this open a bit if that's ok, just in case others encounter the problem as well.

**Comment by gianm** [comment]
Has anyone been able to reproduce this?
