### ISSUE TITLE
Async future handling needs a guava friendly way we can maintain.

### ISSUE THREAD

**Issue by drcrallen** [apache/druid#5415]
As per https://github.com/druid-io/druid/pull/5414#discussion_r170006127 , we need an abstraction that plays nice with Guava versions across a wide range, and ideally uses Java intrinsics whenever possible.

**Comment by leventov** [comment]
`java.util.concurrent.CompletableFuture` alone covers a lot, if not all, cases when Druid uses Guava's ListenableFutures and utilities.
