### ISSUE TITLE
Support retrying on failures for non-realtime ingestion

### ISSUE THREAD

**Issue by jihoonson** [apache/druid#5428]
An indexing task might fail due to various reasons, and one of them is node failures. If an indexing task fails due to node failures, it might be completed by reissuing the failed task on another node. In this case, it would be better if the overlord can resubmit failed tasks automatically without manual handling.

I'm thinking to introduce a new taskContext, called `retryCount`, to specify how many times each task should be retried on failures.

**Comment by nishantmonu51** [comment]
1. additional to task context, would be nice to support this via overlord config. would make configuration easy.
2. i am assuming after this change a transition of status from running -> failed -> running will be valid. Need to have way for user to know for a task with status failed, whether its going to be retried or not.

**Comment by jihoonson** [comment]
@nishantmonu51 thanks for your comment!

> 1. additional to task context, would be nice to support this via overlord config. would make configuration easy.

Good point. I'll add it.

> 2. i am assuming after this change a transition of status from running -> failed -> running will be valid. Need to have way for user to know for a task with status failed, whether its going to be retried or not.

I'm thinking to `retryCount` to taskStatus, so users can check how many times a task was failed before success via overlord's taskStatus API (`http://<OVERLORD_IP>:<port>/druid/indexer/v1/task/{taskId}/status`). Does it make sense?

> 3. IMO this is a useful as a generic feature for all task types, not only batch ingestion. E.g same retry concept can be applied to Merge/Append/Kill/Compaction tasks too.

Makes sense. I changed the title to `Support retrying on failures for non-realtime ingestion` because supervisors or tranquilities are responsible for retrying in realtime ingestion.

**Comment by gianm** [comment]
I this this is a good direction to go -- it's nicer for Druid to take on retrying rather than to push the burden to users. However we need to try to do it right, and the main thing there imo is ensuring idempotency.

It is possible for tasks to have side effects and yet still fail (for example: it publishes and then immediately crashes before it can do final acts like uploading its log files). This means when retrying we have to verify that tasks are idempotent. Otherwise - we will potentially load the same data twice. With Kafka based ingestion, we are OK because of the metadata check (verifying offsets when segments are published). With batch indexing, in overwrite mode we are OK too (since overwriting is idempotent). But in append mode, extra work is needed.

**Comment by jihoonson** [comment]
@gianm that's a good point. Maybe we need finer-granular task status tracking to avoid extra work.

**Comment by gianm** [comment]
@jihoonson I don’t worry too much about extra work, as long as the task does the correct thing. What I do really worry about is the possibilty of appending the same data twice due to retrying after some data had been published.

**Comment by jihoonson** [comment]
@gianm ah yeah, it's more important to make sure there is no duplicated work.

**Comment by nishantmonu51** [comment]
@jihoonson: Adding retryCount to the task status sounds good.

**Comment by nishantmonu51** [comment]
One way to achieve idempotency and avoid duplicate data could be to add a publisher field to the metadata storage when publishing segments.  

For tasks it can be the taskID, when the task is retried, the retry attempts can check whether there are any segments already published with the same task id or not. This has following assumptions though - 
* TaskID is same for each retry attempt. We might need to add a retryAttempt field to tasks table in metadata storage. 
* auto-retryable task always publishes segments in a single metadata transaction atomically.
