### ISSUE TITLE
Unbalanced segments loading

### ISSUE THREAD

**Issue by Llinjing** [apache/druid#5430]
Please see the picture of this link:
https://groups.google.com/forum/#!topic/druid-user/3xXiXceSVjo

For F1 tier, the first machine is double the utilization of other machines. This situation lasted for days . There is nothing wrong for Historical and coordinator log. Is this a bug?

**Comment by nishantmonu51** [comment]
can you check the configs of each node in this tier ? 
Does each node have same config for druid.server.maxSize

**Comment by Llinjing** [comment]
Yes, the config of druid.server.maxSize is same. I have already checked

**Comment by Llinjing** [comment]
![lx_clip1519715851492](https://user-images.githubusercontent.com/20414903/36767473-9b6e5e1c-1c75-11e8-9be4-2c9d88cd79f0.jpg)

I have no idea on this issue. I am not  sure is this cost function bug. (Https://github.com/druid-io/druid/pull/2972). Or , it was due to extreme dynamic configuration of the coordinator ??

 Do you have any good solution?

**Comment by Llinjing** [comment]
@leventov Do you know how to solve this problem? 
Is it because maxSegmentsToMove value is too small (what i set is 10), resulting in coordinator synchronization is too slow ？

**Comment by apollotonkosmo** [comment]
@leventov Did you mamage to sort this out? We have upgraded to 0.13 and we have one node that is filling up  and the other two that are emptying down.

**Comment by leventov** [comment]
I didn't study this problem.
