### ISSUE TITLE
Store lookups-cached-global data on disk for more reliable startup

### ISSUE THREAD

**Issue by gianm** [apache/druid#5518]
Since the changes to block startup on lookup load in 0.11.0 (which are good for consistency) we have a new problem: the lookups-cached-global extension may block startup for an excessively long time, or indefinitely, if an external service it queries is unavailable. This is particularly noticeable with JDBC lookups although it can happen with other types as well. It would be better if they stored the lookup data on disk and restored this on startup, rather than blocking waiting for an initial sync. Ideally, this location should be shared across all Druid JVMs running on the same machine, which would be super helpful for task peons.

This would be analogous to the global `druid.lookup.snapshotWorkingDir` config, although that one only snapshots lookup _config_ and not lookup _data_.

**Comment by dene14** [comment]
@gianm Is it possible to have lookup cache shared between subsequent ingestion tasks? I feel like no, because even if I use offHeap cache type, it generates cache file with dynamic name, for e.g.:
```
# ls -al /opt/apache-druid-0.14.0-incubating/var/tmp/druidMapDB*
-rw-r--r-- 1 root root  56623104 Apr 15 23:18 /opt/apache-druid-0.14.0-incubating/var/tmp/druidMapDB3576988999697240527org.apache.druid.server.lookup.namespace.cache.OffHeapNamespaceExtractionCacheManager
-rw-r--r-- 1 root root 363855872 Apr 15 23:18 /opt/apache-druid-0.14.0-incubating/var/tmp/druidMapDB3576988999697240527org.apache.druid.server.lookup.namespace.cache.OffHeapNamespaceExtractionCacheManager.p
-rw-r--r-- 1 root root  56623104 Apr 15 23:17 /opt/apache-druid-0.14.0-incubating/var/tmp/druidMapDB6315615901868519681org.apache.druid.server.lookup.namespace.cache.OffHeapNamespaceExtractionCacheManager
-rw-r--r-- 1 root root 364904448 Apr 15 23:17 /opt/apache-druid-0.14.0-incubating/var/tmp/druidMapDB6315615901868519681org.apache.druid.server.lookup.namespace.cache.OffHeapNamespaceExtractionCacheManager.p
```

I'm not sure if it deserves a separate issue, but if you have a workaround for this, feel free to share.
Thanks!

**Comment by dene14** [comment]
Also summon @jihoonson :)

**Comment by jihoonson** [comment]
Hi @dene14, you are correct. The lookup cache can't be shared between tasks. I don't think we have a workaround for this yet, but it sounds good to have.

**Comment by dene14** [comment]
@gianm @jihoonson any way to prevent it to be closed?
