### ISSUE TITLE
historical miscalculating remaining disk capacity - segment too large exception causing segments to not load

### ISSUE THREAD

**Issue by sasounda** [apache/druid#5577]
After seeing this error in Druid historical
```
Caused by: com.metamx.common.ISE: Segment[timeseries_dogstatsd_counter_2018-04-04T16:00:00.000Z_2018-04-04T17:00:00.000Z_2018-04-04T16:00:00.000Z_1528210995:152,770,889] too large for storage[/var/tmp/druid/indexCache:22,010].
```
, we notice that the historical node stops loading new segments from realtime and the realtime nodes starts accumulating segments.

Our `maxSize` settings goes like this and we had enough free disk space.
```
druid.server.maxSize=882159184076
druid.segmentCache.locations=[{"path":"/var/tmp/druid/indexCache","maxSize":882159184076}]
```

Restarting Druid historical fixes the issue. We suspect that there is something going wrong with how Druid calculates the available size i.e., `22,010`.

**Comment by jon-wei** [comment]
This is the code that handles that space check:

```
    if (freeSpaceToKeep > 0) {
      long currFreeSpace = path.getFreeSpace();
      if ((freeSpaceToKeep + segment.getSize()) < currFreeSpace) {
        log.warn(
            "Segment[%s:%,d] too large for storage[%s:%,d] to maintain suggested freeSpace[%d], current freeSpace is [%d].",
            segment.getIdentifier(),
            segment.getSize(),
            getPath(),
            available(),
            freeSpaceToKeep,
            currFreeSpace
        );
        return false;
      }
    }
```

Druid is calling Java's standard File.getFreeSpace() to determine `currFreeSpace`: https://docs.oracle.com/javase/8/docs/api/java/io/File.html#getFreeSpace--

Maybe something strange is happening with the partition where `/var/tmp/druid/indexCache` resides when you see that error?

**Comment by sasounda** [comment]
@gianm just wanted to check if someone is looking into this ?

**Comment by jkukul** [comment]
@sasounda I think that `22,010` is not the available size, but rather the size of the segment that the realtime node is trying to hand-off. 

> Our maxSize settings goes like this and we had enough free disk space.

So I guess you also made sure that your disk usage isn't bigger than `882159184076` bytes?

**Comment by sasounda** [comment]
@jkukul did you mean the disk usage for the server or the disk usage for `/var/tmp/druid/indexCache` ?

**Comment by jkukul** [comment]
@sasounda I meant the disk usage for `/var/tmp/druid/indexCache`, thanks.

**Comment by egor-ryashin** [comment]
I found multiple entries in Historical logs:
>i.d.s.l.SegmentLoaderLocalCacheManager - Segment [*] is different than expected size. Expected [*] found [*]

I summed the difference for one hour it showed that segments occupied ~50MB more than expected which can effectively confuse Coordinator working with sizes from the segment metadata.

I propose to add a dynamic configuration parameter to Coordinator named `segmentCacheReserve` (ie `segmentCacheReserve=50` means 50mb of extra space) which tells Coordinator how much space should be left available at any time on a Historical node.

**Comment by dsboo** [comment]
its also happen to me.
my remain disk size 3tb and i configured maxSize below.
> druid.server.maxSize=2000000000000

in my case, when i use disk over 1tb, this error occured.

so i reduced druid.server.maxSize 2000000000000 to 882159184076 and scale out historical node.

finally, error is disappeared.

so i think i can use disk under (full disk size - druid.server.maxSize).

is it right?

thanks.

**Comment by egor-ryashin** [comment]
I can confirm that this is still present in Druid 0.21.

I see logs like:
```
[WARN ] 2021-05-25 14:39:20.718 [SimpleDataSegmentChangeHandler-2] StorageLocation - Segment[<segment_name>:260,453,366] too large for storage/opt/druid/var/segmentCache:7,621,518. Check your druid.segmentCache.locations maxSize param
``` 
To eliminate confusion I can confirm that 7,621,518 number is what Druid thinks about available space in storage.
You can check it here `org/apache/druid/segment/loading/StorageLocation.java:155`
Meanwhile there are at least several GBs available:
```
df -h
...
Avail Use% Mounted on
17G  94% /opt/druid/var
```
Metrics say the same (the correct used size), actually, metrics report from a different in-memory variable, you can find it here `org/apache/druid/server/metrics/HistoricalMetricsMonitor.java:88`

Right now I cannot find a bug in source code, I can only speculate that some exception is uncaught and the available size is not decreased properly, but looking through logs doesn't show there were uncaught exceptions.

I propose to log or send as metrics this variable `org.apache.druid.segment.loading.StorageLocation#availableSizeBytes` so we can track when the issue starts taking place, other debugging ideas are welcome.
