### ISSUE TITLE
Druid Helm Chart

### ISSUE THREAD

**Issue by drcrallen** [apache/druid#5582]
[Helm](https://github.com/kubernetes/helm) is an easy to use deployment system for running groups of services on [kubernetes](https://kubernetes.io/) (k8s). This ask is that a Helm Chart (the thing that defines groups of apps) be developed for easy Druid deployment.

The thing which k8s is *not* terribly good at is a common historical setup where two tiers of historical servers are replicas of each other. I don't know how to get Stateful Sets setup in k8s to accommodate such a setup. But other nodes with no local state like brokers, overlords, coordinators, even routers should be pretty easy to setup charts for.

Easy: 

- [X] Broker
- [X] Overlord
- [X] Coordinator
- [X] Router
- [X] Zookeeper

Hard:

- [ ] Historical
- [ ] Middle manager

**Comment by josephglanville** [comment]
Regarding the "common setup" ff you wanted to create 2 distinct tiers of historical servers you would most likely create 2 different StatefulSets, i.e `statefulset/historical-hot`, `statefulset/historical-cold` or something. Because discovery is done via Zookeeper rather than k8s labels etc no real care has to be taken when doing this, it should "just work".

We are running Druid on k8s (without Helm) so I would be interested in contributing to this effort but don't have the bandwidth to lead it right now.

**Comment by drcrallen** [comment]
@josephglanville the problem with 2 stateful sets is that one doesn't know what the other is doing. So I'm not sure there's a way to say "don't do any operations on this set while the other doesn't meet stateful requirements". Its kind of a... stateful set of stateful sets

**Comment by josephglanville** [comment]
Yeah such a feature would need to be in Helm/Tiller most likely. There is also the problem that `PodDisruptionBudget` can't respect cross statefulset constrains which means that automated cluster operations could prove problematic.

**Comment by andrusha** [comment]
It might be worth looking into CRD and Operators:
https://kubernetes.io/docs/tasks/access-kubernetes-api/extend-api-custom-resource-definitions/
https://coreos.com/blog/introducing-operators.html
https://github.com/coreos/etcd-operator

They allow you to instrument your deployments with custom code.

**Comment by tekn0ir** [comment]
Also consider adding support for k8s as full resource manager, i.e. replacing zookeeper for service discovery etc. It would add neat features like restart strategies for example.

**Comment by townsendbt** [comment]
Hi. I'm wondering if this issue is being considered any time soon?
Thanks, Brian.

**Comment by townsendbt** [comment]
Hi. I'm wondering if this issue is being considered any time soon?
Thanks, Brian.

**Comment by maver1ck** [comment]
@andrusha Going into operator will make this task much more difficult. Simple helm chart will be the best starting point.

**Comment by maver1ck** [comment]
I'm working on helm chart for Druid... Probably sth will be ready next week.

**Comment by maver1ck** [comment]
https://github.com/helm/charts/pull/9314

**Comment by rahulsingh303** [comment]
Checkout this one https://github.com/rahulsingh303/druid-helm . It works for me , tested on both minikube and kubernetes cluster.

**Comment by maver1ck** [comment]
@rahulsingh303 I do a quick look at your chart but I think my PR is superior (i.e. it's using StatefulSets for historical and middlemanagers) and follows the rules of creating helm chart.

**Comment by rahulsingh303** [comment]
@maver1ck I was trained at Google and learnt that stateful sets are not needed unless you really need it for case where you want to bind your pv to a particular server (may be because you have a license or some other business reason) and hence they recommended not to use as no one uses in 99% of cases . Also my friend this is a community and not about who is superior but rather who can contribute and make a better reusable artifact :) .

**Comment by TerryTab** [comment]
incubator druid helm charts have no router configurations, how do I add router to the druid cluster?

**Comment by rhamonantunes** [comment]
@StardustXiaoT Did you manage to do that? I have the same problem!

**Comment by maver1ck** [comment]
Working on merge PR to druid chart.

**Comment by kyprifog** [comment]
@maver1ck whats the status of this?

**Comment by maver1ck** [comment]
https://github.com/helm/charts/tree/master/incubator/druid/templates/router

There is router configuration in the chart.

**Comment by sannour** [comment]
@maver1ck Please share the new home for your druid chart, current one was archived 2 days ago  [#24250](https://github.com/helm/charts/commit/ebe628b5adb8c5410e844a12650fb829dcfdd594)

**Comment by maver1ck** [comment]
I'm curious if this repo can be official one ?

**Comment by sannour** [comment]
> I'm curious if this repo can be official one ?

I hope so.

**Comment by kyprifog** [comment]
I ran the helm chart and it seemed to work fine.  The deprecation is mostly related to a long term initiative to migrate from helm 2 to 3, if you notice all the helm charts in this repo are now "deprecated", which is kind of annoying.  So the maintainers would need to migrate the chart from 2 to 3, is there an issue for this already?

**Comment by himanshug** [comment]
Probably unrelated but relevant based on few comments (https://github.com/apache/druid/issues/5582#issuecomment-388367295 and  https://github.com/apache/druid/issues/5582#issuecomment-389931364) ...

there does exist a druid operator https://github.com/druid-io/druid-operator , you can learn more about it in https://www.youtube.com/watch?v=UqPrttXRBDg 

we are very close to using k8s for discovery and leader election and ability to run Druid cluster without zookeeper  , see https://github.com/apache/druid/pull/10544
