### ISSUE TITLE
Middle Managers have their tasks killed if they restart with a different Port

### ISSUE THREAD

**Issue by drcrallen** [apache/druid#5697]
`io.druid.indexing.overlord.RemoteTaskRunner#removeWorker` keys the middle managers (workers) by their host and port. If a middle manager comes back, but has a different host or port (i.e. marathon assigning a random port on launch) then the cleanup task won't be properly stopped, and the task will be killed once `taskCleanupTimeout` has elapsed

**Comment by jihoonson** [comment]
Hmm, would you elaborate more on what you think the bug is? Looks like the middleManager of different port should be regarded as a different one.

**Comment by jihoonson** [comment]
Hi @drcrallen, do you still think this is a bug? And should we fix this in 0.13.0?
