### ISSUE TITLE
Race Condition on Lookup Status Endpoint

### ISSUE THREAD

**Issue by QubitPi** [apache/druid#5707]
After we send a POST request to update a registered lookup, we will get unpredicted result from GET endpoint on lookup status. This could happen when the GET request hits the coordinator too early OR updating the lookup on historicals involves downloading large amount of data from a remote location. 

A suggested solution could be blocking GET request before update finishes.

I can work to solve this if the is approved to be an issue.

**Comment by leventov** [comment]
This might be essentially the same problem as fixed in https://github.com/druid-io/druid/pull/4758, just on lookup update rather than initial loading.
