### ISSUE TITLE
Systemd Service Unit Files

### ISSUE THREAD

**Issue by doc987** [apache/druid#5715]
Are there systemd unit files for running Druid as a service?  The documentation suggests starting several terminal windows, and then running commands in each to start various Druid processes.  What method is recommended for managing Druid in a production environment?

**Comment by schoren** [comment]
Yes, I'd also like to know this!

**Comment by SamuelMarks** [comment]
Found a couple:
https://github.com/MrAlias/druid/tree/master/templates
https://github.com/redBorder/redborder-druid/tree/master/resources/systemd
