### ISSUE TITLE
Support regex filter to filter input objects for StaticS3Firehose

### ISSUE THREAD

**Issue by jihoonson** [apache/druid#5772]
It would be nice if the regex filter is supported for StaticS3Firehose like for [LocalFirehose](http://druid.io/docs/latest/ingestion/firehose.html#localfirehose).

**Comment by rahmantasnim** [comment]
I'd be down to work on this, but I want to check that you're okay with a potential performance detriment. Unfortunately, there's no native support for passing a regex filter to the s3 api. Any application of a regex filter on the objects would have to be done in the druid code. This should be fine except when there are a ton of objects under the specified prefix. If that sounds okay, I can get started on it.

**Comment by didip** [comment]
@gianm @jihoonson I am interested in building this feature. I am almost done doing it on the company's internal fork.
