### ISSUE TITLE
How to parse UTF-8 encoded Chinese data in druid?

### ISSUE THREAD

**Issue by helenykwang** [apache/druid#5781]
I encountered a problem that displayed data is garbled when I ingest hadoop json files(UTF-8). It seems that druid parsed the data  into GBK code. How can I fix the problem?

**Comment by gianm** [comment]
Druid supports UTF-8 encoding, so I am surprised it didn't work. In fact I have seen it ingest Chinese characters properly before, so maybe there is some decoding problem. What was the data format?

**Comment by helenykwang** [comment]
@gianm  Data is encoded in UTF8. Here it's one row --> {"timestamp":"2018-03-11 00:00:10","guid":"asd1","query":"海伦王"}

**Comment by helenykwang** [comment]
@gianm Data is encoded in UTF8. Here it's one row --> {"timestamp":"2018-03-11 00:00:10","guid":"asd1","query":"海伦王"} 

But, I got output like what the picture shows 

![gbk](https://user-images.githubusercontent.com/26139575/40093725-0f309fb0-58f6-11e8-92b8-0a82035f7b63.png)
