### ISSUE TITLE
When use JDBC PreparedStatement then get errors like: 'DefaultQueryMetrics must not be modified ... '

### ISSUE THREAD

**Issue by davidkeeper** [apache/druid#5795]
When I use JDBC to access Druid,  using 'PreparedStatement' get error response, but using 'Statement' get correct answer.

A simple test sql like below （notice  limit must > 100 will get error, otherwise not.）:
   String execSql = "select time_id, res_ins_id from res_xxx where order by __time desc limit 101";

**When using PreparedStatement it get errors like :** 
	Caused by: java.lang.IllegalStateException: DefaultQueryMetrics must not be modified from multiple threads. If it is needed to gather dimension or metric information from multiple threads or from an async thread, this information should explicitly be passed between threads (e. g. using Futures), or this DefaultQueryMetrics's ownerThread should be reassigned explicitly

```
        PreparedStatement stat = connection.prepareStatement(execSql);
        final ResultSet rs = stat.executeQuery();
        int count = 0;
        while (rs.next())
        {
            count++;
        }
```

**When using Statement it get correct :** 
```
        Statement stat = connection.createStatement();
        final ResultSet rs = stat.executeQuery(execSql);
        int count = 0;
        while (rs.next())
        {
            count++;
        }
```

Expect  for your reply, thanks~~

**Comment by jon-wei** [comment]
@davidkeeper What version of Druid are you running?

**Comment by davidkeeper** [comment]
@jon-wei  we use the latest version: v0.12.0,   and avatica version is :  1.10.0

**Comment by huhusuperma** [comment]
@jon-wei pls mention that the sql is ordered by __time. When i delete "order by __time", the right responses are returned, so i think it may contain a bug about using "ordered by __time" in druid sql of JDBC.

**Comment by davidkeeper** [comment]
@huhusuperma    Here we use time_id as timestamp.  and if remove order by __time instead of 'group by time_id, res_ins_id order by time_id desc'  that's OK, but inner query is change to groupby query, cause low performance.
