### ISSUE TITLE
Regarding expression in Aggregators

### ISSUE THREAD

**Issue by fanwu72** [apache/druid#5806]
Hi team,
Just a quick question here.
I saw the "expression" parameter is added into some aggregators from source code.  I tested it slightly and it works. 
But I don't' find the documentations about it. Is it ready for production use now?

Best regards,
Ryan

**Comment by Dylan1312** [comment]
Hey @fanwu72 

I can't speak for the original authors but the expressions and virtual columns are used in the queries generated by SQL so it seems fair to follow the same guidelines that they're an experimental feature subject to change.

There's an open issue to document them here: https://github.com/druid-io/druid/issues/3634

**Comment by fanwu72** [comment]
@Dylan1312 Thanks for the explanation.
