### ISSUE TITLE
AggregatorFactory.getComparator() must be null-safe

### ISSUE THREAD

**Issue by leventov** [apache/druid#5812]
1) Specify this in the Javadoc of this method.
2) Fix for all implementations in the repository. It's currently not null-safe at least in `DoublesSketchAggregatorFactory`.

@AlexanderSaydakov

**Comment by jihoonson** [comment]
> it might be much better to handle nullability centralized, not to require for each implementer of AggregatorFactory to remember about nullability. E. g. wrap with Comparator.nullsFirst(aggFactory.getComparator()) at the usage sites of getComparator().

I like this idea. @nishantmonu51 any thoughts?

**Comment by gianm** [comment]
Does this need to be a release blocker for 0.14.0?
