### ISSUE TITLE
Make sure that the requested project name does not already exist

### ISSUE THREAD

**Issue by drcrallen** [apache/druid#5823]
http://incubator.apache.org/projects/druid.html

Make sure that the requested project name does not already exist. [Please follow the guide to ensure a suitable project/product name.](http://www.apache.org/foundation/marks/naming.html)

**Comment by a2l007** [comment]
JIRA ticket created: https://issues.apache.org/jira/browse/PODLINGNAMESEARCH-142
@drcrallen Please feel free to assign this issue to me.

**Comment by drcrallen** [comment]
Hmm, @a2l007 I can't seem to assign you without modifying your group membership. Let me see if I can change things around to get the right permissions.
