### ISSUE TITLE
Check and make sure that the papers that transfer rights to the ASF been received. It is only necessary to transfer rights for the package, the core code, and any new code produced by the project.

### ISSUE THREAD

**Issue by drcrallen** [apache/druid#5834]
http://incubator.apache.org/projects/druid.html

**Comment by drcrallen** [comment]
Software grant document receipt confirmed by mattsicker@apache.org on May 7th. Will double check that there are no other items needed.

**Comment by vogievetsky** [comment]
Is this pending on other items?
