### ISSUE TITLE
Check and make sure that the files that have been donated have been updated to reflect the new ASF copyright.

### ISSUE THREAD

**Issue by drcrallen** [apache/druid#5835]
http://incubator.apache.org/projects/druid.html

**Comment by gianm** [comment]
#5796 updated almost all source files. There are a small number that were not updated: https://github.com/apache/incubator-druid/pull/5976#issuecomment-403188239. We can close this issue when those are figured out.

Files with a non-standard header (by Druid standards):

- https://github.com/apache/incubator-druid/blob/master/extendedset/src/main/java/io/druid/extendedset/intset/AbstractIntSet.java
- https://github.com/apache/incubator-druid/blob/master/extendedset/src/main/java/io/druid/extendedset/intset/ConciseSet.java
- https://github.com/apache/incubator-druid/blob/master/extendedset/src/main/java/io/druid/extendedset/intset/IntSet.java

The license on the these three files seems ok (it's Apache 2.0) and also we already call this copying out in the NOTICE file. So they seem ok to me but I'm just calling them out to double-check.

We also have two files with no license header:

- https://github.com/apache/incubator-druid/blob/master/extendedset/src/main/java/io/druid/extendedset/intset/ConciseSetUtils.java
- https://github.com/apache/incubator-druid/blob/master/extendedset/src/main/java/io/druid/extendedset/utilities/IntList.java

In that issue, @fjy said:

> ConciseSetUtils is from the original ConciseSet library under the Apache license. The license header is missing for the file but it should be the same as the rest of the files under the ConciseSet library (Apache v2).

And:

> IntList is from the same place

I can't find the original source of the Concise library. The paper is at https://arxiv.org/pdf/1004.0403.pdf, which links to source at http://concise.svn.sourceforge.net/viewvc/concise?view=rev&revision=1; however, that link is dead.

I did some digging and found this commit: https://github.com/metamx/extendedset/commit/02366f18385b3e082866e5bbbd38357ceee13d79#diff-97bd266eb5d2e8b0e7a38a658921356d. It looks like these files were created in a refactor with code largely taken from ConciseSet (which is Apache licensed). So, that's good.

What's the best way to move forward here? Could we leave the first three files as-is, and add identical, nonstandard headers to the other two files describing where they came from and that they are Apache licensed?
