### ISSUE TITLE
Combining Coordinator and Overlord into one service does not fully work

### ISSUE THREAD

**Issue by TwojaWina** [apache/druid#5910]
**Druid version** : 0.12.1-iap3

We followed the configuration at http://druid.io/docs/latest/configuration/coordinator.html to enable feature `druid.coordinator.asOverlord.enabled=true` . 

However after restarting the Coordinator service, the webUI on http://coordinator-host:port/console.html could not load worker list. We got 500 server error message instead. See screenshot attached

<img width="1536" alt="screen shot 2018-06-27 at 10 51 00 am" src="https://user-images.githubusercontent.com/9752231/41991536-9585b8fa-79fa-11e8-9cd9-31dd590ddcf6.png">

**configuration :** 
- on all nodes -> common.runtime.properties: 
druid.selectors.indexing.serviceName=druid/overlord

- on coordinator node -> runtime.properties: 
druid.coordinator.asOverlord.enabled=true 
druid.coordinator.asOverlord.overlordService=druid/overlord

**Comment by gianm** [comment]
@TwojaWina was there an exception stack trace in the coordinator log?

**Comment by guozhenhong** [comment]
@gianm try to add more indexer configuration in runtime.properties of  coordinator:

druid.indexer.queue.startDelay=PT30S
druid.indexer.runner.type=remote
druid.indexer.storage.type=metadata
