### ISSUE TITLE
API to soft-delete segments by interval

### ISSUE THREAD

**Issue by gianm** [apache/druid#5940]
We have an API to kill (hard delete) segments by interval, but we should have one for soft-delete too. IMO it makes sense to add a `kill` flag to the `"/{dataSourceName}/intervals/{interval}"` API. Although, it may be tough to make this consistent with the whole-datasource API while maintaining backwards compatibility. Some new, friendlier APIs may be called for.

**Comment by vogievetsky** [comment]
this is fixed by https://github.com/apache/incubator-druid/pull/7494 right?
