### ISSUE TITLE
Automatic cleanup druid_tasks table of metastore

### ISSUE THREAD

**Issue by jihoonson** [apache/druid#5994]
`druid_tasks` table stores all submitted tasks to overlords. Since this is never cleaned up automatically, it always grows as more tasks are submitted until people tidy up it manually. 

So, it makes sense to periodically delete old entries from that table as the coordinator does for old segments. I think it also makes sense to delete old entries if `druid.indexer.logs.kill.enabled` option is set because deleting task logs usually mean you don't want to check that task anymore.

**Comment by jihoonson** [comment]
Related to https://github.com/apache/incubator-druid/issues/5979#issuecomment-404050959.

**Comment by xvrl** [comment]
@jihoonson @gianm wasn't this fixed by https://github.com/apache/druid/pull/6592 ?

**Comment by gianm** [comment]
Certainly looks like it.

**Comment by maytasm** [comment]
I have recently tested this and `druid.indexer.logs.kill` does remove both the log file and the task metadata.

**Comment by xvrl** [comment]
ok, I'll close it then. We can reopen if we missed anything
