### ISSUE TITLE
Automatically Determine Ingestion Schema

### ISSUE THREAD

**Issue by doc987** [apache/druid#6004]
Druid should be able to automatically determine the schema to use when the schema is implied by the data received.

Suppose data is being provided by a collection agent such as Collectd or Telegraf.  The specific fields that will be present may not be know ahead of time, will depend on which metrics are collected by those agents, and could change across software versions.  However, Druid should still be able to locate the timestamp, dimensions, and metrics.

For example, the Telegraf output formats are documented here: https://github.com/influxdata/telegraf/blob/master/docs/DATA_FORMATS_OUTPUT.md.  Due to the structure, InfluxDB does not need to be pre-provided with a schema in order to load the data.

The Collectd ouput format documentation is less clear.  Format options include PUTVAL, JSON, and Graphite.  https://collectd.org/wiki/index.php/Table_of_Plugins

Is there a way to ingest this kind of data without trying to determine every possible field that could be collected for every possible unit that was monitored, and then writing a corrsponding ingestion schema?  The exercise would also have to be repeated every time there was a software version change.

**Comment by RestfulBlue** [comment]
Currently you can leave dimensions list empty, then every column, which not specified as metrics, will be indexed as string.

Then you can convert every metric to some legacy format, where you have only one metric field , for example "value" with aggregation longSum. After that you can convert every record to that format
For example if u have record like this:
{ timestamp : "2131249124" , "hostname":"somehost.com" , "cpu": 23 , "memory": 45 } 
when you can convert it to format like this:
{ timestamp : "2131249124" , "hostname":"somehost.com" , "metric":"cpu", "value": 23 } 
{ timestamp : "2131249124" , "hostname":"somehost.com" , "metric":"memory", "value" : 45 }

**Comment by doc987** [comment]
That gets part of the way there, though the data provided by Collectd and Telegraf are formatted somewhat differently.  That means that either the an output transform would be needed for those programs, or an input transform for Druid.

The documentation page for the [Collectd JSON format](https://collectd.org/wiki/index.php/JSON) is currently down.  The Telegraf JSON format documentation is [here](https://github.com/influxdata/telegraf/blob/master/docs/DATA_FORMATS_OUTPUT.md).

Some sample code is shown below to convert JSON from Telegraf to JSON for Druid.  Due to the flattening of the JSON, there are some tag names (metric, name, timestamp, and value) that could result in name collisions, and are therefore dropped (if they exist) in the code below.  Another possibility would be to try and determine an alternative name.

Any opinions on a good approach to take?  For example:
1. Should Druid be able to read the Telegraf JSON format directly?  Since it's a rather generic format, it could also be used by other applications.
2. Should the Telegraf format be flattened to the JSON format that Druid already reads?  If so, should the code be part of Druid, or separate?

The Druid [documentation](http://druid.io/docs/0.12.1/development/modules.html) mentions that ```io.druid.data.input.impl.InputRowParser``` should be extended for an input parser.

```java
import java.util.*;

import com.fasterxml.jackson.core.JsonProcessingException;
import com.fasterxml.jackson.databind.ObjectMapper;
import com.fasterxml.jackson.databind.JsonNode;
import com.fasterxml.jackson.databind.node.ObjectNode;

//given String json from Telegraf, it might be converted to JSON input for Druid as follows
Telegraf_Flatten tf = new Telegraf_Flatten();
JsonNode node = tf.json_string_to_node(json);
json = tf.flatten(node);

class Telegraf_Flatten {
   
   public JsonNode json_string_to_node(String json){
      ObjectMapper mapper = new ObjectMapper();
      JsonNode node = null;
      try{
         node = mapper.readTree(json);
      }catch(java.io.IOException e){
         e.printStackTrace();
      }
      return node;
   }
   
   public String flatten(JsonNode node){
      String json = null;
      JsonNode metrics = node.path("metrics");
      if(metrics.isMissingNode()) json = flatten_single(node);
      else json = this.flatten_batch(metrics);
      return json;
   }
   
   public String flatten_batch(JsonNode metrics){
      String json = "";
      for(JsonNode item : metrics){
         json += this.flatten_single(item);
      }
      return json;
   }
   
   public String flatten_single(JsonNode root){
      
      //extract nested json
      JsonNode fields = root.get("fields");
      JsonNode tags   = root.path("tags");
      
      ((ObjectNode) root).remove("fields");
      
      //flatten tags
      if(!tags.isMissingNode()){
         ((ObjectNode) root).remove("tags");
         Iterator<Map.Entry<String,JsonNode>> iter = tags.fields();
         while(iter.hasNext()){
            Map.Entry<String,JsonNode> entry = iter.next();
            if(root.path(entry.getKey()).isMissingNode()){
               ((ObjectNode) root).set(entry.getKey(),entry.getValue());
            }
         }
      }
      
      //split into one JsonNode object per field
      Iterator<Map.Entry<String,JsonNode>> iter = fields.fields();
      int metrics = fields.size();
      JsonNode[] row = new JsonNode[metrics];
      for(int i=0;iter.hasNext();i++){
         Map.Entry<String,JsonNode> entry = iter.next();
         row[i] = root.deepCopy();
         ((ObjectNode) row[i]).put("metric",entry.getKey());
         ((ObjectNode) row[i]).set("value",entry.getValue());
      }
      
      //convert JsonNode(s) to JSON String
      ObjectMapper mapper = new ObjectMapper();
      String json = "";
      for(int i=0;i<metrics;i++){
         try{
            json += mapper.writeValueAsString(row[i]) + "\n";
         }catch(JsonProcessingException e){
            e.printStackTrace();
         }
      }
      
      return json;
   }
   
}
```

**Comment by doc987** [comment]
Isn't the code above acting as a row parser?  That is, transforming the input JSON format that Telegraf produces into the JSON format the Druid recognizes?

**Comment by josephglanville** [comment]
@doc987 InputRowParsers are actually specific code that is loaded as a Druid extension so rather than running externally of Druid and transforming the data into a format Druid already knows how to parse (like JSON) they can read the format directly and turn it into Druid's internal "InputRow" representation directly. This obviates the need for a configured schema in cases where the message contains the schema itself and there is a logic mapping of the source format to dimensions.

The important part of the picture is that dimensionSpec/metricsSpec in the provided ingestion spec doesn't need to be respected by your InputRowParser, the segment indexing code only cares about values returned from the parser itself which encode this information along with the row contents itself.
See the constructor for MapBasedInputRow for clarity.

**Comment by doc987** [comment]
Okay, so how does one make an InputRowParser and InputRow?  Does an InputRow look something like the code shown below?

```java
import java.util.*;

import com.fasterxml.jackson.core.JsonProcessingException;
import com.fasterxml.jackson.databind.ObjectMapper;
import com.fasterxml.jackson.databind.JsonNode;
import com.fasterxml.jackson.databind.node.ObjectNode;

import org.joda.time.DateTime;


class Telegraf_JSON_InputRow {
   
   private JsonNode root;
   private int time_factor = 1000; //convert input from seconds to milliseconds
   
   public Telegraf_JSON_InputRow(String json){
      this.init(json);
   }
   
   public void init(String json){
      this.root = this.json_string_to_node(json);
      this.time_factor = 1000; //different factors?
   }
   
   public JsonNode json_string_to_node(String json){
      ObjectMapper mapper = new ObjectMapper();
      JsonNode node = null;
      try{
         node = mapper.readTree(json);
      }catch(java.io.IOException e){
         e.printStackTrace();
      }
      return node;
   }
   
   long getTimestampFromEpoch(){
      return this.root.path("timestamp").longValue() * this.time_factor;
   }
   
   DateTime getTimestamp(){
      return new DateTime( this.root.path("timestamp").longValue() * this.time_factor );
   }
   
   List<String> getDimension(String dimension){
      return Arrays.asList( this.root.path("tags").path(dimension).asText() );
   }
   
   List<String> getDimensions(){
      List<String> ret = new ArrayList<String>();
      JsonNode tags = this.root.path("tags");
      if(!tags.isMissingNode()){
         Iterator<Map.Entry<String,JsonNode>> iter = tags.fields();
         while(iter.hasNext()){
            Map.Entry<String,JsonNode> entry = iter.next();
            ret.add(entry.getKey());
         }
      }
      return ret;
   }
   
   Object getRaw(String dimension){
      return new Object(); //what is this supposed to return?
   }
   
   Number getMetric(String dimension){
      return this.root.path("fields").path(dimension).numberValue();
   }
   
}
```

**Comment by richiesgr** [comment]
Hello 
@doc987 have you find a solution I would like to do exactly the same as you do 
getting telegraf  JSON output directly parse into Druid 
Any help ?
Thanks

**Comment by doc987** [comment]
Nope.  I didn't receive a response to my previous comment, and the documentation states that an input parser can be added by extending io.druid.data.input.impl.InputRowParser, but I don't see anywhere where it states how to do that.  If someone has already made, or knows how to make, a Telegraf input parser, then perhaps they could share.
