### ISSUE TITLE
Logging of invalid queries

### ISSUE THREAD

**Issue by erankor** [apache/druid#6017]
Hi all,

When Druid gets an invalid query, is there a way to see the query that was submitted?
I don't see the query body in the broker log - I only see the exception (I'm using the default log4j config, that has 'info' severity). And also - it seems that invalid queries are not logged to the request logger (druid.request.logging).
The motivation here is that I have a monitor on the Druid logs, so I know when an invalid query is somehow sent. But when it happens, I don't know what query it was... (the query can come from many servers)

Thanks!

Eran

**Comment by vogievetsky** [comment]
Hi Eran,

Right now there is only the ability to enable query logging on mass (for all queries).
I think this would be a great option to have.

Best regards,
Vadim

**Comment by gianm** [comment]
Sounds like a good idea -- the main challenge is probably that right now, the request logger expects to get a valid Query object, but we could add a method that accepts invalid queries as byte arrays or something like that.

**Comment by shivtools** [comment]
@gianm Could you please point me to the class that has the request logging logic?

**Comment by shivtools** [comment]
Hey @gianm, I wanted to take up this ticket and would appreciate if you could provide a little more insight into the following questions: 

1. When you refer to adding a new method that accepts invalid queries as byte arrays, I'm assuming that you're referring to this [method](https://github.com/apache/incubator-druid/blob/7a09cde4de1953eee75c5033e863cfde8f94d6c1/server/src/main/java/org/apache/druid/server/QueryLifecycle.java#L328-L334)?
2. Would we also have to modify the [Query](https://github.com/apache/incubator-druid/blob/master/processing/src/main/java/org/apache/druid/query/Query.java) object such that it can store information about the query string? I guess I'm trying to understand how to get to the bytes of the query that you refer to in your comment.

**Comment by erankor** [comment]
Ping. Would be great to have this

**Comment by sbespalov** [comment]
@erankor could please clarify the relevance and requirements for this task?
Currently with `druid.request.logging.type=file` invalid queries seems logged.
Request:
```
curl -i -X POST \
   -H "Content-Type:application/json" \
   -d \
'{"query":"invalid query","resultFormat":"array","header":true}' \
 'http://localhost:8888/druid/v2/sql'
```
Log:
```
2019-11-13T13:55:15.166Z        127.0.0.1               {"sqlQuery/time":1611,"sqlQuery/bytes":-1,"success":false,"context":{"sqlQueryId":"72bcc547-9fd4-4704-b61f-bb9673e39645","nativeQueryIds":"[]"},"identity":"allowAll","exception":"org.apache.calcite.sql.parser.SqlParseException: Non-query expression encountered in illegal context"} {"query":"invalid query","context":{"sqlQueryId":"72bcc547-9fd4-4704-b61f-bb9673e39645","nativeQueryIds":"[]"}}
```

Or maybe you mean invalid request body? 
Request:
```
curl -i -X POST \
   -H "Content-Type:application/json" \
   -d \
'invalid body' \
 'http://localhost:8888/druid/v2/sql'
```
In this case there is only exception in broker logs and no logged query.

**Comment by sbespalov** [comment]
One more case possible with invalid json body:
```
curl -i -X POST \
   -H "Content-Type:application/json" \
   -d \
'{
  "foo":"bar"
}' \
 'http://localhost:8888/druid/v2/sql'
```
In this case there is no logs at all (neither broker nor request), just 500 response with error message in body:
```
{"error":"Instantiation of [simple type, class org.apache.druid.sql.http.SqlQuery] value failed: query"}
```

**Comment by erankor** [comment]
@sbespalov, in the Druid version we are currently using (0.10.0), the sample bad query you pasted is not logged -
```
$ curl -i -X POST -H "Content-Type:application/json" -d '{"query":"invalid query","resultFormat":"array","header":true}' 'http://localhost:8082/druid/v2/'
HTTP/1.1 500 Internal Server Error
Date: Tue, 19 Nov 2019 10:11:28 GMT
Content-Type: application/json
Content-Length: 357
Server: Jetty(9.3.16.v20170120)

{"error":"Unknown exception","errorMessage":"Unexpected token (END_OBJECT), expected FIELD_NAME: missing property 'queryType' that is to contain type id  (for class io.druid.query.Query)\n at [Source: HttpInputOverHTTP@2b261ee9[c=62,q=1,[0]=EOF,s=STREAM]; line: 1, column: 62]","errorClass":"com.fasterxml.jackson.databind.JsonMappingException","host":null}

$ grep -i invalid 2019-11-19.log
$ 
```
So I guess there was progress on this since I opened this issue, which is great!

I think that ideally all queries should be logged (=the raw query body, since it may not parse at all), but cases in which the query body is not a valid JSON are IMHO of lesser importance. I'm saying this because I assume most people are building the queries using some JSON library, which makes the probability of invalid JSON very low.
Most errors are probably queries that are a valid JSON, but make no sense to Druid, for example, a topN query without `threshold`, or a topN query referencing a metric that is not listed in the aggregations etc.
