### ISSUE TITLE
Broker sends sequential requests to the historical for union queries

### ISSUE THREAD

**Issue by a2l007** [apache/druid#6057]
Analyzing groupBy queries based on Union datasources, we have seen that for a given query if a historical has segments for the multiple datasources part of this query, the broker generates multiple requests to this historical, but in a serial manner.
For example, running the following union query:

```
{
  "queryType": "groupBy",
  "dataSource": {
    "type": "union",
    "dataSources": [
      {
        "type": "table",
        "name": "tableA"
      },
      {
        "type": "table",
        "name": "tableB"
      },
      {
        "type": "table",
        "name": "tableC"
      }
    ]
  },
  "intervals": {
    "type": "LegacySegmentSpec",
    "intervals": [
      "2018-07-23T00:00:00.000Z\/2018-07-24T00:00:00.000Z"
    ]
  },
  "virtualColumns": [
    
  ],
  "filter": null,
  "granularity": "DAY",
  "dimensions": [
    {
      "type": "default",
      "dimension": "acc_id"
    }
  ],
  "aggregations": [
    {
      "fieldName": "clicks",
      "name": "clicks",
      "type": "longSum"
    }
  ],
  "postAggregations": [
    
  ],
  "having": null,
  "limitSpec": {
    "type": "NoopLimitSpec"
  },
  "descending": false
}
```
generates logs such as:
```
2018-07-24T14:50:06,500 INFO [qtp1256384385-231[groupBy_q_test_1]] com.metamx.http.client.pool.ChannelResourceFactory - Generating: https://tier
.historical.foo.com:4443
2018-07-24T14:50:40,366 INFO [qtp1256384385-231[groupBy_q_test_1]] com.metamx.http.client.pool.ChannelResourceFactory - Generating: https://tier
.historical.foo.com:4443
```

This historical contains segments for datasources `tableA` and `tableB` and therefore it sends two request to the historical but as it can be seen from the timestamps, there is a delay between both the requests.
 [BrokerServerView](https://github.com/apache/incubator-druid/blob/master/server/src/main/java/io/druid/client/BrokerServerView.java#L291) confirms this behaviour that at an instant for a given query, there can be only a single request to a historical. This behaviour clearly causes query execution delays for union queries.
Before I work on investigating if this can be parallelized, I wanted to check with the community for any comments on whether this is already a known issue with union queries or if it is actually a bug.

**Comment by gianm** [comment]
It doesn't seem ideal or intentional to issue them sequentially like that. IMO, it would be better to issue the queries simultaneously.

My rationale for saying that is that, the way I think about union dataSources, they're meant to treat two dataSources if they were one. If they were one then the query would be fully parallelized, so full parallelization makes sense.

**Comment by a2l007** [comment]
@gianm 
Parallelizing union queries with the existing design doesn't work even using AsyncQueryRunner as the merging for all the queries except GroupByV1 are performed lazily.
I think what would help fix this and union queries overall would be to modify the `Query` interface to accept a list of datasources instead of a single datasource. In this case, the `BrokerServerView` would have to merge the timelines for all the datasources in the list before the segments to be queried are identified. This would essentially condense the queries for each datasource into a single query.
What do you think of this proposal?

**Comment by jihoonson** [comment]
> Parallelizing union queries with the existing design doesn't work even using AsyncQueryRunner as the merging for all the queries except GroupByV1 are performed lazily.

Hi @a2l007, would you elaborate more on this?

**Comment by a2l007** [comment]
@jihoonson Currently the `UnionQueryRunner` executes the query for each datasource sequentially and this is a performance hit for union queries. I'm investigating on how this can be solved. According to my understanding, in the `UnionQueryRunner` all the sequences within the `MergeSequence` would be fetched lazily and so even if I wrap each of these sequences with an AsyncQueryRunner for parallel execution, it wouldn't help because of lazy evaluation. Is my understanding right? 
Going with my reasoning above, I had suggested the proposal for modifying the `Query` interface for multiple datasources. Please let me know your thoughts.

**Comment by jihoonson** [comment]
@a2l007 thanks, but I still wonder how the lazy evaluation in `MergeSequence` prevents the query execution to be parallelized. `AsyncQueryRunner` immediately executes the given query and the returned `LazySequence` can wait for the query execution to be completed when `toYielder()` is called in `MergeSequence`. Even though the `baseRunner` in `UnionQuery` is essentially `CachingClusteredClient` which blocks until it merges all intermediates from historicals, `AsyncQueryRunner` looks feasible to parallelize the query execution in `UnionQuery`.

[The way the broker works is similar](https://github.com/apache/incubator-druid/blob/master/server/src/main/java/org/apache/druid/client/CachingClusteredClient.java#L280-L287).

```java
      return new LazySequence<>(() -> {
        List<Sequence<T>> sequencesByInterval = new ArrayList<>(alreadyCachedResults.size() + segmentsByServer.size());
        addSequencesFromCache(sequencesByInterval, alreadyCachedResults);
        addSequencesFromServer(sequencesByInterval, segmentsByServer);
        return Sequences
            .simple(sequencesByInterval)
            .flatMerge(seq -> seq, query.getResultOrdering());
      });
```

It creates queryRunners which get results from historicals (`DirectDruidClient`) and caches asynchronously, and then merges the returned sequences using `MergeSequence`. 

Am I missing something?

But, even if this is correct, I'm not sure it's a good idea to use `AsyncQueryRunner` in `UnionQuery`. This means we have two layers for parallelizing unionQueries in `UnionQuery` and `CachingClusteredClient` classes. It might be better to improve `CachingClusteredClient` to handle all parallelization logic including for unionQueries. Maybe is this similar to your idea to improve `BrokerServerView`? Though I'm not sure what it means exactly.

**Comment by a2l007** [comment]
Thanks for the explanation @jihoonson 
I had performed some tests wrapping the `AsyncQueryRunner` for each of the runners within the `MergeSequence` but it didn't look like it helped. Anyways I'll take a look again. 
 I agree that using the `AsyncQueryRunner` may not be the best idea and it may require increasing the processing numthreads as the broker uses its query processing executor service for parallelizing it.
The solution what I was suggesting is to modify the getDataSource() API in the Query interface to something like:
`List<DataSource> getDataSource()`
 With this change, we can modify the following `getTimeline` method and construct a combined  VersionedIntervalTimeline<String, ServerSelector> object which includes entries for all the listed datasources:
https://github.com/apache/incubator-druid/blob/master/server/src/main/java/org/apache/druid/client/CachingClusteredClient.java#L256
This timeline can then be used for identifying segments to be queried and from here on`CachingClusteredClient` would treat this as a single query. Does this make sense?

**Comment by jihoonson** [comment]
@a2l007 I see. It sounds a good idea. 

One thing I would like to note is `TimelineLookup` (especially `VersionedIntervalTimeline`) is designed to represent a timeline of segments of a single dataSource. It is responsible for checking the overshadowing relation among segments and returning only _queryable_ segments. Since the overshadowing relation is checked by comparing the `version` of segments of the same `interval` and the same `dataSource`, I would say supporting multiple dataSources for `VersionedIntervalTimeline` might make it too complicated. 

How about doing [this part](https://github.com/apache/incubator-druid/blob/master/server/src/main/java/org/apache/druid/client/CachingClusteredClient.java#L256-L279) for all dataSources of the unionQuery in a loop and returning a single `LazySequence` backed by the sequences for all dataSources? For example,

```java
    Sequence<T> run(final UnaryOperator<TimelineLookup<String, ServerSelector>> timelineConverter)
    {
      final List<Sequence<T>> sequencesByInterval = new ArrayList<>();
      if (query.getDataSource() instanceof UnionDataSource) {
        for (String eachDataSource : ((UnionDataSource) dataSource).getDataSources()) {
          @Nullable
          TimelineLookup<String, ServerSelector> timeline = serverView.getTimeline(eachDataSource);

          // fill alreadyCachedResults and segmentsByServer
        }

        return new LazySequence<>(() -> {
          addSequencesFromCache(sequencesByInterval, alreadyCachedResults);
          addSequencesFromServer(sequencesByInterval, segmentsByServer);
          return Sequences
              .simple(sequencesByInterval)
              .flatMerge(seq -> seq, query.getResultOrdering());
        });
      } else {
        // same as it is
      }
```

**Comment by a2l007** [comment]
Sounds good @jihoonson . I'll test this out. Thanks

**Comment by jihoonson** [comment]
Believe this is still relevant.

**Comment by gianm** [comment]
There was some talk about addressing this in https://github.com/apache/druid/issues/9791.
