### ISSUE TITLE
BUG: intermediate persist directories are not cleaned up

### ISSUE THREAD

**Issue by varaga** [apache/druid#6069]
I am using Druid 0.13.0-SNAPSHOT version of Druid and it's deployed into AWS.
The middle managers run Kafka Indexing Task. The task base directory seem to create directories with the following path...
`persistent/task/xxx_taskId_yy//work/persist/xxx_taskId_yyy/**>`
there are many directories that are not cleaned up for each task created as per the duration.
I presume these are used by the tasks to create intermediate persists for segment handoffs and never are cleaned up once the segments are pushed to deep storage.

I have 1000s of these files & directories left lingering in the intermediate storage.

Here below is an example of the directories: 
`druid-prototype-prod]$ ls -ltrc task/persistent/task/index_kafka_caliper-atomic-processed_prod_test1_ca2d498e9b1957c_pbebfmed/4ea138a5-1791-4b1b-a0a5-390e0d81b5d3/
total 0`

`druid-prototype-prod]$ ls -ltrc task/persistent/task/index_kafka_caliper-atomic-processed_prod_test1_ca2d498e9b1957c_pbebfmed/work/
total 4
drwxr-xr-x 3 root root 6144 Jul 27 17:24 persist`

`druid-prototype-prod]$ ls -ltrc task/persistent/task/index_kafka_caliper-atomic-processed_prod_test1_ca2d498e9b1957c_pbebfmed/work/persist/caliper-atomic-processed_prod_test1_2018-07-10T13\:00\:00.000Z_2018-07-10T14\:00\:00.000Z_2018-07-10T13\:00\:02.005Z_4/
total 4
drwxr-xr-x 3 root root 6144 Jul 27 17:24 0`

`druid-prototype-prod]$ ls -ltrc task/persistent/task/index_kafka_caliper-atomic-processed_prod_test1_ca2d498e9b1957c_pbebfmed/work/persist/caliper-atomic-processed_prod_test1_2018-07-10T13\:00\:00.000Z_2018-07-10T14\:00\:00.000Z_2018-07-10T13\:00\:02.005Z_4/0/
total 4
drwxr-xr-x 2 root root 6144 Jul 27 17:24 tmpOutputFiles`

`druid-prototype-prod]$ ls -ltrc task/persistent/task/index_kafka_caliper-atomic-processed_prod_test1_ca2d498e9b1957c_pbebfmed/work/persist/caliper-atomic-processed_prod_test1_2018-07-10T13\:00\:00.000Z_2018-07-10T14\:00\:00.000Z_2018-07-10T13\:00\:02.005Z_4/0/tmpOutputFiles/
total 0``druid-prototype-prod]$ ls -ltrc task/persistent/task/index_kafka_caliper-atomic-processed_prod_test1_ca2d498e9b1957c_pbebfmed/work/persist/caliper-atomic-processed_prod_test1_2018-07-10T13\:00\:00.000Z_2018-07-10T14\:00\:00.000Z_2018-07-10T13\:00\:02.005Z_4/
total 4
drwxr-xr-x 3 root root 6144 Jul 27 17:24 0`

`druid-prototype-prod]$ ls -ltrc task/persistent/task/index_kafka_caliper-atomic-processed_prod_test1_ca2d498e9b1957c_pbebfmed/work/persist/caliper-atomic-processed_prod_test1_2018-07-10T13\:00\:00.000Z_2018-07-10T14\:00\:00.000Z_2018-07-10T13\:00\:02.005Z_4/0/
total 4
drwxr-xr-x 2 root root 6144 Jul 27 17:24 tmpOutputFiles`

`druid-prototype-prod]$ ls -ltrc task/persistent/task/index_kafka_caliper-atomic-processed_prod_test1_ca2d498e9b1957c_pbebfmed/work/persist/caliper-atomic-processed_prod_test1_2018-07-10T13\:00\:00.000Z_2018-07-10T14\:00\:00.000Z_2018-07-10T13\:00\:02.005Z_4/0/tmpOutputFiles/
total 0`

**Comment by gianm** [comment]
Hi @varaga,

The MiddleManager processes themselves are meant to clean up these directories when tasks exit. Are the MiddleManagers (or the machine itself) crashing before the cleanup can happen?

Also, I _think_ they do not clean up 'stale' directories for unused tasks on startup. This would be a nice feature to add. Something like: remove all task working directories for tasks that are _not_ restored (i.e. in restore.json) Are you interested in contributing a patch for that?

**Comment by applike-ss** [comment]
Is there anything new about this? We're experiencing issues with leftovers as well. This could be related to tasks being rescheduled in kubernetes (just a guess).
