### ISSUE TITLE
Windows Ubuntu Bash and Task Directory Name

### ISSUE THREAD

**Issue by rathish** [apache/druid#6096]
Hi Committers,

I am trying to run Druid in Windows 10 enabled Ubuntu Bash environment, all the nodes are starting up fine and I am able to connect to kafka -> tranquility -> Druid but when creating index , java.io.File is not able to create real-time task directory and throws below error.

io.druid.java.util.common.IOE: Could not create directories: var/druid/task/index_realtime_kafka09090_2018-08-02T08:00:00.000Z_0_0/020e7278-ec01-41e9-958a-7e4d90726233

I think Windows folders are not allowed to have ":" special characters thats why File fails to create directory. I am now moving my trail to proper Ubuntu server. If there is any plan to support such hybrid linux operating system then task folder naming conversion should be considered.

Thanks,
Rathish

**Comment by vogievetsky** [comment]
I think it is a good point about directory names and should be considered for the project @gianm does it make sense to avoid contentious characters like `:`?
For now, Rathish, I can tell you that Windows is solidly out of scope for Druid (and it has never been). Please move to a proper Linux environment.

**Comment by rathish** [comment]
Yea, thanks Vadim. I have moved to proper Linux environment.
