### ISSUE TITLE
pulldeps tools pulls hadoop client for no reason

### ISSUE THREAD

**Issue by pdeva** [apache/druid#6111]
to repro try this command:

```
java  -cp "lib/*" -Ddruid.extensions.directory="extensions" io.druid.cli.Main tools pull-deps  -c "io.druid.extensions.contrib:druid-redis-cache:0.12.1"
```

expected:
download the redis cache extension and its deps

actual:
for some reason, also downloads hadoop client.

**Comment by gianm** [comment]
I think you need to add `--no-default-hadoop` to skip downloading Hadoop. I believe the help and/or docs for this command should mention that, if not we should add a mention of that.

**Comment by pdeva** [comment]
but why download hadoop client i the first place. i never asked for it. 
the bug is regarding default behavior.
the flag should be to ‘enable’ downloading hadoop client not the other way around.
