### ISSUE TITLE
[Proposal] Move Task to move segments while migrating deep storages

### ISSUE THREAD

**Issue by niketh** [apache/druid#6138]
Introduce a new task - Move Task which can move segments and insert metadata correctly while moving deep storages.

@gianm 

```
{
    "type": "move",
    "id": <task_id>,
    "dataSource": <task_datasource>,
    "destination": {
        "overlord": <url>,
        "ioConfig" : {
              "type" : "hadoop",
               "outputSpec" : {
                   "paths" : "hdfs://xxx/yyy/zzz"
               }
          }
       }
    "interval": <interval to specify segments to be merged>,
    "tuningConfig" <move task tuningConfig>,
    "context": <task context>
}
```

**Comment by jihoonson** [comment]
We already have the moveTask for this purpose. What's the difference?

**Comment by niketh** [comment]
@jihoonson I didn't find it in the documentation http://druid.io/docs/latest/ingestion/tasks.html. 
I saw the code some more, some problems with existing implementation:

1. It directly runs on MM, no map reduce option.
2. Doesn't support segments on HDFS.
