### ISSUE TITLE
12 hour segment granularity task producing 6 hour segments

### ISSUE THREAD

**Issue by pdeva** [apache/druid#6170]
We are seeing this behavior for not just 1 but multiple datasources, with similar config as below.
screenshot of coordinator console:
https://www.screencast.com/t/kB6EPZJCK

As you can see segments are created every 6 hours instead of 12 for some reason.
(the hourly segments shown in the screenshot can be ignored, since they are from before we increased the segment granularity to 12H).

Note that the `maxRowsPerSegment` is definitely not being hit, as can be verified by the tiny size of the segments.

config:
```
"granularitySpec": {
      "type": "uniform",
      "segmentGranularity": {"type": "period", "period": "PT12H"},
      "queryGranularity": "MINUTE"
    }
  },
  "tuningConfig": {
    "type": "kafka",
    "maxRowsPerSegment": 5000000
  },
  "ioConfig": {
    "topic": "infraintegrations",
    "consumerProperties": {
      "bootstrap.servers": "xxx"
    },
    "taskCount": 1,
    "replicas": 2,
    "taskDuration": "PT12H"
  }
```

**Comment by scimas** [comment]
@pdeva Did you find a solution to this problem? I'm hitting the same problem with kafka ingestion and period segmentGranularity of PT3H producing segments of 1H length. Druid 0.20.0.

Please reopen this issue if it is not intended the behaviour. And if it is the intended behaviour, may I request the documentation be updated to reflect this? Currently the documentation says "**Any** granularity can be provided here" with a link to query granularities page.

**Comment by scimas** [comment]
Bump

**Comment by scimas** [comment]
Bump
