### ISSUE TITLE
nodes should allow draining

### ISSUE THREAD

**Issue by pdeva** [apache/druid#6172]
currently individual nodes have no concept of draining.
this means when updating the cluster, as you take down nodes, the queries in progress will fail.
similarly, if you have broker nodes behind a load balancer, there is no way to tell the load balancer to stop sending new connection to the node you are about to update, which can result in many seconds of requests being sent to nodes down depending on health check interval.

i suggest adding a couple endpoints to broker nodes:

1. `/health/ping` returns 200 when the broker is ready to serve queries
2. `/health/startDrain` sets a flag that makes `/health/ping` throw 500. this will make load balancer health checks fail while not dropping existing connections, resulting in zero downtime updates.

Similar endpoints can be put on MM and Historical nodes, with coordinator performing the health check. when the health check returns non-200 values, coordinator can instruct broker not to send any new queries.

This will result in 100% zero downtime rolling updates.

**Comment by pdeva** [comment]
@gianm ref the druid-dev syn conversation:

- neither google cloud nor azure load balancers have the ability to check for a file as health checks
- the broker node crashing after setting itself to 'draining' wouldnt affect it, since the `draining` state is set in the local memory of the node. so when it comes back up, it will be marked as 'healthy' automatically.

**Comment by mkuthan** [comment]
In our config load balancer check /druid/broker/v1/loadstatus endpoint. No downtime during rolling update/restart of brokers.

**Comment by lyman** [comment]
The problem of checking /druid/broker/v1/loadstatus is that it returns 200 even if the segment view is not initialized. This requires the load balancer to be able to check not only http code but also response content to keep response correct.

**Comment by leanken** [comment]
we hit the same issue with this topic. Our SLB system detect and determined whether a broker is alive or not only by it's return HTTP Code.
Our Druid Cluster is quite huge, and a broker from start to ready to server might have 10+ seconds time gap.

when our SLB system try call /druid/broker/v1/loadstatus
it might return
HTTP Code: 200
{
    "inventoryInitialized": false
}

and assume that this broker could be served query, hens, some of the request will fail according to this condition.

Proposal: 
Have to look at the latest code of coordinator isLeader API

```
    if (leading) {
      return Response.ok(response).build();
    } else {
      return Response.status(Response.Status.NOT_FOUND).entity(response).build();
    }
```

i suggest that we can have a another broker http endpoint
/druid/broker/v1/isReady
if serverView is not inititalized, return 404, else return 200. and this will make our SLB system work as expected.

@pdeva if you are with my proposal, i can do the pull request, and fix this issue along with the documentation.  FYI.
