### ISSUE TITLE
Lucene indexing for free form text

### ISSUE THREAD

**Issue by RestfulBlue** [apache/druid#6189]
Currently druid uses classic inverted indexes to index string columns. But it not really useful when using free-form text. Currently possible to disable indexes, to have no overhead of such columns, but will be very useful to have possibility to enable full text search.
For example, setup in configuration like this
```json
    {
      "type": "string",
      "name": "additional_info",
      "indexType": "unindexed" // without bitmap
    },
    {
      "type": "string",
      "name": "hostname",
      "indexType": "default" // current inverted index
    },
    {
      "type": "string",
      "name": "log_record",
      "indexType": "lucene" // lucene indexing
    }
```

with this possibility druid can be used to store almost everything related to monitoring and log data, making possible to get fast result for query like this :
```sql
select 
   time_floor(__time, "PT1H") , count(*)
from 
   system_logs
where 
    log_record satisfy "*something*" 
    and hostname = "node1"
group by
    time_floor(__time, "PT1H")
order by
   time_floor(__time, "PT1H")
```

where satisfy apply lucene filter log_record:*something*.

Adding full text search will made druid universal instrument for monitoring and logging different systems(Currently filter by free form text require almost full scan, which not work well, so necessary to store such data in solr or elasticsearch)

**Comment by RestfulBlue** [comment]
Hi , multivalue dimensions will work only in some generic simple case, for example where logs have simple form with space separated words. But even with this form of data, it need external preprocessing, which will be grow with time. For example by first it just split by space, when we realize we also want to split by all special characters, when we realize what we also want to search by part of word, so we k skip n gramm, etc. With what external preprocessing will slowly move to things, what lucene doing. Also with what we cant simply get source text, for like select * from table limit 100, because data in multivalue column splitted and optimized for search. So this requiere denormalization of data and cost additional space.

Simple lucene indexing looks like this :

```java
   Analyzer analyzer = new StandardAnalyzer();

    // Store the index in memory:
    Directory directory = new RAMDirectory();
    // To store an index on disk, use this instead:
    //Directory directory = FSDirectory.open("/tmp/testindex");
    IndexWriterConfig config = new IndexWriterConfig(analyzer);
    IndexWriter iwriter = new IndexWriter(directory, config);
    Document doc = new Document();
    String text = "This is the text to be indexed.";
    doc.add(new Field("fieldname", text, TextField.TYPE_STORED));
    iwriter.addDocument(doc);
    iwriter.close();
    
    // Now search the index:
    DirectoryReader ireader = DirectoryReader.open(directory);
    IndexSearcher isearcher = new IndexSearcher(ireader);
    // Parse a simple query that searches for "text":
    QueryParser parser = new QueryParser("fieldname", analyzer);
    Query query = parser.parse("text");
    ScoreDoc[] hits = isearcher.search(query, null, 1000).scoreDocs;
    assertEquals(1, hits.length);
    // Iterate through the results:
    for (int i = 0; i < hits.length; i++) {
      Document hitDoc = isearcher.doc(hits[i].doc);
      assertEquals("This is the text to be indexed.", hitDoc.get("fieldname"));
    }
    ireader.close();
    directory.close();
```

i think adding it as new column will be great. The main reason is what lucene is more heavy than simple token indexing. Mixing disabled indexing, tokening and lucene in one table can greatly reduce total amount of required disk space compare to full lucene indexing

**Comment by navis** [comment]
I've tried text indexing using lucene (https://www.slideshare.net/navis94/druid-meetup-5th/1). Wish it's helpful to you. Also it's supposed to be presented in ApacheCon NA about geospatial processing on druid with lucene (https://apachecon.dukecon.org/acna/2018/#/scheduledEvent/9d31a2c8e70fc2435).

**Comment by RestfulBlue** [comment]
@navis sadly slideshare is banned in russia :D

**Comment by RobotCharlie** [comment]
Supporting full text search seems to be a very good idea. One of our dimensions is actually a high-cardinal string. We will need to support full text search on this dimension column.

**Comment by RobotCharlie** [comment]
@RestfulBlue . I don't know your exact use case but I am able to have a work around by using `CONTAINS_STRING` scalar function.

See below example,

```
HAVING CONTAINS_STRING(log_record, 'something')
```
