### ISSUE TITLE
[Documentation] Custom Modules

### ISSUE THREAD

**Issue by dyanarose** [apache/druid#6197]
http://druid.io/docs/latest/development/modules.html

This documentation could be made fantastic if each type of custom module available for extension had a complete reference implementation.

At the current time, the documentation is a bit vague on many implementation points, especially registration. This may come down to expecting a familiarity with guice, but the documentation shouldn't expect that. 

This could be rectified by just having a simple reference implementation for each extension point.

**Comment by josephglanville** [comment]
It's partially familiarity with Guice but also familiarity with Jackson. I have been intending to write something about this for a while but never seem to find the time.
It's also worth pointing out that adding configuration is not well documented either, i.e usage of `JsonConfigProvider`.
