### ISSUE TITLE
[Proposal] Vectorized querying for lookups

### ISSUE THREAD

**Issue by a2l007** [apache/druid#6199]
Presently, QTL objects are resolved by the LookupExtractor one key at a time. This proposal is to support a vectorized query model for lookup keys. LookupExtractor presently has an [applyAll() ](https://github.com/apache/incubator-druid/blob/master/processing/src/main/java/io/druid/query/lookup/LookupExtractor.java#L57) method which would be utilized for this case. Based on the LookupExtractor implementation, this would increase the query execution performance for lookups. For the existing design to support this functionality, it would require a configurable number of rows to be buffered before the lookups are resolved.

**Comment by gianm** [comment]
I have been working on vectorized query engines and I think this would dovetail great with them. Hope to have something to post up soon.

**Comment by a2l007** [comment]
Looking forward to that. Is your implementation already taking care of lookup query vectorization? If not I can come back to this and work on it once your PR is out.

**Comment by gianm** [comment]
It's not, just the inner parts of the query engines.

**Comment by a2l007** [comment]
@gianm Since #6794 is merged, I'll start working on this and hopefully post a detailed proposal soon.

**Comment by gianm** [comment]
Ah nice!
