### ISSUE TITLE
Druid 0.11.0 statsD Emitter not sending count related metrics

### ISSUE THREAD

**Issue by ShilpaSivanesan** [apache/druid#6200]
Have enabled statsD monitoring and could view all other events except 

Historical and Broker :
    query/success/count  
    query/failed/count
    query/interrupted/count

coordinator :
     segment/count

historical :
     segment/count

Enabled QueryCountStatsMonitor also
missing out only count related metrics. is it something specific to convertRange?

**Comment by QiuMM** [comment]
@hellobabygogo The doc of statsD Emitter: http://druid.io/docs/latest/development/extensions-contrib/statsd.html.

**Comment by QiuMM** [comment]
@ShilpaSivanesan you should speicify your own `druid.emitter.statsd.dimensionMapPath` which default  is `statsd-emitter/src/main/resources/defaultMetricDimensions.json`.
