### ISSUE TITLE
[Proposal] Add 'checkpoint' API to supervisor for manual checkpointing

### ISSUE THREAD

**Issue by jihoonson** [apache/druid#6208]
Checkpoint was introduced for incremental publishing in Kafka indexing service. Each kafka task can publish their segments if the segment size is large enough in the middle of indexing. Checkpointing is a very important feature and should be tested in various situations.

The main purpose of this proposal is for easy testing of rolling update while checkpointing. If we have an API for manual checkpointing, it would be much easier to test it by simply calling the checkpoint API and do the rolling update.

**Comment by himanshug** [comment]
sounds reasonable.
