### ISSUE TITLE
Csv with Header giving 'Success' but not loading any data

### ISSUE THREAD

**Issue by ranjan321** [apache/druid#6210]
i am giving below config to run csv file which is having header task is getting success but not able to see any data 

"parser" : {
          "parseSpec" : {
          "format" : "csv",
          "hasHeaderRow" : true,
          "skipHeaderRows" : 1,
		 "dimensionsSpec" : {
            "dimensions" : ["STATE_UT_NAME","DISTRICT","JAN","FEB","MAR","APR","MAY","JUN","JUL","AUG","SEP","OCT","NOV","DEC","ANNUAL","Jan-Feb","Mar-May","Jun-Sep","Oct-Dec"]
          },
          "timestampSpec" : {
		    "format" : "auto",
            "column" : "TIME"
          }
        }
      }

When i checked log i found one warning like below.Please let me know any other props i need to add
**io.druid.segment.realtime.firehose.LocalFirehoseFactory - Initialized with [/home/mypoc/druid-0.10.1/quickstart/rainfall-header.csv] files
2018-08-22T09:16:34,007 WARN [task-runner-0-priority-0] io.druid.indexing.common.task.IndexTask - Unable to parse [640] events**

**Comment by ranjan321** [comment]
Still i didn't get any response .please look into this issue as it an urgency

**Comment by a2l007** [comment]
Looks like an issue with your data not adhering to the csv format. As you can see from the logs, all the 640 rows were unparseable. Please double check your data and if you need further help, post a sample of the data that you're attempting to index.
