### ISSUE TITLE
Multiple datasources with multiple topic in one spec file

### ISSUE THREAD

**Issue by Harish346** [apache/druid#6253]
Hi, 
  I have multiple datasources each corresponding to a kafka topic.When I create supervisor for each datasource,many supervisors are created leading to memory issues and creating many pending tasks which takes more time in data ingestion.So I have to write one supervisor spec which have multiple datasources with corresponding topic. Is that possible? Any help would be really appreciated.

**Comment by gianm** [comment]
Hi @Harish346, currently the model is 1 supervisor and 1 set of tasks per datasource.
