### ISSUE TITLE
Druid parse error on formatted time field with non-zero timezone

### ISSUE THREAD

**Issue by zhaojiandong** [apache/druid#6343]
part of jvm.config:
```
-Duser.timezone=Asia/Shanghai
```
timestampSpec config :
```
"timestampSpec": {
    "format": "yyyy-MM-dd HH:mm:ss",
    "column": "logTime"
}
```
events example:
```json
{"logTime":"2018-09-10 18:00:00","dim1":"d1","dim2":"d2","value":100}
{"logTime":"2018-09-10 18:00:00","dim1":"d1","dim2":"d2","value":90}
```
We set user.timezone=Asia/Shanghai, so the correct timestamp is 1536573600000. But druid specifies the UTC timezone, and the TimestampParser recognizes  '2018-09-10 18:00:00'  as  '2018-09-10 18:00:00+00:00' , so it's parsed to 1536602400000.
I will fixed it.

**Comment by gianm** [comment]
This behavior is intentional: see https://github.com/apache/incubator-druid/pull/6344#issuecomment-422906978 (& also a suggested alternate approach in that same comment).
