### ISSUE TITLE
Indexer should report an ip address along with an instance id during provisioning or termination.

### ISSUE THREAD

**Issue by egor-ryashin** [apache/druid#6507]
Indexer (while using **EC2AutoScaler**) reports instance IDs and IP addresses separately while it could report a pair <IP, instance-ID>.
For example, **Indexer Console** `Remote Workers` reports IPs, while `Autoscaling Activity` table reports instance IDs (Druid 0.12).
Proposed changes could help out during debugging of production issues. Right now the operator has to do an additional investigation step during debugging to link IP and ID by searching through Indexer logs and making guesses based on timestamp.

This issue could address both logging and Indexer console.

**Comment by vogievetsky** [comment]
Which API are you referring to specifically?

**Comment by egor-ryashin** [comment]
@vogievetsky I updated the description.
