### ISSUE TITLE
Provide support for min, max window functions

### ISSUE THREAD

**Issue by ciukstar** [apache/druid#6550]
Provide support for min, max window functions. "Feature scaling" (https://en.wikipedia.org/wiki/Feature_scaling) is quite difficult to implement without window functions. At the moment it requires two or more queries.

**Comment by gianm** [comment]
Still a useful request IMO.

**Comment by yurmix** [comment]
It is supported by [Moving Average Query](https://druid.apache.org/docs/latest/development/extensions-contrib/moving-average-query.html) extension. This extension needs more work (mainly SQL support) but it supports MAX/MIN window functions.

**Comment by ciukstar** [comment]
Thanks!
