### ISSUE TITLE
Nodes take a long time (20 min) to exit when zookeeper is down

### ISSUE THREAD

**Issue by danfinch** [apache/druid#660]
If I take down zookeeper and then send a SIGTERM to druid processes, they continuously log exceptions and do not exit.

**Comment by bjozet** [comment]
I was able to reproduce; after stopping zookeeper my thread logs:
`WARN [CuratorFramework-0-SendThread(192.168.33.243:2181)] org.apache.zookeeper.ClientCnxn - Session 0x0 for server null, unexpected error, closing socket connection and attempting reconnect
java.net.ConnectException: Connection refused
	at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method) ~[?:1.7.0_75]
	at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:739) ~[?:1.7.0_75]
	at org.apache.zookeeper.ClientCnxnSocketNIO.doTransport(ClientCnxnSocketNIO.java:361) ~[zookeeper-3.4.6.jar:3.4.6-1569965]
	at org.apache.zookeeper.ClientCnxn$SendThread.run(ClientCnxn.java:1081) [zookeeper-3.4.6.jar:3.4.6-1569965]`

After sending a SIGTERM the process remain running, although I did not receive further messages in logging.

I've uploaded a jstack-l <pid> threaddump to:
http://paste.ubuntu.com/11259668/

**Comment by gianm** [comment]
Hmm, it looks like the only interesting non-daemon thread left is Thread-43, which is trying to unannounce the service from ZK and is in the middle of a retry loop. I *think* it should exit after about 20 minutes when all of its retries are exhausted. Do you know if it was stuck for longer than that?

The reason I think it's about 20 minutes is that Curator's retry policy is ```new BoundedExponentialBackoffRetry(1000, 45000, 30)```.

**Comment by gianm** [comment]
Would it make sense to have a shorter retry policy? We do want to at least try somewhat hard to cleanly shut things down when we get a SIGTERM, and if ZK is unavailable I think it does make sense to wait a bit. Maybe not 20 minutes.

**Comment by bjozet** [comment]
I didn't time the processes afterwards, but when i came back after lunch they were gone :) so it is probably as you say then, that they wait for the 20 min timeout.
