### ISSUE TITLE
Implement the KPL Aggregated Record Format for Kinesis indexing service

### ISSUE THREAD

**Issue by dclim** [apache/druid#6714]
The Kinesis indexing service (#6431) supports de-aggregation of multiple rows packed into a single record by the Kinesis Producer Library's aggregate method for more efficient data transfer. Currently, enabling the de-aggregate functionality requires the user to manually provide the Kinesis Client Library on the classpath, since this library has a license not compatible with Apache projects.

See: https://github.com/apache/incubator-druid/pull/6431/files#diff-88b66c67f91d2ab9d26a23abf0543bfbR312

A better solution would be for the Druid project to implement the protocol ourselves according to the specification here: https://github.com/awslabs/amazon-kinesis-producer/blob/master/aggregation-format.md

For legal reasons, this should be done by a contributor who has not read through the Amazon licensed implementation so that there is no case for copyright infringement (https://en.wikipedia.org/wiki/Clean_room_design).

**Comment by justinborromeo** [comment]
Currently working on this.

**Comment by himanshug** [comment]
https://lists.apache.org/thread.html/95aec3e271903320994fba321c58aff66b739b1f68796c253e430469@%3Cdev.druid.apache.org%3E means we can now package the AWS lib itself instead of implementing the protocol ?

**Comment by justinborromeo** [comment]
@himanshug yes.  Closing #6917 since it's no longer necessary.
