### ISSUE TITLE
Druid SQL: Mapping the gaps in capability

### ISSUE THREAD

**Issue by yurmix** [apache/druid#6771]
Hi,

SQL is the database world's standard API for both querying, updating (DML), structural transformations (DDL) as well as even administration operations.
[Druid SQL](http://druid.io/docs/latest/querying/sql.html) exists but it still not thoroughly covers all Druid capabilities and APIs.

There is a will in the community to close that gap (@gianm recently noted about it in the dev email list).

I believe it would be beneficial to document all the gaps which currently exist for Druid SQL to be in full parity with other mature, commercial analytical databases. Such documentation could promote effort by many contributors to help to close that gap.

Regarding technicalities, I have some suggestions:
1. The list should be broken down to manageable chunks so multiple contributors could participate.
2. It would be helpful to note why SQL support is missing: Is it just SQL or is this capability isn't supported by Druid core.
3. When starting to work on a specific item, we could line its GitHub Issue (And people can also link their existing Issues).

I might spend some of my own time working on a parity comparison with Vertica (which is a mature analytical database, shares many qualities with Druid and with which I have experience with).
I'm not entirely sure, but a parity comparison with an OLAP database might also be relevant (I have no experience with these types of databases). Perhaps @julianhyde could shed some light on the relevancy of this subtopic.

**Comment by mistercrunch** [comment]
We're hoping to deprecate the REST/native Druid connector in Superset and move towards the SQL / SQLAlchemy connector. Understanding the gaps would help us move forward.

@gianm, is there a source of truth for the existing gaps, and is the plan to put the SQL interface forward?

**Comment by gianm** [comment]
@mistercrunch The most authoritative list is in the docs here: https://druid.apache.org/docs/latest/querying/sql.html#unsupported-features, however it's not exhaustive.

The first two ("Multi-value dimensions" and "Set operations on DataSketches aggregators") were added recently. There are also some (esoteric) things missing, like the Search query and some lesser-used extensions. Give me a bit and I'll put together a PR removing those two and adding a few more missing things explicitly.

The plan is certainly to continue pushing the SQL interface forwards and reach parity ASAP.
