### ISSUE TITLE
Use an enum for aggregator cache key byte identifiers instead of static values

### ISSUE THREAD

**Issue by clintropolis** [apache/druid#6823]
[Based on this discussion](https://github.com/apache/incubator-druid/pull/6397#discussion_r228986335) the idea is to use an enum instead of a pile of static variables for associating aggregators to cache keys in `AggregatorUtil`, and use a static initializer to ensure that it is impossible to define the same byte identifier twice. `CacheKeyBuilder` should also be modified to accept the enum instead of the byte value.

**Comment by clintropolis** [comment]
`DimFilterUtils` and `ExtractionCacheHelper` are probably other good candidates for this

**Comment by drcrallen** [comment]
How does this play into proprietary extensions? For example, we have a lookup extension that has a special cache key generation mechanism. Is the intention that custom extensions use this enum to generate their cache keys?

**Comment by clintropolis** [comment]
Good point @drcrallen, I'm not sure how to best handle this. @leventov as the source of this request do you have any ideas?

**Comment by leventov** [comment]
An extensible enum pattern could be used.
```java
interface CacheKeyId {
  byte getId();
}

enum UpstreamCacheKeyId {
  ...
  RESERVED_1((byte) 200),
  ...
  RESERVED_50((byte) 250)
}
```

Extensions are responsible for using ids from the reserved range.

Another option is UTF-8 style, special byte for ids from private extensions:
```java
enum CacheKeyId {
  ...
  EXTENSION(-1)
}
```
Then extensions need to use two-byte identifier, the first byte is `EXTENSION.id`, and then their custom id.

More approaches are possible

**Comment by leventov** [comment]
Another class of scattered constants: `GROUPBY_QUERY`, `TIMESERIES_QUERY`, `TOPN_QUERY`.

**Comment by clintropolis** [comment]
Still relevant
