### ISSUE TITLE
io.druid.cli.Main can not found or load

### ISSUE THREAD

**Issue by chenhaiyan** [apache/druid#6921]
when I load  community and third-party extensions, I use `java -cp "dist/druid/lib/*" -Ddruid.extensions.directory="dist/druid/extensions" -Ddruid.extensions.hadoopDependenciesDir="dist/druid/hadoop-dependencies" org.apache.druid.cli.Main tools pull-deps --no-default-hadoop -c "io.druid.extensions.contrib:druid-orc-extensions:0.12.0"
` to load druid-orc-extension ,but the command always return error with can not find or load io.druid.cli.Main. I highly appreciate if someone can help me!!!

**Comment by chenhaiyan** [comment]
I use the imply, any suggestions?

**Comment by gianm** [comment]
If you're using 0.13.0 it should all be `org.apache`, like

```
java \
  -cp "dist/druid/lib/*" \
  -Ddruid.extensions.directory="dist/druid/extensions" \
  -Ddruid.extensions.hadoopDependenciesDir="dist/druid/hadoop-dependencies" \
  org.apache.druid.cli.Main tools pull-deps \
  --no-default-hadoop \
  -c "org.apache.druid.extensions.contrib:druid-orc-extensions:0.13.0-incubating"
```

**Comment by chenhaiyan** [comment]
thank you gianm 。yeah，when I use 0.13.0，this will work，but I use imply.io，and it always return Error: Could not find or load main class io.druid.cli.Main

**Comment by UmerHamid** [comment]
I using 0.14.2 and When I used this command in my druid distribution:  java `cat conf/druid/coordinator/jvm.config | xargs` -cp conf/druid/_common:conf/druid/coordinator:lib/* org.apache.druid.cli.Main server coordinator

getting same error like could not found or load org.apache.druid.cli.Main.
