### ISSUE TITLE
[Proposal] Adding a Troubleshooting section for developers/contributors

### ISSUE THREAD

**Issue by hpandeycodeit** [apache/druid#6996]
**Background:** 

I have Java 8 as well as 11 installed on my machine and once I forgot to change the JAVA_HOME to jdk 8 due to which my build failed with errors that aren't useful to figure out if that is a Java version issue. 

For eg: 

`[ERROR] /Users/hpandey/projects/incubator-druid/core/src/main/java/org/apache/druid/collections/ReferenceCountingResourceHolder.java:[25,16] cannot find symbol
[ERROR]   symbol:   class Cleaner
[ERROR]   location: package sun.misc
`

Adding a "Troubleshooting" section here on the GitHub can help the new developers or contributors to resolve such common issues which they might encounter during their initial setup or build. 

Thoughts?

Thanks,
Himanshu

**Comment by gianm** [comment]
It could be useful to add a section like that to this document: http://druid.io/docs/latest/development/build.html

**Comment by abossenbroek** [comment]
Just ran into that issue, how do I resolve it?

**Comment by hpandeycodeit** [comment]
@abossenbroek just make sure your JAVA_HOME is pointing to jdk 8 and it will work. I have 8 and 11 installed on my machine so I default it to jdk 8 and it works.
