### ISSUE TITLE
Not enough direct memory

### ISSUE THREAD

**Issue by Alexander1902** [apache/druid#7085]
the druid error :Not enough direct memory.  Please adjust -XX:MaxDirectMemorySize, druid.processing.buffer.sizeBytes, druid.processing.numThreads, or druid.processing.numMergeBu
ffers: maxDirectMemory[2,022,178,816], memoryNeeded[2,684,354,560] = druid.processing.buffer.sizeBytes[536,870,912] * (druid.processing.numMergeBuffers[2] + druid.
processing.numThreads[2] + 1)
but i set "
-server
-Xms12g
-Xmx12g
-XX:MaxDirectMemorySize=5120m
" and "
druid.processing.buffer.sizeBytes=536870912
druid.processing.numThreads=2
".
Why does it make every feedback error when running "bin/post-index-task -- URL http:/*. **. *:: 8090/ - coordinator-url http://*. *. *. *:*:::*: 8081/ - file quickstart/myinsert/flowtable_test.json"?
Please help me.

**Comment by gianm** [comment]
You probably need to edit the task startup options too: `druid.indexer.runner.javaOpts` in middleManager/runtime.properties.
