### ISSUE TITLE
Does druid explicitly support transaction operation

### ISSUE THREAD

**Issue by helianthuslulu** [apache/druid#7127]
# Description

Druid is designed for OLAP，but I was inerested in if it can support ACID operation recently.
Doesanyone know the answer ?

Thanks in advance!

**Comment by gianm** [comment]
Druid ingestion is either append-only (for streams) or bulk-overwrite/append (for batch). I think neither one really fits into the ACID transaction model. But maybe my mind just isn't expansive enough.

**Comment by helianthuslulu** [comment]
Whatever, thank you for your reply~(＾－＾)， your answer gave me enlightening .   I will go on to study @gianm

**Comment by chenhaiyan** [comment]
@gianm thanks for helping us qianm. How to append data when use hadoop batch,no matter parameter overwriteFiles true or false,it only overwrite the old data ,is this a bug or I do something wrong ?

**Comment by vogievetsky** [comment]
Hadoop ingestion only supports overrides
