### ISSUE TITLE
Druid0.13.0 - 405 method not allow when I send post to coordinator url

### ISSUE THREAD

**Issue by YDHui** [apache/druid#7197]
### Affected Version

Druid 0.13.0

### Description

I post a lookup to coordinator url ,and it return a 405 error.
`
curl  -H "Content-type:application/json" -vvv -XPOST http://localhost:8081/druid/coordinator/v1/lookups/config/__default  -d@1.json
`

it return result is 

`
 HTTP/1.1 405 Method Not Allowed
`

and My common config is 

`
druid.extensions.loadList=["druid-parser-route","druid-kafka-indexing-service","mysql-metadata-storage","druid-histogram", "druid-datasketches", "druid-lookups-cached-global"]
`
I think i have added the lookup extension and the json content is ok

**Comment by Honglun** [comment]
Hello，did you solve the issue?

**Comment by vogievetsky** [comment]
I think you need to post to `/druid/coordinator/v1/lookups/config` not `/druid/coordinator/v1/lookups/config/__default`
