### ISSUE TITLE
creating druid database connection in superset?

### ISSUE THREAD

**Issue by wamshkreshna** [apache/druid#7214]
Hi Team ,

I want to create druid sql lab in superset Ui ,but when i created database connection for druid , iam getting following error.

ERROR: {"error": "Connection failed!\n\nThe error message returned was:\n(pydruid.db.exceptions.ProgrammingError) Unauthorized request. (None): None [SQL: 'SELECT TABLE_NAME FROM INFORMATION_SCHEMA.TABLES'] (Background on this error at: http://sqlalche.me/e/f405)"}

here  im using kerberized cluster ,hdp 3.0.1 ,druid version is 0.12.1,superset version is 0.23 .

Regards,
vamshi.

**Comment by egor-ryashin** [comment]
I think this is a good question for Stackoverflow
