### ISSUE TITLE
RPC building block: future hook for repetitive queries

### ISSUE THREAD

**Issue by leventov** [apache/druid#7390]
Generified idea of #7231. A lot of Druid nodes do RPC to each other with idempotency expectations. If one query is already in-flight, another query can just wait for the same `Future`.

I've once implemented similar functionality here in an ad-hoc manner: https://github.com/metamx/druid/commit/772bd29adb829cb5c09eb233ed3bf93209c2a456#diff-b246e418901d237662b3363cdc950d13R118

We can build something generic and allow to use it in a declarative manner, for example, a static utility that accepts a lambda and creates a hook.

**Comment by gianm** [comment]
Still sounds like a good idea.

**Comment by sashidhar** [comment]
@leventov , @gianm ,  I believe request caching https://github.com/Netflix/Hystrix/wiki/How-it-Works#RequestCaching can be helpful in solving this. 

On a different note, we should consider using Hystrix library which helps control interactions between distributed services by adding latency tolerance and fault tolerance logic  improving overall system resiliency.  https://github.com/Netflix/Hystrix/wiki

Hystrix provides a number of patterns to improve system resiliency - Sync/Async executions, Command groups/thread pools, Request collapsing/caching etc etc.
https://github.com/Netflix/Hystrix/wiki/How-To-Use
https://github.com/Netflix/Hystrix/wiki/How-it-Works
