### ISSUE TITLE
druid-cassandra-storage doesn't include high-scale-lib dependency 

### ISSUE THREAD

**Issue by egor-ryashin** [apache/druid#7426]
I've been investigating the issue (https://github.com/apache/incubator-druid/issues/7387) and got this error while the indexing task was starting up:
```
2019-04-08T20:38:23,441 ERROR [main] org.apache.druid.cli.CliPeon - Error when starting up.  Failing.
com.google.inject.ProvisionException: Unable to provision, see the following errors:

1) Error injecting constructor, java.lang.NoClassDefFoundError: org/cliffc/high_scale_lib/NonBlockingHashMap
```
`druid-cassandra-storage` extension lacks `high-scale-lib` dependency and it was excluded sometime ago:
`extensions-contrib/cassandra-storage/pom.xml:116`
```
               <exclusion>
                    <groupId>com.github.stephenc.high-scale-lib</groupId>
                    <artifactId>high-scale-lib</artifactId>
                </exclusion>
```
probably this is related https://github.com/apache/incubator-druid/pull/4313

**Comment by wc188996** [comment]
I found `<groupId>com.github.stephenc.high-scale-lib</groupId>` in `extensions-contrib/cassandra-storage/pom.xml:117`, 
Then checked the pom.xml file mentioned in `extensions-contrib/cassandra-storage/pom.xml:33` 
`<relativePath>../../pom.xml</relativePath>` . I didn't find any dependency of `high-scale-lib` in this file.

I've downloaded the `high-scale-lib-1.1.4.jar`  to `druid/extensions/druid-cassandra-storage` for walking around. My `Apache Druid` is running with the `druid-cassandra-storage` extension now,thanks to egor-ryashin for your previous efforts #7387.

**Comment by egor-ryashin** [comment]
@leventov as you've worked on #4313, probably, you understand better how to fix it. Right now I think that `maven exclusion` should be removed

**Comment by Ken-LiuL** [comment]
same issue

**Comment by Ken-LiuL** [comment]
should remove the exclusion part
