### ISSUE TITLE
disabling data source and killing KIS supervisor doesnt kill existing tasks

### ISSUE THREAD

**Issue by pdeva** [apache/druid#7521]
### Affected Version

0.14-iap3

### Description
to repro:

1. create a datasource with KIS tasks running
2. from the router UI, 'drop data' for the datasource
3. from the router UI, 'terminate' KIS supervisor for datasource

expected:

datasource is marked disabled in router UI.
existing KIS  tasks for datasource are killed.

actual: 

datasource still marked as available and green in router UI, even though it has 0 bytes available.
KIS tasks for datasource are still running

if however, you do 3 before 2, (kill KIS supervisor before 'drop data' on data source) things work as expected....

update:

i can confirm that the remaining task didnt die even after a full day (taskDuration: 1H) and had to be killed manually.

**Comment by gianm** [comment]
It might be related to #2696, if you dropped a segment that was currently being handed-off. Is that what happened?

**Comment by pdeva** [comment]
i dont think so. this bug is super easy to reproduce following the steps mentioned though.
