### ISSUE TITLE
Kafka Indexing Service: Support to read data from record headers of a topic.

### ISSUE THREAD

**Issue by jadireddi** [apache/druid#7539]
Can we extend current functionality of reading `record` data from a kafka topic , to even support reading fields present in `headers` of a record. 

If the `header field` is configured  by the user to read it's value by mentioning it in `metricsSpec` of `supervisor spec`,  Kafka-indexing-service  can support  reading the data of the field from the record headers and dump it in Druid.

If it's a valid proposal, I am open to contribute to this PR.

**Comment by vengateshs** [comment]
I've a similar requirement. Is it possible to reopen this ticket?
