### ISSUE TITLE
How to specify granularity in my groupby type SQL query

### ISSUE THREAD

**Issue by DockerLive** [apache/druid#7581]
In the SQL document I have only seen Timeseries granularity formatted in json using FLOOR(__time TO <unit>) or TIME_FLOOR(__time, period).How TO use this feature in SQL groupby queries such as groupby FLOOR(__time TO DAY), c2, c3;Granularity convert FLOOR(__time TO DAY) TO json format;I don't know how to use it in SQL

**Comment by xueyumusic** [comment]
Hi, @DockerLive ,  there is an [example](https://github.com/apache/incubator-druid/blob/master/sql/src/test/java/org/apache/druid/sql/calcite/CalciteQueryTest.java#L4094), maybe you could refer.

**Comment by DockerLive** [comment]
> Hi, @DockerLive , there is an [example](https://github.com/apache/incubator-druid/blob/master/sql/src/test/java/org/apache/druid/sql/calcite/CalciteQueryTest.java#L4094), maybe you could refer.

TKS, but I found an example  :  GROUP BY FLOOR(__time to hour), dim1      
when group by   Multiple fields 
the ".setGranularity(Granularities.ALL)"   always "all"

**Comment by shizhengchao** [comment]
Hi, @DockerLive ，I have the same question. Do you know the answer?

**Comment by gianm** [comment]
See #7592

**Comment by Mrxiashu** [comment]
It seems that this problem is still not resolved in version 0.21.1
