### ISSUE TITLE
Support for Datasource and Column comments

### ISSUE THREAD

**Issue by john-bodley** [apache/druid#7586]
### Description

Many databases (Hive, MySQL, Postgres, SQLite, etc.) support column and table (datasource) comments which help to provide additional context. I was wondering whether there were any plans to provide similar functionality in Druid?

**Comment by vogievetsky** [comment]
OMG yes, a million times yes. There is definitely some overhead with column comments as they would be propagated with each segment but it would enable some great abilities things with features like https://github.com/apache/incubator-druid/pull/7572 where a high level comment could be assigned to the auto created columns to later better be able to 're-inflate' the spec for repeated ingestion.

**Comment by himanshug** [comment]
For consideration of implementors: At the lowest storage level of segment , there is provision of storing "segment level metadata" which currently has "aggregators" and "granularity" used while indexing to generate that segment, these are used to power "queryGranularity" and "aggregators" analysis types in segmentMetadata query. Technically speaking, any information could be stored there. So, if we decide to store comments at segment level then that is the place.

Or, we could think about something drastically different e.g. having concept of "dataSource metadata" stored in metadataStore for these kind of things.
