### ISSUE TITLE
An question about groupby type SQL query

### ISSUE THREAD

**Issue by shizhengchao** [apache/druid#7592]
How to convert a group by into SQL Query. for example:
```json
{
  "queryType": "groupBy",
  "dataSource": "send_101",
  "granularity": "day",
  "dimensions": ["company_id"],
  "limitSpec": { "type": "default", "limit": 5000, "columns": ["company_id"] },
  "aggregations":[
      {
          "type":"longSum",
          "name":"sendCount",
          "fieldName":"drop_send_count",
          "expression":null
      }
  ],
  "intervals":{
      "type":"intervals",
      "intervals":[
          "2019-05-01T00:00:00.000Z/2019-05-06T00:00:00.001Z"
      ]
  }
}
```
convert to sql query, is like this?
```sql
SELECT
    FLOOR(__time TO DAY) AS DayTime,
    "company_id",
	SUM(drop_send_count) AS DropSendCount
FROM
	send_101
WHERE
	"__time" BETWEEN TIMESTAMP '2019-05-01 00:00:00'
AND TIMESTAMP '2019-05-06 00:00:00'
GROUP BY
	FLOOR(__time TO DAY), "company_id"
```
but, this sql is grouped by two dims。
EXPLAIN PLAN FOR above the sql，i found the granularity always "all"， 
so how to specify granularity in my groupby type SQL query

**Comment by xueyumusic** [comment]
It looks that when translating sql to `GroupByQuery`, [granularities is always set as `ALL`](https://github.com/apache/incubator-druid/blob/master/sql/src/main/java/org/apache/druid/sql/calcite/rel/DruidQuery.java#L958).
Is this a bug or specifically setted? @gianm @clintropolis @justinborromeo

**Comment by gianm** [comment]
I can't find the issue number right now, but essentially the reason for this is that 'granularity' for groupBy does not work the way that you would expect for a SQL GROUP BY when there's an ORDER BY or a LIMIT clause, so it cannot be used by the SQL planner. I think the issue was that dimension ordering is applied within each granular bucket for groupBy, rather than across all buckets as you would expect with SQL.

However, I would like to optimize the execution of `FLOOR(__time TO DAY)` enough that this is not an issue perf-wise. That seems like a good direction to me.

**Comment by deng2** [comment]
> I can't find the issue number right now, but essentially the reason for this is that 'granularity' for groupBy does not work the way that you would expect for a SQL GROUP BY when there's an ORDER BY or a LIMIT clause, so it cannot be used by the SQL planner. I think the issue was that dimension ordering is applied within each granular bucket for groupBy, rather than across all buckets as you would expect with SQL.
> 
> However, I would like to optimize the execution of `FLOOR(__time TO DAY)` enough that this is not an issue perf-wise. That seems like a good direction to me.



> I can't find the issue number right now, but essentially the reason for this is that 'granularity' for groupBy does not work the way that you would expect for a SQL GROUP BY when there's an ORDER BY or a LIMIT clause, so it cannot be used by the SQL planner. I think the issue was that dimension ordering is applied within each granular bucket for groupBy, rather than across all buckets as you would expect with SQL.
> 
> However, I would like to optimize the execution of `FLOOR(__time TO DAY)` enough that this is not an issue perf-wise. That seems like a good direction to me.

I am not using order by or limit clause in my SQL. It still uses the all granularity. Will we fix this?
```
select
    TIME_FLOOR(__time, 'PT1H', TIME_PARSE('2020-03-01T04:00+12:00'), 'Pacific/Kwajalein') as __timestamp,
    app, metric_name,
    count(*) as __count,
    sum(metric_value) as __sum
from viaops_metric_specguide
where
    (
        (__time >= TIME_PARSE('2020-02-23T04:00+12:00') and __time < TIME_PARSE('2020-03-01T04:00+12:00')) or
        (__time >= TIME_PARSE('2020-02-16T04:00+12:00') and __time < TIME_PARSE('2020-02-23T04:00+12:00')) or
        (__time >= TIME_PARSE('2020-02-09T04:00+12:00') and __time < TIME_PARSE('2020-02-16T04:00+12:00')) or
        (__time >= TIME_PARSE('2020-02-02T04:00+12:00') and __time < TIME_PARSE('2020-02-09T04:00+12:00')) or
        (__time >= TIME_PARSE('2020-01-26T04:00+12:00') and __time < TIME_PARSE('2020-02-02T04:00+12:00'))
    )
    and metric_name = 'Successful API Attempt'
    and app = 'Quantum'
    and api in (
          '',
          'stbDeviceEdgeRefresh',
          'deviceEdgeDevices',
          'avappsTermsAndConditions',
          'viewingHistoryEdgeViewingHistory',
          'loginEdgeSessionInfo',
          'searchEdgeSavedSearchRecent',
          'searchEdgeUnfiltered',
          'networkSettingsEdgeSettings',
          'viewingHistoryEdgeCollated',
          'watchListEdgeWatchList',
          'lrmEdgeEntitlements',
          'companionDevicesEdgeHandoff',
          'searchedgeV1CatalogUnfiltered',
          'loginEdgeLogin',
          'savedSearchEdgeSavedSearch'
    )
group by 1, 2, 3
```
