### ISSUE TITLE
Add ability for task and supervisor to recall the exact spec that was sent to them

### ISSUE THREAD

**Issue by vogievetsky** [apache/druid#7631]
### Description

It would be helpful if a task / supervisor could recall the exact JSON spec that was sent to it rather than on that has been through Jackson.

### Motivation

This would greatly improve the usability of any tool that sends a spec to Druid such as the new [data loader](https://github.com/apache/incubator-druid/issues/7502) and then expects to retrieve it. Right now all the default values are inlined by Jackson which means that some information is lost (i.e. did the user really set `taskStatusCheckPeriodMs: 1000` or was that the inlined default?)

**Comment by shivtools** [comment]
@vogievetsky do you have any thoughts on what would be the optimal place to store JSON specs for retrieval?

**Comment by glasser** [comment]
This was inspired by a comment of mine at a meetup last night, about how we find a tool we built that diffs a spec against the currently-deployed version of it useful but how it requires us to normalize the spec via some hacky "link against druid server libraries, set up jackson with lots of null injected objects" stuff.

The feature described here would solve that problem.  Another alternative for my particular use case would be a way for endpoints to normalize specs for you — eg, maybe a convention where a certain HTTP header or query parameter passed to a POST API means "don't actually apply this spec, just round-trip it through serialization and return the output".  I don't know if that would help with the data loader GUI!
