### ISSUE TITLE
longMin/longMax has different result, should unify?

### ISSUE THREAD

**Issue by dijkspicy** [apache/druid#7726]
two sql statement: (col < 0) is always false
1. select max(col) filter(where col < 0) from datasource;
2. select max(col) from datasource where col <0;

we convert these two into two http message while both use longMax aggregator, but 1. sql will return Long.MIN_VALUE, 2. sql will return empty. should these two results combined one?

**Comment by gianm** [comment]
What would SQL standard behavior be?

I think we're not standard for query (2), it should probably return `null`. I'm not sure what query (1) should return.
