### ISSUE TITLE
regression: queries unnecessary pushed down to historicals

### ISSUE THREAD

**Issue by pdeva** [apache/druid#7819]
### Affected Version
druid-0.14.2-incubating

### Description

our segments are hour long (with 1 minute granularity).

However, we are noticing that queries with short time intervals (1 min to 5 mins) that should be handled by KIS tasks on middle managers are being pushed down to historicals for no reason.

for example, the query below covers a 5 minute time range, and is still pushed down to historical for no reason.  

This seems to be a regression which was introduced in some recent version of druid, maybe 0.12 or something, since we didn't see this behavior previously.

Logged query in historical logs:

```js
{
  "queryType": "groupBy",
  "dataSource": {
    "type": "table",
    "name": "apm-minute"
  },
  "intervals": {
    "type": "segments",
    "segments": [
      {
        "itvl": "2019-06-03T02:22:00.000Z/2019-06-03T02:27:00.000Z",
        "ver": "2019-06-02T23:58:59.432Z",
        "part": 0
      }
    ]
  },
  "virtualColumns": [],
  "filter": {
    "type": "and",
    "fields": [
      {
        "type": "selector",
        "dimension": "name",
        "value": "JVM/Memory/HeapMax",
        "extractionFn": null
      },
      {
        "type": "selector",
        "dimension": "jvmid",
        "value": "xxx",
        "extractionFn": null
      }
    ]
  },
  "granularity": {
    "type": "period",
    "period": "PT129600M",
    "timeZone": "UTC",
    "origin": "2019-06-03T02:22:00.000Z"
  },
  "dimensions": [
    {
      "type": "LegacyDimensionSpec",
      "dimension": "name",
      "outputName": "name",
      "outputType": "STRING"
    }
  ],
  "aggregations": [
    {
      "type": "doubleSum",
      "name": "value",
      "fieldName": "value",
      "expression": null
    }
  ],
  "postAggregations": [],
  "having": null,
  "limitSpec": {
    "type": "NoopLimitSpec"
  },
  "context": {
    "applyLimitPushDown": false,
    "defaultTimeout": 300000,
    "finalize": false,
    "groupByOutermost": false,
    "groupByStrategy": "v2",
    "maxQueuedBytes": 0,
    "maxScatterGatherBytes": 9223372036854775807,
    "queryFailTime": 1559529245069,
    "queryId": "f1f0e693-dedb-40fb-8616-06143f4e1639",
    "timeout": 300000
  },
  "descending": false
}
```

**Comment by jihoonson** [comment]
This issue is not about Apache Druid, but some Imply Version. Please use the right channel. Imply user group is https://groups.google.com/forum/#!forum/imply-user-group.

**Comment by pdeva** [comment]
updated to point to druid version instead of imply. can the ticket be reopened now?

**Comment by jihoonson** [comment]
This was changed on purposed. See https://github.com/apache/incubator-druid/pull/4764 for details.

**Comment by pdeva** [comment]
hmm i not sure if #4764 applies to this.
we are quering is the most recent 5 minutes of data.
So the segment being queried cannot possibly be in historical since its not even been persisted yet.
So shouldn't historical be skipped altogether in this case?

**Comment by jihoonson** [comment]
That sounds strange. It shouldn't happen. I'm reopening this issue.

What kind of symptoms are you seeing? Is your query result empty? or do you see any error in brokers?

**Comment by pdeva** [comment]
well what's mysterious is that the queries themselves (to the broker) return correct results without any errors..

**Comment by pdeva** [comment]
any particular log setting you can recommend turning on on any of the nodes to get further insight on this issue?

**Comment by pdeva** [comment]
this issue is still present in 0.16.0

**Comment by gianm** [comment]
I would double check to make sure there aren't any historical segments covering this time range. The `sys.segments` table should help: https://druid.apache.org/docs/latest/querying/sql#system-schema

**Comment by pdeva** [comment]
nope. as mentioned earlier we are only querying the last 5 mins of data and our segments are multi hour long, so no chance for them to be in historical
