### ISSUE TITLE
Query like collect_list and collect_set support

### ISSUE THREAD

**Issue by xueyumusic** [apache/druid#7896]
When doing data statistic and anlysis, it often uses query like `concat_ws(',',collect_list(coupon_id))` after groupby. Could `collect_list` and `collect_set` be an appropriate query in druid? I found it looks a bit hard when implement collect_list as a kind of Aggregator. When implementing BufferedAggregator it does not have fixed bytebuf length and MaxIntermediateSize...

**Comment by pzhdfy** [comment]
As a workround, you can implement BufferedAggregator on heap.
I have done a BufferedAggregator on heap.

extensions-contrib/unique/src/main/java/org/apache/druid/query/aggregation/unique/UniqueBufferAggregator.java
https://github.com/apache/incubator-druid/pull/7594
