### ISSUE TITLE
Consider adding support for a pre-transform filter for transform specs

### ISSUE THREAD

**Issue by jon-wei** [apache/druid#7970]
A user asked the following on the mailing list: https://groups.google.com/d/msg/druid-user/5QfVuff8MJw/65w9qsZ_BQAJ

> I've noticed that in ingestion, when specifying filters section in transformSpec, I can only filter only fields that are in the dimensions list. Even if the field is present in the raw data, if it does not appear in the dimensions list the filter won't consider that field.
This creates a situation where I need to add a field I do not care about to the Data Source's dimensions even though I do not care about that field apart from filtering purposes.
>
>How can we work around this?

Transform spec filters are currently applied after the transforms:

```
/**
   * Transforms an input row, or returns null if the row should be filtered out.
   *
   * @param row the input row
   */
  @Nullable
  public InputRow transform(@Nullable final InputRow row)
  {
    if (row == null) {
      return null;
    }

    final InputRow transformedRow;

    if (transforms.isEmpty()) {
      transformedRow = row;
    } else {
      transformedRow = new TransformedInputRow(row, transforms);
    }

    if (valueMatcher != null) {
      rowSupplierForValueMatcher.set(transformedRow);
      if (!valueMatcher.matches()) {
        return null;
      }
    }

    return transformedRow;
  }
```

If pre-transform filters were supported, you could filter on a column and apply a transform to null out the filter column so that it's not written to the final segments, for cases where the user doesn't want to keep the filter column.

Maybe there are better ways to support that use case as well.

**Comment by vogievetsky** [comment]
This is related to https://github.com/apache/incubator-druid/issues/7952 right? Ideally both transforms and filters would work on all columns regardless of whether the column is in the dimension list or not.

**Comment by shizhengchao** [comment]
> This creates a situation where I need to add a field I do not care about to the Data Source's dim

i don't think so,because I had used it like this. i can give you my json task:

```json
{
  "type": "kafka",
  "dataSchema": {
    "dataSource": "demo",
    "parser": {
      "type": "string",
      "parseSpec": {
        "format": "json",
        "timestampSpec": {
          "column": "timestamp",
          "format": "yyyy-MM-dd HH:mm:ss"
        },
        "dimensionsSpec": {
          "dimensions": [
            "user_id",
            "express_company_id"
          ]
        }
      }
    },
    "metricsSpec": [
      {
        "name": "count",
        "type": "count"
      },
      {
        "name": "drop_count",
        "fieldName": "metric_count",
        "type": "longSum"
      },
      {
        "name": "freight",
        "fieldName": "freight",
        "type": "longSum"
      }
    ],
    "granularitySpec": {
      "type": "uniform",
      "segmentGranularity": "month",
      "queryGranularity": "minute",
      "rollup": true
    },
    "transformSpec": {
      "filter": {
        "type": "selector",
        "dimension": "send_status",
        "value": "101"
      }
    }
  },
  "tuningConfig": {
    "type": "kafka",
    "intermediatePersistPeriod" : "PT10M"
  },
  "ioConfig": {
    "topic": "SendForDruid",
    "consumerProperties": {
      "bootstrap.servers": "localhost:9092"
    },
    "useEarliestOffset": true,
    "taskCount": 1,
    "replicas": 1,
    "taskDuration": "P1D"
  }
}
```
in my `transformSpec`, i can use filter fields that are not in the dimensions list.
