### ISSUE TITLE
Compaction Task Can not config segmentGranularity

### ISSUE THREAD

**Issue by shizhengchao** [apache/druid#7988]
if   `keepSegmentGranularity` is set to False, but where is to set `segmentGranularity`, 
As shown below：
@gianm 

### Affected Version
0.14.1
### Description
![image](https://user-images.githubusercontent.com/22866465/60312991-fae20400-998f-11e9-8c56-1b25473ce44e.png)

**Comment by shizhengchao** [comment]
`interval `  also  can not config.

**Comment by jihoonson** [comment]
Hi @shizhengchao `segmentGranularity` is not supported for auto compaction yet.

**Comment by liuzibei2004** [comment]
a very useful feature，hope could be supported soon
