### ISSUE TITLE
index hadoop task generate IncompletePartitions

### ISSUE THREAD

**Issue by hellobabygogo** [apache/druid#8009]
index hadoop task generate IncompletePartitions when used HashedPartitionsSpec
which cased query result is empty.

### Affected Version

0.12.3

### Description
config:
`"partitionsSpec" : {
        "type" : "hashed",
        "targetPartitionSize" : -1,
        "maxPartitionSize" : -1,
        "assumeGrouped" : false,
        "numShards" : 5,
        "partitionDimensions" : [ ]
      },`

segments:
 test_hadoop_task_2019-06-29T00:00:00.000Z_2019-06-30T00:00:00.000Z_2019-07-01T01:17:02.185Z_1 
 test_hadoop_task_2019-06-29T00:00:00.000Z_2019-06-30T00:00:00.000Z_2019-07-01T01:17:02.185Z_3 

query:
`{
	"query":"select count(*) from \"test_hadoop_task\" where __time > '2019-06-29 08:00:00' and __time < '2019-06-30 08:00:00'",
	"context":{
		"sqlTimeZone":"Asia/Shanghai"
	}
}`

query result: []

**Comment by vogievetsky** [comment]
could you please run:

```sql
SELECT *
FROM sys.segments
WHERE segment_id = 'test_hadoop_task_2019-06-29T00:00:00.000Z_2019-06-30T00:00:00.000Z_2019-07-01T01:17:02.185Z_1'
```

And post the results here?

**Comment by hellobabygogo** [comment]
> could you please run:
> 
> ```sql
> SELECT *
> FROM sys.segments
> WHERE segment_id = 'test_hadoop_task_2019-06-29T00:00:00.000Z_2019-06-30T00:00:00.000Z_2019-07-01T01:17:02.185Z_1'
> ```
> 
> And post the results here?

hi vogievetsky,
Thanks for your reply! the query result is empty. because the segments in test_hadoop_task is IncompletePartitions
