### ISSUE TITLE
Query statement generates an exception

### ISSUE THREAD

**Issue by shuaidonga** [apache/druid#8121]
My commad is：
SELECT * FROM http ORDER BY LENGTH("request.body") DESC

happend ：
Unknown exception / Cannot build plan for query: SELECT * FROM (SELECT * FROM http ORDER BY LENGTH("request.body") DESC) LIMIT 5000 / org.apache.druid.java.util.common.ISE

**Comment by vogievetsky** [comment]
you can not do a raw select query (non group by) in Druid that orders by something other than `__time`
