### ISSUE TITLE
SQL where equals subquery cannot build query plan

### ISSUE THREAD

**Issue by saulfrank** [apache/druid#8123]
### Affected Version

Version 0.15.0

### Description
This query produces: Unknown exception (org.apache.druid.java.util.common.ISE): Cannot build plan for query

select * from "druid"."table"
where __time = (
select max(__time) as file_date from "druid"."table")

I also tried this on the date field but got the same:

select * from "druid"."table"
where file_date = (
select max(file_date) as file_date from "druid"."table")

I would have thought this would work?

**Comment by vogievetsky** [comment]
Looks like you want to look at the last event (or few events) in your datasource. As of Druid 0.15.0 you can do:

```
select * from "druid"."table" ORDER BY __time DESC LIMIT 1
```

(or limit more than 1)

**Comment by saulfrank** [comment]
There are multiple records so that would have to be in the subquery. I
tried putting that in the subquery and it still doesn’t work.

So where __time = (select __time from ...) doesn’t work.

**Comment by vogievetsky** [comment]
I think the issue in your query is that it can not build a query plan on an aggregate.

I just tested this:

```sql
select * from "wikipedia"
where "__time" IN (
  select "__time"
  from "wikipedia"
  WHERE "__time" >= CURRENT_TIMESTAMP - INTERVAL '1' HOUR
  GROUP BY 1
  ORDER BY "__time"
  DESC LIMIT 1
)
```

And it seems to work. 

![image](https://user-images.githubusercontent.com/177816/61673029-c3225f80-aca2-11e9-9bb0-4d753878ff4f.png)

A couple of notes / thoughts:

1. I am not sure `x = (sub query)` is legal in SQL at all, I know `IN` is fine and that also makes more sense to me, I mean the sub query will be a set right?
2. Notice the filter on the inner query, filters make Druid super duper fast, scanning over all the data is not a good use of your servers. Any kind of dynamic filter that you can add to the inner query will do wonders to the speed.
