### ISSUE TITLE
Is there a way to view converted native query for a given sql statement

### ISSUE THREAD

**Issue by vikramarsid** [apache/druid#8130]
Is it possible to convert a SQL statement to a native query? Can we view(any logging option) native queries generated by the router process by converting sql query?

**Comment by vogievetsky** [comment]
Yes! Search https://druid.apache.org/docs/latest/querying/sql.html for `EXPLAIN`

Or in the console:

![image](https://user-images.githubusercontent.com/177816/61673178-4e035a00-aca3-11e9-84b8-707fb2d835e2.png)

To see:

![image](https://user-images.githubusercontent.com/177816/61673197-5bb8df80-aca3-11e9-85f6-b22283279535.png)

**Comment by vikramarsid** [comment]
@vogievetsky  Thank you, appreciate your quick response. I have tried  `EXPLAIN PLAN FOR` for the SQL statement and I get back below text which is not a valid native query json.
Do you have any thought here?
TIA
```
DruidNestedGroupBy(queryBuilder=[DruidQueryBuilder{filter=null, selectProjection=null, grouping=Grouping{dimensions=[DimensionExpression{outputName='d0', expression=DruidExpression{simpleExtraction=d0, expression='"d0"'}, outputType=STRING}, DimensionExpression{outputName='d1', expression=DruidExpression{simpleExtraction=d2, expression='"d2"'}, outputType=STRING}, DimensionExpression{outputName='d2', expression=DruidExpression{simpleExtraction=d3, expression='"d3"'}, outputType=STRING}], aggregations=[Aggregation{virtualColumns=[], aggregatorFactories=[FilteredAggregatorFactory{delegate=CountAggregatorFactory{name='a0'}, filter=!d1 = null}], postAggregator=null}, Aggregation{virtualColumns=[], aggregatorFactories=[LongSumAggregatorFactory{fieldName='a0', expression='null', name='a1'}], postAggregator=null}, Aggregation{virtualColumns=[], aggregatorFactories=[LongMinAggregatorFactory{fieldName='a2', expression='null', name='a2'}], postAggregator=null}, Aggregation{virtualColumns=[], aggregatorFactories=[LongMaxAggregatorFactory{fieldName='a2', expression='null', name='a3'}], postAggregator=null}]}, having=a0 as numeric < 5, limitSpec=null, rowType=RecordType(VARCHAR signature_name, VARCHAR signature_id, VARCHAR appliance_type, BIGINT total_customer_hits, BIGINT total_hits, TIMESTAMP(0) first_seen, TIMESTAMP(0) last_seen), outputRowSignature=RowSignature{d2:STRING, d1:STRING, d0:STRING, a0:LONG, a1:LONG, a2:LONG, a3:LONG}}])
```

**Comment by vogievetsky** [comment]
Oh yeah, some (more complex) queries it can not output as a JSON plan... this might be a good enhancement request.
Could you please share the query that generated that plan?

**Comment by vikramarsid** [comment]
@vogievetsky Thank you for confirming for a new feature request. Meanwhile, is there a way I can get the JSON native query from broker logs? TIA

Here are the complex query and plan

SQL Statement:
```
SELECT s_name, s_id, a_type, sum("hits") as total_hits, count(DISTINCT company_name) as unique_companies, min(__time) as first_seen, max(__time) as last_seen 
FROM wikipedia
WHERE lower(s_name) LIKE '%roger%'
GROUP BY s_name, s_id, a_type
HAVING count(DISTINCT company_name) < 5
```

Plan:
```
DruidNestedGroupBy(queryBuilder=[DruidQueryBuilder{filter=null, selectProjection=null, grouping=Grouping{dimensions=[DimensionExpression{outputName='d0', expression=DruidExpression{simpleExtraction=d0, expression='"d0"'}, outputType=STRING}, DimensionExpression{outputName='d1', expression=DruidExpression{simpleExtraction=d2, expression='"d2"'}, outputType=STRING}, DimensionExpression{outputName='d2', expression=DruidExpression{simpleExtraction=d3, expression='"d3"'}, outputType=STRING}], aggregations=[Aggregation{virtualColumns=[], aggregatorFactories=[FilteredAggregatorFactory{delegate=CountAggregatorFactory{name='a0'}, filter=!d1 = null}], postAggregator=null}, Aggregation{virtualColumns=[], aggregatorFactories=[LongSumAggregatorFactory{fieldName='a0', expression='null', name='a1'}], postAggregator=null}, Aggregation{virtualColumns=[], aggregatorFactories=[LongMinAggregatorFactory{fieldName='a2', expression='null', name='a2'}], postAggregator=null}, Aggregation{virtualColumns=[], aggregatorFactories=[LongMaxAggregatorFactory{fieldName='a2', expression='null', name='a3'}], postAggregator=null}]}, having=a0 as numeric < 5, limitSpec=null, rowType=RecordType(VARCHAR signature_name, VARCHAR signature_id, VARCHAR appliance_type, BIGINT total_customer_hits, BIGINT total_hits, TIMESTAMP(0) first_seen, TIMESTAMP(0) last_seen), outputRowSignature=RowSignature{d2:STRING, d1:STRING, d0:STRING, a0:LONG, a1:LONG, a2:LONG, a3:LONG}}])
```

**Comment by himanshug** [comment]
@vikramarsid Brokers optionally log queries to "request log" (see https://druid.apache.org/docs/latest/configuration/index.html#request-logging ) , you might get it from there .

**Comment by vikramarsid** [comment]
@himanshug  Thank you! I can see native JSON queries for SQL queries in the request logs. 
Quick question: For some queries, I see intervals = "-146136543-09-08T08:23:32.096Z/146140482-04-24T15:36:27.903Z"
I don't think it is a valid ISO 8601 but still query work, do you know if that interval has any significance?

I found few references in druid sql tests

https://github.com/apache/incubator-druid/blob/7baa33049cde3c3751037f014f468db4beb41a4c/sql/src/test/java/org/apache/druid/sql/calcite/http/SqlResourceTest.java#L610

https://github.com/apache/incubator-druid/blob/ea4bad783691da2b8530eb8ad3daf6a0ad2d0a37/sql/src/test/java/org/apache/druid/sql/calcite/CalciteQueryTest.java#L4407

https://github.com/apache/incubator-druid/blob/ea4bad783691da2b8530eb8ad3daf6a0ad2d0a37/sql/src/test/java/org/apache/druid/sql/avatica/DruidAvaticaHandlerTest.java#L349

**Comment by sashidhar** [comment]
@vikramarsid , as far as I understand this means there is no filter on the timestamp dimension, generating an interval covering the time range (−∞,+∞).
