### ISSUE TITLE
allow decommissioning Middle Manager nodes

### ISSUE THREAD

**Issue by pdeva** [apache/druid#8175]
This proposal is written with Kafka Indexing Tasks in mind only.
Please add your thoughts about other indexing tasks.

### Description

Currently removing and adding a new MM node causes temporary phase of data blindness, essentially as good as 'downtime' for users.

Allow decommissioning of Middle Manager nodes, so that new nodes can be added and tasks can be rescheduled on those instantly and without any temporary loss of data.

### Motivation

Currently if you want to remove and add a new MM node, here is the experience. 

Assuming 2 existing nodes A & B, with datasource DS with 2 replicas of KIS tasks.

1. Add a new MM node C
1. Shut down MM node B.
1. DS KIS tasks on node B remain dormant for about 15 minutes
1. after 15 mins the task is set to 'failed' state and rescheduled on node C.
1. since task has to read from begining, the brokers temporary see no data for the last 15 mins or so. thus essentially causing a 'downtime'.
1. after a few minutes node C has fully ingested incoming data and things go back to normal

Ideal scenarios:

1. add new node C
2. decommission node B
3. tasks on node B immediately die with status 'success' and new ones are spun up on Node C
4. no temporary date loss is seen by the brokers

its similar to how currently if you change a supervisor task definition, it starts a new task transparently without any temporary data loss/blindess to the brokers.

**Comment by himanshug** [comment]
have you tried some combination of `<MiddleManager_IP:PORT>/druid/worker/v1/disable` as described in https://druid.apache.org/docs/latest/operations/rolling-updates.html#rolling-restart-graceful-termination-based ?

**Comment by pdeva** [comment]
hmm i did overlook it indeed.

the docs say:

```
 Tasks that have already started will run to completion
```

does that mean if we have a task with an 8 hour duration, we need to wait 8 hours?

**Comment by himanshug** [comment]
> does that mean if we have a task with an 8 hour duration, we need to wait 8 hours?

in general, yes
however, after disabling the MM
you have the option of "killing" those tasks running on the disabled MM , kafka supervisor will automatically re-create them and they would not go to disabled MM
OR, I think, kafka supervisor has a "suspend/resume" feature where you can send a request to suspend it temporarily which will wrap up the current state. and then you can resume which will re-create the tasks.

**Comment by pdeva** [comment]
so there is something i dont understand:

since KIS tasks dont persist the data until their handoff, wont killing or suspending them make them lose their current data? then when they restart, they will need to re-read all that data for the segment from the begining, and during that time if the broker query reaches that 'restarted' task, it will see no value for that timerange.

**Comment by himanshug** [comment]
> since KIS tasks dont persist the data until their handoff, wont killing or suspending them make them lose their current data? then when they restart, they will need to re-read all that data for the segment from the begining, and during that time if the broker query reaches that 'restarted' task, it will see no value for that timerange.

IIRC  if you used suspend/resume , supervisor would create a new checkpoint based on current state of tasks and publish data upto that checkpoint, so resume later will really do a resume.
above wouldn't be true if you just killed the tasks

**Comment by pdeva** [comment]
it still seems a lot of manual work to manually disable every task.
what if you have say 25 tasks running on a MM node. thats a lot to go through to disable and resume each one.
there should be a single api call which does this to make the decommissioning use case easier.

**Comment by himanshug** [comment]
oh I meant the suspend/resume on kafka supervisor , not on the tasks themselves, which is a single API call for one supervisor. See https://druid.apache.org/docs/latest/development/extensions-core/kafka-ingestion#suspending-and-resuming-supervisors

**Comment by pdeva** [comment]
that sounds even worse. since suspending a supervisor will suspend _all_ KIS tasks. so between manually suspending and resuming a supervisor, there will be downtime where the broker cannot read realtime data for that datasource.

also, as per my previous post, this will have to be done for every single supervisor manually. so if there are 25 supervisors, you will need to suspend/resume each one manually (and incur downtime for each one too)

**Comment by himanshug** [comment]
yes you are right on that.
