### ISSUE TITLE
set druid.coordinator.kill.pendingSegments.on to true and remove config option

### ISSUE THREAD

**Issue by pdeva** [apache/druid#8270]
### Description

1. set `druid.coordinator.kill.pendingSegments.on` to `true` by default
2. remove config option entirely

### Motivation

There is no reason to set it to `false` and no downside to setting it to `true`.

If its going to be `true` always, it makes sense to remove the config option entirely, since it reduces the overhead of understanding one more config for the user.

**Comment by xvrl** [comment]
this has been fixed as part of #9385
