### ISSUE TITLE
what is the data store in "/tmp/hadoop-druid/mapred/local/localRunner/druid/jobcache"

### ISSUE THREAD

**Issue by sekingme** [apache/druid#8290]
We found that  somtimes some tmpData will cache in "/tmp/hadoop-druid/mapred/local/localRunner/druid/jobcache", which is processing by middlemanager.

But we cannot find how to change this dir and what is this data.

Besides, there is difference data in this dir. Like: spill0.out、file.out、file.out.index

Confusing..,

**Comment by Observe-secretly** [comment]
My directory "/ tmp / hadoop-druid / mapred / local" has a lot of small files. He may have 5,636,271. Almost run out of "inode". I want to know how this directory is cleaned up, and also what he does.
