### ISSUE TITLE
improve Teamcity build speed

### ISSUE THREAD

**Issue by himanshug** [apache/druid#8366]
Teamcity check is great but takes about 100 mins to complete right now compared to travis build which finished in about 30 mins.
Ref : https://teamcity.jetbrains.com/viewLog.html?buildId=2490978&buildTypeId=OpenSourceProjects_Druid_InspectionsPullRequests

**Comment by ccaominh** [comment]
I have some ideas for this and the basic approach is to use travis to [launch the code inspections from the command line](https://www.jetbrains.com/help/idea/command-line-code-inspector.html) inside an intellij docker image. Some rough prototyping on my laptop shows the analysis completes in about 30 minutes for warnings and errors or about 20 minutes just errors. The drawback is that it likely won't have the nice TeamCity UI to browse the inspection report and view the delta, but it'll definitely be enough to detect if new errors are added and to print information about those errors.

**Comment by himanshug** [comment]
thanks , it might be good enough as long as all necessary info is present in the output .

really appreciate all your contributions towards making build improvements.

**Comment by leventov** [comment]
Or, the project could be moved to Gradle #7866 (which itself should be very good for development speed in many ways), and then IntelliJ's inspections are run using the [plugin](https://github.com/JetBrains/inspection-plugin).

**Comment by himanshug** [comment]
using the gradle pluging would make it possible to run teamcity locally but would that make the analysis happen faster ? is it currently slow because Teamcity allocates small/slow vm/container for executing the analysis ?

**Comment by leventov** [comment]
It may make the analysis happen faster at least because we may run only error inspection checks, but not warnings.

**Comment by himanshug** [comment]
> because we can run only error inspection checks, but not warnings.

is it not possible to adjust current teamcity build settings to do same i.e. just analyze for errors so that it runs faster ?

regarding using the gradle plugin and to decouple it from overall migration to gradle : is it possible to create a gradle based subproject/subdirectory just for teamcity?

**Comment by leventov** [comment]
> is it not possible to adjust current teamcity build settings to do same i.e. just analyze for errors so that it runs faster?

You should consult JetBrains support as documented [here](https://github.com/apache/incubator-druid/blob/master/dev/teamcity.md#contacting-teamcity-support-regarding-problems-with-builds).

**Comment by himanshug** [comment]
I asked because you proposed that it could be done with gradle plugin and I thought you would know whether it could be done on the current build :)

anyways, thanks for the link to documentation. I read through it and discovered that most of the analysis info is stored in `.idea/inspectionProfiles/Druid.xml` which has lines like....


```
$ fgrep "<inspection_tool" .idea/inspectionProfiles/Druid.xml | head
    <inspection_tool class="Annotator" enabled="true" level="WARNING" enabled_by_default="true" />
    <inspection_tool class="AntDuplicateTargetsInspection" enabled="true" level="WARNING" enabled_by_default="true" />
    <inspection_tool class="AntMissingPropertiesFileInspection" enabled="true" level="WARNING" enabled_by_default="true" />
    <inspection_tool class="AntResolveInspection" enabled="true" level="WARNING" enabled_by_default="true" />
    <inspection_tool class="ArrayEquality" enabled="true" level="ERROR" enabled_by_default="true" />
    <inspection_tool class="ArrayEquals" enabled="true" level="ERROR" enabled_by_default="true" />
    <inspection_tool class="ArrayHashCode" enabled="true" level="ERROR" enabled_by_default="true" />
    <inspection_tool class="ArrayObjectsEquals" enabled="true" level="ERROR" enabled_by_default="true" />
    <inspection_tool class="ArraysAsListWithZeroOrOneArgument" enabled="true" level="ERROR" enabled_by_default="true" />
    <inspection_tool class="AssertWithSideEffects" enabled="true" level="ERROR" enabled_by_default="true" />
```

that suggests to me that teamcity build is applying these listed tools while analyzing the code and tagging the violations as WARNING/ERROR/... based on the "level" attribute in there.

there are 142 of these inspection tools , 52 with level ERROR and 90 with rest.
```
$ fgrep "<inspection_tool" .idea/inspectionProfiles/Druid.xml | wc -l
     142
$ fgrep "<inspection_tool" .idea/inspectionProfiles/Druid.xml | grep 'level="ERROR"' | wc -l
      90
$ fgrep "<inspection_tool" .idea/inspectionProfiles/Druid.xml | grep -v 'level="ERROR"' | wc -l
      52
```

I am gonna do a quick PR that removes all `inspection_tool` tags that don't have level ERROR and that should probably make teamcity build only analyze for ERRORs and hopefully run significantly faster as well.
Note: inspection tools could also be disabled/enabled from Intellij IDE UI (Editor -> Inspections)

**Comment by leventov** [comment]
I think this is a bad idea because these warnings have a purpose - engineers who use IntelliJ see them as yellow highlighting and may change the smelly code immediately.

Also, there are a lot of warnings which are not in this XML. The XML lists just non-default settings. All inspections which are warnings by default are not listed.

**Comment by himanshug** [comment]
so , to me it seems , to have different behaviors,  we need to keep two separate xmls
one for teamcity which has stuff based on what we want to happen in teamcity build
and one for intellij IDE users for their local development
not ideal, but would work.

I still don't understand how gradle plugin would solve it though.

**Comment by leventov** [comment]
BTW there is a way to run inspections in Jenkins: https://dzone.com/articles/running-intellij-idea-in-jenkins. Maybe we can make it run in Travis CI, too. (I didn't research this question.)
