### ISSUE TITLE
Druid 0.15.1-incubating upgrade issue

### ISSUE THREAD

**Issue by chenrui333** [apache/druid#8401]
### Affected Version

Druid 0.15.1-incubating

### Description

In https://github.com/Homebrew/homebrew-core/pull/42693, I am trying to help upgrading the druid version, but somehow, I could not connect to `http://localhost:8083/status` when testing locally. 

I did not find any documentation about how to test single-server situation. So file this issue for some support.

**Comment by vogievetsky** [comment]
I see that in your homebrew PR you changed the URL to https://www.apache.org/dyn/closer.cgi?path=/incubator/druid/0.15.1-incubating/apache-druid-0.15.1-incubating-bin.tar.gz

That url does not lead a file, it is just a helper page to find the nearest mirror, does that URL need to link to a specific mirror? Something like https://www-eu.apache.org/dist/incubator/druid/0.15.1-incubating/apache-druid-0.15.1-incubating-bin.tar.gz ?

**Comment by chenrui333** [comment]
@vogievetsky  can you help with the brew upgrade?
