### ISSUE TITLE
Prohibit HashMap(capacity), HashMap(capacity, loadFactor), HashSet, LinkedHashMap constructors

### ISSUE THREAD

**Issue by leventov** [apache/druid#8423]
They are pretty much always misused. See [this SO answer](https://stackoverflow.com/a/30220944/648955) for the explanation. They should be prohibited using forbidden-apis with suggested alternatives: Guava's `Maps.new(Linked)HashMapWithExpectedSize()`, `Sets.newHashSetWithExpectedSize()`.

**Comment by leventov** [comment]
Also `LinkedHashSet`

**Comment by himanshug** [comment]
++++1
