### ISSUE TITLE
allow sharding of timeseries data

### ISSUE THREAD

**Issue by pdeva** [apache/druid#8611]
### Description

Allow sharding of a data by a dimension, eg `accountId`.

This way segments are stored 
1. per accounIid
2. and then for time range for that accountId

### Motivation

We use the terminology of 'small' and 'large' accounts below. Small and large here means small and large in terms of rows of data per account. So a small account may generate 500 rows per hour while a large account may generate 5M rows per hour.

Currently any query requires loading of all the segments for the time range of the query.

If you are storing data for multiple 'accounts' in a single druid cluster, then a query by a small account requires loading as many segments as a large account.

Ideally if a small account is making a query, the cluster should require minimal IO, and only require loading the segments for that particular account.

**Comment by vogievetsky** [comment]
Have you tried the secondary dimension partitioning?

![image](https://user-images.githubusercontent.com/177816/65917390-1b08d100-e38c-11e9-9d34-a18493e18a0a.png)
