### ISSUE TITLE
Can't handle BigInt in web console

### ISSUE THREAD

**Issue by Vaduz** [apache/druid#8617]
## Cause

v8 doesn't support BigInteger when it parse JSON string.

## Proposal

I couldn't figure out handling BigInt natively. But it's enough to handle numbers as string.  

Something like:

```js
JSON.parse(data, (k, v) => typeof v === 'number' ? v.toString() : v)
```

But this may break "Filter by" value feature.

## Affected Version

0.16.0 or lower (I guess all versions)

### Cluster size

* 2 x Master (8 CPU, 32GB Mem, SSD)
* 2 x Query (8 CPU, 32GB Mem, SSD)
* 2 x Data (20 CPU, 64GB Mem, SSD)

### Configurations in use

Cluster configuration is not relevant to this issue but configurations are blow.

* MySQL as metadata storage
* S3 as deep storage
* master jvm xmx: 24g
* broker jvm xmx: 12g
* router jvm xmx: 1g
* historical jvm xmx: 8g
* historical jvm max direct memory size: 25g
* druid_historical_processing_numThreads: 15
* druid_historical_processing_numMergeBuffers: 4
* druid_historical_processing_buffer_sizeBytes: 500000000
* druid_server_maxSize: 300000000000

### Steps to reproduce the problem

```sql
SELECT "id" FROM "table" WHERE "id" = 9223372036854775806
```

You'll see `9223372036854776000` in the output.

This might be an another issue. I can't filter the value by clicking the cell.
I got a following error.

```
Unknown exception / org.apache.calcite.runtime.CalciteContextException: From line 3, column 23 to line 3, column 41: Numeric literal '9223372036854776000' out of range / org.apache.calcite.tools.ValidationException
```

### Any debugging that I've already done

* Data ingestion has done properly
* Query that not using web console works

**Comment by vogievetsky** [comment]
Thanks for figuring that out. I just reproed using your exact example.
