### ISSUE TITLE
Null values not returned for group by JSON response

### ISSUE THREAD

**Issue by Tmb377** [apache/druid#8631]
### Affected Version

0.16.0

### Description
 
When querying with a group by query, if a dimension is null, it is filtered out of the JSON response. When `resultAsArray` is set to true, the null is returned, but if it is set to false, it is not included in the row. Here's an example with the same query with `resultAsArray` set to true and false:

When set to true, this is the resulting row:
`[
        1569801600000,
        null,
        100
    ]`

But when set to false,  this is the row: 
`{
        "version": "v1",
        "timestamp": "2019-09-30T00:00:00.000Z",
        "event": {
            "SomeAggregate": 100
        }
    }`

In previous versions, the dimension would be included with a null value. Our current workaround is to make it a lookup dimension with a mapping for empty string, but I'm not sure if there's a better way.

**Comment by shrutigs** [comment]
Hi,
Is there ETA for fix? The reponse  structure  has been changed from druid 0.15 to 0.16

**Comment by cvasii** [comment]
Hi,
Any updates?

**Comment by asdf2014** [comment]
@Tmb377 It could be an incompatible behavior caused by an additional filter condition of `row[i] != null` in `ResultRow#toMap`. However, I am not sure if it is necessary to ensure compatibility here. @gianm What do you think?

Related to https://github.com/apache/incubator-druid/pull/8196
