### ISSUE TITLE
Feature request to support  GREATEST/LEAST  function in Druid sql 

### ISSUE THREAD

**Issue by vaibhav-imply** [apache/druid#8679]
### Description
`Currently GREATEST/LEAST post-aggregators are available via native druid query. It will be great to have GREATEST/LEAST implementation of post-aggregators as Druid SQL functions.`

### Motivation

`It will make user's life easier as they always feel comfortable writing an SQL over JSON query.`

**Comment by aditya-r-m** [comment]
@gianm can we merge this?
