### ISSUE TITLE
Druid Docker Image

### ISSUE THREAD

**Issue by averma111** [apache/druid#8705]
Docker build is successful. While docker compose I am getting below error

Pulling coordinator (apache/incubator-druid:)...
ERROR: manifest for apache/incubator-druid:latest not found

**Comment by raymond-ong** [comment]
Docker newbie here. I think i am getting the same issue.
When I try to pull the docker image from https://hub.docker.com/r/apache/incubator-druid

> docker pull apache/incubator-druid

I am getting this error

> Using default tag: latest
Error response from daemon: manifest for apache/incubator-druid:latest not found: manifest unknown: manifest unknown

**Comment by himanshug** [comment]
if it helps, I have had success with
```
docker pull apache/incubator-druid:0.16.0-incubating
```

**Comment by himanshug** [comment]
FWIW, Dockerhub has some integration to automatically build the docker images , for ASF projects it is setup by asking Apache Infra ... something in the script used https://issues.apache.org/jira/browse/INFRA-18887 needs to likely change in order to push `latest` tag.

**Comment by mail2shobz** [comment]
> if it helps, I have had success with
> 
> ```
> docker pull apache/incubator-druid:0.16.0-incubating
> ```

This Worked Thanks alot.  also I don't know why the official docker hub registry is not working

**Comment by ncbooth** [comment]
This issue appears to still be happening both with the docker-compose.yml file and attempting to run docker pull apache/druid
