### ISSUE TITLE
Theta Sketch upfront uniform sampling probability setting

### ISSUE THREAD

**Issue by natsumehu** [apache/druid#8714]
Hi, Our dataset sometimes has to deal with highly partitioned/fragmented problems. This leads to thetasketch pretty big or even make the the query extremely computing intensive. We want to use the p-sampling or upfront setting of the theta sketch module to make it better. But it seems like it is not in the setting?

**Comment by gianm** [comment]
Are these config properties of the theta sketches in the datasketches library? If so, we should be able to add them to Druid's wrapper. Are you interested in doing a PR to the datasketches extension that does the necessary changes?

**Comment by natsumehu** [comment]
Sure, I will do that

**Comment by natsumehu** [comment]
@gianm Can you help review this pr? I'm new to the druid open source. The change is already deployed on our test clusters, seems ok. Thanks
