### ISSUE TITLE
"group.id" of ConsumerPropertie be replaced by "kafka-supervisor-%s" in kafka-indexing-service   

### ISSUE THREAD

**Issue by Elvis0607** [apache/druid#8715]
### Affected Version

druid-0.16.0-incubating

### Description

In the class org.apache.druid.indexing.kafka.KafkaRecordSupplier

the function getKafkaConsumer use default consumerConfigs to overwrite the user's consumerProperties

`private KafkaConsumer<byte[], byte[]> getKafkaConsumer()
  {
    final Map<String, Object> consumerConfigs = KafkaConsumerConfigs.getConsumerProperties();
    final Properties props = new Properties();
    addConsumerPropertiesFromConfig(props, sortingMapper, consumerProperties);
    props.putAll(consumerConfigs);
`

consumerConfigs is 
`public class KafkaConsumerConfigs
{
  public static Map<String, Object> getConsumerProperties()
  {
    final Map<String, Object> props = new HashMap<>();
    props.put("metadata.max.age.ms", "10000");
    props.put("group.id", StringUtils.format("kafka-supervisor-%s", RandomIdUtils.getRandomId()));
    props.put("auto.offset.reset", "none");
    props.put("enable.auto.commit", "false");
    props.put("isolation.level", "read_committed");
    return props;
  }
}
`

so the group.id of user's ConsumerProperties will be repalced by the consumerConfigs from KafkaConsumerConfigs.getConsumerProperties()

I think exchange the place of the 2 line will solve the problem

`addConsumerPropertiesFromConfig(props, sortingMapper, consumerProperties);
    props.putAll(consumerConfigs);`

the code 
`addConsumerPropertiesFromConfig(props,` sortingMapper, `consumerProperties);`
should be placed after the code
`props.putAll(consumerConfigs);`

**Comment by gianm** [comment]
Hi @Elvis0607, just wondering, why are you wanting to customize the consumer `group.id`? The design of Druid's Kafka indexing doesn't use Kafka consumer groups (Druid manages offsets itself). So the thinking was that it shouldn't matter what the `group.id` was set to.

If it matters for some reason, then yeah, switching those lines would be useful. Or maybe splitting the properties such that a user can override some but not others (for example, overriding `enable.auto.commit` would I think always be a bad idea).

**Comment by Elvis0607** [comment]
> Hi @Elvis0607, just wondering, why are you wanting to customize the consumer `group.id`? The design of Druid's Kafka indexing doesn't use Kafka consumer groups (Druid manages offsets itself). So the thinking was that it shouldn't matter what the `group.id` was set to.
> 
> If it matters for some reason, then yeah, switching those lines would be useful. Or maybe splitting the properties such that a user can override some but not others (for example, overriding `enable.auto.commit` would I think always be a bad idea).

Our kafka platform must be accessed with a assigned  group.id. So I think this place may be better if 
having  more choices

**Comment by kyostyle1** [comment]
I have this issue too.

**Comment by mjain1994** [comment]
I have this issue as well .Were you able to resolve ? @kyostyle1 @Elvis0607

**Comment by LeeMo2K10** [comment]
I have this issue too.

**Comment by FrankChen021** [comment]
@Elvis0607 @kyostyle1 @mjain1994 @LeeMo2K10 Could you tell me how does your kafka platform restrict client access by a pre-assigned group id ? 

Kafka clients provides two ways of API , auto and manual topic assignment. And group.id for manual topic assignment has no meaning. I mean, any Kafka admin platforms should also support this kind of use of kafka consumer API.

**Comment by kyostyle1** [comment]
@FrankChen021 In my company, any topic must be have ACL configure using Vault PKI. So we must define pre-assigned group.id to consume message.

**Comment by abhishekagarwal87** [comment]
The `group.id` is mainly used for broker managed client coordination which druid is doing by itself. Ideally, `group.id` should have no role in the message consumption path after the partitions are assigned. what errors/exceptions do you see in the tasks if you try to connect to the broker anyway. I am wondering where does this fail precisely.

**Comment by kyostyle1** [comment]
Basically, the connection was rejected by brokers. Errors details: Not authorized to access topics: [Topic authorization failed.]

**Comment by asdf2014** [comment]
@phuchuynh9994 Make sense to me. Otherwise, the Kafka business data with Consumer authentication enabled cannot be written to the Druid cluster. Maybe we should make the `group.id` option is configurable, but by default, we still generate it randomly.

cc @gianm

**Comment by FrankChen021** [comment]
I have not dive into Kafka to see which requests from consumer are limited by kafka brokers. As far as I know, poll operation of KafkaComsumer does not send `group.id` to kafka brokers which means that operation could not be restricted. 

Since kafka-acl allows ACLs to be configured on a specified consumer group, I think it makes sense to make `group.id` configurable.
