### ISSUE TITLE
Druid Task not getting started after submitting kafka supervisor spec

### ISSUE THREAD

**Issue by salmanbw** [apache/druid#8742]
Hi Team

I was running a druid kafka supervisor spec and it was working fine, data was also getting ingested into the datasource. But i had to increase the maxRowsPerSegment in the supervisor spec as kafka wasn't able to ingest data after it reaches limit. 

So i terminate the spec from overload console. And resubmitted the spec. It is reflecting in the supervisor spec but no task has been started. There is no task in the running task. 

Can you please help me with it.

**Comment by vogievetsky** [comment]
Hi! What version is this on?

I am really hoping you say 0.16.0. If so please let me know what is the detailed status shown in the unified console:

![image](https://user-images.githubusercontent.com/177816/67590786-c2212400-f710-11e9-83c6-f475bffc27d2.png)

**Comment by salmanbw** [comment]
We have 0.14.0 version.

**Comment by RestfulBlue** [comment]
is there any errors in overlord/coordinator logs?

**Comment by salmanbw** [comment]
No, there are no errors, the supervisors are running but no task is getting generated. Do you want me to share any screenshot. Please let me know
