### ISSUE TITLE
Test minor compaction for a single dataSource with kafka-indexing

### ISSUE THREAD

**Issue by ArtinTD** [apache/druid#8766]
Hi,

I just updated a druid cluster to 0.16.0 and I want to test minor compaction in it. because segment locking is an experimental feature I don't want to set `druid.indexer.tasklock.forceTimeChunkLock` to false in the overlord configuration. I want to test this on a single dataSource which has a kafka-based ingestion by submitting compaction tasks with segment lock on this dataSource. is there a way to set `forceTimeChunkLock` in a kafka supervisor config or can I directly submit a kafka-ingestion task without a supervisor with `forceTimeChunkLock` set to false in task context?

Either way I just want to test this feature without seting a clusterwide config.

**Comment by zenfenan** [comment]
@ArtinTD 

When you submit the Kafka ingestion spec, you can provide the context map with `forceTimeChunkLock` set to `false` like
```
{
  "type": "kafka",
  "ioConfig": {
     ...
  },
  "tuningConfig": {
     ...
  },
  "dataSchema": {
     ...
  },
  "context": {
    "forceTimeChunkLock": false
  }
}
```
