### ISSUE TITLE
Allow MILLISECOND as a synonym for NONE in queryGranularity

### ISSUE THREAD

**Issue by vogievetsky** [apache/druid#8781]
### Description

Taken from: https://github.com/apache/incubator-druid/pull/8763#discussion_r339420344

Right now the UI looks like this:

![image](https://user-images.githubusercontent.com/177816/67812480-8661c380-fa5c-11e9-8ca3-30b68b4f516b.png)

`NONE` really means `MILLISECOND` and it would be a lot clearer and cleaner if that is what the user inputed.

**Comment by shashanksi2009** [comment]
I would like to take a look into this.

**Comment by yashwanth-Thota** [comment]
I would like to work on this
