### ISSUE TITLE
web-console failed to compiled

### ISSUE THREAD

**Issue by koupeng** [apache/druid#8786]
Please provide a detailed title (e.g. "Broker crashes when using TopN query with Bound filter" instead of just "Broker crashes").

### Affected Version

The Druid version 0.16.0 

### Description
ERROR in ./src/entry.scss (./node_modules/css-loader/dist/cjs.js!./node_modules/postcss-loader/src??postcss!./node_modules/sass-loader/dist/cjs.js!./src/entry.scss)
Module build failed (from ./node_modules/sass-loader/dist/cjs.js):
SassError: File to import not found or unreadable: ../lib/react-table.
        on line 21 of F:\gitsource\incubator-druid-master\web-console\src\entry.scss
>> @import '../lib/react-table';

   ^

 @ ./src/entry.scss 1:14-171 20:4-31:5 23:25-182
 @ ./src/entry.ts

ERROR in ./src/views/query-view/query-input/query-input.tsx
Module not found: Error: Can't resolve '../../../../lib/sql-docs' in 'F:\gitsource\incubator-druid-master\web-console\src\views\query-view\query-input'
 @ ./src/views/query-view/query-input/query-input.tsx 10:17-52
 @ ./src/views/query-view/query-view.tsx
 @ ./src/views/index.ts
 @ ./src/console-application.tsx
 @ ./src/entry.ts

ERROR in ./src/views/query-view/query-view.tsx
Module not found: Error: Can't resolve '../../../lib/sql-docs' in 'F:\gitsource\incubator-druid-master\web-console\src\views\query-view'
 @ ./src/views/query-view/query-view.tsx 12:17-49
 @ ./src/views/index.ts
 @ ./src/console-application.tsx
 @ ./src/entry.ts

ERROR in ./src/ace-modes/dsql.js
Module not found: Error: Can't resolve '../../lib/sql-docs' in 'F:\gitsource\incubator-druid-master\web-console\src\ace-modes'
 @ ./src/ace-modes/dsql.js 25:21-50
 @ ./src/entry.ts

**Comment by vogievetsky** [comment]
Try running `npm run compile` in the console dir. It will run `./script/build` which will make the file you are missing.

**Comment by koupeng** [comment]
@vogievetsky thanks,but,my pc is win10？

**Comment by vogievetsky** [comment]
Druid dev does not work right on windows. Do you want to develop all of Druid or just the web console?
Can you try executing all the commands inside of `web-console`'s `script/build` bash script yourself?

**Comment by vogievetsky** [comment]
The build system for the console has changed for the Druid 24 release and I believe this issue is solved. Closing, please reopen if I am wrong.
