### ISSUE TITLE
how to connect kafka of Authentication using SASL

### ISSUE THREAD

**Issue by koupeng** [apache/druid#8787]
### Affected Version

0.16.0

### Description

how to connect kakfa by zookeeper?

**Comment by junneyang** [comment]
+1

**Comment by junneyang** [comment]
> +1

solvde ~

"ioConfig": {
      "type": "kafka",
      "consumerProperties": {
        "bootstrap.servers": "**xxxxx:9093,yyyyy:9093,zzzzz:9093**",
        "security.protocol": "SASL_PLAINTEXT",
        "sasl.mechanism": "PLAIN",
        "sasl.jaas.config": "org.apache.kafka.common.security.plain.PlainLoginModule required username='**username_here**' password='**password_here**';"
      },
      "topic": "**kafka_topic_here**"
    },

**Comment by koupeng** [comment]
> > +1
> 
> solvde ~
> 
> "ioConfig": {
> "type": "kafka",
> "consumerProperties": {
> "bootstrap.servers": "**xxxxx:9093,yyyyy:9093,zzzzz:9093**",
> "security.protocol": "SASL_PLAINTEXT",
> "sasl.mechanism": "PLAIN",
> "sasl.jaas.config": "org.apache.kafka.common.security.plain.PlainLoginModule required username='**username_here**' password='**password_here**';"
> },
> "topic": "**kafka_topic_here**"
> }

3Q~~~
