### ISSUE TITLE
Flatten Json Field inside TSV?

### ISSUE THREAD

**Issue by MrMoronIV** [apache/druid#8790]
I have a Kafka Event in TSV which has a field that contains JSON. it possible to flatten this json field for ingestion, and so, how?

I now have something like this for the parser, which works great:
```
    "parser": {
      "type": "string",
      "parseSpec": {
        "format": "tsv",
        "timestampSpec": {
          "column": "derived_tstamp",
          "format": "auto"
        },
        "hasHeaderRow": false,
        "columns": [
          "column1",
          "column2",
          "jsonColumn"
       ]
```

How would I flatten `jsonColumn`? Do I need to include multiple parseSpecs, is that even possible? Or can the column have a specific `flattenSpec` defined in the columns array?

**Comment by vogievetsky** [comment]
This is not currently possible, but would be a cool feature.

**Comment by MrMoronIV** [comment]
Can this somehow be implemented/ actually ve taken care of? It saves me (and probably many others) from writing an extra step (in my case kafka streams application in Java and saving the data again ina new topic). This would be much more convenient :)
