### ISSUE TITLE
groupBy() query is not working in Node Js

### ISSUE THREAD

**Issue by Jaymin-adzmedia** [apache/druid#8820]
Hello,

I need to get records by time. For that, I have used groupBy() query. TopN() query is working fine but once i use groupBy(). It is showing nodejs error.

Nodejs: Internal server error: 5000 code.

Can you help me to solve this.

**Comment by vogievetsky** [comment]
Could you post more details of the query and the error please?

**Comment by Jaymin-adzmedia** [comment]
Hello vogievetsky,

Here is my query in node:

> var queryRep = client.timeseries();
>                     queryRep.dataSource(APP_REPORTING_DATA_SOURCE)
>                         .granularity(reqGranularity)
>                         .aggregation('count', 'rows');

when I add limit(maxLimit) in query it is showing me.

```
TypeError: client.timeseries(...).limit is not a function
2|DSP-api  |     at dimensionData (/home/ec2-user/reports/dsp_reports/controllers/ReportController.js:255:56)
```

Can you help me in this case?

**Comment by vogievetsky** [comment]
I am not sure what query client you are using but it looks like you are doing `client.timeseries()` which is not a groupBy query

**Comment by Jaymin-adzmedia** [comment]
Hello,
here is my query

`var queryRep = client.timeseries();
                        queryRep.dataSource(APP_REPORTING_DATA_SOURCE)
                            .granularity(reqGranularity)
                            //.limit(maxRecords)
                            // .descending(true)
                            .aggregation('count', 'rows');`

If I wanted to implement descending(true) it is getting error as below

`TypeError: queryRep.dataSource(...).granularity(...).descending is not a function`

can you provide a solution for that.
