### ISSUE TITLE
queryGranularity is hard coded in compaction task

### ISSUE THREAD

**Issue by sixtus** [apache/druid#8830]
https://github.com/apache/incubator-druid/blob/master/indexing-service/src/main/java/org/apache/druid/indexing/common/task/CompactionTask.java#L593

I am migrating from hadoop compaction to native compaction and just noticed I can't change the granularity (we use this to keep 2 days at minute and then switch to hour).

Is there any reason to hard coded it? Or is it safe to make that a config option similar to `segmentGranularity`? If the later, I can do a PR. Just trying to make sure, I am not running into a trap.

**Comment by sixtus** [comment]
Is it as simple as https://github.com/liquidm/druid/pull/5/files ?

**Comment by jihoonson** [comment]
Hi @sirpkt, thanks for your report. This is just not implemented yet. I think basically the change in https://github.com/liquidm/druid/pull/5/files would work.

**Comment by sixtus** [comment]
I think you mean me. I will test this asap. Will likely need documentation too for PR against apache repo.
