### ISSUE TITLE
Supervisor Task failing without any error

### ISSUE THREAD

**Issue by hara5** [apache/druid#8861]
I created a new load data activity using Kafka and supervisor task is in UNHEALTHY STATE and all tasks are failing in 6 seconds.

Druid Version:  apache-druid-0.16.0-incubating
Any pointers on the issue

![Screen Shot 2019-11-13 at 7 27 22 PM](https://user-images.githubusercontent.com/46867513/68777869-c4113f80-064b-11ea-8e49-90651340ae89.png)

![Screen Shot 2019-11-13 at 7 22 48 PM](https://user-images.githubusercontent.com/46867513/68777885-cbd0e400-064b-11ea-8d0e-ef38ca47e246.png)

![Screen Shot 2019-11-13 at 7 22 55 PM](https://user-images.githubusercontent.com/46867513/68777897-d0959800-064b-11ea-82ad-705248fccb41.png)

**Comment by jp707049** [comment]
Check overlord logs

**Comment by alexandra-diaconu** [comment]
I am running into same issue, but not able to find the logs anywhere. Have you figured it out what was your problem?

**Comment by hara5** [comment]
unable to figure it out yet

**Comment by hara5** [comment]
@alexandra-diaconu Did you able top figure out the issue?

**Comment by selfeky** [comment]
Have the exact same problem!

**Comment by suneet-s** [comment]
@hara5 @selfeky what do the overlord logs say?

**Comment by selfeky** [comment]
@suneet-s nothing in overload

druid/indexer/v1/task/{task_id}/log

ends with:

```2020-01-27T19:54:05,019 INFO [main] org.apache.druid.indexing.worker.executor.ExecutorLifecycle - Attempting to lock file[/tmp/persistent/task/index_kafka_groups_a577fe538149f50_koghokai/lock].
2020-01-27T19:54:05,022 INFO [main] org.apache.druid.indexing.worker.executor.ExecutorLifecycle - Acquired lock file[/tmp/persistent/task/index_kafka_groups_a577fe538149f50_koghokai/lock] in 3ms.
2020-01-27T19:54:05,023 INFO [parent-monitor-0] org.apache.druid.indexing.worker.executor.ExecutorLifecycle - Triggering JVM shutdown.```

**Comment by vikramarsid** [comment]
@selfeky Did you resolve this issue ?

**Comment by selfeky** [comment]
@vikramarsid no unfortunately

**Comment by rishibhutada** [comment]
@alexandra-diaconu, @selfeky @hara5 
were you able to solve the issue? I am facing the same issue.

**Comment by selfeky** [comment]
@rishibhutada no unfortunately

**Comment by nikhilamunipalli** [comment]
Same issue.. Any help?

**Comment by horidon** [comment]
same for me

**Comment by sohansamant8** [comment]
Any update on this issue? I am facing the same issue in druid version 0.21.0. Any help on this is highly appreciated..My overload logs are throwing this error though: 

[IndexTaskClient-sohan-ptest106-0] IndexTaskClient - submitRequest failed for [http://X.X.X.X:XXXX/druid/worker/v1/chat/index_kafka_sohan-ptest106_c3b658fdb5709c4_eplnnhed/offsets/current], with message [No route to host (Host unreachable)]

Note: IP address has been masked..

**Comment by tej24** [comment]
Is this solved as we are also facing the same issue. hard reset might temporarily solve it but the supervisors get into unhealthy_tasks status.. It isn't stable. Any help or suggestion is appreciated

**Comment by abhishekagarwal87** [comment]
what version are you on? I would suggest using the latest version as many bug fixes have been made. Errors have been made much better over time. If you are seeing it on the latest version, overlord and task logs can offer more clues as to what is happening.
