### ISSUE TITLE
Unable to load data from local file：Parameter 'directory' is not a directory

### ISSUE THREAD

**Issue by datagic** [apache/druid#8865]
When I use local index to load data （Version 0.15.1）
I use "curl - x 'post' - H 'content type: application/JSON' - D @/var/local/xxx.json http://x.x.x.x: 8081/Druid/indexer/v1/task" as the request according to the official document.
I found that the data could not be loaded into the Druid cluster, and the error was:
“Parameter 'directory' is not a directory: /var/local/data”

My Druid is deployed on two servers. When I execute the curl command in druid01, Druid will randomly select one of the two servers, and then go to this server to find the "basedir" configured in the JSON file.
So sometimes data loading succeeds and sometimes fails.

Have you ever met this problem and how to solve it.
Thank you very much.

**Comment by MahsaSeifikar** [comment]
have the same issue
