### ISSUE TITLE
Enable static imports in tests

### ISSUE THREAD

**Issue by leventov** [apache/druid#8885]
As per https://lists.apache.org/thread.html/aed871e3a7d696c1e7a99085d0eab8b20b7c8efa76db3b75dc65f0cf@%3Cdev.druid.apache.org%3E

**Comment by kanibs** [comment]
Hey, Can I pick this?

**Comment by leventov** [comment]
@kanibs sure

**Comment by kanibs** [comment]
Hey @leventov, So I was going through all the attached resources in this issue- and to my understanding, I believe that we need to refactor the Unit Tests in such a way we have minimum statics and hence avoiding static imports and usages. Please correct me here if I have understood in a different way. If that is the case then fixing all the tests in a single PR would not be so easy. So can we break this PR in a more granular way to reduce the scope to a few Classes or maybe module wise, whichever is less?

**Comment by leventov** [comment]
The goal of this issue is just to fix hard&fast rule of prohibiting any static imports, which prohibits some fluent API patterns in test codebase. It can be literally a few lines of code tweaking checkstyle config (or whatever tool governs this for us, I don't remember)

**Comment by kanibs** [comment]
Hey @leventov, thanks for the suggestion/help. I have create the Pull request - https://github.com/apache/druid/pull/9764 for this.
