### ISSUE TITLE
Ingestion task not submitting when using s3-statsic firehose

### ISSUE THREAD

**Issue by AmlanRath** [apache/druid#8898]
When trying to submit an ingestion task using s3 firehose, getting error - 

{"error":"Instantiation of [simple type, class org.apache.druid.indexing.common.task.IndexTask] value failed: null"}

### Affected Version

Error encountered in version 0.14.2

### Description

The ingestion spec for the task am submitting is as follows :

{
  "type": "index",
  "spec": {
    "dataSchema": {
      "dataSource": "reco_collab_data",
      "parser": {
        "type": "string",
        "parseSpec": {
          "format": "json",
          "timestampSpec": {
            "format": "yyyy-MM-dd'T'HH:mm:ss.SSS",
            "column": "eventTime"
          },
          "dimensionsSpec": {
            "dimensions": [
              {
                "type": "LONG",
                "name": "product_id"
              },
              "experiment",
              "variation",
              {
                "type": "LONG",
                "name": "recoProductListSize"
              }
            ]
          }
        }
      },
      "metricsSpec": [
        {
          "type": "count",
          "name": "_count"
        }
      ],
      "granularitySpec": {
        "segmentGranularity": "DAY",
        "queryGranularity": "hour",
        "rollup": true
      }
    },
    "tuningConfig": {
      "type": "index",
      "maxRowsInMemory": "100000",
      "maxRowsPerSegment": "5000000"
    },
    "ioconfig": {
      "type": "index",
      "firehose": {
        "type": "static-s3",
        "uris": [
          "s3://hs-data-engineering/druidtest/testfile.log"
        ]
      }
    }
  }
}

If I replace task type index with index_parallel I get error with ParallelIndexTask instead, but the same error occurs. Can someone tell if anything is wrong in my ingestion spec or something other missing ? For the record this is a production setup with 32 realtime tasks running always and 20-30 other batch tasks running throughout the day, so I don't think it's an issue with the cluster though could always have overlooked something.

**Comment by jon-wei** [comment]
Unfortunately that error message isn't very useful, but maybe it's this part of the spec:

```
"ioconfig": {
```
It needs to be `ioConfig`

Do you see any stack traces in the overlord log when this happens?
