### ISSUE TITLE
TaskLockbox not release unused lock

### ISSUE THREAD

**Issue by hellobabygogo** [apache/druid#8912]
when the kis task run for a long time about 15 days, but the lateMessageRejectionPeriod = PT86400S.  we can't submit index_hadoop task when the data was three days ago.  The reason is that the task did not release the 15 day time lock，Actually, the time lock should be released one day ago.

### Affected Version

0.12.3

**Comment by hellobabygogo** [comment]
@jihoonson do you have any suggestions?

**Comment by jihoonson** [comment]
Hi @hellobabygogo, thank you for the report. Yes, this is one of the issues of the time chunk lock. With the time chunk lock, the task acquires locks for the time chunks where new segments are going to be created. These locks are not released until the task is complete. I think this is to simplify the task lock system especially to avoid deadlocks (like, two tasks could wait each other to lock time chunks what the other task is holding). 

This problem can be avoided with the new segment lock system which was introduced in 0.16. Check https://druid.apache.org/docs/latest/ingestion/tasks.html#task-lock-system for more details. Also please note that this is still an experimental feature.
