### ISSUE TITLE
Make DruidAvaticaHandler extensible to support auth on mTLS JDBC requests

### ISSUE THREAD

**Issue by a2l007** [apache/druid#8931]
### Description

The proposal is to provide a way to perform custom authentication on jdbc requests primarily in cases where it isn't feasible to use the jdbc context. To do this, I'd like to make `DruidAvaticaHandler` extensible specifically to override the avatica handler method: [AbstractAvaticaHandler.isUserPermitted](https://calcite.apache.org/avatica/apidocs/org/apache/calcite/avatica/server/AbstractAvaticaHandler.html#isUserPermitted(org.apache.calcite.avatica.server.AvaticaServerConfiguration,org.eclipse.jetty.server.Request,javax.servlet.http.HttpServletRequest,javax.servlet.http.HttpServletResponse))
This method may be extended to perform custom authentication on jdbc requests especially in usecases involving mutual TLS JDBC requests.
Since it can also handle authentication on jdbc contexts, `Authenticator.authenticateJDBCContext` could be deprecated going forward.

### Motivation
With the existing design, it is only possible to authenticate druid SQL queries over JDBC using the jdbc context which uses `Authenticator.authenticateJDBCContext`. For secured clusters using mutual TLS, it may not be possible/recommended to provide additional credentials over jdbc context.

**Comment by a2l007** [comment]
@jon-wei Does this approach sound reasonable? Thanks :)

**Comment by jon-wei** [comment]
> Since it can also handle authentication on jdbc contexts, Authenticator.authenticateJDBCContext could be deprecated going forward.

How do you envision the Authenticators fitting in with the AvaticaHandler extensions?

**Comment by a2l007** [comment]
@jon-wei My initial plan was to keep AvaticaHandler extensions separate from the Authenticators. But it might be better to just override `isUserPermitted` in `DruidAvaticaHandler` and this would call a new method say `authenticateJDBCRequest(HttpServletRequest clientRequest)` in the Authenticator. The auth result can then be pushed to the request context that can be used for authorization later on. So the end user would only have to implement a new method within their existing authenticators which would handle the jdbc requests. 
`authenticateJDBCRequest` can eventually replace `authenticateJDBCContext` since it would be possible to extract the context from the request itself.
Please let me know if you feel there is a better way to do this.

**Comment by jon-wei** [comment]
@a2l007 

The Authenticators can provide a servlet Filter, would it it be possible to pass the `HttpServletRequest` from `AbstractAvaticaHandler.isUserPermitted` into those Filters?

What would the mTLS authentication check look like? (Would it just be pulling the identity from the client certificate, since the TLS negotiation would've checked the certificates by then?)

**Comment by a2l007** [comment]
@jon-wei 

> The Authenticators can provide a servlet Filter, would it it be possible to pass the `HttpServletRequest` from `AbstractAvaticaHandler.isUserPermitted` into those Filters?

I don't think `isUserPermitted` would be able to do that. Even if it did, servlet filters are not applied to jdbc requests though are they? 
`isUserPermitted` would iterate through the list of authenticators and invoke `authenticateJDBCRequest(HttpServletRequest clientRequest)` on them.

> What would the mTLS authentication check look like? (Would it just be pulling the identity from the client certificate, since the TLS negotiation would've checked the certificates by then?)

The authentication check could vary based on the implementation, but the essential flow would be to extract the X509 cert from the request and use the identity for authentication.

**Comment by jon-wei** [comment]
> isUserPermitted would iterate through the list of authenticators and invoke authenticateJDBCRequest(HttpServletRequest clientRequest) on them.

At a high level that sounds fine to me, with eventual deprecation of `authenticateJDBCContext` as you described earlier.

Can you sketch out how that request context set in `isUserPermitted` would be passed to the rest of the Druid SQL system and authorizers?

**Comment by a2l007** [comment]
@jon-wei The request input stream could be modified to add the authentication result with a specific key so that it can be accessible from the `info` object in `DruidMeta.openConnection(final ConnectionHandle ch, final Map<String, String> info)` . In this case, there wouldn't be any change to the Druid SQL flow except in `DruidMeta.authenticateConnection`. Here, the context could be checked for the authentication result or else call `authenticateJDBCContext` with the context.

The issue however is that modifying the request inputstream to add the authentication result to the request body isn't a clean approach and I'm wondering if there is a better way to do this.
