### ISSUE TITLE
help understanding some basics to overcome query lag

### ISSUE THREAD

**Issue by AvinoamBN** [apache/druid#9017]
Hi,
So I'm kinda new to apache druid, and I've been assigned with finding the source of a lag when querying.
so far, I've learnt how to read the cluster conf files and how to query for metrics.
I was trying to follow the docs to check how I can fine tune the configuration and optimize the historical and broker, but some options values are a mystery to me.
like "_heap size_" and `druid.cache.sizeInBytes` and `druid.server.maxSize`.

1. to reach max heap size of 24G RAM, do i need a 48 cpu cores server?
2. what is the free system memory / druid.server.maxSize ratio? the docs mention "should be set such that a Historical is not allocated an excessive amount of segment data"... what is considered excessive, what the formula?

regarding querying the metrics datasource:
I'm doing a select query with mysql, and sending it via POST to the broker.
example query:
```
{
"query":
"SELECT * FROM \"metrics\" 
    WHERE \"__time\" BETWEEN 
        TIMESTAMP '2019-12-11 00:00:00' AND 
        TIMESTAMP '2019-12-11 23:59:59' 
      AND 
        \"dataSource\" = 'orgrimmar'
      AND
        \"metric\" = 'query/time'
      AND 
        \"type\" = 'select'
      AND
         \"value\" > 10000 
  ORDER BY 1 limit 10"
}
```

this query give results that look like this:

```
{
  "__time": "2019-12-11T15:00:49.878Z",
  "count": 1,
  "dataSource": "orgrimmar",
  "hasFilters": "true",
  "host": "druid-broker1:8083",
  "interval": "2019-11-26T10:18:51.681Z/2019-12-11T15:00:34.664Z",
  "metric": "query/time",
  "numComplexMetrics": 0,
  "numDimensions": 0,
  "numMetrics": 0,
  "server": "",
  "type": "select",
  "value": 13288
}
```

How can i find out why did this query take 13 seconds to complete?
How can i find out what and where is the bottle-neck?

**Comment by jp707049** [comment]
Hello AvinoamBN,

- Have a look at this for heap sizing: https://druid.apache.org/docs/latest/operations/basic-cluster-tuning.html
How can i find out why did this query take 13 seconds to complete?
- Each druid services and emit metrics: https://druid.apache.org/docs/latest/operations/metrics.html
- You can enable metrics emission by following: https://druid.apache.org/docs/latest/configuration/index.html#enabling-metrics and https://druid.apache.org/docs/latest/configuration/index.html#emitting-metrics
How can i find out what and where is the bottle-neck?
- For initial steps to find bottle-neck, make sure you have set the runtime.properties correctly in both broker and historical.
- There can be many factors affecting the query performance such as, segment sizing, number of historical nodes, high volume of data in query response, the type of query being executed (whether you can use/modify the query, check for topN, groupBy and timeseries)

Hope this helps you figure out some things. :)

**Comment by himanshug** [comment]
once you have metrics , pay special attention to following metrics...

broker:
query/time,  query/node/time , query/node/ttfb

historicals:
query/time, query/segment/time, query/wait/time, segment/scan/pending,

those metrics should help identify the split for 13s .

watch for GC and Page swapping activity on all nodes that were in processing path of that query.

(I am assuming you don't have realtime indexing setup)

hth

**Comment by AvinoamBN** [comment]
- Thanks for the reply @**jp707049**, but I've been there already.

- Thanks @**himanshug**, this sounds like the start of what I'm looking for!
1) My following question would be: How do I query for all of the above metrics you mentioned, but with their "relationship" to a specific query?
Like how do I pull information (all those metrics) on a single query?
Does the queries have some type of uniqueID record that is attached to all relevant data? I tried connecting them with the "__time" value but I'm not sure its 100% accurate.

2) _GC and Page swapping activity_ - how do I do that? (an example would be appreciated!)

3) _realtime indexing_ - maybe it is set up. how do I check? and what will it provide?

**Comment by himanshug** [comment]
>  How do I query for all of the above metrics you mentioned, but with their "relationship" to a specific query?

all queries running in Druid are given a specific ID and that ID is propagated as a dimension in the emitted metric (typically, "id") . Please see relevant docs https://druid.apache.org/docs/latest/operations/metrics.html and try to see some of them on your cluster and it would be more clear hopefully.

> GC and Page swapping activity - how do I do that? (an example would be appreciated!)

for non-druid info , I'm afraid I would point you to just search internet for those. Typically users would send gc logs to file , some of the jvm options are described in https://druid.apache.org/docs/latest/operations/recommendations.html

> realtime indexing - maybe it is set up. how do I check? and what will it provide?

https://druid.apache.org/docs/latest/ingestion/index.html

that should hopefully get you on the right path.

**Comment by AvinoamBN** [comment]
Thanks again for your reply @himanshug ,
So what am I doing wrong?
the docs say: 

> 

Metric | Description | Dimensions | Normal Value
-- | -- | -- | --
query/time | Milliseconds taken to complete a query. | Common:  dataSource, type, interval, hasFilters, duration, context,  remoteAddress, id. Aggregation Queries: numMetrics, numComplexMetrics.  GroupBy: numDimensions. TopN: threshold, dimension. | < 1s

So im running to different type of query, an SQL one and a JSON one, both via the POST API.

SQL query is pretty much this:
`SELECT * FROM \"metrics\" WHERE  \"metric\" = 'query/time'`
This returns results like this:
```
{
    "__time": "2019-11-16T09:00:07.594Z",
    "count": 1,
    "dataSource": "orgrimmar",
    "hasFilters": "true",
    "host": "druid-broker1:8083",
    "interval": "2019-10-30T10:24:18.761Z/2019-11-16T09:00:01.771Z",
    "metric": "query/time",
    "numComplexMetrics": 0,
    "numDimensions": 0,
    "numMetrics": 0,
    "server": "",
    "type": "select",
    "value": 2482
  },
```
there is no "id" in that result, nor other things mentioned in the doc's (such as: duration, context,  remoteAddress...)

JSON query looks like this:
```
{
  "queryType": "select",
  "dataSource": "metrics",
  "granularity": "all",
	"dimensions": [],
	"filter": {
		"type": "in",
		"dimension": "metric",
		"values": ["query/time"]
	},
	"intervals": [
		"2019-12-16T00:00:00/2019-12-16T23:59:59"
	],
	"pagingSpec":{"pagingIdentifiers": {}, "threshold":1 }
}
```
this returns results like this:
```
[
  {
    "timestamp": "2019-12-16T00:00:00.003Z",
    "result": {
      "pagingIdentifiers": {
        "metrics_2019-12-16T00:00:00.000Z_2019-12-16T01:00:00.000Z_2019-12-16T04:35:02.747Z": 0
      },
      "dimensions": [
        "server",
        "metric",
        "hasFilters",
        "host",
        "interval",
        "type",
        "dataSource"
      ],
      "metrics": [
        "numComplexMetrics",
        "numDimensions",
        "count",
        "numMetrics",
        "value"
      ],
      "events": [
        {
          "segmentId": "metrics_2019-12-16T00:00:00.000Z_2019-12-16T01:00:00.000Z_2019-12-16T04:35:02.747Z",
          "offset": 0,
          "event": {
            "timestamp": "2019-12-16T00:00:02.010Z",
            "dataSource": "orgrimmar",
            "server": null,
            "type": "groupBy",
            "interval": [
              "2019-12-09T14:00:00.000Z/2019-12-09T15:00:00.000Z",
              "2019-12-10T13:00:00.000Z/2019-12-10T14:00:00.000Z",
              "2019-12-12T03:00:00.000Z/2019-12-12T04:00:00.000Z",
              "2019-12-12T21:00:00.000Z/2019-12-12T22:00:00.000Z",
              "2019-12-13T12:00:00.000Z/2019-12-13T13:00:00.000Z",
              "2019-12-15T02:00:00.000Z/2019-12-15T03:00:00.000Z"
            ],
            "metric": "query/time",
            "host": "druid-historical40:8083",
            "hasFilters": "false",
            "numComplexMetrics": 0,
            "numDimensions": 2,
            "count": 2,
            "numMetrics": 2,
            "value": 258
          }
        }
      ]
    }
  }
]
```
once again, there is no dimension named "id".

Am I querying this wrong, looking at it wrong, or understanding it wrong?
I have read the docs a few times now. its either I'm lacking some basic understanding of this, or I'm looking at this the wrong way.

Please advise,
thank you so much

**Comment by himanshug** [comment]
Please see https://druid.apache.org/docs/latest/configuration/index.html#emitting-metrics 
Druid has a emitter framework for emitting metrics . Druid does not dictate how and where emitted metrics are stored. That part of emitter framework is extensible. There are few core implementations like "logging", "http" etc .
.. and some more in extensions, see https://druid.apache.org/docs/latest/development/extensions.html#community-extensions

emitter implementation is free to remove some of the high cardinality dimensions such as id, aggregate multiple events etc if target storage system can not handle raw metrics emitted by Druid. That is what is happening in your case I think. Emitter, that your setup is using, is one of those that discards "id" dimension and probably aggregating the "query/time" into average so what you see is probably the average of two "query/time" metric events.

if you configure "logging" emitter, you should see "id" dimension in metric event in the log because "logging" emitter doesn't filter or aggregate anything but just dumps whatever it gets into the logs.

**Comment by AvinoamBN** [comment]
thank you very much for your help.
I'll dig in the docs again,

happy holidays
