### ISSUE TITLE
[Proposal] Druid discovery extension for Kubernetes

### ISSUE THREAD

**Issue by himanshug** [apache/druid#9053]
### Motivation

Druid has provisions for writing an extension that could be used for "node discovery" and "leader election". Such extension coupled with "HTTP" based "segment management" and "remote task runner" could be used to obviate the need of operating a Zookeeper cluster for Druid.
However, no such extension exists and above is just theory.

Proposal is to write an extension based on APIs exposed by Kubernetes API server (which itself is backed by [etcd](https://github.com/etcd-io/etcd) ) which has sufficient primitives to be able to do  "node discovery" and "leader election" .

### Proposed changes

A new extension, "druid-kubernetes-extensions" , would be added with implementations of various discovery related interfaces such as "DruidNodeDiscoveryProvider", "DruidLeaderSelector", "DruidNodeAnnouncer" etc.
Additionally, since this is first such extension, there might be some changes needed in core as well to enable writing the extension.

### Rationale

etcd based extension could also be written, but in many Kubernetes deployments, access to etcd is guarded and users of K8s clusters are not expected to use it. So for users(I happen to be one of those) deploying Druid on kubernetes, it is required to not depend directly on etcd. So, I decided not to pursue that.
it is also possible to have Druid implement one of the consensus algorithms, but that is a lot more work and is very error prone. Consensus algorithms are notoriously hard to implement. In the current use case, that is not strictly needed.

More importantly, on most cloud providers, K8S control plane comes with a fixed cost so using it instead of zookeeper lets you remove 3 zk pods for free and adds to cloud cost savings.

### Operational impact

None

### Test plan (optional)

I would be testing the extension on my own Druid clusters deployed in Kubernetes.

**Comment by sascha-coenen** [comment]
NICE!!!!!

> etcd based extension could also be written....

there's an official java client library for accessing the k8s api. it's available here:
https://github.com/kubernetes-client/java

it looks quite complete and starting with  version 7.0.0 it is easy to use.
on the main github page there are examples which demonstrate how to watch for nodes/pods etc and there is also an example that implements leader election. (LeaderElectionExample)

I'm currently checking it out for implementing an autoscaler for druid indexer jobs on k8s.

Just to mention it, there is another proposal that is remotely related in that it is about integrating Druid with k8s. Perhaps these two functionalities could end up living in the same kubernetes extension: https://github.com/apache/druid/issues/8801

**Comment by himanshug** [comment]
@sascha-coenen thanks, yes I am using the kubernetes-client for java. only problems I have seen with that so far is that it breaks backward compatibility in some of the releases. However, it is pretty up-to-date and hopefully APIs will become more stable in time. That said, examples do really help getting things to work quicker.

**Comment by himanshug** [comment]
I got something functional and working  in https://github.com/himanshug/druid/tree/k8s/extensions-core/kubernetes-extensions . I am still in the process of testing it more carefully and deploy on some real clusters to further validate.

**Comment by himanshug** [comment]
Just wanted to note an unforeseen advantage I am realizing from not using ZK but using K8S API server instead for the discovery is that AWS (and Probably GCP too) has a fixed cost of control plane (including K8S Master) , so this pretty much helps you reduce cloud cost by not having to deploy those 3 zk pods.

**Comment by clintropolis** [comment]
Just curious, does this proposal support running multiple druid clusters within the same kubernetes cluster (similar to how Druid clusters can share a zookeeper by using separate paths)?

**Comment by clintropolis** [comment]
>Just curious (i haven't looked at the code yet), does this proposal support running multiple druid clusters within the same kubernetes cluster (similar to how Druid clusters can share a zookeeper by using separate paths)?

Ah, is this done with namespaces I guess? (started looking at the code 😅 )

**Comment by himanshug** [comment]
thanks for taking a look. this would totally allow multiple Druid clusters on same k8s cluster, even within same k8s namespace ... there is a `String K8sDiscoveryConfig.clusterIdentifier` in the config provided by the user and is responsible for creating uniqueness.

**Comment by himanshug** [comment]
that said I haven't really tested multiple Druid clusters within same namespace part yet, so maybe I over-spoke .. however it could be made possible if not already [ I think] , forgot the details as it has been a while I have done things to that code :)

that said, multiple Druid clusters within one k8s cluster is allowed for sure.

**Comment by clintropolis** [comment]
Cool, yeah i just stumbled into that cluster identifier bit and was wondering what it was, thanks for the explanation :+1:
