### ISSUE TITLE
Fix tdigest aggregators to handle null values and enable them to be used for rollup during ingestion

### ISSUE THREAD

**Issue by samarthjain** [apache/druid#9069]
### Affected Version
0.16.0
The Druid version where the problem was encountered.
0.16.0
### Description
During our local testing I ran into an issue where the t-digest aggregators throw an NPE when a null value is encountered. Additionally, while doing the ingestion, it turned out that the aggregators need to implement the `makeAggregateCombiner` interface. While this worked fine in 0.12.0, something has changed from then which makes this an explicit requirement.

**Comment by clintropolis** [comment]
heh, just noticed the null handling thing last night while evaluating if complex sketch aggs handle null valued numeric columns correctly :+1:
