### ISSUE TITLE
Incompatible JARS while Running Apache Druid 0.16 on GKE , Jenkins Twistlock Vulnerabilities 

### ISSUE THREAD

**Issue by averma111** [apache/druid#9079]
The Devops team today have come up with Twistlock Vulnerabilities which are 49 in total number for Druid running on GKE.

### Affected Version

0.16

### Description

Please include as much detailed information about the problem as possible.
- Cluster size--Single instance micro quick start
- Configurations in use--default configuration
- Steps to reproduce the problem--No Idea
One of the example I am sharing below

**com.fasterxml.jackson.core_jackson-databind   Package version :2.4.0 Fixed version:2.9.7**

Description which is mentioned is below.

FasterXML jackson-databind 2.x before 2.9.7 might allow remote attackers to execute arbitrary code by leveraging failure to block the slf4j-ext class from polymorphic deserialization.

Does future Druid version is fixing this type of issue.

Thanks,
Ashish

**Comment by jnaous** [comment]
0.17 does have a significant number of vulnerabilities fixed. That said,
the Hadoop client has a number of vulnerabilities that are hard to fix, and
it should be excluded from vuln scanning if you are not using it.

**Comment by averma111** [comment]
Thank you so much for clarification.

Thanks,
Ashish

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10
