### ISSUE TITLE
Unbalanced synchronization of ResponseContext.REGISTERED_KEYS

### ISSUE THREAD

**Issue by leventov** [apache/druid#9106]
To make it really thread-safe:
 1. `keyOf()` and `getAllRegisteredKeys()` should be made synchronized;
 2. `getAllRegisteredKeys()` should return a defensive copy: `new TreeMap<>(REGISTERED_KEYS).values()`

Relevant concurrency checklist items: https://github.com/code-review-checklists/java-concurrency#unsafe-concurrent-point-read, https://github.com/code-review-checklists/java-concurrency#unsafe-concurrent-iteration

**Comment by esevastyanov** [comment]
Agreed. There is no guarantee that `registerKey` would be called only from class static blocks as originally designed.
