### ISSUE TITLE
Fix concurrency of ComplexMetrics

### ISSUE THREAD

**Issue by leventov** [apache/druid#9107]
A possible solution:
 1. Make `COMPLEX_SERIALIZERS` a `ConcurrentHashMap`
 2. Convert the whole body of `registerSerde()` method as a single `COMPLEX_SERIALIZERS.compute()` operation

Alternatively, both `getSerdeForType()` and `registerSerde()` methods could be made `synchronized`.

**Comment by imrahul361** [comment]
I am Newbie to open source. and I would like to contribute to this issue.
So,May I know how can I contribute to it?
