### ISSUE TITLE
how auto compaction work?

### ISSUE THREAD

**Issue by smildlzj** [apache/druid#9132]
my compaction config as follow, but i can't see any compact task  submit
```
{
dataSource: "android@event",
taskPriority: 25,
inputSegmentSizeBytes: 838860800,
targetCompactionSizeBytes: 719430400,
maxRowsPerSegment: null,
maxNumSegmentsToCompact: 168,
skipOffsetFromLatest: "P10D",
tuningConfig: null,
taskContext: null
}
```

compactionTaskSlotRatio: 0.8,
maxCompactionTaskSlots: 2147483647
worker capacity: 20

**Comment by smildlzj** [comment]
look as like #9016,  i want compact small segments to speed up for query

**Comment by pawantekchandani** [comment]
hey @smildlzj 
Which version of Druid are you using?

**Comment by smildlzj** [comment]
> hey @smildlzj
> Which version of Druid are you using?

hi, version is 0.16.1-incubating

**Comment by suneet-s** [comment]
hi @smildlzj you can submit a compaction job just like an index task - see this tutorial https://druid.apache.org/docs/latest/tutorials/tutorial-compaction.html#compact-the-data

`bin/post-index-task --file quickstart/tutorial/compaction-keep-granularity.json --url http://localhost:8081`

Hope this helps!

**Comment by jihoonson** [comment]
Hi @smildlzj, if any compaction task is not being triggered, probably the coordinator decided to skip to compact segments in some intervals. Looking at your configuration, would you please double check the followings?

- Is the total segment size in the same interval smaller than `inputSegmentSizeBytes`?
- Is the total number of segments in the same interval smaller than `maxNumSegmentsToCompact`?
- Does the interval of the segments you want to compact overlap with the interval of `(endTimeOfTheMostRecentSegment - skipOffsetFromLatest, endTimeOfTheMostRecentSegment)`

Also, the reason should be logged in the coordinator log file as below:

```java
        if (!isCompactibleSize) {
          log.warn(
              "total segment size[%d] for datasource[%s] and interval[%s] is larger than inputSegmentSize[%d]."
              + " Continue to the next interval.",
              candidates.getTotalSize(),
              candidates.segments.get(0).getDataSource(),
              candidates.segments.get(0).getInterval(),
              inputSegmentSize
          );
        }
        if (!isCompactibleNum) {
          log.warn(
              "Number of segments[%d] for datasource[%s] and interval[%s] is larger than "
              + "maxNumSegmentsToCompact[%d]. If you see lots of shards are being skipped due to too many "
              + "segments, consider increasing 'numTargetCompactionSegments' and "
              + "'druid.indexer.runner.maxZnodeBytes'. Continue to the next interval.",
              candidates.getNumSegments(),
              candidates.segments.get(0).getDataSource(),
              candidates.segments.get(0).getInterval(),
              maxNumSegmentsToCompact
          );
        }
        if (!needsCompaction) {
          log.warn(
              "Size of most of segments[%s] is larger than targetCompactionSizeBytes[%s] "
              + "for datasource[%s] and interval[%s]. Skipping compaction for this interval.",
              candidates.segments.stream().map(DataSegment::getSize).collect(Collectors.toList()),
              targetCompactionSizeBytes,
              candidates.segments.get(0).getDataSource(),
              candidates.segments.get(0).getInterval()
          );
        }
```

**Comment by stevenchen3** [comment]
Encountered the same here. I am using Druid `0.16.0` and below is my automatic compaction config:

```yaml
{
  "compactionConfigs":[
    {
      "dataSource":"mydatasource",
      "taskPriority":25,
      "inputSegmentSizeBytes":500000000,
      "targetCompactionSizeBytes":500000000,
      "maxRowsPerSegment":null,
      "maxNumSegmentsToCompact":1000,
      "skipOffsetFromLatest":"P1D",
      "tuningConfig":null,
      "taskContext":null
    }
  ],
  "compactionTaskSlotRatio":0.75,
  "maxCompactionTaskSlots":2147483647
}

# I have a total 20 task slots
```

I was trying to enable auto-compact to merge small segments (about 100KB per segment) to bigger ones. The segment size of the same interval does not exceed above `500000000` and the total number of small segments is about 900 (this number for my test env, it will be much bigger in production env).

However, I did not see any compaction task running, nor observe any logs (related to https://github.com/apache/druid/issues/9132#issuecomment-576832985).

Wondering anyone has any idea to resolve this?

**Comment by stevenchen3** [comment]
> Encountered the same here. I am using Druid `0.16.0` and below is my automatic compaction config:
> 
> ```yaml
> {
>   "compactionConfigs":[
>     {
>       "dataSource":"mydatasource",
>       "taskPriority":25,
>       "inputSegmentSizeBytes":500000000,
>       "targetCompactionSizeBytes":500000000,
>       "maxRowsPerSegment":null,
>       "maxNumSegmentsToCompact":1000,
>       "skipOffsetFromLatest":"P1D",
>       "tuningConfig":null,
>       "taskContext":null
>     }
>   ],
>   "compactionTaskSlotRatio":0.75,
>   "maxCompactionTaskSlots":2147483647
> }
> 
> # I have a total 20 task slots
> ```
> 
> I was trying to enable auto-compact to merge small segments (about 100KB per segment) to bigger ones. The segment size of the same interval does not exceed above `500000000` and the total number of small segments is about 900 (this number for my test env, it will be much bigger in production env).
> 
> However, I did not see any compaction task running, nor observe any logs (related to [#9132 (comment)](https://github.com/apache/druid/issues/9132#issuecomment-576832985)).
> 
> Wondering anyone has any idea to resolve this?

If I use `0.17.0`, I can see the auto-compaction tasks running. Unfortunately, I can't use `0.17.0` in production at the moment. Wondering if this is a bug in `0.16.0`? Any around for `0.16.0`? @jihoonson
