### ISSUE TITLE
Druid Historicals are showing Max Size 300gb

### ISSUE THREAD

**Issue by averma111** [apache/druid#9143]
Druid Version :0.15

We are using two 2TB linux bosxes are historical but we only see that 300gb is used for storing data.

Can we increase the size of 300gb to more like 1TB in Druid settings.

Thanks,
Ashish

**Comment by Dylan1312** [comment]
Hey @averma111 

Have a look at the configuration options in the historical's runtime.properties

druid.server.maxSize
and
druid.segmentCache.locations
