### ISSUE TITLE
Question: Clickstream Sources

### ISSUE THREAD

**Issue by Poincare** [apache/druid#9153]
I imagine that many Druid users apply Druid as a store for clickstream/user activity data within a web application.

Our team would like to set this up, but are curious to hear what the setup looks like for other teams with this usecase. 

The two projects related to clickstream ingestion I've seen are [Divolte](https://divolte.io/) and [snowplow](https://github.com/snowplow/snowplow). The former seems to support Druid more painlessly than the latter, but it's unclear if it's used at scale and maintained actively. Are there any other projects that do clickstream ingestion on web that we should be looking at?

More generally: If you're using Druid for user activity or clickstream data, what does your stack look like?

Thanks!

**Comment by pawantekchandani** [comment]
> I imagine that many Druid users apply Druid as a store for clickstream/user activity data within a web application.
> 
> Our team would like to set this up, but are curious to hear what the setup looks like for other teams with this usecase.
> 
> The two projects related to clickstream ingestion I've seen are [Divolte](https://divolte.io/) and [snowplow](https://github.com/snowplow/snowplow). The former seems to support Druid more painlessly than the latter, but it's unclear if it's used at scale and maintained actively. Are there any other projects that do clickstream ingestion on web that we should be looking at?
> 
> More generally: If you're using Druid for user activity or clickstream data, what does your stack look like?
> 
> Thanks!

Hi Dhaivat. 
I am using Druid for my project [Adsgraphy](https://adsgraphy.com) in production. I must say that I am glad that I chose Druid over other databases. My project involves storing of clickstream and then generating various reports on that data for different data. 
Although there are many companies using it at scale one of them is Kochava which certainly has a high amount of clickstream data. I am in the early days of our company product launch. And my project is ingesting 30-50 million clicks per day. 
Hope that helps.
Pawan Tekchandani
