### ISSUE TITLE
CSV and TSV complains about missing findColumnsFromHeader or hasHeaderRow which are optional

### ISSUE THREAD

**Issue by jihoonson** [apache/druid#9156]
### Affected Version

0.17.0 branch

### Description

Here's the stack trace.

```
org.apache.druid.java.util.common.IAE: At least one of [Property{name='hasHeaderRow', value=null}, Property{name='findColumnsFromHeader', value=null}] must be present

	at org.apache.druid.indexer.Checks.checkOneNotNullOrEmpty(Checks.java:44)
	at org.apache.druid.data.input.impl.DelimitedInputFormat.<init>(DelimitedInputFormat.java:100)
	at org.apache.druid.data.input.impl.CsvInputFormat.<init>(CsvInputFormat.java:39)
```

`findColumnsFromHeader` should have different default values depending on `columns`. If `columns` is null, there should be no default value for `findColumnsFromHeader` so that users can be notified if `columns` is missing by mistake. If `columns` is not null, `findColumnsFromHeader` should be defaulted to false.

**Comment by jon-wei** [comment]
Fixed by #9199
