### ISSUE TITLE
White screen when trying to access Druid UI

### ISSUE THREAD

**Issue by konmavrakis** [apache/druid#9162]
### Affected Version
apache-druid-0.16.1-incubating & apache-druid-0.16.0-incubating

### Description

While trying to run `micro-quickstart` in a Google Cloud Compute Engine VM (*nix), when trying to visit the Druid dashboard I get an error on `unified-console.html` page, `web-console-0.16.0.js:35 Uncaught SyntaxError: Unexpected token ')'`, and the whole page is white.

When visiting the `old-console` I got no error or when visiting `console`.

Let me know if you need anything else. 

Please include as much detailed information about the problem as possible.
- Steps to reproduce the problem
```
wget https://www-eu.apache.org/dist/incubator/druid/0.16.0-incubating/apache-druid-0.16.0-incubating-bin.tar.gz
tar -xzf apache-druid-0.16.1-incubating-bin.tar.gz 
cd apache-druid-0.16.1-incubating
curl https://archive.apache.org/dist/zookeeper/zookeeper-3.4.14/zookeeper-3.4.14.tar.gz -o zookeeper-3.4.14.tar.gz 
tar -xzf zookeeper-3.4.14.tar.gz 
mv zookeeper-3.4.14 zk

# and then 

./bin/start-micro-quickstart
```

Then when visiting the Druid UI I have the error that described above.

**Comment by vogievetsky** [comment]
what browser are you using?

**Comment by konmavrakis** [comment]
Latest Chrome and Firefox browsers

**Comment by vogievetsky** [comment]
Tested this extensively and can not reproduce. I am assuming it is fixed. Closing. Please reopen if you manage to reproduce on a newer version of Druid.
