### ISSUE TITLE
DelimitedInputFormat doesn't support the multi-character delimiter which is supported by DelimitedParser

### ISSUE THREAD

**Issue by jihoonson** [apache/druid#9188]
### Affected Version

0.17.0 and master

### Description

The behavior of `DelimitedInputFormat` is different from the `DelimitedParser` in supporting multi-character delimiter. It currently uses the first character as its delimiter if the given delimiter has multiple characters. This behavior should be fixed to match with the behavior of `DelimitedParser`.

**Comment by jon-wei** [comment]
Fixed by #9199
