### ISSUE TITLE
Reanimate Pig specific handling in the Avro parser

### ISSUE THREAD

**Issue by a2l007** [apache/druid#9211]
### Description

Apache Pig dependencies as well as related functionality were removed from the Avro parser in #7810 
We internally use Pig extensively and the Pig specific transformation within the Avro parser extension is useful for us especially for parsing data bags. I would like to add the `fromPigAvroStorage` flag based processing back to the Avro Parser. In terms of tests, I can find a way to test this without adding the Pig dependency back.
I apologize for missing out on raising this concern on the original PR.

Any objections @gianm @Fokko ?

**Comment by gianm** [comment]
Hmm, I think if Pig support can be re-introduced without causing problems with getting stuck on old versions of dependencies, then that is fine by me. That was what @Fokko was trying to unblock originally in #7810.

@Fokko what do you think? (Also @ccaominh, any opinion? — I know you also did some dependency-management related work recently.)

**Comment by ccaominh** [comment]
As long as we can still use newer versions of dependencies I don't see any problems. (For example, avro needs to be on the latest 1.9.1 version as it addresses security vulnerabilities present in older versions.)

**Comment by a2l007** [comment]
Thanks for being supportive of the usecase. I've raised a PR for this.

**Comment by Fokko** [comment]
I'm fine with re-introducing pig support in a lightweight manner. It would be great if we can keep the pig dependency out of it since it hasn't been updated for a very long time.
