### ISSUE TITLE
Previous sequenceNumber [344019] is no longer available for partition [0]

### ISSUE THREAD

**Issue by liujunhui** [apache/druid#9221]
{
  "dataSource": "rd_stack",
  "stream": "rd_stack",
  "partitions": 1,
  "replicas": 1,
  "durationSeconds": 3600,
  "activeTasks": [],
  "publishingTasks": [],
  "latestOffsets": {
    "0": 174
  },
  "minimumLag": {},
  "aggregateLag": 0,
  "offsetsLastUpdated": "2020-01-18T08:27:44.985Z",
  "suspended": false,
  "healthy": false,
  "state": "UNHEALTHY_SUPERVISOR",
  "detailedState": "UNABLE_TO_CONNECT_TO_STREAM",
  "recentErrors": [
    {
      "timestamp": "2020-01-18T08:26:30.003Z",
      "exceptionClass": "org.apache.druid.java.util.common.ISE",
      "message": "org.apache.druid.java.util.common.ISE: Previous sequenceNumber [344019] is no longer available for partition [0]. You can clear the previous sequenceNumber and start reading from a valid message by using the supervisor's reset API.",
      "streamException": true
    },
    {
      "timestamp": "2020-01-18T08:26:59.996Z",
      "exceptionClass": "org.apache.druid.java.util.common.ISE",
      "message": "org.apache.druid.java.util.common.ISE: Previous sequenceNumber [344019] is no longer available for partition [0]. You can clear the previous sequenceNumber and start reading from a valid message by using the supervisor's reset API.",
      "streamException": true
    },
    {
      "timestamp": "2020-01-18T08:27:29.997Z",
      "exceptionClass": "org.apache.druid.java.util.common.ISE",
      "message": "org.apache.druid.java.util.common.ISE: Previous sequenceNumber [344019] is no longer available for partition [0]. You can clear the previous sequenceNumber and start reading from a valid message by using the supervisor's reset API.",
      "streamException": true
    }
  ]
}

**Comment by HailongJson** [comment]
在线等挺急的

**Comment by davyWong3** [comment]
“You can clear the previous sequenceNumber and start reading from a valid message by using the supervisor's reset API“ 
![image](https://user-images.githubusercontent.com/9134877/72715431-71a05200-3bab-11ea-9474-09d19ff565ae.png)
/druid/indexer/v1/supervisor/<supervisorId>/reset

**Comment by suneet-s** [comment]
@liujunhui I'd like to try and help with this issue, but I don't understand the problem. Can you describe when this exception happened,, what changed in your environment if anything. Was this a new supervisor job that just started running? Was this an already running job, that just started failing?

I've seen this happen for me when the ingestion spec has been failing for a while. I've resolved that by fixing the ingestion spec and resetting the supervisor as the error message suggests

**Comment by hackallan** [comment]
> “You can clear the previous sequenceNumber and start reading from a valid message by using the supervisor's reset API“
> ![image](https://user-images.githubusercontent.com/9134877/72715431-71a05200-3bab-11ea-9474-09d19ff565ae.png)
> /druid/indexer/v1/supervisor/[supervisorId]/reset

hi,I want to solve this problem before it happens, not reset it every time
