### ISSUE TITLE
druid 有中国社群嘛

### ISSUE THREAD

**Issue by Doslin** [apache/druid#9226]
问题如题

**Comment by asdf2014** [comment]
@Doslin 欢迎加入 [![](https://img.shields.io/badge/QQ%E7%BE%A4-1670647-blue.svg)](https://shang.qq.com/wpa/qunwpa?idkey=f86b3c8de20da1658a3bb42df17a2fc4eee0d75c4a130a63585fdd257e3565ed)

**Comment by heiswade** [comment]
@asdf2014 加群答案是啥

**Comment by SWH12** [comment]
有群吗？群号是啥？

**Comment by asdf2014** [comment]
@heiswade 跳表的平均空间复杂度，答案 `O(n)`

**Comment by asdf2014** [comment]
@SWH12 QQ群：1670647，钉钉群：23318065 ，欢迎加入 :smile:

**Comment by liuxiaohui1221** [comment]
感谢😊
