### ISSUE TITLE
Bring Azure functionality to core functionality

### ISSUE THREAD

**Issue by zachjsh** [apache/druid#9240]
### Motivation

There is a significant potential Azure user base interested in using or already using Druid. Bringing Azure functionality to core will make druid easier to use on the Azure platform, and will help ensure the quality of this functionality.

### Proposed changes

1. Update unit tests to increase test coverage for the extension. Clean up any messy code.
2. Offically deprecate firehose functionality for azure, and implement a new input source mechanism. firehose implementation will not be maintained nor tested.
3. Move the azure-extension into extensions-core, we are willing to put effort into maintaining this extension as time goes on. Pull out common things that may be shared across multiple azure services and put them in https://github.com/apache/druid/tree/master/cloud

### Rationale

Bringing Azure functionality into core will make druid easier to use on the Azure platform, and will help ensure the quality of this functionality.

### Operational impact

The firehose implementation for the Azure extension will be officially deprecated. Existing functionality of firehose will remain, but will not be maintained nor tested. Existing users using firehose will continue to have the existing level of quality and functionality, so there will be no impact to existing operations. However we should urge these customers to switch to inputSource, or maybe we can make the change over seamless in the codebase.

### Test plan (optional)

We will have a full suite of integration tests to test druid against azure, similar to what we have for testing against existing core supported platforms. Unit test code coverage will be mandated to be above a certain percentage, ignoring the deprecated firehose code.

**Comment by jihoonson** [comment]
@zachjsh thanks for bringing this up! I like the idea. Would you please fill out the missing sections in the proposal? Rationale and Operational impact sections are mandatory and I think this proposal should include the Test plan section as well. You can leave some sections empty if you don't think anything is required, but I believe you have somethings to write for each section.

**Comment by jihoonson** [comment]
@zachjsh thanks for the update. :slightly_smiling_face:

**Comment by drcrallen** [comment]
Is there anything that needs to go under https://github.com/apache/druid/tree/master/cloud to support Azure?

**Comment by zachjsh** [comment]
@drcrallen , i dont think that anything is needed in https://github.com/apache/druid/tree/master/cloud. This directory confuses me, it seems to be for common code, but there doesnt seem to be any code shared here. There are just specific implementations of cloud provider configs and modules. I think that should live in the extension rather than here.

**Comment by zachjsh** [comment]
This work was done in https://github.com/apache/druid/pull/9394, and previous commits that improved quality to this extension. Closing this out.
