### ISSUE TITLE
web console in 'coordinator' fallback mode context menu has query with sql option

### ISSUE THREAD

**Issue by clintropolis** [apache/druid#9242]
### Affected Version

0.17.0+

### Description

Very minor issue on datasources view (maybe others?), but the context menu still has the query options: 

<img width="321" alt="Screen Shot 2020-01-22 at 4 30 05 PM" src="https://user-images.githubusercontent.com/1577461/72948987-cc68b380-3d3b-11ea-9953-bc190742b8a7.png">

Clicking takes you to the query page which promptly errors about not being able to query.

**Comment by vogievetsky** [comment]
Lol finally got around to fixing it ☝️ . It took exactly 20 seconds.
