### ISSUE TITLE
missing explanation for router configurations

### ISSUE THREAD

**Issue by gulinfu** [apache/druid#9248]
missing router configurations
from the router config example: 
```druid.host=#{IP_ADDR}:8080
druid.plaintextPort=8080
druid.service=druid/router

druid.router.defaultBrokerServiceName=druid:broker-cold
druid.router.coordinatorServiceName=druid:coordinator
druid.router.tierToBrokerMap={"hot":"druid:broker-hot","_default_tier":"druid:broker-cold"}
druid.router.http.numConnections=50
druid.router.http.readTimeout=PT5M

# Number of threads used by the Router proxy http client
druid.router.http.numMaxThreads=100

druid.server.http.numThreads=100
```

in https://druid.apache.org/docs/latest/design/router.html,

I can't find anything about `druid.router.http.numConnections`, `druid.router.http.numMaxThreads` in the configuration section:https://druid.apache.org/docs/latest/configuration/index.html#router

Are these parameters working? How do they work to tune the concurrency performance? Need more info in the configuration section.

**Comment by layoaster** [comment]
I'm also in need of guidance for these two parameters as they look like relevant for query concurrency/performance
