### ISSUE TITLE
Druid Ldap

### ISSUE THREAD

**Issue by averma111** [apache/druid#9256]
Does current version of Druid that is 0.16.1 supports LDAP authentication?.

If yes then what are the properties required for the change in common run time files.

LDAP extension
Druid now supports LDAP authentication. Authorization using LDAP groups is also supported by mapping LDAP groups to Druid roles.

LDAP authentication is handled by specifying an LDAP-type credentials validator.
Authorization using LDAP is handled by specifying an LDAP-type role provider, and defining LDAP group->Druid role mappings within Druid.
LDAP integration requires the druid-basic-security core extension. Please see https://druid.apache.org/docs/0.17.0/development/extensions-core/druid-basic-security.html for details.

As this is the first release with LDAP support, and there are a large variety of LDAP ecosystems, some LDAP use cases and features may not be supported yet. Please file an issue if you need enhancements to this new functionality.

**Comment by mohammadjkhan** [comment]
LDAP authentication isn’t available or supported in Druid 0.16.1, it is instead officially supported in 0.17.0

But, I believe the LDAP authentication changes are compatible and would work with Druid 0.16.1 as well.
So, If you REALLY want LDAP authentication feature for 0.16.1, you can try and test it out by placing the Druid 0.17.0 druid-basic-security extension to your Druid 0.16.0 extensions folder.

Thanks,
Mohammad J. Khan
