### ISSUE TITLE
Website must not link directly to artifact

### ISSUE THREAD

**Issue by sebbASF** [apache/druid#9264]
The feather at the bottom of every page links directly to a binary artifact.

Links to artifact downloads must be accompanied by the means to verify them, i.e. KEYS, sigs, hashes and verification instructions. Links should point to download pages, not individual downloads. The link must be removed or changed to point to the download page.

**Comment by gianm** [comment]
It seems like the link doesn't actually even work anyway (ouch). It links to a location that is not on the mirrors. I'm okay with either making it link to https://druid.apache.org/downloads.html or removing the icon (since there's already a download button in the header anyway).

**Comment by gianm** [comment]
@vogievetsky what do you think?
