### ISSUE TITLE
Error while building docker image for Druid

### ISSUE THREAD

**Issue by singqwe** [apache/druid#9268]
I am doing this [tutorial](https://druid.apache.org/docs/latest/tutorials/tutorial-batch-hadoop.html) to load batch data using Apache Hadoop and I try to run this command to build a Docker image named "druid-hadoop-demo" with version tag "2.8.5" : `docker build -t druid-hadoop-demo:2.8.5 .`

but it gives me this error

```
(Step 14/53 : RUN curl -s https://archive.apache.org/dist/hadoop/core/hadoop-2.8.3/hadoop-2.8.3.tar.gz | tar -xz -C /usr/local/ ---> Running in 7baa699ccc29

gzip: stdin: unexpected end of file tar: Child returned status 1 tar: Error is not recoverable: exiting now The command '/bin/sh -c curl -s https://archive.apache.org/dist/hadoop/core/hadoop-2.8.3/hadoop-2.8.3.tar.gz | tar -xz -C /usr/local/' returned a non-zero code: 2)

```
Any help is appreciated.

**Comment by ccaominh** [comment]
This is fixed by https://github.com/apache/druid/pull/8753
