### ISSUE TITLE
Mark Tranform interface with @extensionPoint

### ISSUE THREAD

**Issue by mitchlloyd** [apache/druid#9311]
### Description

Transforms were originally added to Druid in [this PR](https://github.com/apache/druid/pull/4890) and it's currently possible to add transform extensions. Has this interface settled enough to make this an official `@extensionPoint`.

### Motivation

Our current use cases involve taking multiple fields at ingest time and running them through a large set of business rules to arrive at a single normalized value. Doing this work at ingest time saves us work at query time and provides historical consistency for these derived fields.

Rather than having no compatibility guarantee, it would be nice to know that we have a deprecation  period to fix anything in our extension that needs to change.

**Comment by jihoonson** [comment]
Hi @mitchlloyd, it sounds good to me. Are you interested in making a PR?

**Comment by mitchlloyd** [comment]
Sure thing @jihoonson. I opened #9319 and I'm waiting on the build.
