### ISSUE TITLE
Use spark to load the Druid

### ISSUE THREAD

**Issue by xiaohui0318** [apache/druid#9342]
Recently, the company is going to go to druid, I am learning the knowledge of storage, but I found that MR was used for data loading. Later, I found the project spark-druid-batch, and found that it was no longer updated. I would like to ask why the community did not develop the spark version of the library code, based on what considerations, is the MR library performance is good enough now or is spark unstable? Please give advice or comments

**Comment by sascha-coenen** [comment]
Hi,
I'm just another Druid user, so I can't comment on the "why" part of your question, but it might be interesting for you to know that the most recent two Druid releases were heavily focussed on bringing into place a new native ingestion which might eventually be recommendable over both the MR and the Spark based ingestion methods.
You can find it here: https://druid.apache.org/docs/latest/ingestion/native-batch.html
The index_parallel task along with a new type of Druid node named "indexer"
(https://staging-druid.imply.io/docs/design/indexer.html) would be the most recent variant for ingesting data. This new native setup is still labelled as experimental but might soon be the simplest way to ingest data.

**Comment by itaiy** [comment]
To follow-up on the question and above reply - in some cases, we'd still like to have a way to ingest data directly from Spark.
There was a related conversation going on in Druid's user google group and on the Slack channel, and it's now consolidated to Druid's dev mailing list, see [here](https://lists.apache.org/thread.html/r8219a7be0583ae3d9a2303fa7f21872782cf0703812a410bb62acfef%40%3Cdev.druid.apache.org%3E)
