### ISSUE TITLE
Druid to Presto Querying data

### ISSUE THREAD

**Issue by averma111** [apache/druid#9345]
Druid Version :0.17

Hi Team,

We are trying to access Druid via broker and coordinator URLs via Presto. We are seeing some challenges in querying large Druid data sources.Small data sources are easily query able 

73,243,851 rows -Real time Streaming data
18,100,826 rows -Batch Load 
817,205 rows-Real time Streaming data.

Let me know if we can optimize broker/historical nodes for fast data retrieval.

Thanks,
Ashish

**Comment by asdf2014** [comment]
Hi, @averma111 . I wrote a blog to introduce how to use Presto Druid Connector, I hope it can be helpful to you. [https://yuzhouwan.com/posts/200906#Apache-Druid-Connector](https://yuzhouwan.com/posts/200906#Apache-Druid-Connector)
