### ISSUE TITLE
string_to_array ordering

### ISSUE THREAD

**Issue by fstolba** [apache/druid#9346]
### Affected Version
0.17

### Description
When using the function `string_to_array` on ingest the ordering of the resulting arrays seems random. I would expect the array elements to keep the order they had in the constituting string. Is this to be expected / by design?

### Example:
```
Function Call                                         Result
string_to_array("A_B_C", "_")                         ["C", "B", "A"]
string_to_array("D_E_F", "_")                         ["E", "D", "F"]
string_to_array("A_B", "_")                           ["A", "B"]
string_to_array("A_B_B_C", "_")                       ["A", "C", "B", "B"]
```

### Desired result:
```
Function Call                                         Result
string_to_array("A_B_C", "_")                         ["A", "B", "C"]
string_to_array("D_E_F", "_")                         ["D", "E", "F"]
string_to_array("A_B", "_")                           ["A", "B"]
string_to_array("A_B_B_C", "_")                       ["A", "B", "B", "C"]
```

**Comment by setop** [comment]
using 0.21.1 (unified console shows 0.20.0), when I add a transformation using the web console, I get "null" as a result...

![Screenshot 2021-11-17 at 15-46-40 Apache Druid](https://user-images.githubusercontent.com/7794056/142222893-a4c878d4-dcb0-4be1-8a69-a66b90ace521.png)


if use a column as the first argument I get weird output.

**Comment by kkarnam2713** [comment]
@setop try the delimiter with single quotes. like string_to_array(log, '_')
