### ISSUE TITLE
CSV Lookup Load pending

### ISSUE THREAD

**Issue by hara5** [apache/druid#9349]
I am using Druid quick-start. I have loaded CSV lookup file on the server. But it is unable to load the lookup file

**Step 1:**
> curl -H "Content-Type: application/json" \
>   --data @lookup.json \
>   http://<IP>:8081/druid/coordinator/v1/lookups/config

` {
  "__default": {
    "test": {
      "version": "v1",
      "lookupExtractorFactory": {
        "type": "cachedNamespace",
        "extractionNamespace": {
          "type": "uri",
          "uri": "file:/home/analytics/apache-druid-0.16.1-incubating/test.csv",
          "namespaceParseSpec": {
            "format": "csv",
            "columns": [
              "key",
              "value"
            ]
          },
          "pollPeriod": "PT30S"
        },
        "firstCacheTimeout": 0
      }
    }
  }
}`

**Step 2:**
 http://IP:8081/druid/coordinator/v1/lookups/status
`{"__default":{"test":{"loaded":false}}}`

**Step 3:**
 http://IP:8081/druid/coordinator/v1/lookups/config/all
`{"__default":{"test":{"loaded":false,"pendingNodes":["localhost:8101","localhost:8082","localhost:8083"]}}}`

Do I need to restart any component after adding a lookup? 
P.S. I tried adding lookup config from Front End as well and results are same

**Comment by felixmw** [comment]
I am struggle with the same issue.
