### ISSUE TITLE
Doc: SqlFirehose(Postgres) to Input source.

### ISSUE THREAD

**Issue by pktippa** [apache/druid#9369]
Since Firehoses are deprecated, needed guidance in finding doc for converting PostgreSQL SqlFirehose to Input source.

**Comment by jihoonson** [comment]
Hi @pktippa, the SqlFirehose is not deprecated yet. I admit the doc (https://druid.apache.org/docs/0.17.0/ingestion/native-batch.html#sqlfirehose) is confusing. It should be fixed.

**Comment by pktippa** [comment]
thanks @jihoonson
