### ISSUE TITLE
SQL: NVL does not work with empty strings as documentation states it would

### ISSUE THREAD

**Issue by sascha-coenen** [apache/druid#9415]
### Affected Version
0.16.0 and 0.17.0

### Description

NVL does NOT work with empty strings

```
SELECT
   NVL('something', 'fallback') AS tst1,   
   NVL(null, 'fallback') AS tst2,
   NVL('', 'fallback') AS tst3
```
this yields
"something", "fallback", ""

According to the documentation, the third projection should also yield the output "fallback"
> NVL(expr,expr-for-null) | Returns 'expr-for-null' if 'expr' is null (or empty string for string type).

I would petition to not change the documentation but the behaviour of the function because it is useful to also deal with empty strings.
Other functions like COALESCE have the same issue. Also a missed LOOKUP() should result in a null value but instead produces an empty string. This means that long combinations of CASE, NVL, NULLIF, COALESCE and LOOKUP need to be used just to implement something in SQL that is equivalent to the plywood function fallback()

**Comment by gianm** [comment]
I'd make a similar comment about this as https://github.com/apache/druid/issues/9416#issuecomment-591673574.
