### ISSUE TITLE
SQL: column references cannot be replaced by constants

### ISSUE THREAD

**Issue by sascha-coenen** [apache/druid#9418]
### Affected Version
0.16.0 and 0.17.0

### Description

The following query throws an exception. However if the LOOKUP is performed on a column reference, then it works even though the column would also just evaluate to a string value for each row. 

```
SELECT
   LOOKUP('some', 'adtype_by_adtypeid') AS tst
```

**Comment by gianm** [comment]
What exception do you get? A query like that should work fine, as long as the lookup exists and is loaded on the Broker that handles the query.

**Comment by sascha-coenen** [comment]
I'm getting the following;

```
SQL Error [00000]: Error -1 (00000) : Error while executing SQL "SELECT¶   LOOKUP('some', 'adtype_by_adtypeid') AS tst": Remote driver error: RuntimeException: java.lang.AssertionError: Type mismatch:¶rowtype of new rel:¶RecordType(VARCHAR tst) NOT NULL¶rowtype of set:¶RecordType(VARCHAR NOT NULL tst) NOT NULL -> AssertionError: Type mismatch:¶rowtype of new rel:¶RecordType(VARCHAR tst) NOT NULL¶rowtype of set:¶RecordType(VARCHAR NOT NULL tst) NOT NULL
```

This is with SQL compatible null handling turned OFF.
I can check tomorrow what I get back if I have it switched on.

I'm beginning to understand that the behaviour under compatible null handling is more important to get right as it is the desired true north state to thave compat mode switched on, but as we experience a performance issue with compat mode, we need to stick with the default mode for now. I'll update the ticket tomorrow when I have access to the cluster again with what I get under compat mode.
