### ISSUE TITLE
Source package download from website has files with errors

### ISSUE THREAD

**Issue by zihuanglin** [apache/druid#9427]
### Description
The source package download  from [website](https://druid.apache.org/downloads.html) has files with errors, some files name do not end in `. java`
e.g. 
* apache-druid-0.17.0-src/core/src/main/ava/org/apache/druid/collections/ReferenceCountingResourceHol
* apache-druid-0.17.0-src/core/src/main/java/org/apache/druid/common/config/NullValueHandlingConfig.ja
*  apache-druid-0.17.0-src/core/src/main/java/org/apache/druid/data/input/FirehoseFactoryToInputSourceA
...

And i confirmed that SHA512 code of the downloaded file is right.

**Comment by clintropolis** [comment]
Hmm, I just downloaded the source package and I am not seeing the same behavior, could something about your environment have truncated the file names when unpacking?

**Comment by zihuanglin** [comment]
Thanks clintropolis, there's something wrong with the way I unpacking the file, I've changed my way and it's okay
