### ISSUE TITLE
Error while Load the dat from Postgresql to Druid through Spec

### ISSUE THREAD

**Issue by MoushmiDas** [apache/druid#9430]
Hi Team,
I am trying to Load the data from Postgresql to Apache Druid(apache-druid-0.17.0) , but I am getting below error:
"SQL firehose error with org.apache.druid.segment.realtime.firehose.SqlFirehoseFactory cannot be cast to org.apache.druid.data.input.FiniteFirehoseFactory."
seems the issue is already resolve in the below Ticket request:
*SQL firehose error #9359
*Fix compatibility issues with SqlFirehose #9365
Could you please help me to get the new io-configuration for the postgresql.
Currently we are using below io-config for which we are getting above error:
"ioConfig": {
"type": "index",
"firehose": {
"type": "sql",
"database": {
"type": "postgresql",
"connectorConfig": {
"connectURI": "jdbc:postgresql://<Host_Name>:<PortNo.>/<DB_Name>",
"user": "<User_Name>",
"password": "<Pass_word>"
}
},
"sqls": [
"select * from Table;"
]
}
}

**Comment by BeckerK** [comment]
its already re-implementet in the master branch.. .
you can build your own druid version 

https://github.com/apache/druid/issues/9434#issuecomment-593826170
