### ISSUE TITLE
Posgresql to Druid direct data insertion

### ISSUE THREAD

**Issue by averma111** [apache/druid#9434]
Druid : 0.17

I have a use case where I need to directly insert data into Druid using PostgreSQL via jdbc

Please let me know the IO configuration for it

Thanks,
Ashish

**Comment by a2l007** [comment]
Have you tried using the SQL Firehose: https://druid.apache.org/docs/latest/ingestion/native-batch.html#sqlfirehose ?

**Comment by BeckerK** [comment]
for 0.17.0 you have to build your own druid version
http://druid.apache.org/docs/latest/development/build.html

instead of this command 
"mvn clean install -Papache-release,dist,rat -DskipTests"
use this one 
"mvn clean install -Pdist -DskipTest"

the second command will save you some time.
