### ISSUE TITLE
Hdfs inputSource not supported by native batch ingestion v0.17

### ISSUE THREAD

**Issue by jalbs** [apache/druid#9443]
Hdfs inputSource not supported by native batch ingestion v0.17.

### Affected Version

0.17

### Description

Hdfs inputSource not supported by native batch ingestion v0.17 even the documentation says it is possible (https://druid.apache.org/docs/latest/ingestion/native-batch.html#hdfs-input-source):

Failed to submit task: Could not resolve type id 'hdfs' as a subtype of `org.apache.druid.data.input.InputSource`: known type ids = [druid, http, inline, local] (for POJO property 'inputSource') at [Source: (org.eclipse.jetty.server.HttpInputOverHTTP); line: 1, column: 5067] (through reference chain: org.apache.druid.indexing.common.task.batch.parallel.ParallelIndexSupervisorTask["spec"]->org.apache.druid.indexing.common.task.batch.parallel.ParallelIndexIngestionSpec["ioConfig"]->org.apache.druid.indexing.common.task.batch.parallel.ParallelIndexIOConfig["inputSource"])

**Comment by jihoonson** [comment]
Hi, did you include the `druid-hdfs-storage` extension in your load list? How to load extension is explained in the document you linked.

**Comment by jalbs** [comment]
Yes, I have that extension loaded along with parquet, avro and mysql-metadata

**Comment by jihoonson** [comment]
If you have loaded it, it should be logged at the beginning of the task logs. Would you please check the task logs?
