### ISSUE TITLE
Make delete from deep storage multi-threaded

### ISSUE THREAD

**Issue by samarthjain** [apache/druid#9457]
I recently enabled the druid.coordinator.segment.kill.on  to enable kill tasks to delete unused segments from metadata and deep storage. After configuring it to delete 10K segments in one run, I noticed that it takes a while to delete 10K segments from the deep storage (S3 in our case). 

This can be improved by making the delete from deep storage multi-threaded.

**Comment by himanshug** [comment]
another avenue to explore would be  to batch the  delete calls  from FS if Hdfs supports batch deletion. That could potentially be much faster without introducing multithreading in there.
I  see that  delete from metadata store are  already batched, but FS  delete calls are done one after another.

**Comment by samarthjain** [comment]
Good suggestion, @himanshug. I see aws sdk client does support batch deletes. Let me post a PR that pursues this option.

**Comment by zhangyue19921010** [comment]
> Good suggestion, @himanshug. I see aws sdk client does support batch deletes. Let me post a PR that pursues this option.

Hi @samarthjain Is there any update for this issue? We have met the same issue in our PRD, and this new feature seems useful.
