### ISSUE TITLE
No implementation for org.apache.druid.query.QuerySegmentWalker was bound

### ISSUE THREAD

**Issue by lamberken** [apache/druid#9483]
### Affected Version

0.17.0

### Description

Add `druid-moving-average-query` extension, router throw
```
2020-03-09T07:37:24,035 INFO [main] org.apache.druid.initialization.Initialization - Loading extension [druid-datasketches], jars: druid-datasketches-0.17.0.jar, commons-math3-3.6.1.jar
2020-03-09T07:37:25,905 WARN [main] org.apache.hadoop.util.NativeCodeLoader - Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
Exception in thread "main" java.lang.RuntimeException: com.google.inject.CreationException: Unable to create injector, see the following errors:

1) No implementation for org.apache.druid.query.QuerySegmentWalker was bound.
  while locating com.google.inject.Provider<org.apache.druid.query.QuerySegmentWalker>
    for the 1st parameter of org.apache.druid.query.movingaverage.MovingAverageQueryToolChest.<init>(MovingAverageQueryToolChest.java:61)
  at org.apache.druid.query.movingaverage.MovingAverageQueryModule.configure(MovingAverageQueryModule.java:48) (via modules: com.google.inject.util.Modules$OverrideModule -> org.apache.druid.query.movingaverage.MovingAverageQueryModule)

1 error
	at org.apache.druid.cli.GuiceRunnable.makeInjector(GuiceRunnable.java:72)
	at org.apache.druid.cli.ServerRunnable.run(ServerRunnable.java:58)
	at org.apache.druid.cli.Main.main(Main.java:113)
Caused by: com.google.inject.CreationException: Unable to create injector, see the following errors:

1) No implementation for org.apache.druid.query.QuerySegmentWalker was bound.
  while locating com.google.inject.Provider<org.apache.druid.query.QuerySegmentWalker>
    for the 1st parameter of org.apache.druid.query.movingaverage.MovingAverageQueryToolChest.<init>(MovingAverageQueryToolChest.java:61)
  at org.apache.druid.query.movingaverage.MovingAverageQueryModule.configure(MovingAverageQueryModule.java:48) (via modules: com.google.inject.util.Modules$OverrideModule -> org.apache.druid.query.movingaverage.MovingAverageQueryModule)

1 error
	at com.google.inject.internal.Errors.throwCreationExceptionIfErrorsExist(Errors.java:470)
	at com.google.inject.internal.InternalInjectorCreator.initializeStatically(InternalInjectorCreator.java:155)
	at com.google.inject.internal.InternalInjectorCreator.build(InternalInjectorCreator.java:107)
	at com.google.inject.Guice.createInjector(Guice.java:99)
	at com.google.inject.Guice.createInjector(Guice.java:73)
	at com.google.inject.Guice.createInjector(Guice.java:62)
	at org.apache.druid.initialization.Initialization.makeInjectorWithModules(Initialization.java:431)
	at org.apache.druid.cli.GuiceRunnable.makeInjector(GuiceRunnable.java:69)
	... 2 more
2020-03-09T07:39:28,242 INFO [main] org.hibernate.validator.internal.util.Version - HV000001: Hibernate Validator 5.2.5.Final
```

### Another exception

If add `druid-moving-average-query` to broker as doc says, when query will throw
![image](https://user-images.githubusercontent.com/20113411/76209175-35e54880-623c-11ea-9b42-759e63e56b94.png)

**Comment by marcboivin** [comment]
couldn't tell you why this is closed. 

The extension doc clearly states to only enable on the broker. Doing that doesn't work. 

#4835 states that you need to avoid enabling the extension on non-query nodes. 

Using Druid's own docker-compose file I created a second environment for query node. Applied it to : 

* Historical
* Broker

Meaning that 

* Coordinator
* Middlemanager
* Router 

Don't have it enabled. 

Still get the type id error. 

<img width="1000" alt="Screen Shot 2020-04-01 at 9 32 30 AM" src="https://user-images.githubusercontent.com/202231/78143125-d3770680-73fb-11ea-9d3e-422660ab7723.png">

Extension is loaded on historical node: 

> docker git:(master) ✗ docker logs historical | grep extension
> Setting druid.extensions.loadList=["druid-moving-average-query","druid-histogram", "druid-kafka-indexing-service", "druid-datasketches", "druid-lookups-cached-global", "postgresql-metadata-storage"] in /tmp/conf/druid/cluster/data/historical/runtime.properties
> 2020-04-01T13:26:02,213 INFO [main] org.apache.druid.initialization.Initialization - Loading extension [druid-moving-average-query], jars: druid-moving-average-query-0.17.0.jar
> 2020-04-01T13:26:02,218 INFO [main] org.apache.druid.initialization.Initialization - Loading extension [druid-histogram], jars: druid-histogram-0.17.0.jar
> 2020-04-01T13:26:02,221 INFO [main] org.apache.druid.initialization.Initialization - Loading extension [druid-kafka-indexing-service], jars: kafka-clients-2.2.1.jar, lz4-java-1.6.0.jar, zstd-jni-1.3.3-1.jar, druid-kafka-indexing-service-0.17.0.jar, snappy-java-1.1.7.2.jar
> 2020-04-01T13:26:02,225 INFO [main] org.apache.druid.initialization.Initialization - Loading extension [druid-datasketches], jars: druid-datasketches-0.17.0.jar, commons-math3-3.6.1.jar
> 2020-04-01T13:26:02,227 INFO [main] org.apache.druid.initialization.Initialization - Loading extension [druid-lookups-cached-global], jars: druid-lookups-cached-global-0.17.0.jar, mapdb-1.0.8.jar
> 2020-04-01T13:26:02,229 INFO [main] org.apache.druid.initialization.Initialization - Loading extension [postgresql-metadata-storage], jars: postgresql-metadata-storage-0.17.0.jar, postgresql-42.2.8.jar
> 2020-04-01T13:26:02,545 INFO [main] org.apache.druid.initialization.Initialization - Loading extension [druid-moving-average-query], jars: druid-moving-average-query-0.17.0.jar
> 2020-04-01T13:26:02,549 INFO [main] org.apache.druid.initialization.Initialization - Loading extension [druid-histogram], jars: druid-histogram-0.17.0.jar
> 2020-04-01T13:26:02,555 INFO [main] org.apache.druid.initialization.Initialization - Loading extension [druid-kafka-indexing-service], jars: kafka-clients-2.2.1.jar, lz4-java-1.6.0.jar, zstd-jni-1.3.3-1.jar, druid-kafka-indexing-service-0.17.0.jar, snappy-java-1.1.7.2.jar
> 2020-04-01T13:26:02,560 INFO [main] org.apache.druid.initialization.Initialization - Loading extension [druid-datasketches], jars: druid-datasketches-0.17.0.jar, commons-math3-3.6.1.jar
> 2020-04-01T13:26:02,579 INFO [main] org.apache.druid.initialization.Initialization - Loading extension [druid-lookups-cached-global], jars: druid-lookups-cached-global-0.17.0.jar, mapdb-1.0.8.jar
> 2020-04-01T13:26:02,585 INFO [main] org.apache.druid.initialization.Initialization - Loading extension [postgresql-metadata-storage], jars: postgresql-metadata-storage-0.17.0.jar, postgresql-42.2.8.jar
> 2020-04-01T13:26:05,426 INFO [main] org.apache.druid.cli.CliHistorical - * druid.extensions.loadList: ["druid-moving-average-query","druid-histogram", "druid-kafka-indexing-service", "druid-datasketches", "druid-lookups-cached-global", "postgresql-metadata-storage"]

Extension is loaded on broker as well:

> ✗ docker logs broker | grep extension
> Setting druid.extensions.loadList=["druid-moving-average-query","druid-histogram", "druid-kafka-indexing-service", "druid-datasketches", "druid-lookups-cached-global", "postgresql-metadata-storage"] in /tmp/conf/druid/cluster/query/broker/runtime.properties
> 2020-04-01T13:26:02,107 INFO [main] org.apache.druid.initialization.Initialization - Loading extension [druid-moving-average-query], jars: druid-moving-average-query-0.17.0.jar
> 2020-04-01T13:26:02,111 INFO [main] org.apache.druid.initialization.Initialization - Loading extension [druid-histogram], jars: druid-histogram-0.17.0.jar
> 2020-04-01T13:26:02,114 INFO [main] org.apache.druid.initialization.Initialization - Loading extension [druid-kafka-indexing-service], jars: kafka-clients-2.2.1.jar, lz4-java-1.6.0.jar, zstd-jni-1.3.3-1.jar, druid-kafka-indexing-service-0.17.0.jar, snappy-java-1.1.7.2.jar
> 2020-04-01T13:26:02,117 INFO [main] org.apache.druid.initialization.Initialization - Loading extension [druid-datasketches], jars: druid-datasketches-0.17.0.jar, commons-math3-3.6.1.jar
> 2020-04-01T13:26:02,119 INFO [main] org.apache.druid.initialization.Initialization - Loading extension [druid-lookups-cached-global], jars: druid-lookups-cached-global-0.17.0.jar, mapdb-1.0.8.jar
> 2020-04-01T13:26:02,122 INFO [main] org.apache.druid.initialization.Initialization - Loading extension [postgresql-metadata-storage], jars: postgresql-metadata-storage-0.17.0.jar, postgresql-42.2.8.jar
> 2020-04-01T13:26:02,441 INFO [main] org.apache.druid.initialization.Initialization - Loading extension [druid-moving-average-query], jars: druid-moving-average-query-0.17.0.jar
> 2020-04-01T13:26:02,448 INFO [main] org.apache.druid.initialization.Initialization - Loading extension [druid-histogram], jars: druid-histogram-0.17.0.jar
> 2020-04-01T13:26:02,457 INFO [main] org.apache.druid.initialization.Initialization - Loading extension [druid-kafka-indexing-service], jars: kafka-clients-2.2.1.jar, lz4-java-1.6.0.jar, zstd-jni-1.3.3-1.jar, druid-kafka-indexing-service-0.17.0.jar, snappy-java-1.1.7.2.jar
> 2020-04-01T13:26:02,464 INFO [main] org.apache.druid.initialization.Initialization - Loading extension [druid-datasketches], jars: druid-datasketches-0.17.0.jar, commons-math3-3.6.1.jar
> 2020-04-01T13:26:02,478 INFO [main] org.apache.druid.initialization.Initialization - Loading extension [druid-lookups-cached-global], jars: druid-lookups-cached-global-0.17.0.jar, mapdb-1.0.8.jar
> 2020-04-01T13:26:02,483 INFO [main] org.apache.druid.initialization.Initialization - Loading extension [postgresql-metadata-storage], jars: postgresql-metadata-storage-0.17.0.jar, postgresql-42.2.8.jar
> 2020-04-01T13:26:05,371 INFO [main] org.apache.druid.cli.CliBroker - * druid.extensions.loadList: ["druid-moving-average-query","druid-histogram", "druid-kafka-indexing-service", "druid-datasketches", "druid-lookups-cached-global", "postgresql-metadata-storage"]

I'd be happy to provide a pull request for the doc if I can figure out what's wrong.

Regards

**Comment by marcboivin** [comment]
Followup, if I query the broker node directly it works. So I'm guessing I need a way to tell the overlord that my broker supports moving average. 

How?

**Comment by marcboivin** [comment]
Tried it with the Helm chart on 0.18 Still an issue. Any pointer on how to resolve? 

Thank you

**Comment by anandgm007** [comment]
Using 0.18.1, Wanted to add the moving average extension and i changed the load_extension in broker alone.
Here is my load_extention in _common, common.runtime.properties
druid.extensions.loadList=["druid-s3-extensions", "mysql-metadata-storage","druid-hdfs-storage", "druid-kafka-indexing-service", "druid-datasketches","druid-moving-average-query"]

Getting the following error in router.log when i restart the broker service
2020-08-06T13:52:10,538 WARN [main] org.apache.hadoop.util.NativeCodeLoader - Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
Exception in thread "main" java.lang.RuntimeException: com.google.inject.CreationException: Unable to create injector, see the following errors:

No implementation for org.apache.druid.query.QuerySegmentWalker was bound.
while locating com.google.inject.Provider<org.apache.druid.query.QuerySegmentWalker>
for the 1st parameter of org.apache.druid.query.movingaverage.MovingAverageQueryToolChest.(MovingAverageQueryToolChest.java:61)
at org.apache.druid.query.movingaverage.MovingAverageQueryModule.configure(MovingAverageQueryModule.java:48) (via modules: com.google.inject.u
til.Modules$OverrideModule -> org.apache.druid.query.movingaverage.MovingAverageQueryModule)
Should i include "druid-moving-average-query" in the overload also? right now its just the broker.

**Comment by lessmian** [comment]
Any update on this? I have exactly the same problem as @marcboivin and @anandgm007

**Comment by bharatmotwani** [comment]
Any update on this ? I am also seeing same problem

**Comment by rec7y33** [comment]
Hello, i got the same problem...
btw, @marcboivin, how do you query the broker node directly?
Thanks

> Followup, if I query the broker node directly it works. So I'm guessing I need a way to tell the overlord that my broker supports moving average.
> 
> How?
