### ISSUE TITLE
Switch Docker base to CentOS and include kerberos tools

### ISSUE THREAD

**Issue by xrl** [apache/druid#9495]
### Description

We are using Druid with a SASL (GSSAPI/Kerberos) Kafka cluster. In order to regenerate tokens we provide the jaas.conf with a script for running ktutil. The ktutil which comes in Debian does not allow us to feed in the password from the script but the CentOS ktutil does work.

### Motivation

It would be helpful to all Druid users talking to a kerberized kafka if docker image was all ready to go. I think Kafka is sufficiently common that it makes sense to provide this authentication tooling out of the box. This would also keep Druid users on the official docker image, so future bug fixes and security patches are easy to distribute with a docker tag update.

**Comment by mkapoor17** [comment]
I too would advocate for this change. To utilize Kerberos and the kafka extension, I ended creating my own custom image that is now a lot different than the base image and went through a lot of headache trying to get ktutil to work - changing to CentOS did the trick. 

I do want to go back to the official image but the significant differences between the OS distros and ktutil output makes it unlikely that I will.
