### ISSUE TITLE
Official Docker Image Error Response

### ISSUE THREAD

**Issue by psytron** [apache/druid#9506]
Official Druid Docker Image:
https://hub.docker.com/r/apache/incubator-druid

Running default command produces error:
$>docker pull apache/incubator-druid
Using default tag: latest
Error response from daemon: manifest for apache/druid:latest not found"

**Comment by himanshug** [comment]
not exactly  the fix but you can try to get  a specific version, that works.

**Comment by pdiblasi** [comment]
Hi,
still having the same issue when trying to pull docker image
> docker pull apache/druid
Using default tag: latest
Error response from daemon: manifest for apache/druid:latest not found: manifest unknown: manifest unknown
