### ISSUE TITLE
Instructions page url in build.md show "Page not found" 

### ISSUE THREAD

**Issue by JaeGeunBang** [apache/druid#9521]
Hello.

While reading the build.md file (https://github.com/apache/druid/blob/master/docs/development/build.md), I clicked on Instruction here and found "Page not found" on the Instruction page.

The URL of the Instruction page is https://github.com/apache/druid/blob/master/docs/content/development/build.md, and I confirmed that there is no /docs/content.

**Comment by JaeGeunBang** [comment]
The same issue occurs when linking to the Metadata section in the link document(https://github.com/apache/druid/blob/master/dev/intellij-setup.md)

**Comment by clintropolis** [comment]
Hi @JaeGeunBang, yep those links look broken, thanks for the report :+1:

**Comment by clintropolis** [comment]
I opened #9537 to fix these (and a couple of other issues)
