### ISSUE TITLE
How do I keep a dimension where all the values are empty？？？

### ISSUE THREAD

**Issue by xiaohui0318** [apache/druid#9528]
When data is ingestion, if there is a column in which all values are null,druid will remove this dimension; In this case, the query for this field will report an error. Is there any way to keep this dimension or set the default value for this null value?

**Comment by xiaohui0318** [comment]
I found a way, in a middlemanager configuration and set druid.Generic.UseDefaultValueForNull=false(single-server/micro-quickstart), and then change the null to "",this dimension into the druid; After I modify the druid middlemanager on line in this way, but it does not take effect. Do I need to modify other configurations?

**Comment by bharadwajrembar** [comment]
Hey is there any update to this? We have also hit this.

**Comment by xiaohui0318** [comment]
> Hey is there any update to this? We have also hit this.

I wrote my own code；
