### ISSUE TITLE
Druid connectivity with external query clients

### ISSUE THREAD

**Issue by averma111** [apache/druid#9541]
Druid Version : 0.17.

We are trying to connect Druid Ldap enabled to presto to query Druid database. 
When presto connects to Druid it says druid schema not found.

What setting in ldap do we need to make to expose the broker queryable.

Thanks,
Ashish

**Comment by asdf2014** [comment]
Hi, @averma111 . It seems that you are using Presto DB's Druid connector. The main developer of the connector may be able to help. @zhenxiao @beinan

**Comment by asdf2014** [comment]
Hi, @averma111 . It seems that you are using PrestoDB's Druid connector. The main developer of the connector may be able to help. @zhenxiao @beinan

**Comment by beinan** [comment]
Hi @averma111,  I think you might have to expose both coordinator and broker.

I just checked the code, looks like all the requests of metadata and druid sql pushdown are sent to the broker.   

Can I have the error message and stack trace?   you can get the stack trace by  "presto-cli --debug", thanks!

**Comment by averma111** [comment]
@asdf2014  From Presto 0.2.4.4 they are providing the plugin out of the box yes we need to provide the co oridnator and broker  host along with sql alchemy
