### ISSUE TITLE
Facing Error: Failed to sample data: Duplicate column entries found

### ISSUE THREAD

**Issue by Rohit-Stackroute** [apache/druid#9557]
So , I followed the tutorial  [kafka-druid tutorial](https://druid.apache.org/docs/latest/tutorials/tutorial-kafka.html)
Why it is coming when I am trying to pass csv data from kafka. Strange , when I am passing after converting it to json , there is no error. What are the properties do I need to change and why ?

<img width="1680" alt="Screenshot 2020-03-23 at 5 09 28 PM" src="https://user-images.githubusercontent.com/54025487/77387334-2543df00-6db3-11ea-89f6-fbd149174e2d.png">

**Comment by sagarwala** [comment]
@Rohit-Stackroute Were you able to get a resolution for the issue?
