### ISSUE TITLE
org.apache.druid.collections.StupidPool - Not closed! Object leaked from StupidPool while loading lookups

### ISSUE THREAD

**Issue by venkatramanp** [apache/druid#9599]
### Affected Version

Druid 0.17

### Description

Occasionally the following error is seen while lookups are being loaded:
Problem
--------
Occasionally, "WARN [Reference Handler] org.apache.druid.collections.StupidPool - Not
closed! Object leaked from StupidPool" message is seen when lookup is being loaded.

> 2020-03-21T10:01:21,169 INFO
> [LookupExtractorFactoryContainerProvider-Startup-1]
> org.apache.druid.query.lookup.LookupReferencesManager - Starting
> lookup
> [order_has_geogps_targeting]:[LookupExtractorFactoryContainer{version='2020-02-17T22:06:24.677Z',
> lookupExtractorFactory=NamespaceLookupExtractorFactory{extractionNamespace=JdbcExtractionNamespace{connectorConfig=DbConnectorConfig{createTables=false,
> connectURI='jdbc:postgresql://testrds.amazonaws.com:5432/manager',
> user='imply',
> passwordProvider=org.apache.druid.metadata.DefaultPasswordProvider,
> dbcpProperties=null}, table='lookups.orders', keyColumn='lineId',
> valueColumn='has_geogps_targeting', tsColumn='null', filter='null',
> pollPeriod=PT53M}, firstCacheTimeout=300000, injective=false,
> extractorID='namespace-factory-JdbcExtractionNamespace{connectorConfig=DbConnectorConfig{createTables=false,
> connectURI='jdbc:postgresql://testrds.amazonaws.com:5432/manager',
> user='imply',
> passwordProvider=org.apache.druid.metadata.DefaultPasswordProvider,
> dbcpProperties=null}, table='lookups.orders', keyColumn='lineId',
> valueColumn='has_geogps_targeting', tsColumn='null', filter='null',
> pollPeriod=PT53M}-bcef2348-ccae-4ea5-8693-1d0fd6f7dcee'}}]
> 2020-03-21T10:01:21.241+0000: [GC (Allocation Failure) 
> 946687K->492598K(2122752K), 0.1333336 secs] 2020-03-21T10:01:21,375
> WARN [Reference Handler] org.apache.druid.collections.StupidPool - Not
> closed! Object leaked from StupidPool{name=littleEndByteBufPool,
> objectsCacheMaxCount=2147483647, poolSize=0}. Allowing gc to prevent
> leak. 2020-03-21T10:01:21,375 WARN [Reference Handler]
> org.apache.druid.collections.StupidPool - Not closed! Object leaked
> from StupidPool{name=littleEndByteBufPool,
> objectsCacheMaxCount=2147483647, poolSize=0}. Allowing gc to prevent
> leak. 2020-03-21T10:01:21,375 WARN [Reference Handler]
> org.apache.druid.collections.StupidPool - Not closed! Object leaked
> from StupidPool{name=littleEndByteBufPool,
> objectsCacheMaxCount=2147483647, poolSize=0}. Allowing gc to prevent
> leak. 2020-03-21T10:01:21,375 WARN [Reference Handler]
> org.apache.druid.collections.StupidPool - Not closed! Object leaked
> from StupidPool{name=littleEndByteBufPool,
> objectsCacheMaxCount=2147483647, poolSize=0}. Allowing gc to prevent
> leak. 2020-03-21T10:01:21,375 WARN [Reference Handler]
> org.apache.druid.collections.StupidPool - Not closed! Object leaked
> from StupidPool{name=littleEndByteBufPool,
> objectsCacheMaxCount=2147483647, poolSize=0}. Allowing gc to prevent
> leak. 2020-03-21T10:01:21,375 WARN [Reference Handler]
> org.apache.druid.collections.StupidPool - Not closed! Object leaked
> from StupidPool{name=littleEndByteBufPool,
> objectsCacheMaxCount=2147483647, poolSize=0}. Allowing gc to prevent
> leak. 2020-03-21T10:01:21,375 WARN [Reference Handler]
> org.apache.druid.collections.StupidPool - Not closed! Object leaked
> from StupidPool{name=littleEndByteBufPool,
> objectsCacheMaxCount=2147483647, poolSize=0}. Allowing gc to prevent
> leak. 2020-03-21T10:01:21,375 WARN [Reference Handler]
> org.apache.druid.collections.StupidPool - Not closed! Object leaked
> from StupidPool{name=littleEndByteBufPool,
> objectsCacheMaxCount=2147483647, poolSize=0}. Allowing gc to prevent
> leak. 2020-03-21T10:01:21,375 WARN [Reference Handler]
> org.apache.druid.collections.StupidPool - Not closed! Object leaked
> from StupidPool{name=littleEndByteBufPool,
> objectsCacheMaxCount=2147483647, poolSize=0}. Allowing gc to prevent
> leak. 2020-03-21T10:01:21,375 WARN [Reference Handler]
> org.apache.druid.collections.StupidPool - Not closed! Object leaked
> from StupidPool{name=littleEndByteBufPool,
> objectsCacheMaxCount=2147483647, poolSize=0}. Allowing gc to prevent
> leak. 2020-03-21T10:01:21,376 WARN [Reference Handler]
> org.apache.druid.collections.StupidPool - Not closed! Object leaked
> from StupidPool{name=littleEndByteBufPool,
> objectsCacheMaxCount=2147483647, poolSize=0}. Allowing gc to prevent
> leak. 2020-03-21T10:01:21,376 WARN [Reference Handler]
> org.apache.druid.collections.StupidPool - Not closed! Object leaked
> from StupidPool{name=littleEndByteBufPool,
> objectsCacheMaxCount=2147483647, poolSize=0}. Allowing gc to prevent
> leak. 2020-03-21T10:01:21,376 WARN [Reference Handler]
> org.apache.druid.collections.StupidPool - Not closed! Object leaked
> from StupidPool{name=littleEndByteBufPool,
> objectsCacheMaxCount=2147483647, poolSize=0}. Allowing gc to prevent
> leak. 2020-03-21T10:01:21,376 WARN [Reference Handler]
> org.apache.druid.collections.StupidPool - Not closed! Object leaked
> from StupidPool{name=littleEndByteBufPool,
> objectsCacheMaxCount=2147483647, poolSize=0}. Allowing gc to prevent
> leak. 2020-03-21T10:01:21,376 WARN [Reference Handler]
> org.apache.druid.collections.StupidPool - Not closed! Object leaked
> from StupidPool{name=littleEndByteBufPool,
> objectsCacheMaxCount=2147483647, poolSize=0}. Allowing gc to prevent
> leak. 2020-03-21T10:01:21,376 WARN [Reference Handler]
> org.apache.druid.collections.StupidPool - Not closed! Object leaked
> from StupidPool{name=littleEndByteBufPool,
> objectsCacheMaxCount=2147483647, poolSize=0}. Allowing gc to prevent
> leak. 2020-03-21T10:01:21,376 WARN [Reference Handler]
> org.apache.druid.collections.StupidPool - Not closed! Object leaked
> from StupidPool{name=littleEndByteBufPool,
> objectsCacheMaxCount=2147483647, poolSize=0}. Allowing gc to prevent
> leak. 2020-03-21T10:01:21,376 WARN [Reference Handler]
> org.apache.druid.collections.StupidPool - Not closed! Object leaked
> from StupidPool{name=littleEndByteBufPool,
> objectsCacheMaxCount=2147483647, poolSize=0}. Allowing gc to prevent
> leak. 2020-03-21T10:01:21,376 WARN [Reference Handler]
> org.apache.druid.collections.StupidPool - Not closed! Object leaked
> from StupidPool{name=littleEndByteBufPool,
> objectsCacheMaxCount=2147483647, poolSize=0}. Allowing gc to prevent
> leak. 2020-03-21T10:01:21,376 WARN [Reference Handler]
> org.apache.druid.collections.StupidPool - Not closed! Object leaked
> from StupidPool{name=littleEndByteBufPool,
> objectsCacheMaxCount=2147483647, poolSize=0}. Allowing gc to prevent
> leak. 2020-03-21T10:01:21,376 WARN [Reference Handler]
> org.apache.druid.collections.StupidPool - Not closed! Object leaked
> from StupidPool{name=littleEndByteBufPool,
> objectsCacheMaxCount=2147483647, poolSize=0}. Allowing gc to prevent
> leak. 2020-03-21T10:01:21,376 WARN [Reference Handler]
> org.apache.druid.collections.StupidPool - Not closed! Object leaked
> from StupidPool{name=littleEndByteBufPool,
> objectsCacheMaxCount=2147483647, poolSize=0}. Allowing gc to prevent
> leak. 2020-03-21T10:01:21,376 WARN [Reference Handler]
> org.apache.druid.collections.StupidPool - Not closed! Object leaked
> from StupidPool{name=littleEndByteBufPool,
> objectsCacheMaxCount=2147483647, poolSize=0}. Allowing gc to prevent
> leak. 2020-03-21T10:01:21,376 WARN [Reference Handler]
> org.apache.druid.collections.StupidPool - Not closed! Object leaked
> from StupidPool{name=littleEndByteBufPool,
> objectsCacheMaxCount=2147483647, poolSize=0}. Allowing gc to prevent
> leak. 2020-03-21T10:01:21,376 WARN [Reference Handler]
> org.apache.druid.collections.StupidPool - Not closed! Object leaked
> from StupidPool{name=littleEndByteBufPool,
> objectsCacheMaxCount=2147483647, poolSize=0}. Allowing gc to prevent
> leak. 2020-03-21T10:01:21,377 WARN [Reference Handler]
> org.apache.druid.collections.StupidPool - Not closed! Object leaked
> from StupidPool{name=littleEndByteBufPool,
> objectsCacheMaxCount=2147483647, poolSize=0}. Allowing gc to prevent
> leak.

Doesn't seem to be causing any issues with lookup though.

**Comment by dganguli** [comment]
There's a comment in the code about this that may be helpful:

https://github.com/apache/druid/blob/master/core/src/main/java/org/apache/druid/collections/StupidPool.java#L43

**Comment by AKarbas** [comment]
Any update? -- is this okay?
Facing the same issue.

**Comment by Stephan3555** [comment]
Facing same issue. See this a couple of thousand times per minute
