### ISSUE TITLE
Kerberos in Druid

### ISSUE THREAD

**Issue by averma111** [apache/druid#9628]
Hi Team,

We have successfully setup Kerberos on Druid and we are trying to open Router console page, the page is failing with 403 status code and logs says below issue:

2020-04-06T15:22:44,293 WARN [qtp1051927339-80] org.apache.druid.security.kerberos.KerberosAuthenticator - AuthenticationToken ignored: org.apache.hadoop.security.authentication.util.SignerException: Invalid signed text:

How to resolve this issue. We are not able to open console page.Although we are able to insert data and query it.

Thanks,
Ashish

**Comment by himanshug** [comment]
that looks like something was wrong with signed secret in the cookie, you should clear your cookies and try again.

**Comment by averma111** [comment]
@himanshug  we have cleared cookies several time, everything is working excpet UI is not opening.
The first time your open the router you get below error
GSSException: Defective token detected (Mechanism level: GSSHeader did not find the right tag)

when we fresh it again we get below error

Problem accessing /unified-console.html. Reason:

    org.apache.hadoop.security.authentication.util.SignerException: Invalid signed text:

**Comment by himanshug** [comment]
first error  could be related  to https://stackoverflow.com/questions/47227276/gssexception-defective-token-detected-when-trying-to-authenticate-to-tomcat  and that leads to second error

**Comment by sydt2014** [comment]
This caused by CookieManager in KerberosHttpClient；CookieManager can not work correctly.

**Comment by basapuram-kumar** [comment]
Cleaning the cookies worked for me to access the web UI's from local mac
