### ISSUE TITLE
EXPLAIN SQL query with no limit generates invalid query

### ISSUE THREAD

**Issue by suneet-s** [apache/druid#9699]
### Affected Version

Tested in 0.18, haven't verified in older versions

### Description

If you use the web console's explain feature for a query with smart limits disabled it generates an invalid SQL query

```
SELECT * from wikipedia
```

generates

```
{
  "queryType": "scan",
  "dataSource": {
    "type": "table",
    "name": "wikipedia"
  },
  "intervals": {
    "type": "intervals",
    "intervals": [
      "-146136543-09-08T08:23:32.096Z/146140482-04-24T15:36:27.903Z"
    ]
  },
  "virtualColumns": [],
  "resultFormat": "compactedList",
  "batchSize": 20480,
  "limit": 9223372036854776000,
  "order": "none",
  "filter": null,
  "columns": [
    "__time",
    "channel",
    "cityName",
    "comment",
    "count",
    "countryIsoCode",
    "countryName",
    "diffUrl",
    "flags",
    "isAnonymous",
    "isMinor",
    "isNew",
    "isRobot",
    "isUnpatrolled",
    "namespace",
    "page",
    "regionIsoCode",
    "regionName",
    "sum_added",
    "sum_blah",
    "sum_blah2",
    "sum_blah3",
    "sum_commentLength",
    "sum_deleted",
    "sum_delta",
    "sum_deltaBucket",
    "user"
  ],
  "legacy": false,
  "context": {
    "sqlQueryId": "cc783735-4d86-4c29-aab3-77df8b93334f"
  },
  "descending": false,
  "granularity": {
    "type": "all"
  }
}
```

which fails with

```
Numeric value (9223372036854776000) out of range of long (-9223372036854775808 - 9223372036854775807) at [Source: (org.eclipse.jetty.server.HttpInputOverHTTP); line: 1, column: 257] (through reference chain: org.apache.druid.query.scan.ScanQuery["limit"])
```

**Comment by jihoonson** [comment]
Seems like `EXPLAIN PLAN FOR` query returns a valid query plan.

**Comment by suneet-s** [comment]
It's also worth noting that running a native query through the web console changes the limit somehow

```
{"queryType":"scan","dataSource":{"type":"table","name":"wikipedia"},"intervals":{"type":"intervals","intervals":["-146136543-09-08T08:23:32.096Z/146140482-04-24T15:36:27.903Z"]},"virtualColumns":[],"resultFormat":"compactedList","batchSize":20480,"limit":9223372036854775296,"order":"none","filter":null,"columns":["__time","channel","cityName","comment","count","countryIsoCode","countryName","diffUrl","flags","isAnonymous","isMinor","isNew","isRobot","isUnpatrolled","namespace","page","regionIsoCode","regionName","sum_added","sum_blah","sum_blah2","sum_blah3","sum_commentLength","sum_deleted","sum_delta","sum_deltaBucket","user"],"legacy":false,"descending":false,"granularity":{"type":"all"}}
```
In this query you can see that the limit is set to 9....5296

However, when I execute the query, I get an error saying
```
Numeric value (9223372036854776000) out of range of long (-9223372036854775808 - 9223372036854775807) at [Source: (org.eclipse.jetty.server.HttpInputOverHTTP); line: 1, column: 257] (through reference chain: org.apache.druid.query.scan.ScanQuery["limit"])
```

The limit works up to `9223372036854775295`

When I used inspect element to look at the request being made, the native query for that large limit is `9223372036854775000` So it looks like the web console is changing the limit under the covers somehow. This does not appear to be an issue for small limits - up to ~ 1 000 trillion (quadrillion?) in my  tests. at 1 000 000 trillion (quintillion?) the limit starts to change

**Comment by vogievetsky** [comment]
The issue here is that in JS the only numbers are doubles and doubles can not represent a number that high.

![image](https://user-images.githubusercontent.com/177816/84552182-c3658800-acc4-11ea-9532-afcb26399ab7.png)

The web console parses the JSON from the explain plan and that automatically parses the numbers into JS numbers. Is it possible for Druid's explain plan to return numbers that are not JS safe as strings?

https://stackoverflow.com/questions/47188449/json-max-int-number/47188576

Doing so would be more inline with the JSON spec: https://tools.ietf.org/html/rfc7159#section-6

```
   Note that when such software is used, numbers that are integers and
   are in the range [-(2**53)+1, (2**53)-1] are interoperable in the
   sense that implementations will agree exactly on their numeric
   values.
```

**Comment by vogievetsky** [comment]
![WhatsApp Image 2020-06-16 at 9 14 01 AM](https://user-images.githubusercontent.com/177816/84801869-9101a680-afb4-11ea-86e3-1aaa89dbc354.jpeg)

**Comment by vogievetsky** [comment]
This seems to be no longer an issue. Just tested it.

![image](https://user-images.githubusercontent.com/177816/101229258-33d9da00-3654-11eb-88c2-befa3ef15ebf.png)

I'm closing this but reopen if I am missing something.
