### ISSUE TITLE
DruidLeaderClient.goAsync() is broken

### ISSUE THREAD

**Issue by jihoonson** [apache/druid#9701]
### Affected Version

0.18.0

### Description

This bug seems to be introduced after https://github.com/apache/druid/pull/9481. Before this PR, `DruidLeaderClient` used to use `ServerDiscoverySelector` to find the leader. Since only the leader Overlord and Coordinator announce themselves, `ServerDiscoverySelector` could return the current leader to `DruidLeaderClient`. But now, `DruidLeaderClient` picks up the first node returned from `DruidNodeDiscovery` which knows all announced nodes. Since `DruidLeaderClient.goAsync()` doesn't follow redirection (https://github.com/apache/druid/issues/8716), some methods of the system table which use `goAsync()` API returns an error with the Temporary Redirect status.

**Comment by jihoonson** [comment]
This is a release blocker for 0.18.0 since Druid doesn't work with multi-masters.

**Comment by jihoonson** [comment]
I think we can revert #9481 for both master and 0.18.0 branches since it doesn't have any changes other than removing `ServerDiscoverySelector` from `DruidLeaderClient`. @himanshug does it make sense?

**Comment by himanshug** [comment]
@jihoonson `DruidLeaderClient` is designed  to follow  redirects so as to land requests to  leader. can  you please describe, what functionality is broken by this change ?

**Comment by jihoonson** [comment]
When it tries to follow redirects, [it checks the current known leader](https://github.com/apache/druid/blob/cda9f41e69ebc0513782805fca9ead378c1910ab/server/src/main/java/org/apache/druid/discovery/DruidLeaderClient.java#L282-L294) which calls `pickOneHost()`. This function used to use `ServerDiscoverySelector` before #9481 which returns the known leader, but now it just returns the first node from `DruidNodeDiscovery`.

https://github.com/apache/druid/blob/cda9f41e69ebc0513782805fca9ead378c1910ab/server/src/main/java/org/apache/druid/discovery/DruidLeaderClient.java#L297-L307

**Comment by himanshug** [comment]
ignoring name of that method, when we  make request to wrong leader, we should get a HTTP 302 back and that is redirect is then followed  to  get the request to right node (see https://github.com/apache/druid/blob/cda9f41e69ebc0513782805fca9ead378c1910ab/server/src/main/java/org/apache/druid/discovery/DruidLeaderClient.java#L210 ) and newly  discovered leader  is then cached  ( see  https://github.com/apache/druid/blob/cda9f41e69ebc0513782805fca9ead378c1910ab/server/src/main/java/org/apache/druid/discovery/DruidLeaderClient.java#L231  )

**Comment by gianm** [comment]
The problem happens with `DruidLeaderClient.goAsync`, which lets callers provide their own HttpResponseHandler, but doesn't contain the leader-following logic. It is used by the Druid SQL system tables so they can avoid materializing the entire response for the APIs they are hitting (which could be large). Perhaps the best fix is that it should learn how to follow leaders.

**Comment by jihoonson** [comment]
Yep, sorry for confusing. @himanshug you're right about `DruidLeaderClient.g()`, but it happens with `goAsync()` as @gianm mentioned which is reported in https://github.com/apache/druid/issues/8716.

I agree that the best approach to fix this would fix https://github.com/apache/druid/issues/8716, but we are running out of time for 0.18.0, I'm still inclined to reverting https://github.com/apache/druid/pull/9481 for now.

**Comment by gianm** [comment]
Reverting the patch makes sense to me, then for the next release, adding it back along with implementing redirects for `goAsync`.

**Comment by himanshug** [comment]
ah, I see , wasn't aware of this change. I agree, right fix is  to make it follow leader.

for now, I think right way to  fix it  to  not  revert #9481 but rather use `DruidLeaderSelector` interface to get  the   leader.. so as  to not add  hardcoded dependency  back to zk. Similar to what router  is doing  `DruidLeaderSelector.getCurrentLeader()` for  example https://github.com/apache/druid/blob/master/server/src/main/java/org/apache/druid/server/AsyncManagementForwardingServlet.java#L95

that will revert the behavior equivalent to using zk  specific  `ServerDiscoverySelector`

let me do a PR unless someone sees problems with that ..  @gianm @jihoonson  ?

**Comment by himanshug** [comment]
or rather, to expedite things, let us revert #9481 for now.

I will revive that along with bringing in `DruidLeaderSelector.getCurrentLeader()` or follow redirect in goAsync later.

**Comment by jihoonson** [comment]
@gianm @himanshug thanks for understanding! The PR is ready at https://github.com/apache/druid/pull/9702.
