### ISSUE TITLE
Druid Batch Load is Very slow

### ISSUE THREAD

**Issue by averma111** [apache/druid#9715]
Druid Version:0.15

Druid cluster setup with two historical nodes. We are trying to insert 100 millions into druid in tsv format and it took 7 hrs for Druid cluster setup to insert the rows.

Any parameters we can setup to increase the load performance.

Appreciate any help!!

**Comment by gianm** [comment]
If you are doing batch loads, try making sure that there are enough parallel tasks running, and that your files are split up enough that we can launch enough parallel tasks.

**Comment by averma111** [comment]
@gianm  could you please tell me what exact setting I have to change in cluster setup. I want test it first in lower environment before moving to prod

**Comment by jihoonson** [comment]
@averma111 it's `maxNumConcurrentSubTasks` in `tuningConfig`. Please check out the documentation here: https://druid.apache.org/docs/latest/ingestion/native-batch.html.

**Comment by liran-funaro** [comment]
I tried @gianm suggestions and they worked great to speed up the performance in a different project I worked on (see our [ingestion schema](https://github.com/liran-funaro/druid/wiki/Ingestion-Schema)).
We managed to increase the performance by 800% (see our [performance evaluation](https://github.com/liran-funaro/druid/wiki/Evaluation)).
But note that when increasing the number of workers, the RAM usage is increased dramatically.
If this is an issue for you, please consider checking out our improved implementation that reduces the RAM and CPU usage by over 50% during the ingestion process (#10001).
