### ISSUE TITLE
SQL query with Like can't add anything else

### ISSUE THREAD

**Issue by qiqi0818** [apache/druid#9719]
Druid Version:0.16

SQL-1:SELECT "TABLE_NAME" FROM INFORMATION_SCHEMA.TABLES WHERE  TABLE_NAME NOT LIKE '%err%' . This is OK!

SQL-2:SELECT "TABLE_NAME" FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_TYPE = 'TABLE' AND TABLE_NAME NOT LIKE '%err%'. This return "Query returned no data" 

Why SQL only have a like condition is OK. Can't add anything else?

**Comment by gianm** [comment]
I just tried this on Druid 0.18.0 and it works OK. Perhaps it was fixed since 0.16.

**Comment by qidaijie2018** [comment]
> I just tried this on Druid 0.18.0 and it works OK. Perhaps it was fixed since 0.16.

Thank you.
