### ISSUE TITLE
NPE when using AvroStreamInputRowParser and Kafka

### ISSUE THREAD

**Issue by jihoonson** [apache/druid#9728]
### Affected Version

0.18.0

### Description

This bug was added in #9625. Stack trace is

```java.lang.NullPointerException: inputFormatat com.google.common.base.Preconditions.checkNotNull(Preconditions.java:229) ~[guava-16.0.1.jar:?]at org.apache.druid.indexing.seekablestream.SettableByteEntityReader.<init>(SettableByteEntityReader.java:57) ~[druid-indexing-service-0.18.0-iap3.jar:0.18.0-iap3]at org.apache.druid.indexing.seekablestream.SeekableStreamIndexTaskRunner.runInternal(SeekableStreamIndexTaskRunner.java:379) ~[druid-indexing-service-0.18.0-iap3.jar:0.18.0-iap3]at org.apache.druid.indexing.seekablestream.SeekableStreamIndexTaskRunner.run(SeekableStreamIndexTaskRunner.java:276) [druid-indexing-service-0.18.0-iap3.jar:0.18.0-iap3]at org.apache.druid.indexing.seekablestream.SeekableStreamIndexTask.run(SeekableStreamIndexTask.java:164) [druid-indexing-service-0.18.0-iap3.jar:0.18.0-iap3]at org.apache.druid.indexing.overlord.SingleTaskBackgroundRunner$SingleTaskBackgroundRunnerCallable.call(SingleTaskBackgroundRunner.java:421) [druid-indexing-service-0.18.0-iap3.jar:0.18.0-iap3]at org.apache.druid.indexing.overlord.SingleTaskBackgroundRunner$SingleTaskBackgroundRunnerCallable.call(SingleTaskBackgroundRunner.java:393) [druid-indexing-service-0.18.0-iap3.jar:0.18.0-iap3]at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_242]at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_242]at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_242]at java.lang.Thread.run(Thread.java:748) [?:1.8.0_242]```

**Comment by lkm** [comment]
@jihoonson Ran into this while testing 0.18, this will prevent any Kafka Avro supervisor from working, right? Are you working on a patch?

**Comment by TheRum** [comment]
I'm also facing the same issue. Avro parser doesn't work with kafka streaming ingestion.

**Comment by jihoonson** [comment]
This issue is even worse. Only CSV and JSON will work with Kafka indexing service. I'm working on a patch.
