### ISSUE TITLE
Datasource still queries the data even after removing data from segments-cache?

### ISSUE THREAD

**Issue by BigDataArtist** [apache/druid#9749]
My Datasource in druid still reads the data from segments-cache( Which is historical data I guess)
after removing the files 

cd var/druid/segment-cache/tableName/015-09-12T00:00:00.000Z_2015-09-13T00:00:00.000Z/2020-04-22T20:20:06.280Z/0

 version.bin
 meta.smoosh
9 Apr 23 02:52 factory.json
 4820891 Apr 23 02:52 00000.smoosh

My understanding is once  I delete this data, the druid data source should not be able to query data.

I even restarted the druid, but I could still query the data from the same table name.

Please explain why its happening?

**Comment by SWH12** [comment]
this segments stored in hdfs too
