### ISSUE TITLE
docker hub should have a mysql connector image

### ISSUE THREAD

**Issue by jinleileiking** [apache/druid#9750]
```
This image contains solely the postgres metadata storage connector. If you need the mysql metadata storage connector, you can use Dockerfile.mysql to add it to the base image above.

```

As said, the officicial dockerfile just have a postgress connect. We should have a  MYSQL official docker image!

**Comment by jihoonson** [comment]
Hi, MySQL connector cannot be bundled because it's GPL. You can download it manually.
