### ISSUE TITLE
how can i modify Druid console URL?

### ISSUE THREAD

**Issue by HoraceLee** [apache/druid#9752]
my console url is : http://ip:8888/unified-console.html#
i want to modify it to:  http://ip:8888/MyTag/unified-console.html#

What am I supposed to do?

**Comment by frank-lam** [comment]
@HoraceLee can you fix this ? I got the same issuses

**Comment by frank-lam** [comment]
@HoraceLee Apache Druid 是不是 web 界面没法支持 代理模式？
