### ISSUE TITLE
Native json qury runs even on non-existent druid datasource  

### ISSUE THREAD

**Issue by v-vishwa** [apache/druid#9753]
Native json query runs even on non-existent druid datasource  

**Steps to reproduce** 
1. Run a native druid JSON query on any datasource of your wish which is not present in the cluster.
<img width="1426" alt="json_Query_on_non-existent_dataSource" src="https://user-images.githubusercontent.com/51313197/80097306-b52ea180-8588-11ea-8d4d-d2f8bce53992.png">
2. You would see the query runs without result, rather throwing the error ( dataSource Not found )

Druid SQL understand well and throws table/datasource not found an error .

**Comment by jihoonson** [comment]
This seems like an intended behavior rather than a bug. In Druid, datasource can be thought as a label for segments. That means, Druid doesn't do anything with datasource, but only cares whether there are segments to query.

**Comment by cswarth** [comment]
This is by far the most annoying behavior I have encountered with druid.  I can't tell you how many hours i have wasted debugging typos or other sources of bad datasource names!   
Typo in one line out of hundreds in a json spec?  No results.
Maybe there is a validation mode?  No, f-off, no results.
Nothing makes me hate druid more than this overtly anti-user behavior.  Not even a warning?  No even "are you sure about this?"  Just "no results"?!?
