### ISSUE TITLE
Whether the minimum time does not support less than 1970-01-01T00:00:00.000Z?

### ISSUE THREAD

**Issue by MrDLontheway** [apache/druid#9808]
### Affected Version

0.17

### Description

because it is below the minTimestamp[1970-01-01T00:00:00.000Z]
<img width="1383" alt="tmpdruid" src="https://user-images.githubusercontent.com/29403543/80859138-de3de900-8c90-11ea-8b23-dd07fa688ee6.png">

**Comment by egor-ryashin** [comment]
It affects 0.20 as well, it happens in sampling at least. I see Builder is created with default `minTimestamp` at org/apache/druid/indexing/overlord/sampler/InputSourceSampler.java
```java 
 private IncrementalIndex<Aggregator> buildIncrementalIndex(SamplerConfig samplerConfig, DataSchema dataSchema)
  {
    final IncrementalIndexSchema schema = new IncrementalIndexSchema.Builder()
        .withTimestampSpec(dataSchema.getTimestampSpec())
        .withQueryGranularity(dataSchema.getGranularitySpec().getQueryGranularity())
        .withDimensionsSpec(dataSchema.getDimensionsSpec())
        .withMetrics(ArrayUtils.addAll(dataSchema.getAggregators(), INTERNAL_ORDERING_AGGREGATOR))
        .withRollup(dataSchema.getGranularitySpec().isRollup())
        .build();
```
