### ISSUE TITLE
Docker Hub Builds are outdated

### ISSUE THREAD

**Issue by alekseyp** [apache/druid#9822]
Hello,

Are there plans to push/automate docker hub images?
Right now the last one us 0.16.1 and it's 5 months old.

https://hub.docker.com/r/apache/incubator-druid/builds

Or is it better practice to just build you own images?

**Comment by jon-wei** [comment]
The dockerhub images are now at https://hub.docker.com/r/apache/druid/builds, following graduation from Apache Incubator

**Comment by averma111** [comment]
You need to add appropriate tags to get the latest image.
