### ISSUE TITLE
Druid start-micro-quickstart, Unrecognized VM option 'ExitOnOutOfMemoryError'

### ISSUE THREAD

**Issue by sjx782392329** [apache/druid#9829]
Please provide a detailed title (e.g. "Broker crashes when using TopN query with Bound filter" instead of just "Broker crashes").

### Affected Version

Druid version 0.17.0

### Description

I start the druid in the aliyun ECS.
My system is Ubuntu x64，1 core 20G disk
My Java version is **1.8.0_202**

When I run the ./bin/start-micro-quickstart, it will spend sometime, and then I see some filed information.
![image](https://user-images.githubusercontent.com/33451661/81134343-01b1ae00-8f87-11ea-8d7f-1cf4f51106d3.png)
I cat the error log, it seems JVM option **ExitOnOutOfMemoryError** can not unrecognized
![image](https://user-images.githubusercontent.com/33451661/81134440-5523fc00-8f87-11ea-9c2f-854780eb7f2e.png)
I search the error information in google, they recommend me **update the java version**.
Now my java version is updated. But I also receive the error information.
Please help me，thank you very much~

**Comment by averma111** [comment]
You need to reduces the heap size of each druid nodes according to the memory available in your system.

Check with free -g and find out the RAM available

**Comment by FrankChen021** [comment]
what is the version of java you're using now ? it woks well with java 1.8.0_221 on my environment.

By the way, your server is 1 Core 20G Disk, and seems that the memory is also very low. To start druid on such a poor hardware, maybe you should try [nano configuration](https://druid.apache.org/docs/latest/operations/single-server.html#nano-quickstart-1-cpu-4gb-ram). Micro configuration at least costs 1.5G heap memory.

**Comment by sjx782392329** [comment]
I find my AliyunECS‘ is 2G RAM and 40G Disk，now I start with nano，this question stills exist.

**Comment by sjx782392329** [comment]
When I exec the ./start_nano_quick_start ，my ram is radually rise. This machine is almost died.
![image](https://user-images.githubusercontent.com/33451661/85504491-baf34280-b61e-11ea-9cc9-0cd248ae280d.png)
What can i do for this situation.

**Comment by sjx782392329** [comment]
I start this service successful, my machine's RAM is so slow. I use nano start, that costs about 3G RAM. thank you very much.
