### ISSUE TITLE
DRUID:Sharding of data in distributed data node

### ISSUE THREAD

**Issue by soumyajose0784** [apache/druid#9838]
Can i get an advise on how sharding of data happens in a data node cluster with multiple historical nodes(how data is distributed across each historical node)

**Comment by yuanlihan** [comment]
> how data is distributed across each historical node

Hi @soumyajose0784, the `druid.coordinator.balancer.strategy` property defines the balancing strategy to distribute segments among the historicals. See https://druid.apache.org/docs/latest/configuration/index.html#coordinator-operation and https://druid.apache.org/docs/latest/operations/rule-configuration.html for details. Hope it helps.
