### ISSUE TITLE
How to enable Apache Druid alerts through kafka-emmiter?

### ISSUE THREAD

**Issue by ifilkovic** [apache/druid#9841]
Hello,

this is /home/centos/apache-druid-0.16.0-incubating/conf/druid/cluster/_common/common.runtime.properties config:        

druid.extensions.loadList=["druid-hdfs-storage", "druid-kafka-indexing-service", "druid-datasketches", "kafka-emitter"]
druid.monitoring.monitors["org.apache.druid.java.util.metrics.SysMonitor","org.apache.druid.java.util.metrics.JvmMonitor"]
druid.emitter=kafka
druid.emitter.kafka.bootstrap.servers=172.23.97.48:31000
druid.emitter.kafka.metric.topic=druid-metrics
druid.emitter.kafka.alert.topic=druid-alerts
druid.emitter.kafka.producer.config={"max.block.ms":10000}

druid-metrics, are emitting, but alerts are not.
                              
Also, nothing important in logs.

BR,
IF

**Comment by yuanlihan** [comment]
Hi @ifilkovic, I also had encountered this issue months ago. You can get the patch https://github.com/apache/druid/pull/9573  and rebuild the `kafka-emitter` module. Hope it helps.

**Comment by ifilkovic** [comment]
Tnx @yuanlihan, will test it and report here.

**Comment by yuanlihan** [comment]
@ifilkovic if your kafka broker does not set this property `auto.create.topics.enable`, then don't forget to manually create topic `druid-alerts` first.

**Comment by ifilkovic** [comment]
@yuanlihan, I have created the topic manually, so that is not a problem.

What I have concluded is that the documentation about druid alerts is fairly small and practically non-existent. When and in what cases are alerts fired? 

I will try to contribute with that after all the findings.

**Comment by yuanlihan** [comment]
> When and in what cases are alerts fired?

I also do not find any explicit rules or principles about firing alerts. In my opinion, everyone can try to add alert metrics which are reasonable. eg:

https://github.com/apache/druid/blob/16d293d6e0d81963af3b3d468efd658317d91052/server/src/main/java/org/apache/druid/server/coordination/SegmentLoadDropHandler.java#L318

**Comment by ifilkovic** [comment]
Conclusion:

It is very hard to force alerts.

From the,
https://github.com/apache/druid/search?p=1&q=log.makeAlert&unscoped_q=log.makeAlert

you can see all cases when alerts are fired.

@yuanlihan, tnx mate.
