### ISSUE TITLE
failed tasks due to 'ISE' exception

### ISSUE THREAD

**Issue by brianbushree** [apache/druid#9845]
### Affected Version

0.17.0

### Description

We're ingesting data from Kafka and we've noticed this exception a couple times now... Here's how it normally surfaces: 

We'll see druid metrics that indicate there were 2 failed tasks. We then use the Druid UI to grab the task IDs that failed. Around the same time we'll notice some spike in ingest lag.

After some investigation we'll find the exception below in one of the tasks however the other task that was listed as failed in the UI has no exceptions in the log...

Also in both tasks, we've noticed that the report.json says the task was COMPLETED with no error message.

```
org.apache.druid.java.util.common.ISE: Attempting to publish with empty segment set, but total row count was not 0: [2202792].
    at org.apache.druid.segment.realtime.appenderator.BaseAppenderatorDriver.publishInBackground(BaseAppenderatorDriver.java:566)
    at org.apache.druid.segment.realtime.appenderator.StreamAppenderatorDriver.lambda$publish$1(StreamAppenderatorDriver.java:281)
    at org.apache.druid.java.util.common.concurrent.ListenableFutures$1.onSuccess(ListenableFutures.java:50)
    at com.google.common.util.concurrent.Futures$4.run(Futures.java:1181)
    at com.google.common.util.concurrent.MoreExecutors$SameThreadExecutorService.execute(MoreExecutors.java:297)
    at com.google.common.util.concurrent.ExecutionList.executeListener(ExecutionList.java:156)
    at com.google.common.util.concurrent.ExecutionList.execute(ExecutionList.java:145)
    at com.google.common.util.concurrent.AbstractFuture.set(AbstractFuture.java:185)
    at com.google.common.util.concurrent.Futures$ChainingListenableFuture$1.run(Futures.java:872)
    at com.google.common.util.concurrent.MoreExecutors$SameThreadExecutorService.execute(MoreExecutors.java:297)
    at com.google.common.util.concurrent.Futures$ImmediateFuture.addListener(Futures.java:102)
    at com.google.common.util.concurrent.Futures$ChainingListenableFuture.run(Futures.java:868)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
    at java.lang.Thread.run(Thread.java:748)
```

Couple questions here:
1. What does this exception mean and what's the best way to troubleshoot this?
2. Why does the report.json indicate that there were no errors?
3. Is it possible that a task failure from an exception like this could cause a separate task to fail? Maybe if they were running on the same node?

**Comment by jihoonson** [comment]
Hi @brianbushree, thank you for the report! It seems that this should never happen which means it would be likely a bug. I have a couple of theories for the potential bug, but am not 100% sure what happened yet. If possible, could you share the logs of both failed tasks and the overlord logs?

**Comment by brianbushree** [comment]
I'll see if we can share those requested logs - we may need to do some sanitization before uploading them here...

Let me follow up and get back to you.

**Comment by Pankaj260100** [comment]
we are still seeing this issue in Druid 25.0.0. Also, attaching the logs:
 ` "errorMsg": "java.util.concurrent.ExecutionException: org.apache.druid.java.util.common.ISE: Attempting to publish with empty segment set, but total row count was not 0: [2442738].\n\tat com.google.common.util.concurrent.AbstractFuture$Sync.getValue(AbstractFuture.java:299)\n\tat com.google.common.util.concurrent.AbstractFuture$Sync.get(AbstractFuture.java:286)\n\tat com.google.common.util.concurrent.AbstractFuture.get(AbstractFuture.java:116)\n\tat org.apache.druid.indexing.seekablestream.SeekableStreamIndexTaskRunner.checkPublishAndHandoffFailure(SeekableStreamIndexTaskRunner.java:935)\n\tat org.apache.druid.indexing.seekablestream.SeekableStreamIndexTaskRunner.runInternal(SeekableStreamIndexTaskRunner.java:608)\n\tat org.apache.druid.indexing.seekablestream.SeekableStreamIndexTaskRunner.run(SeekableStreamIndexTaskRunner.java:266)\n\tat org.apache.druid.indexing.seekablestream.SeekableStreamIndexTask.runTask(SeekableStreamIndexTask.java:151)\n\tat org.apache.druid.indexing.common.task.AbstractTask.run(AbstractTask.java:169)\n\tat org.apache.druid.indexing.overlord.ThreadingTaskRunner$1.call(ThreadingTaskRunner.java:210)\n\tat org.apache.druid.indexing.overlord.ThreadingTaskRunner$1.call(ThreadingTaskRunner.java:152)\n\tat java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)\n\tat java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)\n\tat java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)\n\tat java.base/java.lang.Thread.run(Thread.java:833)\nCaused by: org.apache.druid.java.util.common.ISE: Attempting to publish with empty segment set, but total row count was not 0: [2442738].\n\tat org.apache.druid.segment.realtime.appenderator.BaseAppenderatorDriver.publishInBackground(BaseAppenderatorDriver.java:588)\n\tat org.apache.druid.segment.realtime.appenderator.StreamAppenderatorDriver.lambda$publish$1(StreamAppenderatorDriver.java:284)\n\tat com.google.common.util.concurrent.Futures$ChainingListenableFuture.run(Futures.java:861)\n\tat com.google.common.util.concurrent.MoreExecutors$SameThreadExecutorService.execute(MoreExecutors.java:297)\n\tat com.google.common.util.concurrent.ExecutionList.executeListener(ExecutionList.java:156)\n\tat com.google.common.util.concurrent.ExecutionList.execute(ExecutionList.java:145)\n\tat com.google.common.util.concurrent.AbstractFuture.set(AbstractFuture.java:185)\n\tat com.google.common.util.concurrent.Futures$ChainingListenableFuture$1.run(Futures.java:872)\n\tat com.google.common.util.concurrent.MoreExecutors$SameThreadExecutorService.execute(MoreExecutors.java:297)\n\tat com.google.common.util.concurrent.Futures$ImmediateFuture.addListener(Futures.java:102)\n\tat com.google.common.util.concurrent.Futures$ChainingListenableFuture.run(Futures.java:868)\n\t... 3 more\n",`

**Comment by Pankaj260100** [comment]
@AmatyaAvadhanula, does [this patch](https://github.com/apache/druid/pull/14995) of yours fix the above issue? Thanks

**Comment by AmatyaAvadhanula** [comment]
@Pankaj260100, yes, it was intended to fix this issue
