### ISSUE TITLE
When using Spatial filters, what is the unit of radius

### ISSUE THREAD

**Issue by SWH12** [apache/druid#9847]
When I use a spatial filter, I don't know what the unit of radius is, kilometers or degrees?

By calculation I got the distance between coordinates [38,115] and [39.93883,116.51135] to be 152.7 kilometers.

When I use the spatial filter and type as radius, set coords to [38, 115], radius to 2, the result is empty; but set tcoords to [38, 115], radius to 3, the result is [39.93883, 116.51135 ].

**Comment by SWH12** [comment]
The unit of radius is Latitude or longitude.

**Comment by emetselaar** [comment]
Hi, great that you found that out. I am wondering now how to use it. Have you found an easy way for this?

**Comment by SWH12** [comment]
> Hi, great that you found that out. I am wondering now how to use it. Have you found an easy way for this?

Unfortunately, the spatial query statement of druid is not the same as what we want. I guess that the real spatial filtering function will seriously slow down the query speed.
If you really need to use Druid for spatial query business, I suggest you modify the code that implements this function in Druid

**Comment by emetselaar** [comment]
I made one workaround like this:

```sql
SELECT
MyDataRows,
FROM "Datasource"
WHERE
(POWER(DataLatitude-52.1, 2) + POWER( (DataLongitude-5.1)*COS(RADIANS(52.1)),2)) < POWER(5/68, 2)
```
I am searching around Lat =52.1 and Lon = 5.1 with a radius of 5(km) and I assume that 1 degree is 68 km length at my latititude.

The result will be all rows that have a DataLatitude and DataLongitude within that radius. 

This is based on
https://jonisalonen.com/2014/computing-distance-between-coordinates-can-be-simple-and-fast/ (the SQL part)
and the table at the following page to get the 1 degree is 68 km (the contstant at the end of the formula):
https://en.wikipedia.org/wiki/Longitude#Length_of_a_degree_of_longitude

**Comment by SWH12** [comment]
> I made one workaround like this:
> 
> ```sql
> SELECT
> MyDataRows,
> FROM "Datasource"
> WHERE
> (POWER(DataLatitude-52.1, 2) + POWER( (DataLongitude-5.1)*COS(RADIANS(52.1)),2)) < POWER(5/68, 2)
> ```
> 
> I am searching around Lat =52.1 and Lon = 5.1 with a radius of 5(km) and I assume that 1 degree is 68 km length at my latititude.
> 
> The result will be all rows that have a DataLatitude and DataLongitude within that radius.
> 
> This is based on
> https://jonisalonen.com/2014/computing-distance-between-coordinates-can-be-simple-and-fast/ (the SQL part)
> and the table at the following page to get the 1 degree is 68 km (the contstant at the end of the formula):
> https://en.wikipedia.org/wiki/Longitude#Length_of_a_degree_of_longitude

**Comment by SWH12** [comment]
> I made one workaround like this:
> 
> ```sql
> SELECT
> MyDataRows,
> FROM "Datasource"
> WHERE
> (POWER(DataLatitude-52.1, 2) + POWER( (DataLongitude-5.1)*COS(RADIANS(52.1)),2)) < POWER(5/68, 2)
> ```
> 
> I am searching around Lat =52.1 and Lon = 5.1 with a radius of 5(km) and I assume that 1 degree is 68 km length at my latititude.
> 
> The result will be all rows that have a DataLatitude and DataLongitude within that radius.
> 
> This is based on
> https://jonisalonen.com/2014/computing-distance-between-coordinates-can-be-simple-and-fast/ (the SQL part)
> and the table at the following page to get the 1 degree is 68 km (the contstant at the end of the formula):
> https://en.wikipedia.org/wiki/Longitude#Length_of_a_degree_of_longitude

I agree with your workaround , and this is probably the simplest solution. The only problem is that 68 should be replaced with 110.25 in the formula, because this value does not change with the Latitude(https://jonisalonen.com/2014/computing-distance-between-coordinates-can-be-simple-and-fast/ (the SQL part)). Such as:
```
SELECT
MyDataRows,
FROM "Datasource"
WHERE
(POWER(DataLatitude-52.1, 2) + POWER( (DataLongitude-5.1)*COS(RADIANS(52.1)),2)) < POWER(5/110.25, 2)
```

I have a question, why doesn’t Druid use this calculation method？ In the class named RadiusBound:
```
  public boolean contains(float[] otherCoords)
  {
    double total = 0.0;
    for (int i = 0; i < coords.length; i++) {
      total += Math.pow(otherCoords[i] - coords[i], 2);
    }

    return (total <= Math.pow(radius, 2));
  }
```
