### ISSUE TITLE
Is there an api to get queryId？ 

### ISSUE THREAD

**Issue by hushaoqing** [apache/druid#9850]
purpose:
Want to cancel / stop time-consuming queries

Looks like this pr https://github.com/apache/druid/pull/5514 is what i need

**Comment by yuanlihan** [comment]
Hi @hushaoqing, I would like to recommend the new feature [Query laning and prioritization](https://github.com/apache/druid/releases#query-laning) introduced in version 0.18.0. This feature provides an elegant way to control capacities for certain classes of queries. See https://druid.apache.org/docs/latest/configuration/index.html#query-prioritization-and-laning for details. Hope it helps.
