### ISSUE TITLE
datasource is disabled, how to enable？

### ISSUE THREAD

**Issue by Maplejw** [apache/druid#9868]
My datasource(note_client_behavior) is disabled, and then I click the enable's button,but it do not take effect.
![1](https://user-images.githubusercontent.com/24646597/81881895-ed436600-95c3-11ea-88e8-902ab20c4e1e.jpg)
When I click the enable's button,the coordinator log
![2](https://user-images.githubusercontent.com/24646597/81882152-8e322100-95c4-11ea-90ee-e92500ec18ab.jpg)
The segements data are still stored in deep storage, not deleted.So how to let it enable? 
 
![3](https://user-images.githubusercontent.com/24646597/81882398-41027f00-95c5-11ea-8d36-37130c3848ad.jpg)

**Comment by yuanlihan** [comment]
Hi @Maplejw 
When you disable a datasource, by default Druid will first marks segments as unused and then in the next operation cycle of Coordinator(>= P1M by default), the disable segments will be unloaded from historical nodes. Similar process for (re-)enabling datasource.
Also in your case, can check if segments are marked as used in table `druid_segments` after enabling.
 See https://druid.apache.org/docs/latest/configuration/index.html#coordinator-operation for details.

**Comment by Maplejw** [comment]
> Hi @Maplejw
> When you disable a datasource, by default Druid will first marks segments as unused and then in the next operation cycle of Coordinator(>= P1M by default), the disable segments will be unloaded from historical nodes. Similar process for (re-)enabling datasource.
> Also in your case, can check if segments are marked as used in table `druid_segments` after enabling.
> See https://druid.apache.org/docs/latest/configuration/index.html#coordinator-operation for details.

First thanks your answer.
I query the table <code>druid_segments</code>,The value of used is 0.
So segments are marked as unused.

**Comment by yuanlihan** [comment]
> And I query the table druid_segments,The value of used is 0 not 1.

Seems that clicking the `enable` button failed to mark segments as used. Possibly there is a bug in the version of console page you used(but it works in version 0.18.0). You can use the restful API `/druid/coordinator/v1/datasources/{dataSourceName}/markUsed` instead.

**Comment by Maplejw** [comment]
> > And I query the table druid_segments,The value of used is 0 not 1.
> 
> Seems that clicking the `enable` button failed to mark segments as used. Possibly there is a bug in the version of console page you used(but it works in version 0.18.0). You can use the restful API `/druid/coordinator/v1/datasources/{dataSourceName}/markUsed` instead.

It works when I use the restful API. Thanks
