### ISSUE TITLE
how export druid data to hive table or hdfs?

### ISSUE THREAD

**Issue by ZhangHuirui** [apache/druid#9916]
how export druid data to hive table or hdfs?

**Comment by kouddy** [comment]
Hi @ZhangHuirui,

At my workplace, because Druid supports JDBC connection via Apache Calcite's Avatica JDBC driver, we have been using Spark to load data from Druid to HDFS using JDBC connection as mentioned in https://spark.apache.org/docs/latest/sql-data-sources-jdbc.html

**Comment by SWH12** [comment]
Or we can write code by ourselves
