### ISSUE TITLE
Limit clause in subquery can cause outer query to fail if the outer query is an aggregation

### ISSUE THREAD

**Issue by maytasm** [apache/druid#9949]
### Description

Limit clause in subquery can cause outer query to fail if the outer query is an aggregation with org.apache.druid.sql.calcite.rel.CannotBuildQueryException: Subquery could not be converted to GroupBy query.

### Motivation

This might be related to https://github.com/apache/druid/issues/8774 and https://github.com/apache/druid/pull/8775

I have reproduced the following in CalciteQueryTest

- `SELECT m2, AVG(dim1) FROM (SELECT * FROM foo AS t1 INNER JOIN foo AS t2 ON t1.m1 = t2.m1 LIMIT 10) AS t3 GROUP BY m2`
Fails with org.apache.druid.sql.calcite.rel.CannotBuildQueryException: Subquery could not be converted to GroupBy query

- `SELECT m2, AVG(dim1) FROM (SELECT * FROM foo AS t1 INNER JOIN foo AS t2 ON t1.m1 = t2.m1) AS t3 GROUP BY m2 `
Works fine.

- `SELECT t1.m2, AVG(t1.dim1) FROM (SELECT * FROM foo LIMIT 10) AS t1 INNER JOIN foo AS t2 ON t1.m1 = t2.m1 GROUP BY t1.m2`
Works fine.

- `SELECT m2, dim1 FROM (SELECT * FROM foo AS t1 INNER JOIN foo AS t2 ON t1.m1 = t2.m1 LIMIT 10) AS t3`
Works fine.

I believe Druid should be able to handle this case. Am I missing anything on why we are not able to support this?

**Comment by abhishekagarwal87** [comment]
I can no longer reproduce this issue.

**Comment by maytasm** [comment]
I think I fixed it in https://github.com/apache/druid/issues/9949#:~:text=May%2031%2C%202020-,Fix%20Subquery%20could%20not%20be%20converted%20to%20groupBy%20query%20%239959,-Merged
