### ISSUE TITLE
SQL SELECT with IN filter containing null value throws ISE

### ISSUE THREAD

**Issue by suneet-s** [apache/druid#9977]
### Affected Version

0.19

### Description

The following query 

```
select * from druid.foo where dim2 in ('a', null)
```

fails to plan with this exception

```
Unknown exception / Cannot build plan for query: select * from druid.foo where dim2 in ('a', null) / org.apache.druid.java.util.common.ISE
```

This query should be able to use an in dim filter with a null value, but the Calcite planning phase fails with this error

```
Missing conversion is LogicalSort[convention: NONE -> DRUID]
There is 1 empty subset: rel#4087:Subset#5.DRUID.[], the relevant part of the original plan is as follows
4085:LogicalSort(fetch=[100:BIGINT])
  4083:LogicalProject(subset=[rel#4084:Subset#4.NONE.[]], __time=[$0], dim1=[$1], dim2=[$2], dim3=[$3], m1=[$4], m2=[$5])
    4081:LogicalJoin(subset=[rel#4082:Subset#3.NONE.[]], condition=[=($2, $6)], joinType=[inner])
      4050:LogicalTableScan(subset=[rel#4077:Subset#0.NONE.[]], table=[[druid, foo]])
      4051:LogicalValues(subset=[rel#4098:Subset#1.NONE.[]], tuples=[[{ 'a' }, { null }]])
```

**Comment by suneet-s** [comment]
Druid does not support joins against constant conditions - see #9994 

Calcite translates any in clause with a null to a join expression. If the in filter does not have null, Calcite will translate the query to an IN filter. So Druid can not support this type of query til #9994 is fixed.

If you want this query to work, re-write it to

```
select * from druid.foo where dim2 in ('a')
```

This will produce the same results as the query filed in this issue.

If you want the query to match nulls, then the above query should be re-written to

```
select * from druid.foo where dim2 in ('a') or dim2 is NULL
```

**Comment by maytasm** [comment]
FYI: Regarding Calcite translates any in clause with a null to a join expression -> this is not optimal on Calcite planning. I believe Calcite should not forbids null in the IN clause. See: https://issues.apache.org/jira/browse/CALCITE-4048 for related discussion.
