### ISSUE TITLE
Aggregation function returns no data on query with "where clause" that "where clause" value is the field that get from sub-query nesting aggregation function

### ISSUE THREAD

**Issue by jiezang** [apache/druid#9983]
Aggregation function returns no data on query with "where clause" that "where clause" value is the field that get from sub-query nesting aggregation function. **This is found in Druid 0.18.1 and it works fine in Druid 0.16.1.** 

This can be reproduced on Druid sample datasource "wikipedia"

### Affected Version

0.18.x

### Description
Here are how to reproduce on Druid sample datasource "wikipedia"

**The following is the query runs with problem. Number "79" is expected to be returned, but no data is returned in Druid 0.18.1. It works on Druid 0.16.1.  This is not tested on Druid 0.17**

_with abc as
(
  select countryName, (CASE when sum(added)<100 then 1 else 100 END) as totalAdded from wikipedia group by countryName
)
SELECT count(*) from abc where totalAdded>1_

-------------------------------------------------------------------------------------------
**When replace "count(*)" with totalAdded in query as following, 79 entries are returned as expected.**

_with abc as
(
  select countryName, (CASE when sum(added)<100 then 1 else 100 END) as totalAdded from wikipedia group by countryName
)
SELECT totalAdded from abc where totalAdded>1_

-------------------------------------------------------------------------------------------
**When remove where clause, aggregation function count works fine.**

_with abc as
(
  select countryName, (CASE when sum(added)<100 then 1 else 100 END) as totalAdded from wikipedia group by countryName
)
SELECT count(*) from abc_

-------------------------------------------------------------------------------------------
**When use "countryName" in where clause, aggregation function count works fine as well.**
_with abc as
(
  select countryName, (CASE when sum(added)<100 then 1 else 100 END) as totalAdded from wikipedia group by countryName
)
SELECT count(*) from abc where countryName='Canada'_

**Comment by abhishekagarwal87** [comment]
No longer reproducible on master.
