### ISSUE TITLE
Kill task sopped by OOM on large number of segments

### ISSUE THREAD

**Issue by AKarbas** [apache/druid#9996]
Hi.

I'm on Druid 0.16.0-incubating on OpenJDK 8u162-jre.

I had this overly large datasource with ~170K segments, being ingested from Kafka.
The problem was the data was wrongly timestamped and on each run of the ingestion task, hundreds of segments were created if not thousands.

I realized this, and in an attempt to clean up, stopped the supervisor, dropped the datasource, and issued a kill task to clean it up all the way. -- all through the druid console.

Now, the kill task fails with this as it's last log line:
```
Terminating due to java.lang.OutOfMemoryError: Java heap space
```

Some logged configurations (Tell me what to add.):
```
druid.indexer.runner.javaOpts: -server -Xms1g -Xmx1g -XX:MaxDirectMemorySize=1536m -Duser.timezone=UTC -Dfile.encoding=UTF-8 -XX:+ExitOnOutOfMemoryError -Djava.util.logging.manager=org.apache.logging.log4j.jul.LogManager
druid.indexer.fork.property.druid.processing.buffer.sizeBytes: 268435456
druid.indexer.fork.property.druid.processing.numMergeBuffers: 2
druid.indexer.fork.property.druid.processing.numThreads: 1
```

Any ideas? I was thinking submitting kill tasks with smaller time chunks than `1000-...` to `3000-...` could reduce the number of segments to kill in each run, but shouldn't this be handled automatically?

Lastly, if this in fact is a bug that still exists in the latest version, I'd be happy to submit a PR to fix it if you point me in the right direction.

Cheers

**Comment by FrankChen021** [comment]
we're using the same version. And several months ago, we deleted more than 300K segments without any error. 

Have you checked the available memory on your server ? Could you attach the full task log here ?

**Comment by jihoonson** [comment]
Hi @AKarbas, the kill task first retrieves all segments to kill in memory, so the OOM error probably was because of too many segments compared to the max Java heap size. You can either increase the max heap size or reduce the number of segments per kill task. 

BTW, have you considered setting `druid.coordinator.kill.on`? The coordinator will issue kill tasks automatically. See https://druid.apache.org/docs/latest/configuration/index.html#coordinator-operation for more details.

**Comment by jihoonson** [comment]
@AKarbas I opened https://github.com/apache/druid/issues/10002. It could help in your use case in the future.

**Comment by AKarbas** [comment]
@FrankChen021 :

I tested the memory. It is configured to use 1GB of heap and up to 1.5GB of direct memory (as you can see in the issue description). The metrics emitted by druid show no more than about 200MB of heap of non-heap memory usage (each), but looking at server metrics not emitted by druid, the task used about 1.8 GB in total and that much was freed after it failed.

**Comment by AKarbas** [comment]
> Have you checked the available memory on your server ?

@FrankChen021: I tested the memory usage.

It is configured to use 1GB of heap and up to 1.5GB of direct memory (as you can see in the issue description).

The metrics emitted by druid show no more than about 200MB of heap of non-heap memory usage (each), but looking at server metrics not emitted by druid, the task used about 1.8 GB in total and that much was freed after it failed.
Also, about 50% of the configured memory for the whole MiddleManager was free the whole time.
